In [ ]:
from datetime import datetime, timezone

import funcoes_eua as f_eua
import funcoes_sec as f_sec
import pandas as pd
import yfinance as yf

# Alterando a exibição dos números para não usar notação científica
# pd.set_option('display.float_format', '{:,.2f}'.format)

## **Funções de Scraping SEC**

Canal Sunrise Analysis:
* Part 1 - https://www.youtube.com/watch?v=y_tvyJCdCBo
* Part 2 - https://www.youtube.com/watch?v=viibnZRIiYc
* Part 3 - https://www.youtube.com/watch?v=wvqfHWaSuJQ&t
* Part 4 - https://www.youtube.com/watch?v=gpvG9vYBzwc
* Part 5 - https://www.youtube.com/watch?v=kJ0VJrJYB48
* Part 6 - https://www.youtube.com/watch?v=SneBju9SgLs

Para fazer o scraping dos principais documentos (balance sheet, income statement e cash flow statement) utilizar as funções:
* **cik_matching_ticker**: mostra qual é o número CIK da empresa;
* **f_sec.get_filtered_filings**: retorna os números dos documentos que contém a DRE, BP e FC de cada ano/trimestre;
* **labels_dict**: retorna os rótulos formatados dos documentos;
* **f_sec.process_one_statement**: faz o scraping do documento;
* **f_sec.rename_statement**: aplica a formatação dos rótulos no documento.

In [ ]:
# Algumas vezes, a função **f_sec.process_one_statement** não consegue fazer o scraping do documento
# É muito provavelmente, porque a string do documento não está no dicionário 'statement_keys_map'
# Para ver qual é a string do documento rodar a função **get_statement_file_names_in_filing_summary**
# Ela retorna um dicionário {'string do documento': 'número do documento'}:
{
    'condensed consolidated statements of income': 'R2.htm',
    'condensed consolidated statement of comprehensive income': 'R3.htm',
    'condensed consolidated balance sheets': 'R4.htm',
    "condensed consolidated statements of shareholders' equity": 'R5.htm',
    'condensed consolidated statements of shareholders??? equity (parenthetical)': 'R6.htm',
    'condensed consolidated statements of cash flows': 'R7.htm'
}

# Verificar se a 'string do documento' está no dicionário 'statement_keys_map'. Caso não esteja, adicionar no 'statement_keys_map'

# f_sec.get_statement_file_names_in_filing_summary(ticker=ticker, accession_number='000165204426000071', headers=f_sec.header)

# **Setor de Semicondutores**

## NVIDIA

* 1Q -> Lançamento em Abril (04);
* 2Q -> Lançamento em Julho (07);
* 3Q -> Lançamento em Outubro (10);
* 10K -> Lançamento em Janeiro (01).

In [ ]:
ticker = 'nvda'
f_sec.cik_matching_ticker(ticker)

### Scraping NVIDIA 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_nvda = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017, 2018, 2019 e 2020
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000104581020000010', # 2020
            '000104581019000023', # 2019
            '000104581018000010', # 2018
            '000104581017000027', # 2017
        ]
    },
    index=pd.to_datetime([
        '2020-01-26',
        '2019-01-27',
        '2018-01-28',
        '2017-01-29',
    ])
)

# Concatenando os dfs
df_lst_acc_num_nvda = pd.concat([df_lst_acc_num_nvda, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_nvda.index = pd.to_datetime(df_lst_acc_num_nvda.index, format='%Y-%m-%d')

df_lst_acc_num_nvda

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_nvda['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10k = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Long-term Debt, Excluding Current Maturities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt'
df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2020-01-26'] = df_balance_sheet_10k.loc['Long-term Debt', '2020-01-26'] 
df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2019-01-27'] = df_balance_sheet_10k.loc['Long-term Debt', '2019-01-27'] 
df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2018-01-28'] = df_balance_sheet_10k.loc['Long-term Debt', '2018-01-28'] 
df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2017-01-29'] = df_balance_sheet_10k.loc['Long-term Debt', '2017-01-29'] 

# A linha 'Deferred Income Tax Assets, Net' na coluna abaixo está zerada
# A informação está na linha 'Deferred Tax Assets, Gross, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2020-01-26'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Gross, Noncurrent', '2020-01-26'] 

# A linha 'Marketable Securities, Current' nas colunas abaixo está zerada
# As informações estão na linha 'nvda_MarketableSecuritiesAndEquitySecuritiesFVNI'
df_balance_sheet_10k.loc['Marketable Securities, Current', '2026-01-25'] = df_balance_sheet_10k.loc['nvda_MarketableSecuritiesAndEquitySecuritiesFVNI', '2026-01-25'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Deferred Tax Assets, Gross, Noncurrent',
    'Long-term Debt',
    'nvda_MarketableSecuritiesAndEquitySecuritiesFVNI'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Outstanding',
    'Commitments and Contingencies',
    'Convertible Debt, Current',
    'Temporary Equity, Par Value',
    'Capital Lease Obligations, Noncurrent'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'EquitySecuritiesFVNINoncurrent': 'Equity Securities FVNI Noncurrent',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_nvda['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10k = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10k.loc['InterestExpenseNonoperating', '2024-01-28'] = df_income_statement_10k.loc['Interest Expense', '2024-01-28'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2023-01-29'] = df_income_statement_10k.loc['Interest Expense', '2023-01-29'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2022-01-30'] = df_income_statement_10k.loc['Interest Expense', '2022-01-30'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2021-01-31'] = df_income_statement_10k.loc['Interest Expense', '2021-01-31'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2020-01-26'] = df_income_statement_10k.loc['Interest Expense', '2020-01-26'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2019-01-27'] = df_income_statement_10k.loc['Interest Expense', '2019-01-27'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2019-01-27'] = df_income_statement_10k.loc['Interest Expense', '2019-01-27'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2018-01-28'] = df_income_statement_10k.loc['Interest Expense', '2018-01-28'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2017-01-29'] = df_income_statement_10k.loc['Interest Expense', '2017-01-29'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-01-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-01-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-01-26'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-01-26'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-01-27'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-01-27'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-01-27'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-01-27'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-01-28'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-01-28'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-01-29'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-01-29'] 

# A linha 'Reveneus' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenue from Contract with Customer, Excluding Assessed Tax'
df_income_statement_10k.loc['Revenues', '2021-01-31'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2021-01-31'] 
df_income_statement_10k.loc['Revenues', '2020-01-26'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-01-26'] 
df_income_statement_10k.loc['Revenues', '2019-01-27'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2019-01-27'] 

# A linha 'Cost of Revenue' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cost of Goods and Services Sold'
df_income_statement_10k.loc['Cost of Revenue', '2021-01-31'] = df_income_statement_10k.loc['Cost of Goods and Services Sold', '2021-01-31'] 
df_income_statement_10k.loc['Cost of Revenue', '2020-01-26'] = df_income_statement_10k.loc['Cost of Goods and Services Sold', '2020-01-26'] 
df_income_statement_10k.loc['Cost of Revenue', '2019-01-27'] = df_income_statement_10k.loc['Cost of Goods and Services Sold', '2019-01-27'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Interest Expense',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Revenue from Contract with Customer, Excluding Assessed Tax',
    'Cost of Goods and Services Sold',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'us-gaap_OperatingExpensesAbstract',
    'Restructuring Charges',
    'Common Stock, Dividends, Per Share, Cash Paid'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'nvda_BusinessCombinationAdvancedConsiderationWrittenOff': 'Business Combination Advanced Consideration Written Off',
    'InterestExpenseNonoperating': 'Interest Expense'
})

# Formatando o número para ficar positivo
df_income_statement_10k.loc['Interest Expense'] = df_income_statement_10k.loc['Interest Expense'] * -1

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_nvda['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Payments to Acquire Productive Assets' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets'
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2023-01-29'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2023-01-29'] 
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2022-01-30'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2022-01-30'] 
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2021-01-31'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2021-01-31'] 
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2020-01-26'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2020-01-26'] 
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2019-01-27'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2019-01-27'] 
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2018-01-28'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2018-01-28'] 
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2017-01-29'] = df_cash_flow_10k.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2017-01-29'] 

# A linha 'Proceeds from Stock Plans' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_Netproceedspaymentsrelatedtoemployeestockplans'
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2023-01-29'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2023-01-29'] 
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2022-01-30'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2022-01-30'] 
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2021-01-31'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2021-01-31'] 
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2020-01-26'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2020-01-26'] 
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2019-01-27'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2019-01-27'] 
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2018-01-28'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2018-01-28'] 
df_cash_flow_10k.loc['Proceeds from Stock Plans', '2017-01-29'] = df_cash_flow_10k.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2017-01-29'] 

# A linha 'Depreciation, Depletion and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Depreciation, Depletion and Amortization, Nonproduction'
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2021-01-31'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2021-01-31'] 
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2020-01-26'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2020-01-26'] 
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2019-01-27'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2019-01-27'] 
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2018-01-28'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2018-01-28'] 
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2017-01-29'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2017-01-29'] 

# A linha 'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale and Maturity of Marketable Securities'
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-01-31'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2021-01-31'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-01-26'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2020-01-26'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2019-01-27'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2019-01-27'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2018-01-28'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2018-01-28'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2017-01-29'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2017-01-29'] 

# A linha 'nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities'
df_cash_flow_10k.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2023-01-29'] = df_cash_flow_10k.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2023-01-29'] 
df_cash_flow_10k.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2022-01-30'] = df_cash_flow_10k.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2022-01-30'] 
df_cash_flow_10k.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2021-01-31'] = df_cash_flow_10k.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2021-01-31'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2019-01-27'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2019-01-27'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-01-28'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-01-28'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-01-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-01-29'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2019-01-27'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2019-01-27'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-01-28'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-01-28'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-01-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-01-29'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Depreciation, Depletion and Amortization, Nonproduction',
    'Proceeds from Sale and Maturity of Marketable Securities',
    'nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets',
    'nvda_Netproceedspaymentsrelatedtoemployeestockplans',
    'nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash and Cash Equivalents, at Carrying Value'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'nvda_RestructuringchargesNoncash',
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'nvda_Reimbursementofheadquartersbuildingdevelopmentcostsfromlessor',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'nvda_Goodwilladjustmentrelatedtopreviouslyacquiredbusiness3dfx'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['ProceedsFromSaleOfEquitySecuritiesFvNi', '2024-01-28'] = 1
df_cash_flow_10k.loc['ProceedsFromSaleOfEquitySecuritiesFvNi', '2023-01-29'] = 8

df_cash_flow_10k.loc['PaymentsToAcquireEquitySecuritiesFvNi', '2024-01-28'] = -862
df_cash_flow_10k.loc['PaymentsToAcquireEquitySecuritiesFvNi', '2023-01-29'] = -85

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'nvda_BusinessCombinationAdvancedConsiderationWrittenOff': 'Business Combination Advanced Consideration Written Off',
    'nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities':'Payments For Financed Property Plant And Equipment And Intangible Assets Financing Activities',
    'nvda_Proceedsfromsaleoflonglivedassetsandinvestments': 'Proceeds From Sale Of Long Lived Assets And Investments',
    'nvda_GainsonSalesoflonglivedassetsandinvestment': 'Gains on Sales of Long Lived Assets And Investment'
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Debt, Current': 'Short-term Debt',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt',
    'Operating Lease, Liability, Noncurrent': 'Long-term Operating Lease Liabilities',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments to Acquire Productive Assets': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# 'acc_num' entre 2022 e 2026
df_lst_acc_num_nvda_sorted = df_lst_acc_num_nvda.sort_index()
acc_num_list_nvda_sliced = df_lst_acc_num_nvda_sorted.loc['2022':'2026', 'acc_num']

# Fazendo o scraping do leases (10-K)
leases_lst = []

for acc_num in acc_num_list_nvda_sliced:

    # Fazendo o scraping do leases (10-K) -> 'Note 17 – Leases' -> 'short-term operating lease liabilities'
    leases_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10k = f_sec.rename_statement(leases_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10k = leases_10k.iloc[:, 0]
    leases_lst.append(leases_10k)

# Juntando todos os dfs que estão em listas em apenas um df
# Para não dar o erro na hora da concatenação 'InvalidIndexError: Reindexing only valid with uniquely valued Index objects'ArithmeticError
# Tenho que usar a função 'keep=first'
df_leases_10k = pd.DataFrame()

# Iterando sobre cada DataFrame na lista e concatene-os ao DataFrame resultante
for df in leases_lst:
    df = df[~df.index.duplicated(keep='first')]  # Removendo os rótulos duplicados se necessário
    df_leases_10k = pd.concat([df_leases_10k, df], axis=1)
    
# Renomeando a linha do índice
df_leases_10k = df_leases_10k.rename(index={
    'Operating Lease, Liability, Current': 'Short-term Operating Lease Liabilities',

})

# Selecionando a linha desejada
df_leases_10k = df_leases_10k.loc[['Short-term Operating Lease Liabilities']]

# Criando as colunas dos anos de 2017, 2018, 2019, 2020 e 2021
df_leases_10k.loc['Short-term Operating Lease Liabilities', '2017-01-29'] = 0
df_leases_10k.loc['Short-term Operating Lease Liabilities', '2018-01-28'] = 0
df_leases_10k.loc['Short-term Operating Lease Liabilities', '2019-01-27'] = 0
df_leases_10k.loc['Short-term Operating Lease Liabilities', '2021-01-31'] = 121
df_leases_10k.loc['Short-term Operating Lease Liabilities', '2020-01-26'] = 91

# Ordenando o df
df_leases_10k = df_leases_10k[sorted(df_leases_10k.columns, reverse=True)]

df_leases_10k

In [ ]:
# Selecionando o 'acc_num' do ano de 2024 - Nvidia tem 'Investments in non-affiliated entities' em 2024. Em 2025 e 2026, ela não possui
acc_num_2024 = '000104581024000029'

# Fazendo o scraping do 'Investments in non-affiliated entities' (10-K) -> 'Note 10 - Balance Sheet Components' → 'Other assets' 
cross_holding_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2024, statement_name='cross_holding')
cross_holding_10k = f_sec.rename_statement(cross_holding_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
cross_holding_10k = cross_holding_10k.drop('us-gaap_SupplyCommitmentLineItems')

# Renomeando a linha do índice
cross_holding_10k  = cross_holding_10k .rename(index={
    'Other Long-term Investments': 'Investments in Non-affiliated Entities',

})

# Selecionando a linha desejada
cross_holding_10k  = cross_holding_10k .loc[['Investments in Non-affiliated Entities']]

# Criando as colunas dos anos de 2025 e 2026
cross_holding_10k .loc['Investments in Non-affiliated Entities', '2025-01-26'] = 0
cross_holding_10k .loc['Investments in Non-affiliated Entities', '2026-01-25'] = 0

# Ordenando o df
cross_holding_10k = cross_holding_10k[sorted(cross_holding_10k.columns, reverse=True)]

cross_holding_10k

In [ ]:
# 'acc_num' do ano mais recente
last_acc_num = df_lst_acc_num_nvda.iloc[0].item()

# Fazendo o scraping das receitas por segmento geográfico
geographic_revenue_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='geographic_revenue')
geographic_revenue_10k = f_sec.rename_statement(geographic_revenue_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
geographic_revenue_10k = geographic_revenue_10k.drop('us-gaap_RevenuesFromExternalCustomersAndLongLivedAssetsLineItems')

# Resetando o index do df, porque ele possui vários index igauis
geographic_revenue_10k = geographic_revenue_10k.reset_index(drop=True)

# Renomeado o index do df
geographic_revenue_10k = geographic_revenue_10k.rename(index={
    0: 'Total revenue',
    2: 'Revenue - United States',
    4: 'Revenue - Taiwan',
    7: 'Revenue - China',
    9: 'Revenue - Other',
})

# Selecionando as linhas desejadas
geographic_revenue_10k  = geographic_revenue_10k .loc[[
    'Total revenue',
    'Revenue - United States',
    'Revenue - Taiwan',
    'Revenue - China',
    'Revenue - Other'
]]

geographic_revenue_10k

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')
    df_leases_10k.to_excel(writer, sheet_name='leases')
    cross_holding_10k.to_excel(writer, sheet_name='cross_holding')
    geographic_revenue_10k.to_excel(writer, sheet_name='geographic_revenue')

### Scraping NVIDIA 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_nvda = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 1Q do ano de 2020
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000104581020000147', # 2Q 2020
            '000104581020000065', # 1Q 2020
        ]
    },
    index=pd.to_datetime([
        '2020-07-26',
        '2020-04-26',
    ])
)

# Concatenando os dfs
df_lst_acc_num_10q_nvda = pd.concat([df_lst_acc_num_10q_nvda, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_10q_nvda.index = pd.to_datetime(df_lst_acc_num_10q_nvda.index, format='%Y-%m-%d')
df_lst_acc_num_10q_nvda

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2020 p/ iteração
df_lst_acc_num_10q_nvda_sliced = df_lst_acc_num_10q_nvda.loc['2020-04-26':]
df_lst_acc_num_10q_nvda_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_nvda_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10q = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Long-term Debt, Excluding Current Maturities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt'
df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-07-26'] = df_balance_sheet_10q.loc['Long-term Debt', '2020-07-26'] 
df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-04-26'] = df_balance_sheet_10q.loc['Long-term Debt', '2020-04-26'] 

# A linha 'Other Assets, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Other Assets'
df_balance_sheet_10q.loc['Other Assets, Noncurrent', '2020-07-26'] = df_balance_sheet_10q.loc['Other Assets', '2020-07-26'] 
df_balance_sheet_10q.loc['Other Assets, Noncurrent', '2020-04-26'] = df_balance_sheet_10q.loc['Other Assets', '2020-04-26'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Long-term Debt',
    'Other Assets'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Outstanding'

])

# Arrumando e adicionando alguns números no df
# Em '2026-04-26', o 'Marketable Securities' foi dividido em dois itens 'Marketable debt securities' ('Debt Securities, Current') e 'Marketable equity securities' ('Equity Securities, FV-NI')
df_balance_sheet_10q.loc['Marketable Securities, Current', '2026-07-26'] = 34143 + 42783
df_balance_sheet_10q.loc['Marketable Securities, Current', '2026-04-26'] = 37098 + 30237

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_nvda_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10q = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-04-28'] = df_income_statement_10q.loc['Interest Expense', '2024-04-28'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-10-29'] = df_income_statement_10q.loc['Interest Expense', '2023-10-29'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-07-30'] = df_income_statement_10q.loc['Interest Expense', '2023-07-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-04-30'] = df_income_statement_10q.loc['Interest Expense', '2023-04-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-10-30'] = df_income_statement_10q.loc['Interest Expense', '2022-10-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-07-31'] = df_income_statement_10q.loc['Interest Expense', '2022-07-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-05-01'] = df_income_statement_10q.loc['Interest Expense', '2022-05-01'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-10-31'] = df_income_statement_10q.loc['Interest Expense', '2021-10-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-08-01'] = df_income_statement_10q.loc['Interest Expense', '2021-08-01'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-05-02'] = df_income_statement_10q.loc['Interest Expense', '2021-05-02'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-10-25'] = df_income_statement_10q.loc['Interest Expense', '2020-10-25'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-07-26'] = df_income_statement_10q.loc['Interest Expense', '2020-07-26'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-04-26'] = df_income_statement_10q.loc['Interest Expense', '2020-04-26'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-08-01'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-08-01'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-05-02'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-05-02'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-10-25'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-10-25'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-07-26'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-07-26'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-04-26'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-04-26'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Interest Expense',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop('us-gaap_IncomeStatementAbstract')

# Renomeando a linha do índice 'nvda_BusinessCombinationAdvancedConsiderationWrittenOff'
df_income_statement_10q = df_income_statement_10q.rename(index={
    'nvda_BusinessCombinationAdvancedConsiderationWrittenOff': 'Business Combination Advanced Consideration Written Off',
    'InterestExpenseNonoperating': 'Interest Expense'
})

# Formatando o número para ficar positivo
df_income_statement_10q.loc['Interest Expense'] = df_income_statement_10q.loc['Interest Expense'] * -1

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Interest Expense', '2026-07-26'] = 227

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_nvda_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Proceeds from Stock Plans' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans'
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2023-10-29'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2023-10-29']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2023-07-30'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2023-07-30']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2023-04-30'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2023-04-30']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2022-10-30'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2022-10-30']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2022-07-31'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2022-07-31']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2022-05-01'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2022-05-01']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2021-10-31'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2021-10-31']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2021-08-01'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2021-08-01']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2021-05-02'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2021-05-02']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2020-10-25'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2020-10-25']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2020-07-26'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2020-07-26']
df_cash_flow_10q.loc['Proceeds from Stock Plans', '2020-04-26'] = df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2020-04-26']

# A linha 'nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_Netproceedspaymentsrelatedtoemployeestockplans'
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2022-05-01'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2022-05-01'] 
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2021-10-31'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2021-10-31'] 
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2021-08-01'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2021-08-01'] 
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2021-05-02'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2021-05-02']
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2020-10-25'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2020-10-25']
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2020-07-26'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2020-07-26']
df_cash_flow_10q.loc['nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans', '2020-04-26'] = df_cash_flow_10q.loc['nvda_Netproceedspaymentsrelatedtoemployeestockplans', '2020-04-26']

# A linha 'nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities'
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2021-10-31'] = df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2021-10-31'] 
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2021-08-01'] = df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2021-08-01'] 
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2021-05-02'] = df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2021-05-02']
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2020-10-25'] = df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2020-10-25']
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2020-07-26'] = df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2020-07-26']
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2020-04-26'] = df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities', '2020-04-26']

# A linha 'Payments to Acquire Productive Assets' nas colunas abaixo estão zeradas
# As informações estão na linha 'nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets'
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2023-07-30'] = df_cash_flow_10q.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2023-07-30']
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2023-04-30'] = df_cash_flow_10q.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2023-04-30']
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2022-10-30'] = df_cash_flow_10q.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2022-10-30']
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2022-07-31'] = df_cash_flow_10q.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2022-07-31']
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2022-05-01'] = df_cash_flow_10q.loc['nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets', '2022-05-01']

# A linha 'Depreciation, Depletion and Amortization' nas colunas abaixo estão zeradas	
# As informações estão na linha 'Depreciation, Depletion and Amortization, Nonproduction'
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2021-08-01'] = df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2021-08-01'] 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2021-05-02'] = df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2021-05-02'] 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2020-10-25'] = df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2020-10-25'] 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2020-07-26'] = df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2020-07-26'] 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2020-04-26'] = df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2020-04-26'] 

# A linha 'Payments for (Proceeds from) Other Investing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Other Investments'
df_cash_flow_10q.loc['Payments for (Proceeds from) Other Investing Activities', '2020-10-25'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2020-10-25']
df_cash_flow_10q.loc['Payments for (Proceeds from) Other Investing Activities', '2020-07-26'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2020-07-26']
df_cash_flow_10q.loc['Payments for (Proceeds from) Other Investing Activities', '2020-04-26'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2020-04-26']

# A linha 'nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Property, Plant, and Equipment'
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2020-07-26'] = df_cash_flow_10q.loc['Payments to Acquire Property, Plant, and Equipment', '2020-07-26']
df_cash_flow_10q.loc['nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities', '2020-04-26'] = df_cash_flow_10q.loc['Payments to Acquire Property, Plant, and Equipment', '2020-04-26']

# A linha 'Share-based Payment Arrangement, Noncash Expense' na coluna abaixo estão zeradas
# As informações estão na linha 'Share-based Payment Arrangement, Expense'
df_cash_flow_10q.loc['Share-based Payment Arrangement, Noncash Expense', '2023-04-30'] = df_cash_flow_10q.loc['Share-based Payment Arrangement, Expense', '2023-04-30'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'nvda_PaymentsToAcquireMarketableDebtAndEquitySecurities'
df_cash_flow_10q.loc['Payments to Acquire Debt Securities, Available-for-sale', '2026-04-26'] = df_cash_flow_10q.loc['nvda_PaymentsToAcquireMarketableDebtAndEquitySecurities', '2026-04-26']

# A linha 'ProceedsFromSaleOfEquitySecuritiesFvNi' na coluna abaixo está zerada
# As informações estão na linha 'nvda_ProceedsFromSaleOfNonMarketableSecurities'
df_cash_flow_10q.loc['ProceedsFromSaleOfEquitySecuritiesFvNi', '2026-04-26'] = df_cash_flow_10q.loc['nvda_ProceedsFromSaleOfNonMarketableSecurities', '2026-04-26'] 

# A linha 'PaymentsToAcquireEquitySecuritiesFvNi' na coluna abaixo está zerada
# As informações estão na linha 'nvda_PaymentsToAcquireNonMarketableSecurities'
df_cash_flow_10q.loc['PaymentsToAcquireEquitySecuritiesFvNi', '2026-04-26'] = df_cash_flow_10q.loc['nvda_PaymentsToAcquireNonMarketableSecurities', '2026-04-26'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Depreciation, Depletion and Amortization, Nonproduction',
    'Share-based Payment Arrangement, Expense',
    'nvda_Netproceedspaymentsrelatedtoemployeestockplans',
    'nvda_PaymentsForFinancedPropertyPlantAndEquipmentFinancingActivities',
    'nvda_PurchasesOfPropertyAndEquipmentAndIntangibleAssets',
    'Payments to Acquire Other Investments',
    'Payments to Acquire Property, Plant, and Equipment',
    'nvda_NetProceedsPaymentsRelatedToEmployeeStockPlans',
    'nvda_PaymentsToAcquireMarketableDebtAndEquitySecurities',
    'nvda_ProceedsFromSaleOfNonMarketableSecurities',
    'nvda_PaymentsToAcquireNonMarketableSecurities',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Proceeds from Sale and Maturity of Marketable Securities',
    'Cash and Cash Equivalents, at Carrying Value',
    'Restricted Cash, Current'
])

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'nvda_BusinessCombinationAdvancedConsiderationWrittenOff': 'Business Combination Advanced Consideration Written Off',
    'nvda_PaymentsForFinancedPropertyPlantAndEquipmentAndIntangibleAssetsFinancingActivities': 'Payments For Financed Property Plant And Equipment And Intangible Assets Financing Activities',
    'PaymentsToAcquireEquitySecuritiesFvNi': 'Payments To Acquire Equity Securities FvNi',
    'ProceedsFromSaleOfEquitySecuritiesFvNi': 'Proceeds From Sale Of Equity Securities FvNi',
    'nvda_ProceedsFromSaleOfEquitySecurities': 'Proceeds From Sale Of Equity Securities',
    'nvda_PaymentsToAcquireEquitySecurities': 'Payments To Acquire Equity Securities'
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Debt, Current': 'Short-term Debt',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt',
    'Operating Lease, Liability, Noncurrent': 'Long-term Operating Lease Liabilities',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments to Acquire Productive Assets': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# 'acc_num' entre '2021-10-31' e '2026-07-26'
df_lst_acc_num_10q_nvda_sorted = df_lst_acc_num_10q_nvda_sliced['acc_num'].sort_index()
df_lst_acc_num_10q_nvda_sliced_2 = df_lst_acc_num_10q_nvda_sorted.loc['2021-10-31':'2026-07-26']

# Fazendo o scraping do leases (10-Q)
leases_lst = []

for acc_num in df_lst_acc_num_10q_nvda_sliced_2:

    # Fazendo o scraping do leases (10-Q) -> 'Note 17 – Leases' -> 'short-term operating lease liabilities'
    leases_10q = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10q = f_sec.rename_statement(leases_10q, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10q = leases_10q.iloc[:, 0]
    leases_lst.append(leases_10q)

# Removendo duplicatas de índice em cada série
leases_lst_clean = [df[~df.index.duplicated(keep='first')] for df in leases_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10q = pd.concat(leases_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_leases_10q = df_leases_10q.drop('us-gaap_LeasesAbstract')

# Renomeando a linha do índice
df_leases_10q = df_leases_10q.rename(index={
    'Operating Lease, Liability, Current': 'Short-term Operating Lease Liabilities',
})

# Selecionando a linha desejada
df_leases_10q = df_leases_10q.loc[['Short-term Operating Lease Liabilities']]

# Criando as colunas dos trimestre de '2020-04-26', '2020-07-26', '2020-10-25', '2021-05-02' e '2021-08-01'
df_leases_10q.loc['Short-term Operating Lease Liabilities', '2020-04-26'] = 100
df_leases_10q.loc['Short-term Operating Lease Liabilities', '2020-07-26'] = 124
df_leases_10q.loc['Short-term Operating Lease Liabilities', '2020-10-25'] = 116
df_leases_10q.loc['Short-term Operating Lease Liabilities', '2021-05-02'] = 135
df_leases_10q.loc['Short-term Operating Lease Liabilities', '2021-08-01'] = 132

# Ordenando o df
df_leases_10q = df_leases_10q[sorted(df_leases_10q.columns, reverse=True)]

df_leases_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')
    df_leases_10q.to_excel(writer, sheet_name='leases')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
nvda_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

nvda_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

nvda_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

nvda_leases = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10k.xlsx', 
    sheet_name='leases', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
nvda_bs.columns = pd.to_datetime(nvda_bs.columns)
nvda_is.columns = pd.to_datetime(nvda_is.columns)
nvda_cf.columns = pd.to_datetime(nvda_cf.columns)
nvda_leases.columns = pd.to_datetime(nvda_leases.columns)

# Transformando as colunas em apenas o ano
nvda_bs.columns = nvda_bs.columns.year
nvda_is.columns = nvda_is.columns.year
nvda_cf.columns = nvda_cf.columns.year
nvda_leases.columns = nvda_leases.columns.year

In [ ]:
# Preços da NVDA
nvda_close = yf.download('NVDA', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Janeiro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025', '2026'
]
last_jan_close = []

for year in lst_years:
    last_close = nvda_close[f'{year}-01'].iloc[-1]
    last_jan_close.append(last_close)

# Transformando em uma série pandas
nvda_close_jan = pd.Series(last_jan_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nvda_close_jan = nvda_close_jan.reindex(index=nvda_close_jan.index[::-1])

# Arredondamento de duas casas decimais
nvda_close_jan = round(nvda_close_jan, 2)

# Teve um split de 10:1 em 10/06/2024 (https://br.investing.com/equities/nvidia-corp-historical-data-splits)
nvda_close_jan.loc['2024'] = nvda_close_jan.loc['2024'] * 10
nvda_close_jan.loc['2023'] = nvda_close_jan.loc['2023'] * 10
nvda_close_jan.loc['2022'] = nvda_close_jan.loc['2022'] * 10
# Teve um split de 4:1 em 20/07/2021 (https://br.investing.com/equities/nvidia-corp-historical-data-splits) 
# Tenho que multiplcar os dois splits (4*10=40)
nvda_close_jan.loc['2021'] = nvda_close_jan.loc['2021'] * 40
nvda_close_jan.loc['2020'] = nvda_close_jan.loc['2020'] * 40
nvda_close_jan.loc['2019'] = nvda_close_jan.loc['2019'] * 40
nvda_close_jan.loc['2018'] = nvda_close_jan.loc['2018'] * 40
nvda_close_jan.loc['2017'] = nvda_close_jan.loc['2017'] * 40

# Transformando o index em int
nvda_close_jan .index = nvda_close_jan .index.astype(int)

nvda_close_jan

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = nvda_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=nvda_close_jan, df_is=nvda_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=nvda_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=nvda_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=nvda_close_jan, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=nvda_close_jan, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=nvda_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=nvda_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=nvda_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=nvda_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=nvda_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=nvda_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=nvda_bs, df_is=nvda_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=nvda_close_jan, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=nvda_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Short-term Debt', 'Long-term Debt', 'Long-term Operating Lease Liabilities']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=nvda_bs, lst_itens_divida=lst_divida)
div_bruta_total = div_bruta.values + nvda_leases.values
div_bruta_total = pd.Series(div_bruta_total[0], index=idx)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta_total, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda =  f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=nvda_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=nvda_is, df_bs=nvda_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=nvda_is, df_bs=nvda_bs, div_bruta=div_bruta_total, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=nvda_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=nvda_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=nvda_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=nvda_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=nvda_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=nvda_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=nvda_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=nvda_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=nvda_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Debt, Net of Issuance Costs']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nvda_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Debt',
    'Payments of Debt Issuance Costs'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nvda_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=nvda_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=nvda_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=nvda_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=nvda_cf, df_is=nvda_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=nvda_cf, df_is=nvda_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=nvda_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=nvda_bs, df_is=nvda_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=nvda_bs, df_is=nvda_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=nvda_bs, df_is=nvda_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=nvda_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=nvda_bs, df_is=nvda_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=nvda_is, df_bs=nvda_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=nvda_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta_total,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
nvda_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
nvda_indicadores_10k.columns = nomes_col
nvda_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
nvda_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

nvda_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

nvda_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

nvda_leases_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_10q.xlsx',
    sheet_name='leases',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
nvda_bs_10q.columns = [f_sec.ajustar_mes_04_07_10(col) for col in nvda_bs_10q.columns]
nvda_is_10q.columns = [f_sec.ajustar_mes_04_07_10(col) for col in nvda_is_10q.columns]
nvda_cf_10q.columns = [f_sec.ajustar_mes_04_07_10(col) for col in nvda_cf_10q.columns]
nvda_leases_10q.columns = [f_sec.ajustar_mes_04_07_10(col) for col in nvda_leases_10q.columns]

In [ ]:
# Preços da NVDA
nvda_close = yf.download('NVDA', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Abril, Julho e Outubro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025',
]
lst_months = ['04', '07', '10']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = nvda_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
nvda_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nvda_close_months = nvda_close_months.reindex(index=nvda_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Fevereiro, Maio e Agosto)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '04', 
    '07', 
    # '10'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = nvda_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
nvda_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nvda_close_months_atual = nvda_close_months_atual.reindex(nvda_close_months_atual.index[::-1])

# Juntando as duas series pandas
nvda_close_months = pd.concat([nvda_close_months_atual, nvda_close_months])

# Arredondamento de duas casas decimais
nvda_close_months = round(nvda_close_months, 2)

# Teve um split de 10:1 em 10/06/2024 (https://br.investing.com/equities/nvidia-corp-historical-data-splits)
nvda_close_months.loc['04-2024'] = nvda_close_months.loc['04-2024'] * 10
nvda_close_months.loc['10-2023'] = nvda_close_months.loc['10-2023'] * 10
nvda_close_months.loc['07-2023'] = nvda_close_months.loc['07-2023'] * 10
nvda_close_months.loc['04-2023'] = nvda_close_months.loc['04-2023'] * 10
nvda_close_months.loc['10-2022'] = nvda_close_months.loc['10-2022'] * 10
nvda_close_months.loc['07-2022'] = nvda_close_months.loc['07-2022'] * 10
nvda_close_months.loc['04-2022'] = nvda_close_months.loc['04-2022'] * 10
nvda_close_months.loc['10-2021'] = nvda_close_months.loc['10-2021'] * 10
nvda_close_months.loc['07-2021'] = nvda_close_months.loc['07-2021'] * 10
# Teve um split de 4:1 em 20/07/2021 (https://br.investing.com/equities/nvidia-corp-historical-data-splits)
# Tenho que multiplcar os dois splits (4*10=40)
nvda_close_months.loc['04-2021'] = nvda_close_months.loc['04-2021'] * 40

# Substituindo o index para ficar igual ao dos dados fundamentalistas
nvda_close_months.index = nvda_bs_10q.columns[:-3]

nvda_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = nvda_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=nvda_close_months, df_is=nvda_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=nvda_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=nvda_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=nvda_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=nvda_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=nvda_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=nvda_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=nvda_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=nvda_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=nvda_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=nvda_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=nvda_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=nvda_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=nvda_bs_10q, df_is=nvda_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=nvda_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=nvda_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Short-term Debt', 'Long-term Debt', 'Long-term Operating Lease Liabilities']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=nvda_bs_10q, lst_itens_divida=lst_divida)
div_bruta_total_10q = div_bruta_10q.values + nvda_leases_10q.loc['Short-term Operating Lease Liabilities'].values[0:-3]
div_bruta_total_10q = pd.Series(div_bruta_total_10q, index=idx_10q[0:-3])

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_total_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q =  f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=nvda_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=nvda_is_10q, df_bs=nvda_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=nvda_is_10q, df_bs=nvda_bs_10q, div_bruta=div_bruta_total_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[2]

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=nvda_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=nvda_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=nvda_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=nvda_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=nvda_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='04')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=nvda_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='04')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=nvda_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='04')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=nvda_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Debt, Net of Issuance Costs']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nvda_cf_10q, first_quarter='04', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=nvda_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=nvda_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=nvda_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=nvda_cf_10q, first_quarter='04')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=nvda_cf_10q, df_is=nvda_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=nvda_cf_10q, df_is=nvda_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=nvda_cf_10q,  first_quarter='04')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=nvda_bs_10q, df_is=nvda_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=nvda_bs_10q, df_is=nvda_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=nvda_bs_10q, df_is=nvda_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=nvda_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=nvda_bs_10q, df_is=nvda_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=nvda_is_10q, df_bs=nvda_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=nvda_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_total_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
nvda_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
nvda_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
nvda_indicadores_10q = nvda_indicadores_10q.fillna(0)

nvda_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//nvidia//nvda_indicators.xlsx') as writer:
    nvda_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    nvda_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## AMD

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'amd'
f_sec.cik_matching_ticker(ticker)

### Scraping AMD 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_amd = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_amd.index = pd.to_datetime(df_lst_acc_num_amd.index, format='%Y-%m-%d')
df_lst_acc_num_amd

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2017 p/ iteração
df_lst_acc_num_amd_sliced = df_lst_acc_num_amd.loc['2017-12-30':]
df_lst_acc_num_amd_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_amd_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10k = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Accounts Payable, Other' na coluna abaixo estão zeradas
# A informação está na linha 'Accounts Payable, Related Parties, Current'
df_balance_sheet_10k.loc['Accounts Payable, Other', '2022-12-31'] = df_balance_sheet_10k.loc['Accounts Payable, Related Parties, Current', '2022-12-31'] 
df_balance_sheet_10k.loc['Accounts Payable, Other', '2021-12-25'] = df_balance_sheet_10k.loc['Accounts Payable, Related Parties, Current', '2021-12-25'] 
df_balance_sheet_10k.loc['Accounts Payable, Other', '2020-12-26'] = df_balance_sheet_10k.loc['Accounts Payable, Related Parties, Current', '2020-12-26'] 
df_balance_sheet_10k.loc['Accounts Payable, Other', '2019-12-28'] = df_balance_sheet_10k.loc['Accounts Payable, Related Parties, Current', '2019-12-28'] 
df_balance_sheet_10k.loc['Accounts Payable, Other', '2018-12-29'] = df_balance_sheet_10k.loc['Accounts Payable, Related Parties, Current', '2018-12-29'] 
df_balance_sheet_10k.loc['Accounts Payable, Other', '2017-12-30'] = df_balance_sheet_10k.loc['Accounts Payable, Related Parties, Current', '2017-12-30'] 

# A linha 'Other Receivables' nas colunas abaixo estão zeradas
# As informações estão na linha 'Related Party Transaction, Due from (to) Related Party, Current' e 'amd_RelatedPartyTransactionPrepaidExpenseCurrent'
df_balance_sheet_10k.loc['Other Receivables', '2022-12-31'] = df_balance_sheet_10k.loc['Related Party Transaction, Due from (to) Related Party, Current', '2022-12-31'] 
df_balance_sheet_10k.loc['Other Receivables', '2021-12-25'] = df_balance_sheet_10k.loc['Related Party Transaction, Due from (to) Related Party, Current', '2021-12-25'] 
df_balance_sheet_10k.loc['Other Receivables', '2020-12-26'] = df_balance_sheet_10k.loc['Related Party Transaction, Due from (to) Related Party, Current', '2020-12-26'] 
df_balance_sheet_10k.loc['Other Receivables', '2019-12-28'] = df_balance_sheet_10k.loc['amd_RelatedPartyTransactionPrepaidExpenseCurrent', '2019-12-28'] 
df_balance_sheet_10k.loc['Other Receivables', '2018-12-29'] = df_balance_sheet_10k.loc['amd_RelatedPartyTransactionPrepaidExpenseCurrent', '2018-12-29'] 
df_balance_sheet_10k.loc['Other Receivables', '2017-12-30'] = df_balance_sheet_10k.loc['amd_RelatedPartyTransactionPrepaidExpenseCurrent', '2017-12-30'] 

# A linha 'Treasury Stock, Common, Shares' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Shares'
df_balance_sheet_10k.loc['Treasury Stock, Common, Shares', '2022-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Shares', '2022-12-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Shares', '2021-12-25'] = df_balance_sheet_10k.loc['Treasury Stock, Shares', '2021-12-25'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Shares', '2020-12-26'] = df_balance_sheet_10k.loc['Treasury Stock, Shares', '2020-12-26'] 

# A linha 'Short-term Investments' nas colunas abaixo estão vazias
# A informação está na linha 'Marketable Securities, Current'
df_balance_sheet_10k.loc['Short-term Investments', '2019-12-28'] = df_balance_sheet_10k.loc['Marketable Securities, Current', '2019-12-28'] 
df_balance_sheet_10k.loc['Short-term Investments', '2018-12-29'] = df_balance_sheet_10k.loc['Marketable Securities, Current', '2018-12-29'] 

# A linha 'Prepaid Expense and Other Assets, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Prepaid Expense, Current'
df_balance_sheet_10k.loc['Prepaid Expense and Other Assets, Current', '2018-12-29'] = df_balance_sheet_10k.loc['Prepaid Expense, Current', '2018-12-29'] 
df_balance_sheet_10k.loc['Prepaid Expense and Other Assets, Current', '2017-12-30'] = df_balance_sheet_10k.loc['Prepaid Expense, Current', '2017-12-30'] 

# A linha 'Short-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Line of Credit, Current'
df_balance_sheet_10k.loc['Short-term Debt', '2018-12-29'] = df_balance_sheet_10k.loc['Line of Credit, Current', '2018-12-29'] 
df_balance_sheet_10k.loc['Short-term Debt', '2017-12-30'] = df_balance_sheet_10k.loc['Line of Credit, Current', '2017-12-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Marketable Securities, Current',
    'Accounts Payable, Related Parties, Current',
    'Treasury Stock, Shares',
    'Related Party Transaction, Due from (to) Related Party, Current',
    'amd_RelatedPartyTransactionPrepaidExpenseCurrent',
    'Prepaid Expense, Current',
    'Line of Credit, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Debt, Current',
    'Treasury Stock, Common, Shares',
    'Other Assets, Current',
    'Deferred Revenue, Current'
])

df_balance_sheet_10k

In [ ]:
# Os dados do income statement da AMD de 2017 não estão consolidados em uma coluna. Eles estão separados em quatro colunas '2017-12-30', '2017-09-30', '2017-07-01' e '2017-04-01'
income_statement_2017 = f_sec.process_one_statement(ticker='amd', accession_number='000000248818000042', statement_name='income_statement')
income_statement_2017 = f_sec.rename_statement(income_statement_2017, label_dictionary=labels_dict)

# Selecionando apenas as quatros primeiras colunas do df
income_statement_2017 = income_statement_2017.iloc[:, 0:4]

# Substituindo os NaN por 0
income_statement_2017 = income_statement_2017.fillna(0)

# Somando as quatro colunas para dar o resultado do income statement de 2017 
is_2017 = income_statement_2017.sum(axis=1)

# Transformando em um df
amd_is_2017 = pd.DataFrame({'2017-12-30':is_2017})

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
amd_is_2017 = amd_is_2017.drop([
    'us-gaap_IncomeStatementAbstract',
    'Amortization of Intangible Assets',
    'amd_RestructuringAndOtherSpecialChargesNet'

])

# Arrumando a escala do df
amd_is_2017.loc['Revenue, Net (Deprecated 2018-01-31)'] = amd_is_2017.loc['Revenue, Net (Deprecated 2018-01-31)'] / 1000000
amd_is_2017.loc['Cost of Goods Sold (Deprecated 2018-01-31)'] = amd_is_2017.loc['Cost of Goods Sold (Deprecated 2018-01-31)'] / 1000000
amd_is_2017.loc['Gross Profit'] = amd_is_2017.loc['Gross Profit'] / 1000000
amd_is_2017.loc['Research and Development Expense'] = amd_is_2017.loc['Research and Development Expense'] / 1000000
amd_is_2017.loc['Selling, General and Administrative Expense'] = amd_is_2017.loc['Selling, General and Administrative Expense'] / 1000000
amd_is_2017.loc['Other Operating Income'] = amd_is_2017.loc['Other Operating Income'] / 1000000
amd_is_2017.loc['Operating Income (Loss)'] = amd_is_2017.loc['Operating Income (Loss)'] / 1000000
amd_is_2017.loc['Interest Expense'] = amd_is_2017.loc['Interest Expense'] / 1000000
amd_is_2017.loc['Other Nonoperating Income (Expense)'] = amd_is_2017.loc['Other Nonoperating Income (Expense)'] / 1000000
amd_is_2017.loc['Income Tax Expense (Benefit)'] = amd_is_2017.loc['Income Tax Expense (Benefit)'] / 1000000
amd_is_2017.loc['Income (Loss) from Equity Method Investments'] = amd_is_2017.loc['Income (Loss) from Equity Method Investments'] / 1000000
amd_is_2017.loc['Net Income (Loss) Attributable to Parent'] = amd_is_2017.loc['Net Income (Loss) Attributable to Parent'] / 1000000

# Arrumando e adicionando alguns números no df
amd_is_2017.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-12-30'] = 69
amd_is_2017.loc['Earnings Per Share, Basic'] = 0.04
amd_is_2017.loc['Earnings Per Share, Diluted'] = 0.04
amd_is_2017.loc['Weighted Average Number of Shares Outstanding, Basic'] = 952
amd_is_2017.loc['Weighted Average Number of Shares Outstanding, Diluted'] = 1039

##############################################################################################

# Os dados do income statement da AMD de 2018 não estão consolidados em uma coluna. Eles estão separados em quatro colunas '2018-12-30', '2018-09-30', '2018-07-01' e '2018-04-01'
income_statement_2018 = f_sec.process_one_statement(ticker='amd', accession_number='000000248819000011', statement_name='income_statement')
income_statement_2018 = f_sec.rename_statement(income_statement_2018, label_dictionary=labels_dict)

# Selecionando apenas as quatros primeiras colunas do df
income_statement_2018 = income_statement_2018.iloc[:, 0:4]

# Substituindo os NaN por 0
income_statement_2018 = income_statement_2018.fillna(0)

# Somando as quatro colunas para dar o resultado do income statement de 2017
is_2018 = income_statement_2018.sum(axis=1)

# Transformando em um df
amd_is_2018 = pd.DataFrame({'2018-12-29':is_2018})

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
amd_is_2018 = amd_is_2018.drop([
    'us-gaap_IncomeStatementAbstract',
    'amd_RestructuringAndOtherSpecialChargesNet'
])

# Arrumando e adicionando alguns números no df
amd_is_2018.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-12-29'] = 330
amd_is_2018.loc['Weighted Average Number of Shares Outstanding, Basic', '2018-12-29'] = 982
amd_is_2018.loc['Weighted Average Number of Shares Outstanding, Diluted', '2018-12-29'] = 1064

# Renomeando o index do df do income statement de 2017
idx_renamed = {
    'Revenue, Net (Deprecated 2018-01-31)': 'Revenue from Contract with Customer, Excluding Assessed Tax',
    'Cost of Goods Sold (Deprecated 2018-01-31)': 'Cost of Goods and Services Sold', 
}
amd_is_2017 = amd_is_2017.rename(index=idx_renamed)

# Juntandos os dfs de 2017 e 2018 
df_is_1718 = pd.concat([amd_is_2018, amd_is_2017], axis=1)

# Adicionando as linhas ('Amortization Of Acquisition Related Intangibles' e 'Gain Loss On Licensing Agreement') p/ ficar do mesmo tamanho do 'df_income_statement_10k'
novas_linhas = pd.DataFrame({'2018-12-29': [0], '2017-12-30': [0]}, index=['Amortization Of Acquisition Related Intangibles', 'Gain Loss On Licensing Agreement'])
df_is_1718 = pd.concat([df_is_1718, novas_linhas])

# Arrumando a formatação da coluna '2017-12-30' (os nº estão com zeros a mais e fica mostrando em notação científica)
df_is_1718.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-30'] = df_is_1718.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-30'] 
df_is_1718.loc['Cost of Goods and Services Sold', '2017-12-30'] = df_is_1718.loc['Cost of Goods and Services Sold', '2017-12-30'] 
df_is_1718.loc['Gross Profit', '2017-12-30'] = df_is_1718.loc['Gross Profit', '2017-12-30'] 
df_is_1718.loc['Research and Development Expense', '2017-12-30'] = df_is_1718.loc['Research and Development Expense', '2017-12-30'] 
df_is_1718.loc['Selling, General and Administrative Expense', '2017-12-30'] = df_is_1718.loc['Selling, General and Administrative Expense', '2017-12-30'] 
df_is_1718.loc['Operating Income (Loss)', '2017-12-30'] = df_is_1718.loc['Operating Income (Loss)', '2017-12-30']
df_is_1718.loc['Interest Expense', '2017-12-30'] = df_is_1718.loc['Interest Expense', '2017-12-30']
df_is_1718.loc['Other Nonoperating Income (Expense)', '2017-12-30'] = df_is_1718.loc['Other Nonoperating Income (Expense)', '2017-12-30']
df_is_1718.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-12-30'] = df_is_1718.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-12-30']
df_is_1718.loc['Income Tax Expense (Benefit)', '2017-12-30'] = df_is_1718.loc['Income Tax Expense (Benefit)', '2017-12-30'] 
df_is_1718.loc['Income (Loss) from Equity Method Investments', '2017-12-30'] = df_is_1718.loc['Income (Loss) from Equity Method Investments', '2017-12-30'] 
df_is_1718.loc['Net Income (Loss) Attributable to Parent', '2017-12-30'] = df_is_1718.loc['Net Income (Loss) Attributable to Parent', '2017-12-30']
df_is_1718.loc['Other Operating Income', '2017-12-30'] = df_is_1718.loc['Other Operating Income', '2017-12-30']

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_is_1718 = df_is_1718.drop([
    'Amortization Of Acquisition Related Intangibles',
    'Gain Loss On Licensing Agreement',
    'Other Operating Income'
])

##############################################################################################

# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_amd_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10k = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'amd_GainLossOnLicensingAgreement' na coluna abaixo está zerada
# A informação está na linha 'amd_GainOnLicensingAgreement'
df_income_statement_10k.loc['amd_GainLossOnLicensingAgreement', '2019-12-28'] = df_income_statement_10k.loc['amd_GainOnLicensingAgreement', '2019-12-28'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop('amd_GainOnLicensingAgreement')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'amd_RestructuringAndOtherSpecialChargesNet',
    'Other Operating Income',
    'Amortization of Intangible Assets',
    'Revenue, Net (Deprecated 2018-01-31)',
    'Cost of Goods Sold (Deprecated 2018-01-31)',
    'Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization',
    'amd_AmortizationOfAcquisitionRelatedIntangibles',
    'Cost, Depreciation, Amortization and Depletion',
    'amd_AmortizationOfAcquisitionRelatedIntangiblesCOGS'
])

# Excluindo a coluna do ano de '2017' e '2018', pois ela não está com os dados consolidados do período
df_income_statement_10k = df_income_statement_10k.drop('2017-12-30', axis=1)
df_income_statement_10k = df_income_statement_10k.drop('2018-12-29', axis=1)

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'amd_AmortizationOfAcquisitionRelatedIntangibles_Opex': 'Amortization Of Acquisition Related Intangibles',
    'amd_GainLossOnLicensingAgreement': 'Gain Loss On Licensing Agreement'
})

# Arrumando alguns números no df
df_income_statement_10k.loc['Earnings Per Share, Basic', '2024-12-28'] = 1.01
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2024-12-28'] = 1.00
df_income_statement_10k.loc['Earnings Per Share, Basic', '2023-12-30'] = 0.53
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2023-12-30'] = 0.53
df_income_statement_10k.loc['Earnings Per Share, Basic', '2022-12-31'] = 0.85
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2022-12-31'] = 0.84
df_income_statement_10k.loc['Earnings Per Share, Basic', '2021-12-25'] = 2.61
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2021-12-25'] = 2.57
df_income_statement_10k.loc['Earnings Per Share, Basic', '2020-12-26'] = 2.10
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2020-12-26'] = 2.06
df_income_statement_10k.loc['Earnings Per Share, Basic', '2019-12-28'] = 0.31
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2019-12-28'] = 0.30

# Adicionando as colunas dos anos de 2017 e 2018 no df
df_income_statement_10k_final = pd.concat([df_income_statement_10k, df_is_1718], axis=1)

# Transformando o tipo das colunas de str p/ datetime
df_income_statement_10k_final.columns = pd.to_datetime(df_income_statement_10k_final.columns, format='%Y-%m-%d')

# Substituindo os NaN por 0
df_income_statement_10k_final = df_income_statement_10k_final.fillna(0)

df_income_statement_10k_final

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_amd_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Proceeds from Maturities, Prepayments and Calls of Short-term Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale, Maturity and Collection of Short-term Investments'
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2022-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Short-term Investments', '2022-12-31'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2021-12-25'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Short-term Investments', '2021-12-25'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2020-12-26'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Short-term Investments', '2020-12-26'] 

# A linha 'Other Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Depreciation, Depletion and Amortization'
df_cash_flow_10k.loc['Other Depreciation and Amortization', '2019-12-28'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2019-12-28'] 
df_cash_flow_10k.loc['Other Depreciation and Amortization', '2018-12-29'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2018-12-29'] 
df_cash_flow_10k.loc['Other Depreciation and Amortization', '2017-12-30'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2017-12-30'] 

#  A linha 'Increase (Decrease) in Due to Related Parties' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accounts Payable, Related Parties'
df_cash_flow_10k.loc['Increase (Decrease) in Due to Related Parties', '2019-12-28'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable, Related Parties', '2019-12-28'] 
df_cash_flow_10k.loc['Increase (Decrease) in Due to Related Parties', '2018-12-29'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable, Related Parties', '2018-12-29'] 
df_cash_flow_10k.loc['Increase (Decrease) in Due to Related Parties', '2017-12-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable, Related Parties', '2017-12-30'] 

# A linha 'Increase (Decrease) in Accounts Payable' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accounts Payable and Accrued Liabilities'
df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable', '2019-12-28'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable and Accrued Liabilities', '2019-12-28'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable', '2018-12-29'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable and Accrued Liabilities', '2018-12-29'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable', '2017-12-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable and Accrued Liabilities', '2017-12-30'] 

# A linha 'Proceeds from Maturities, Prepayments and Calls of Short-term Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale'
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2019-12-28'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2019-12-28'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2018-12-29'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2018-12-29'] 
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2017-12-30'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2017-12-30'] 

#  A linha 'Repayments of Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Long-term Debt' e 'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security'
df_cash_flow_10k.loc['Repayments of Debt', '2019-12-28'] = df_cash_flow_10k.loc['Repayments of Long-term Debt', '2019-12-28'] 
df_cash_flow_10k.loc['Repayments of Debt', '2018-12-29'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2018-12-29'] 
df_cash_flow_10k.loc['Repayments of Debt', '2017-12-30'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2017-12-30'] 

# A linha 'amd_AcquisitionsNetOfCashAcquiredAllOthers' na coluna abaixo está zerada
# As informações estão na linha 'Payments to Acquire Businesses, Net of Cash Acquired'
df_cash_flow_10k.loc['amd_AcquisitionsNetOfCashAcquiredAllOthers', '2022-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2022-12-31']

# A linha 'Operating Lease, Right-of-Use Asset, Amortization Expense' na coluna abaixo está zerada
# As informações estão na linha 'amd_OperatingLeaseRightofUseAssetAmortization'                                        
df_cash_flow_10k.loc['Operating Lease, Right-of-Use Asset, Amortization Expense', '2019-12-28'] = df_cash_flow_10k.loc['amd_OperatingLeaseRightofUseAssetAmortization', '2019-12-28'] 

# A linha 'Payments to Acquire Short-term Investments' na coluna abaixo está zerada
# As informações estão na linha 'Payments to Acquire Debt Securities, Available-for-sale'
df_cash_flow_10k.loc['Payments to Acquire Short-term Investments', '2019-12-28'] = df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2019-12-28'] 

#  A linha 'Proceeds from Short-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from (Repayments of) Short-term Debt'
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2019-12-28'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Short-term Debt', '2019-12-28'] 

#  A linha 'Gain (Loss) on Disposition of Property Plant Equipment' na coluna abaixo está zerada
# As informações estão na linha 'Gain (Loss) on Disposition of Assets'
df_cash_flow_10k.loc['Gain (Loss) on Disposition of Property Plant Equipment', '2018-12-29'] = df_cash_flow_10k.loc['Gain (Loss) on Disposition of Assets', '2018-12-29'] 

#  A linha 'Payments to Acquire Short-term Investments' na coluna abaixo está zerada
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities'
df_cash_flow_10k.loc['Payments to Acquire Short-term Investments', '2018-12-29'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2018-12-29'] 

#  A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' na coluna abaixo está zerada
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-12-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-12-30'] 

#  A linha 'Proceeds from Short-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from (Repayments of) Lines of Credit'
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2017-12-30'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Lines of Credit', '2017-12-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Proceeds from Sale, Maturity and Collection of Short-term Investments',
    'Depreciation, Depletion and Amortization',
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'amd_OperatingLeaseRightofUseAssetAmortization',
    'Increase (Decrease) in Accounts Payable, Related Parties',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Payments to Acquire Debt Securities, Available-for-sale',
    'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale',
    'Proceeds from (Repayments of) Short-term Debt',
    'Gain (Loss) on Disposition of Assets',
    'Payments to Acquire Available-for-sale Securities',
    'Repayments of Long-term Debt',
    'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Proceeds from (Repayments of) Lines of Credit',
    'Proceeds from Divestiture of Interest in Consolidated Subsidiaries'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Other Adjustments to Income, Discontinued Operations',
    'amd_AmortizationOfInventoryFairValueAdjustment',
    'amd_IssuanceOfTreasuryStockToPartiallySettleDebt',
    'Restricted Cash, Current',
    'amd_DeferredProceedsOnSaleOfReceivable',
    'amd_DeferredCashOnSoldReceivables',
    'Issuance of Stock and Warrants for Services or Claims',
    'Proceeds from Issuance of Common Stock',
    'Proceeds from Issuance of Long-term Debt',
    'amd_RestructuringandOtherSpecialChargesNetNoncash',
    'Proceeds from Sale of Property, Plant, and Equipment',
    'Other Significant Noncash Transaction, Value of Consideration Given',
    'Stock Issued',
    'amd_NoncashActivitiesOther',
    'Conversion of Stock, Amount Converted',
    'Cash Acquired from Acquisition',
    'Deconsolidation, Gain (Loss), Amount',
    'amd_Deferredcashonsoldreceivables',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Cash Provided by (Used in) Operating Activities, Discontinued Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'amd_InventoryLossAtRecoveryFromContractManufacturer',
    'Asset Impairment Charges',
    'Proceeds from Warrant Exercises',
])

# Arrumando alguns números no df
df_cash_flow_10k.loc['amd_AcquisitionsNetOfCashAcquiredAllOthers', '2023-12-30'] = -131
df_cash_flow_10k.loc['Amortization', '2023-12-30'] = 2811 	
df_cash_flow_10k.loc['Amortization', '2022-12-31'] = 3548 	
df_cash_flow_10k.loc['Payments to Acquire Short-term Investments', '2017-12-30'] = -222 	
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities', '2019-12-28'] = 220 	 	
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities', '2018-12-29'] = 81 	
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities', '2017-12-30'] = -8 	
df_cash_flow_10k.loc['Payments to Acquire Other Investments', '2023-12-30'] = 11 	
df_cash_flow_10k.loc['Payments to Acquire Other Investments', '2022-12-31'] = 5 	
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-30'] = 1266
	
# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'amd_IncreaseDecreaseinPrepaymentsRelatedParties': 'Increase Decrease in Prepayments Related Parties',
    'amd_AcquisitionsNetOfCashAcquiredAllOthers': 'Acquisitions Net Of Cash Acquired All Others',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Short-term Investments': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k_final = df_income_statement_10k_final.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Other Depreciation and Amortization': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k_final.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping AMD 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_amd = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_amd.index = pd.to_datetime(df_lst_acc_num_10q_amd.index, format='%Y-%m-%d')
df_lst_acc_num_10q_amd

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2020 p/ iteração
df_lst_acc_num_10q_amd_sliced = df_lst_acc_num_10q_amd.loc['2020-03-28':]
df_lst_acc_num_10q_amd_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_amd_sliced['acc_num']:

    # Cash flow statement
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Other Receivables, Net, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Due from Related Parties, Current'
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2022-09-24'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2022-09-24'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2022-06-25'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2022-06-25'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2022-03-26'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2022-03-26'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2021-09-25'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2021-09-25'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2021-06-26'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2021-06-26'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2021-03-27'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2021-03-27'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2020-09-26'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2020-09-26'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2020-06-27'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2020-06-27'] 
df_balance_sheet_10q.loc['Other Receivables, Net, Current', '2020-03-28'] = df_balance_sheet_10q.loc['Due from Related Parties, Current', '2020-03-28'] 

# A linha 'Accounts Payable, Other' nas colunas abaixo estão zeradas
# As informações estão na linha 'Due to Related Parties, Current'
df_balance_sheet_10q.loc['Accounts Payable, Other', '2022-09-24'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2022-09-24'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2022-06-25'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2022-06-25'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2022-03-26'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2022-03-26'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2021-09-25'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2021-09-25'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2021-06-26'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2021-06-26'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2021-03-27'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2021-03-27'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2020-09-26'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2020-09-26'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2020-06-27'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2020-06-27'] 
df_balance_sheet_10q.loc['Accounts Payable, Other', '2020-03-28'] = df_balance_sheet_10q.loc['Due to Related Parties, Current', '2020-03-28'] 

# A linha 'Short-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt, Current Maturities'
df_balance_sheet_10q.loc['Short-term Debt', '2026-03-28'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2026-03-28'] 
df_balance_sheet_10q.loc['Short-term Debt', '2025-09-27'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2025-09-27'] 

# A linha 'Short-term Investments' na coluna abaixo está zerada
# As informações estão na linha 'Marketable Securities, Current'
df_balance_sheet_10q.loc['Short-term Investments', '2020-03-28'] = df_balance_sheet_10q.loc['Marketable Securities, Current', '2020-03-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Due from Related Parties, Current',
    'Due to Related Parties, Current',
    'Long-term Debt, Current Maturities',
    'Marketable Securities, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Common Stock, Shares, Outstanding',
    'Common Stock, Par or Stated Value Per Share',
    'Common Stock, Shares Authorized',
    'Common Stock, Shares, Issued'
])

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_amd_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'amd_AmortizationOfAcquisitionRelatedIntangiblesOpex' nas colunas abaixo estão zeradas
# As informações estão na linha 'Amortization of Intangible Assets'
df_income_statement_10q.loc['amd_AmortizationOfAcquisitionRelatedIntangiblesOpex', '2022-06-25'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2022-06-25'] 
df_income_statement_10q.loc['amd_AmortizationOfAcquisitionRelatedIntangiblesOpex', '2022-03-26'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2022-03-26'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop('Amortization of Intangible Assets')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization',
    'amd_AmortizationOfAcquisitionRelatedIntangiblesCOGS',
    'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Basic Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Diluted Share',
])

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2026-03-28'] = 0.01
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2024-06-29'] = 0.16
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2023-04-01'] = -0.09
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2020-06-27'] = 0.13
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2020-03-28'] = 0.14

# Renomeando algumas linhas do índice
df_income_statement_10q = df_income_statement_10q.rename(index={
    'amd_AmortizationOfAcquisitionRelatedIntangiblesOpex': 'Amortization Of Acquisition Related Intangibles - OPEX',
    'amd_GainOnLicensingAgreement': 'Gain On Licensing Agreement'
})

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_amd_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Increase (Decrease) in Due from Related Parties' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Due from Related Parties, Current'
df_cash_flow_10q.loc['Increase (Decrease) in Due from Related Parties', '2020-09-26'] = df_cash_flow_10q.loc['Increase (Decrease) in Due from Related Parties, Current', '2020-09-26']
df_cash_flow_10q.loc['Increase (Decrease) in Due from Related Parties', '2020-06-27'] = df_cash_flow_10q.loc['Increase (Decrease) in Due from Related Parties, Current', '2020-06-27']
df_cash_flow_10q.loc['Increase (Decrease) in Due from Related Parties', '2020-03-28'] = df_cash_flow_10q.loc['Increase (Decrease) in Due from Related Parties, Current', '2020-03-28']

# A linha 'Increase (Decrease) in Due to Related Parties' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Due to Related Parties, Current'
df_cash_flow_10q.loc['Increase (Decrease) in Due to Related Parties', '2020-09-26'] = df_cash_flow_10q.loc['Increase (Decrease) in Due to Related Parties, Current', '2020-09-26']
df_cash_flow_10q.loc['Increase (Decrease) in Due to Related Parties', '2020-06-27'] = df_cash_flow_10q.loc['Increase (Decrease) in Due to Related Parties, Current', '2020-06-27']
df_cash_flow_10q.loc['Increase (Decrease) in Due to Related Parties', '2020-03-28'] = df_cash_flow_10q.loc['Increase (Decrease) in Due to Related Parties, Current', '2020-03-28']

# A linha 'Increase (Decrease) in Accounts Payable' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accounts Payable and Accrued Liabilities'
df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2020-09-26'] = df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable and Accrued Liabilities', '2020-09-26']
df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2020-06-27'] = df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable and Accrued Liabilities', '2020-06-27']
df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2020-03-28'] = df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable and Accrued Liabilities', '2020-03-28']

# A linha 'amd_AcquisitionsNetOfCashAcquiredAllOthers' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Businesses, Gross' e 'Payments to Acquire Businesses, Net of Cash Acquired'
df_cash_flow_10q.loc['amd_AcquisitionsNetOfCashAcquiredAllOthers', '2022-09-24'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Gross', '2022-09-24']
df_cash_flow_10q.loc['amd_AcquisitionsNetOfCashAcquiredAllOthers', '2022-06-25'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2022-06-25']

# A linha 'Equity Securities, FV-NI, Gain (Loss)' nas colunas abaixo estão zeradas
# As informações estão na linha 'Other than Temporary Impairment Losses, Investments'
df_cash_flow_10q.loc['Equity Securities, FV-NI, Gain (Loss)', '2021-06-26'] = df_cash_flow_10q.loc['Other than Temporary Impairment Losses, Investments', '2021-06-26']
df_cash_flow_10q.loc['Equity Securities, FV-NI, Gain (Loss)', '2021-03-27'] = df_cash_flow_10q.loc['Other than Temporary Impairment Losses, Investments', '2021-03-27']

# A linha 'Operating Lease, Right-of-Use Asset, Amortization Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'amd_OperatingLeaseRightofUseAssetAmortization'
df_cash_flow_10q.loc['Operating Lease, Right-of-Use Asset, Amortization Expense', '2020-06-27'] = df_cash_flow_10q.loc['amd_OperatingLeaseRightofUseAssetAmortization', '2020-06-27']
df_cash_flow_10q.loc['Operating Lease, Right-of-Use Asset, Amortization Expense', '2020-03-28'] = df_cash_flow_10q.loc['amd_OperatingLeaseRightofUseAssetAmortization', '2020-03-28']

# A linha 'Payments to Acquire Short-term Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Debt Securities, Available-for-sale'
df_cash_flow_10q.loc['Payments to Acquire Short-term Investments', '2020-06-27'] = df_cash_flow_10q.loc['Payments to Acquire Debt Securities, Available-for-sale', '2020-06-27']
df_cash_flow_10q.loc['Payments to Acquire Short-term Investments', '2020-03-28'] = df_cash_flow_10q.loc['Payments to Acquire Debt Securities, Available-for-sale', '2020-03-28']

# A linha 'Proceeds from Maturities, Prepayments and Calls of Short-term Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale'
df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2020-06-27'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-06-27']
df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2020-03-28'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-03-28']

# A linha 'Repayments of Debt' na coluna abaixo está zerada
# As informações estão na linha 'Repayments of Short-term Debt'
df_cash_flow_10q.loc['Repayments of Debt', '2022-09-24'] = df_cash_flow_10q.loc['Repayments of Short-term Debt', '2022-09-24']

# A linha 'Other Depreciation and Amortization' na coluna abaixo está zerada
# As informações estão na linha 'Depreciation, Depletion and Amortization'
df_cash_flow_10q.loc['Other Depreciation and Amortization', '2023-09-30'] = df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2023-09-30']

# A linha 'amd_InventoryLossAtContractManufacturer' na coluna abaixo está zerada
# As informações estão na linha 'Inventory Write-down'
df_cash_flow_10q.loc['amd_InventoryLossAtContractManufacturer', '2024-03-30'] = df_cash_flow_10q.loc['Inventory Write-down', '2024-03-30']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Depreciation, Depletion and Amortization',
    'Inventory Write-down',
    'Payments to Acquire Businesses, Gross',
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'Other than Temporary Impairment Losses, Investments',
    'Increase (Decrease) in Due from Related Parties, Current',
    'Increase (Decrease) in Due to Related Parties, Current',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'amd_OperatingLeaseRightofUseAssetAmortization',
    'Payments to Acquire Debt Securities, Available-for-sale',
    'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale',
    'Repayments of Short-term Debt'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Proceeds from Issuance of Unsecured Debt',
    'Proceeds from Sale and Collection of Receivables',
    'Proceeds from Warrant Exercises',
    'amd_IssuanceOfTreasuryStockToPartiallySettleDebt',
    'Stock Issued',
    'Repayments of Long-term Debt',
    'Other Adjustments to Income, Discontinued Operations',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Cash Provided by (Used in) Operating Activities, Discontinued Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'Cash Provided by (Used in) Investing Activities, Discontinued Operations',
    'Cash and Cash Equivalents, at Carrying Value, Including Discontinued Operations',
    'Restricted Cash',
    'Restricted Cash, Current',
    'Stock Issued During Period, Value, Treasury Stock Reissued',
    'AssetAcquisitionContingentConsiderationLiability',
    'Payments to Acquire Interest in Subsidiaries and Affiliates',
    'amd_LiabilitiesAssumedRSUTaxWithholding',
    'amd_InventoryLossAtContractManufacturer',
    'Cash Acquired from Acquisition',
    'amd_AcquisitionsNetOfCashAcquiredAllOthers',
    'Business Combination, Consideration Transferred, Equity Interests Issued and Issuable',
    'Gain (Loss) on Extinguishment of Debt',
    'Stock Issued During Period, Value, Conversion of Convertible Securities',
    'Noncash or Part Noncash Acquisition, Fixed Assets Acquired',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Disposal Group, Including Discontinued Operations'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['amd_AmortizationOfInventoryFairValueAdjustment', '2022-09-24'] = 187
df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2024-06-29'] = 4113
df_cash_flow_10q.loc['Other Depreciation and Amortization', '2020-06-27'] = 140
df_cash_flow_10q.loc['Other Depreciation and Amortization', '2020-03-28'] = 68

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'amd_ReleaseOfReservesForTaxLiabilities': 'Release Of Reserves For Tax Liabilities',
    'amd_AmortizationOfInventoryFairValueAdjustment': 'Amortization Of Inventory Fair Value Adjustment',
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Short-term Investments': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Other Depreciation and Amortization': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
amd_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

amd_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

amd_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
amd_bs.columns = pd.to_datetime(amd_bs.columns)
amd_is.columns = pd.to_datetime(amd_is.columns)
amd_cf.columns = pd.to_datetime(amd_cf.columns)

# Transformando as colunas em apenas o ano
amd_bs.columns = amd_bs.columns.year
amd_is.columns = amd_is.columns.year
amd_cf.columns = amd_cf.columns.year

In [ ]:
# Preços da AMD
amd_close = yf.download('AMD', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_dec_close = []

for year in lst_years:
    last_close = amd_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
amd_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amd_close_dec = amd_close_dec.reindex(index=amd_close_dec.index[::-1])

# Arredondamento de duas casas decimais
amd_close_dec = round(amd_close_dec, 2)

# Não realizou split recentemente (https://br.investing.com/equities/adv-micro-device-historical-data-splits)

# Transformando o index em int
amd_close_dec.index = amd_close_dec.index.astype(int)

amd_close_dec

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = amd_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=amd_close_dec, df_is=amd_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=amd_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=amd_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=amd_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=amd_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=amd_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=amd_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=amd_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=amd_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=amd_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=amd_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=amd_bs, df_is=amd_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=amd_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=amd_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Short-term Debt', 'Long-term Debt, Excluding Current Maturities', 'Operating Lease, Liability, Noncurrent']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=amd_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda =  f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=amd_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=amd_is, df_bs=amd_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=amd_is, df_bs=amd_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=amd_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=amd_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=amd_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=amd_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=amd_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=amd_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=amd_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=amd_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase Decrease in Prepayments Related Parties',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Due to Related Parties',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities',
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=amd_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=amd_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Short-term Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amd_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amd_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=amd_is, idx=idx)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=amd_is,
    idx=idx
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=amd_is,
        idx=idx
)

# DPA e Payout - AMD não paga dividendo

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=amd_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=amd_bs, df_is=amd_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=amd_bs, df_is=amd_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=amd_bs, df_is=amd_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=amd_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=amd_bs, df_is=amd_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=amd_is, df_bs=amd_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=amd_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10q,
    fcff_10q,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
amd_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
amd_indicadores_10k.columns = nomes_col
amd_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
amd_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

amd_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

amd_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
amd_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amd_bs_10q.columns]
amd_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amd_is_10q.columns]
amd_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amd_cf_10q.columns]

In [ ]:
# Preços da AMD
amd_close = yf.download('AMD', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025',
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = amd_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
amd_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amd_close_months = amd_close_months.reindex(index=amd_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = amd_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
amd_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amd_close_months_atual = amd_close_months_atual.reindex(index=amd_close_months_atual.index[::-1])

# Juntando as duas series pandas
amd_close_months = pd.concat([amd_close_months_atual, amd_close_months])

# Arredondamento de duas casas decimais
amd_close_months = round(amd_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/adv-micro-device-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
amd_close_months.index = amd_bs_10q.columns[:-3]

amd_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = amd_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=amd_close_months, df_is=amd_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=amd_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=amd_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=amd_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=amd_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=amd_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=amd_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=amd_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=amd_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=amd_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=amd_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=amd_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=amd_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=amd_bs_10q, df_is=amd_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=amd_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=amd_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Short-term Debt', 'Long-term Debt, Excluding Current Maturities', 'Operating Lease, Liability, Noncurrent']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=amd_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q =  f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=amd_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=amd_is_10q, df_bs=amd_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=amd_is_10q, df_bs=amd_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=amd_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=amd_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=amd_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=amd_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=amd_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=amd_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Due to Related Parties',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=amd_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=amd_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=amd_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=amd_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt', 'Repayments of Commercial Paper']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amd_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=amd_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=amd_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=amd_is_10q,
        idx=idx_10q
)

# DPA e Payout - AMD não paga dividendo

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=amd_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=amd_bs_10q, df_is=amd_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=amd_bs_10q, df_is=amd_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=amd_bs_10q, df_is=amd_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=amd_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=amd_bs_10q, df_is=amd_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=amd_is_10q, df_bs=amd_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=amd_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
amd_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
amd_indicadores_10q.columns = nomes_col
amd_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//amd//amd_indicators.xlsx') as writer:
    amd_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    amd_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Intel

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'intc'
f_sec.cik_matching_ticker(ticker)

### Scraping Intel 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_intel = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando o 'acc_num' de 2017
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000005086319000007', # 2018
            '000005086318000007', # 2017
        ]
    },
    index=pd.to_datetime([
        '2018-12-30',
        '2017-12-30',
    ])
)

# Concatenando os dfs
df_lst_acc_num_intel = pd.concat([df_lst_acc_num_intel, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_intel.index = pd.to_datetime(df_lst_acc_num_intel.index, format='%Y-%m-%d')

df_lst_acc_num_intel

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_intel['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10k = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# A informação está na linha 'Property, Plant and Equipment, Net'
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2022-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2022-12-31'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2021-12-25'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2021-12-25'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-12-26'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2020-12-26'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-12-28'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2019-12-28'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2018-12-29'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2018-12-29'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2017-12-30'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2017-12-30'] 

# A linha 'intc_EquityInvestments' nas colunas abaixo estão zeradas
# A informação está na linha 'Available-for-sale Securities, Equity Securities, Noncurrent'
df_balance_sheet_10k.loc['intc_EquityInvestments', '2020-12-26'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Equity Securities, Noncurrent', '2020-12-26'] 
df_balance_sheet_10k.loc['intc_EquityInvestments', '2019-12-28'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Equity Securities, Noncurrent', '2019-12-28'] 
df_balance_sheet_10k.loc['intc_EquityInvestments', '2018-12-29'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Equity Securities, Noncurrent', '2018-12-29'] 
df_balance_sheet_10k.loc['intc_EquityInvestments', '2017-12-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Equity Securities, Noncurrent', '2017-12-30'] 

# A linha 'Deferred Income Tax Liabilities, Net' nas colunas abaixo estão zeradas
# A informação está na linha 'Deferred Tax Liabilities, Net, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2020-12-26'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2020-12-26'] 
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2019-12-28'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2019-12-28'] 
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2018-12-29'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2018-12-29'] 
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2017-12-30'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2017-12-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# A informação está na linha 'Cash and Cash Equivalents, at Carrying Value'
df_balance_sheet_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-12-29'] = df_balance_sheet_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-12-29'] 
df_balance_sheet_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-30'] = df_balance_sheet_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-12-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop('Property, Plant and Equipment, Net')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Contract with Customer, Liability, Current',
    'Disposal Group, Including Discontinued Operation, Liabilities, Current',
    'Disposal Group, Including Discontinued Operation, Assets, Current',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest",
    'Deferred Revenue, Current',
    'Cash and Cash Equivalents, at Carrying Value'
])

# Renomeando as linhas do índice que estão sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'intc_EquityInvestments': 'Equity Investments'
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_intel['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10k = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Equity Securities, FV-NI, Gain (Loss)' na coluna abaixo estão zeradas
# As informações estão nsa linhas 'intc_GainsLossesOnEquityInvestments' e 'Gain (Loss) on Investments' 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2024-12-28'] = df_income_statement_10k.loc['intc_GainsLossesOnEquityInvestments', '2024-12-28'] 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2021-12-25'] = df_income_statement_10k.loc['Gain (Loss) on Investments', '2021-12-25'] 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2021-12-25'] = df_income_statement_10k.loc['Gain (Loss) on Investments', '2021-12-25'] 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2020-12-26'] = df_income_statement_10k.loc['Gain (Loss) on Investments', '2020-12-26'] 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2019-12-28'] = df_income_statement_10k.loc['Gain (Loss) on Investments', '2019-12-28'] 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2018-12-29'] = df_income_statement_10k.loc['Gain (Loss) on Investments', '2018-12-29'] 
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2017-12-30'] = df_income_statement_10k.loc['Gain (Loss) on Investments', '2017-12-30'] 

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' na coluna abaixo está zerada
# As informações estão na linha 'Revenue, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-30'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-12-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'intc_GainsLossesOnEquityInvestments',
    'Gain (Loss) on Investments',
    'Revenue, Net (Deprecated 2018-01-31)',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Depreciation, Depletion and Amortization, Nonproduction'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop('us-gaap_IncomeStatementAbstract')

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['Earnings Per Share, Diluted', '2025-12-27'] = -0.06
df_income_statement_10k.loc['Equity Securities, FV-NI, Gain (Loss)', '2025-12-27'] = 514

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_intel['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss) Attributable to Parent'
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-12-25'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2021-12-25'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-12-26'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2020-12-26'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-12-28'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2019-12-28'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2018-12-29'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2018-12-29'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2017-12-30'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2017-12-30'] 

# A linha 'Restructuring Charges' nas colunas abaixo estão zeradas
# As informações estão na linha 'Restructuring, Settlement and Impairment Provisions'
df_cash_flow_10k.loc['Restructuring Charges', '2021-12-25'] = df_cash_flow_10k.loc['Restructuring, Settlement and Impairment Provisions', '2021-12-25']  
df_cash_flow_10k.loc['Restructuring Charges', '2017-12-30'] = df_cash_flow_10k.loc['Restructuring, Settlement and Impairment Provisions', '2017-12-30']  

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-12-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-12-29'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-12-30'] 

# A linha 'Net Cash Provided by (Used in) Operating Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Operating Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2018-12-29'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities, Continuing Operations', '2018-12-29'] 
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2017-12-30'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities, Continuing Operations', '2017-12-30'] 

# A linha 'Net Cash Provided by (Used in) Investing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Investing Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2018-12-29'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities, Continuing Operations', '2018-12-29'] 
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2017-12-30'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities, Continuing Operations', '2017-12-30'] 

# A linha 'Net Cash Provided by (Used in) Financing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Financing Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2018-12-29'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities, Continuing Operations', '2018-12-29'] 
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2017-12-30'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities, Continuing Operations', '2017-12-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-12-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-12-29'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-12-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-12-30'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities'
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2017-12-30'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2017-12-30'] 

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities'
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-12-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-12-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Net Income (Loss) Attributable to Parent',
    'Restructuring, Settlement and Impairment Provisions',
    'Cash and Cash Equivalents, at Carrying Value',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Sale of Available-for-sale Securities',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'Transfer to Investments',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Financing Activities, Continuing Operations',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Gain (Loss) on Sale of Equity Investments',
    'Payment, Tax Withholding, Share-based Payment Arrangement',
    'Gain (Loss) on Extinguishment of Debt',
    'Proceeds from (Repayments of) Short-term Debt',
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Equity Securities, FV-NI', '2017-12-30'] = -2583
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2023-12-30'] = -2033
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2022-12-31'] = -5148
df_cash_flow_10k.loc['intc_AssetImpairmentChargesAndGainLossOnDisposalOfPropertyPlantAndEquipment', '2023-12-30'] = 33
df_cash_flow_10k.loc['intc_AssetImpairmentChargesAndGainLossOnDisposalOfPropertyPlantAndEquipment', '2022-12-31'] = 301
df_cash_flow_10k.loc['intc_ProceedsFromCapitalGrants', '2022-12-31'] = 246
df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2023-12-30'] = -13
df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2022-12-31'] = -681
df_cash_flow_10k.loc['Proceeds from Equity Method Investment, Distribution, Return of Capital', '2017-12-30'] = 5236
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-12-30'] = 1105

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'intc_AssetImpairmentChargesAndGainLossOnDisposalOfPropertyPlantAndEquipment': 'Asset Impairment Charges And Gain Loss On Disposal Of Property Plant And Equipment',
    'intc_ProceedsFromCapitalGrants': 'Proceeds From Capital Grants',
    'intc_DivestitureAdditionsToPropertyPlantAndEquipmentHeldForSale': 'Divestiture Additions To Property Plant And Equipment Held For Sale',
    'intc_PaymentsToAcquirePropertyPlantAndEquipmentFinancingActivities': 'Payments To Acquire Property Plant And Equipment Financing Activities',
    'intc_ProceedsFromIssuanceOfCommonStockWarrantsAndEscrowedShares': 'Proceeds From Issuance Of Common Stock Warrants And Escrowed Shares',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents': 'Cash and Cash Equivalents',
    'Debt Securities, Available-for-sale, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Intel 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_intel = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_intel.index = pd.to_datetime(df_lst_acc_num_10q_intel.index, format='%Y-%m-%d')
df_lst_acc_num_10q_intel

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2020 p/ iteração
df_lst_acc_num_10q_intel_sliced = df_lst_acc_num_10q_intel.loc['2020-03-28':]
df_lst_acc_num_10q_intel_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_intel_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10q = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-09-25'] = df_balance_sheet_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-09-25'] 
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-06-26'] = df_balance_sheet_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-06-26'] 
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-03-27'] = df_balance_sheet_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-03-27'] 
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-09-26'] = df_balance_sheet_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-09-26'] 
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-06-27'] = df_balance_sheet_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-06-27'] 
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-03-28'] = df_balance_sheet_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-03-28'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Property, Plant and Equipment, Net'
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2021-09-25'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2021-09-25'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2021-06-26'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2021-06-26'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2021-03-27'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2021-03-27'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-09-26'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-09-26'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-06-27'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-06-27'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-03-28'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-03-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Cash and Cash Equivalents, at Carrying Value',
    'Property, Plant and Equipment, Net',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Temporary Equity, Carrying Amount, Attributable to Parent',
    'Preferred Stock, Value, Issued',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest",
    
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2025-06-28'] = 9643 	

# Renomeando as linhas do índice que estão sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'intc_EquityInvestments': 'Equity Investments',
    'intc_AssetsHeldForSale': 'Assets Held For Sale',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_intel_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10q = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-06-27'] = 5104 
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-03-28'] = 5083 
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-06-28'] = 4369
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-03-29'] = 4343

df_income_statement_10q.loc['Earnings Per Share, Diluted', '2026-06-27'] = -2.16
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2026-03-28'] = -0.73
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2025-09-27'] = 0.90
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2025-06-28'] = -0.67
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2025-03-29'] = -0.19
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2024-06-29'] = -0.38
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2024-03-30'] = -0.09
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2024-09-28'] = -3.88

df_income_statement_10q.loc['Equity Securities, FV-NI, Gain (Loss)', '2026-06-27'] = -39

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_intel_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Other Depreciation and Amortization'
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-10-01'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-10-01']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-07-02'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-07-02']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-04-02'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-04-02']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-09-25'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-09-25']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-06-26'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-06-26']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-03-27'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-03-27']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-09-26'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-09-26']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-06-27'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-06-27']
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-03-28'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-03-28']

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations' e 'Cash and Cash Equivalents, at Carrying Value' 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2025-06-28'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2025-06-28']
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-09-25'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-09-25']
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-06-26'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-06-26']
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-03-27'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-03-27']
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-09-26'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-09-26']
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-06-27'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-06-27']
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-03-28'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-03-28']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Net Income (Loss) Attributable to Parent',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Cash and Cash Equivalents, at Carrying Value'

])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'Proceeds from (Repayments of) Short-term Debt',
    'intc_PaymentsForAcceleratedShareRepurchaseForwardAgreements',
])

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'intc_AssetImpairmentChargesAndGainLossOnDisposalOfPropertyPlantAndEquipment': 'Asset Impairment Charges And Gain Loss On Disposal Of Property Plant And Equipment',
    'intc_NonCashGainsLossesOnEquityInvestmentsNet': 'Non Cash Gains Losses On Equity Investments Net',
    'intc_ProceedsFromPartnerContributions': 'Proceeds From Partner Contributions',
    'intc_DivestitureAdditionsToPropertyPlantAndEquipmentHeldForSale': 'Divestiture Additions To Property Plant And Equipment Held For Sale',
    'intc_ProceedsFromCapitalGrants': 'Proceeds From Capital Grants',
    'intc_NoncashCapitalRelatedGovernmentAssistance': 'Non cash Capital Related Government Assistance',
    'intc_PaymentsToAcquirePropertyPlantAndEquipmentFinancingActivities': 'Payments To Acquire Property Plant And Equipment Financing Activities',
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents': 'Cash and Cash Equivalents',
    'Debt Securities, Available-for-sale, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'

})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation': 'Depreciation, Depletion and Amortization',
     'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
     'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
intel_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

intel_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

intel_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
intel_bs.columns = pd.to_datetime(intel_bs.columns)
intel_is.columns = pd.to_datetime(intel_is.columns)
intel_cf.columns = pd.to_datetime(intel_cf.columns)

# Transformando as colunas em apenas o ano
intel_bs.columns = intel_bs.columns.year
intel_is.columns = intel_is.columns.year
intel_cf.columns = intel_cf.columns.year

In [ ]:
# Preços da INTC
intel_close = yf.download('INTC', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]
last_dec_close = []

for year in lst_years:
    last_close = intel_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
intel_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
intel_close_dec = intel_close_dec.reindex(index=intel_close_dec.index[::-1])

# Arredondamento de duas casas decimais
intel_close_dec = round(intel_close_dec, 2)

# Não realizou split recentemente (https://br.investing.com/equities/intel-corp-historical-data-splits)

# Transformando o index em int
intel_close_dec.index = intel_close_dec.index.astype(int)

intel_close_dec

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = intel_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=intel_close_dec, df_is=intel_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=intel_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=intel_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=intel_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=intel_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=intel_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=intel_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=intel_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=intel_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=intel_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=intel_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=intel_bs, df_is=intel_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=intel_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=intel_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Debt, Current', 'Long-term Debt, Excluding Current Maturities', 'Other Liabilities, Noncurrent']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=intel_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda =  f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=intel_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=intel_is, df_bs=intel_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=intel_is, df_bs=intel_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=intel_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=intel_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=intel_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=intel_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=intel_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=intel_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=intel_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Income Taxes Payable, Net of Income Taxes Receivable',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=intel_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=intel_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Long-term Debt',
    'Proceeds from Issuance of Commercial Paper'	
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=intel_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt',
    'Repayments of Commercial Paper',
    'Finance Lease, Principal Payments'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=intel_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income =f_eua. indicador_taxes_operating_income(ten_k=True, df_is=intel_is, idx=idx)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=intel_is,
    idx=idx
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=intel_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=intel_cf, df_is=intel_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=intel_cf, df_is=intel_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=intel_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=intel_bs, df_is=intel_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=intel_bs, df_is=intel_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=intel_bs, df_is=intel_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=intel_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=intel_bs, df_is=intel_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=intel_is, df_bs=intel_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=intel_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10q,
    fcff_10q,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
intel_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
intel_indicadores_10k.columns = nomes_col
intel_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
intel_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

intel_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

intel_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
intel_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in intel_bs_10q.columns]
intel_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in intel_is_10q.columns]
intel_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in intel_cf_10q.columns]

In [ ]:
# Preços da INTC
intel_close = yf.download('INTC', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024', 
    '2025',
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = intel_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
intel_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
intel_close_months = intel_close_months.reindex(index=intel_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Fevereiro, Maio e Agosto)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03', 
    '06', 
    # '09'
] 

last_close_months_atual = []

for month in lst_actual_months:
    last_close = intel_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_months_atual.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
intel_close_months_atual = pd.Series(last_close_months_atual, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
intel_close_months_atual = intel_close_months_atual.reindex(index=intel_close_months_atual.index[::-1])

# Juntando as duas series pandas
intel_close_months = pd.concat([intel_close_months_atual, intel_close_months])

# Arredondamento de duas casas decimais
intel_close_months = round(intel_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/intel-corp-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
intel_close_months.index = intel_bs_10q.columns[:-3]

intel_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = intel_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=intel_close_months, df_is=intel_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=intel_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=intel_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=intel_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=intel_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=intel_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=intel_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=intel_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=intel_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=intel_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=intel_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=intel_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=intel_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=intel_bs_10q, df_is=intel_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=intel_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=intel_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Debt, Current', 'Long-term Debt, Excluding Current Maturities', 'Other Liabilities, Noncurrent']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=intel_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=intel_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=intel_is_10q, df_bs=intel_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=intel_is_10q, df_bs=intel_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=intel_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=intel_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=intel_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=intel_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=intel_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Income Taxes Payable, Net of Income Taxes Receivable',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=intel_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=intel_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=intel_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=intel_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Long-term Debt',
    'Proceeds from Issuance of Commercial Paper'   
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt',
    'Repayments of Commercial Paper',
    'Finance Lease, Principal Payments'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=intel_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=intel_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=intel_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=intel_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=intel_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=intel_cf_10q, df_is=intel_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=intel_cf_10q, df_is=intel_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=intel_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=intel_bs_10q, df_is=intel_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=intel_bs_10q, df_is=intel_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=intel_bs_10q, df_is=intel_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=intel_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=intel_bs_10q, df_is=intel_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=intel_is_10q, df_bs=intel_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=intel_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
intel_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
intel_indicadores_10q.columns = nomes_col
intel_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//intel//intc_indicators.xlsx') as writer:
    intel_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    intel_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Micron

* 1Q -> Lançamento em Dezembro (12);
* 2Q -> Lançamento em Março (03);
* 3Q -> Lançamento em Junho (06);
* 10K -> Lançamento em Setembro (09).

In [ ]:
ticker = 'mu'
f_sec.cik_matching_ticker(ticker)

### Scraping Micron 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_micron = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_micron.index = pd.to_datetime(df_lst_acc_num_micron.index, format='%Y-%m-%d')
df_lst_acc_num_micron

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2017 p/ iteração
df_lst_acc_num_micron_sliced = df_lst_acc_num_micron.loc['2017-08-31':]
df_lst_acc_num_micron_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_micron_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10k = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'GovernmentAssistanceLiabilityNoncurrent' nas colunas abaixo estão zeradas
# A informação estão nas linhas 'mu_UnearnedGovernmentAssistanceNoncurrent' e 'mu_UnearnedGovernmentIncentivesNoncurrent'
df_balance_sheet_10k.loc['GovernmentAssistanceLiabilityNoncurrent', '2023-08-31'] = df_balance_sheet_10k.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2023-08-31'] 
df_balance_sheet_10k.loc['GovernmentAssistanceLiabilityNoncurrent', '2022-09-01'] = df_balance_sheet_10k.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2022-09-01'] 
df_balance_sheet_10k.loc['GovernmentAssistanceLiabilityNoncurrent', '2021-09-02'] = df_balance_sheet_10k.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2021-09-02'] 
df_balance_sheet_10k.loc['GovernmentAssistanceLiabilityNoncurrent', '2020-09-03'] = df_balance_sheet_10k.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2020-09-03'] 
df_balance_sheet_10k.loc['GovernmentAssistanceLiabilityNoncurrent', '2019-08-29'] = df_balance_sheet_10k.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2019-08-29'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# A informação está na linha 'Property, Plant and Equipment, Net'
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-08-29'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2019-08-29'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2018-08-30'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2018-08-30'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2017-08-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2017-08-31'] 

# A linha 'Debt Securities, Available-for-sale, Current' nas colunas abaixo estão zeradas
# A informação está na linha 'Available-for-sale Securities, Current'
df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2018-08-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2018-08-30'] 
df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2017-08-31'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2017-08-31'] 

# A linha 'Debt Securities, Available-for-sale, Noncurrent' nas colunas abaixo estão zeradas
# A informação está na linha 'Available-for-sale Securities, Noncurrent'
df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Noncurrent', '2018-08-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Noncurrent', '2018-08-30'] 
df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Noncurrent', '2017-08-31'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Noncurrent', '2017-08-31'] 

#  Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'mu_UnearnedGovernmentAssistanceNoncurrent',
    'mu_UnearnedGovernmentIncentivesNoncurrent',
    'Property, Plant and Equipment, Net',
    'Available-for-sale Securities, Current',
    'Available-for-sale Securities, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsAbstract',
    'mu_AssetsHeldForSaleCurrent',
    'Redeemable Noncontrolling Interest, Equity, Preferred, Carrying Amount',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest",
    'Temporary Equity, Carrying Amount, Attributable to Parent',
    'Deferred Revenue, Current',
    'Equity Method Investments'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc['Other Liabilities, Current', '2018-08-30'] = 521
df_balance_sheet_10k.loc['GovernmentAssistanceLiabilityNoncurrent', '2018-08-30'] = 227

# Renomeando as linhas do índice que estão sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization': 'Property, plant, and equipment',
    'GovernmentAssistanceLiabilityNoncurrent': 'Government Assistance Liability Noncurrent'
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_micron_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10k = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'InterestExpenseNonoperating' na coluna abaixo estão zeradas
# As informações estão na linha 'Interest Expense' 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2023-08-31'] = df_income_statement_10k.loc['Interest Expense', '2023-08-31'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2022-09-01'] = df_income_statement_10k.loc['Interest Expense', '2022-09-01'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2021-09-02'] = df_income_statement_10k.loc['Interest Expense', '2021-09-02'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2020-09-03'] = df_income_statement_10k.loc['Interest Expense', '2020-09-03'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2019-08-29'] = df_income_statement_10k.loc['Interest Expense', '2019-08-29'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2018-08-30'] = df_income_statement_10k.loc['Interest Expense', '2018-08-30'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2017-08-31'] = df_income_statement_10k.loc['Interest Expense', '2017-08-31'] 

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' na coluna abaixo estão zeradas
# As informações estão nas linhas 'Revenues' e 'Revenue, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-08-30'] = df_income_statement_10k.loc['Revenues', '2018-08-30'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-08-31'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-08-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Revenues',
    'Revenue, Net (Deprecated 2018-01-31)',
    'Interest Expense'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest'

])

# Renomeando as linhas do índice que estão sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'InterestExpenseNonoperating': 'Interest Expense',
})

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_micron_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Net Income (Loss) Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2022-09-01'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-09-01'] 
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2021-09-02'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-09-02'] 
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2020-09-03'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-09-03'] 
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2019-08-29'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-08-29'] 
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2018-08-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2018-08-30'] 
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2017-08-31'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2017-08-31'] 

# A linha 'mu_ProceedsFromGovernmentAssistance' nas colunas abaixo estão zeradas
# As informações estão na linha 'mu_ProceedsFromGovernmentIncentives'
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2022-09-01'] = df_cash_flow_10k.loc['mu_ProceedsFromGovernmentIncentives', '2022-09-01'] 
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2021-09-02'] = df_cash_flow_10k.loc['mu_ProceedsFromGovernmentIncentives', '2021-09-02'] 
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2020-09-03'] = df_cash_flow_10k.loc['mu_ProceedsFromGovernmentIncentives', '2020-09-03'] 
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2019-08-29'] = df_cash_flow_10k.loc['mu_ProceedsFromGovernmentIncentives', '2019-08-29'] 
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2018-08-30'] = df_cash_flow_10k.loc['mu_ProceedsFromGovernmentIncentives', '2018-08-30'] 
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2017-08-31'] = df_cash_flow_10k.loc['mu_ProceedsFromGovernmentIncentives', '2017-08-31'] 

# A linha 'mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid' nas colunas abaixo estão zeradas
# As informações estão na linha 'mu_CapitalExpendituresIncurredNotYetPaidAndFinanceLeaseObligationsIncurred' e 'Capital Expenditures Incurred but Not yet Paid'
df_cash_flow_10k.loc['mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid', '2021-09-02'] = df_cash_flow_10k.loc['mu_CapitalExpendituresIncurredNotYetPaidAndFinanceLeaseObligationsIncurred', '2021-09-02'] 
df_cash_flow_10k.loc['mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid', '2020-09-03'] = df_cash_flow_10k.loc['Capital Expenditures Incurred but Not yet Paid', '2020-09-03'] 
df_cash_flow_10k.loc['mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid', '2019-08-29'] = df_cash_flow_10k.loc['Capital Expenditures Incurred but Not yet Paid', '2019-08-29'] 
df_cash_flow_10k.loc['mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid', '2018-08-30'] = df_cash_flow_10k.loc['Capital Expenditures Incurred but Not yet Paid', '2018-08-30'] 
df_cash_flow_10k.loc['mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid', '2017-08-31'] = df_cash_flow_10k.loc['Capital Expenditures Incurred but Not yet Paid', '2017-08-31'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities' 
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2018-08-30'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2018-08-30'] 
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2017-08-31'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2017-08-31'] 

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities' 
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2018-08-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2018-08-30'] 
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-08-31'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-08-31'] 

# A linha 'Depreciation, Depletion and Amortization' na coluna abaixo está zerada
# As informações estão na linha 'mu_DepreciationandAmortizationofIntangibleAssets' 
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2017-08-31'] = df_cash_flow_10k.loc['mu_DepreciationandAmortizationofIntangibleAssets', '2017-08-31'] 

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale' 
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-08-31'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2017-08-31'] 

# A linha 'Proceeds from Issuance or Sale of Equity' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Stock Options Exercised' 
df_cash_flow_10k.loc['Proceeds from Issuance or Sale of Equity', '2017-08-31'] = df_cash_flow_10k.loc['Proceeds from Stock Options Exercised', '2017-08-31'] 

# A linha 'Increase (Decrease) in Deferred Income Taxes' na coluna abaixo está zerada
# As informações estão na linha 'Increase (Decrease) in Deferred Revenue' 
df_cash_flow_10k.loc['Increase (Decrease) in Deferred Income Taxes', '2017-08-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue', '2017-08-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'mu_ProceedsFromGovernmentIncentives',
    'mu_CapitalExpendituresIncurredNotYetPaidAndFinanceLeaseObligationsIncurred',
    'Capital Expenditures Incurred but Not yet Paid',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Sale of Available-for-sale Securities',
    'mu_DepreciationandAmortizationofIntangibleAssets',
    'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale',
    'Proceeds from Stock Options Exercised',
    'Increase (Decrease) in Deferred Revenue'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Sale Leaseback Transaction, Gross Proceeds, Financing Activities',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract',
    'Payment, Tax Withholding, Share-based Payment Arrangement',
    'Payments to Noncontrolling Interests',
    'Business Combination, Step Acquisition, Equity Interest in Acquiree, Remeasurement Gain',
    'Income (Loss) from Equity Method Investments'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Other Current Liabilities', '2023-08-31'] = -817
df_cash_flow_10k.loc['Increase (Decrease) in Other Current Liabilities', '2022-09-01'] = 400
df_cash_flow_10k.loc['mu_ProceedsFromGovernmentAssistance', '2017-08-31'] = 21
df_cash_flow_10k.loc['Payments for Repurchase of Common Stock', '2018-08-30'] = -71
df_cash_flow_10k.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2017-08-31'] = 194

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'mu_ProceedsFromGovernmentAssistance': 'Proceeds From Government Assistance',
    'mu_PaymentsOnEquipmentPurchaseContracts': 'Payments On Equipment Purchase Contracts',
    'mu_CapitalExpendituresIncurredOnPurchaseContractsNotYetPaid': 'Capital Expenditures Incurred On Purchase Contracts Not Yet Paid',
    'mu_PaymentsForDerivativeAndHedgeInvestingActivities': 'Payments For Derivative And Hedge Investing Activities',
    'mu_ProceedsForDerivativeAndHedgeInvestingActivities': 'Proceeds For Derivative And Hedge Investing Activities',
    'mu_BusinessCombinationConsiderationTransferredSettlementOfReceivablesPayablesWithAcquireeNet': 'Business Combination Consideration Transferred Settlement Of Receivables Payables With Acquiree Net',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Debt Securities, Available-for-sale, Current': 'Marketable Securities, Current',
    'Debt Securities, Available-for-sale, Noncurrent': 'Long-term Marketable Investments, Non Current',
    'Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Micron 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_micron = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_micron.index = pd.to_datetime(df_lst_acc_num_10q_micron.index, format='%Y-%m-%d')
df_lst_acc_num_10q_micron

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de dez-2019 p/ iteração
df_lst_acc_num_10q_micron_sliced = df_lst_acc_num_10q_micron.loc['2019-11-28':]
df_lst_acc_num_10q_micron_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_micron_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10q = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'mu_UnearnedGovernmentAssistanceNoncurrent' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'GovernmentAssistanceLiabilityNoncurrent' e 'mu_UnearnedGovernmentIncentivesNoncurrent'
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2025-05-29'] = df_balance_sheet_10q.loc['GovernmentAssistanceLiabilityNoncurrent', '2025-05-29'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2025-02-27'] = df_balance_sheet_10q.loc['GovernmentAssistanceLiabilityNoncurrent', '2025-02-27'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2024-11-28'] = df_balance_sheet_10q.loc['GovernmentAssistanceLiabilityNoncurrent', '2024-11-28'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2023-06-01'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2023-06-01'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2023-03-02'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2023-03-02'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2022-12-01'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2022-12-01'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2022-06-02'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2022-06-02'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2022-03-03'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2022-03-03'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2021-12-02'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2021-12-02'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2021-06-03'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2021-06-03'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2021-03-04'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2021-03-04'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2020-12-03'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2020-12-03'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2020-05-28'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2020-05-28'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2020-02-27'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2020-02-27'] 
df_balance_sheet_10q.loc['mu_UnearnedGovernmentAssistanceNoncurrent', '2019-11-28'] = df_balance_sheet_10q.loc['mu_UnearnedGovernmentIncentivesNoncurrent', '2019-11-28'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' estão zeradas nas colunas abaixo estão zeradas
# As informações estão na linha 'Property, Plant and Equipment, Net'
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-05-28'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-05-28'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-02-27'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-02-27'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-11-28'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2019-11-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Property, Plant and Equipment, Net',
    'GovernmentAssistanceLiabilityNoncurrent',
    'mu_UnearnedGovernmentIncentivesNoncurrent',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsAbstract',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    'mu_AssetsHeldForSaleCurrent',
    'Common Stock, Shares, Outstanding',
    'Common Stock, Par or Stated Value Per Share',
    'Common Stock, Shares Authorized',
    'Common Stock, Shares, Issued',
    'Redeemable Noncontrolling Interest, Equity, Preferred, Carrying Amount',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest"
])
                                            
# Renomeando as linhas do índice que estão sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'mu_UnearnedGovernmentAssistanceNoncurrent': 'Unearned Government Assistance Non Current'
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_micron_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10q = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'InterestExpenseNonoperating' estão zeradas nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-05-30'] = df_income_statement_10q.loc['Interest Expense', '2024-05-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-02-29'] = df_income_statement_10q.loc['Interest Expense', '2024-02-29'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-11-30'] = df_income_statement_10q.loc['Interest Expense', '2023-11-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-06-01'] = df_income_statement_10q.loc['Interest Expense', '2023-06-01'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-03-02'] = df_income_statement_10q.loc['Interest Expense', '2023-03-02'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-12-01'] = df_income_statement_10q.loc['Interest Expense', '2022-12-01'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-06-02'] = df_income_statement_10q.loc['Interest Expense', '2022-06-02'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-03-03'] = df_income_statement_10q.loc['Interest Expense', '2022-03-03'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-12-02'] = df_income_statement_10q.loc['Interest Expense', '2021-12-02'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-06-03'] = df_income_statement_10q.loc['Interest Expense', '2021-06-03'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-03-04'] = df_income_statement_10q.loc['Interest Expense', '2021-03-04'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-12-03'] = df_income_statement_10q.loc['Interest Expense', '2020-12-03'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-05-28'] = df_income_statement_10q.loc['Interest Expense', '2020-05-28'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-02-27'] = df_income_statement_10q.loc['Interest Expense', '2020-02-27'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2019-11-28'] = df_income_statement_10q.loc['Interest Expense', '2019-11-28'] 

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Interest Expense',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Restructuring, Settlement and Impairment Provisions'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2024-05-30'] = 0.3
df_income_statement_10q.loc['Earnings Per Share, Diluted', '2023-11-30'] = -1.12
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-11-30'] = 1100

# Renomeando as linhas do índice que estão sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'mu_UnearnedGovernmentAssistanceNoncurrent': 'Unearned Government Assistance Non Current'
})

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_micron_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale'
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2023-06-01'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2023-06-01']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2023-03-02'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2023-03-02']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2022-12-01'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2022-12-01']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2022-06-02'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2022-06-02']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2022-03-03'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2022-03-03']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2021-12-02'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-12-02']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2021-06-03'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-06-03']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2021-03-04'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-03-04']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-12-03'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-12-03']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-05-28'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-05-28']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-02-27'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-02-27']
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2019-11-28'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2019-11-28']

# A linha 'mu_ProceedsFromGovernmentAssistance' nas colunas abaixo estão zeradas
# As informações estão na linha 'mu_ProceedsFromGovernmentIncentives'
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2023-06-01'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2023-06-01']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2023-03-02'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2023-03-02']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2022-12-01'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2022-12-01']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2022-06-02'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2022-06-02']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2022-03-03'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2022-03-03']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2021-12-02'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2021-12-02']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2021-06-03'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2021-06-03']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2021-03-04'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2021-03-04']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2020-12-03'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2020-12-03']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2020-05-28'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2020-05-28']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2020-02-27'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2020-02-27']
df_cash_flow_10q.loc['mu_ProceedsFromGovernmentAssistance', '2019-11-28'] = df_cash_flow_10q.loc['mu_ProceedsFromGovernmentIncentives', '2019-11-28']

# A linha 'Net Income (Loss) Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-06-03'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-06-03']
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-03-04'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-03-04']
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-12-03'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-12-03']
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-05-28'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-05-28']
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-02-27'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-02-27']
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2019-11-28'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-11-28']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale',
    'mu_ProceedsFromGovernmentIncentives',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Restructuring Costs and Asset Impairment Charges'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['Increase (Decrease) in Other Noncurrent Liabilities', '2025-05-29'] = -681
df_cash_flow_10q.loc['Increase (Decrease) in Other Noncurrent Liabilities', '2024-11-28'] = 132
df_cash_flow_10q.loc['Increase (Decrease) in Other Noncurrent Liabilities', '2024-05-30'] = 769


# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'mu_ProceedsFromGovernmentAssistance': 'Proceeds From Government Assistance',
    'mu_PaymentsOnEquipmentPurchaseContracts': 'Payments On Equipment Purchase Contracts'
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Debt Securities, Available-for-sale, Current': 'Marketable Securities, Current',
    'Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',    
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
micron_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

micron_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

micron_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
micron_bs.columns = pd.to_datetime(micron_bs.columns)
micron_is.columns = pd.to_datetime(micron_is.columns)
micron_cf.columns = pd.to_datetime(micron_cf.columns)

# Transformando as colunas em apenas o ano
micron_bs.columns = micron_bs.columns.year
micron_is.columns = micron_is.columns.year
micron_cf.columns = micron_cf.columns.year

In [ ]:
# Preços da MU
micron_close = yf.download('MU', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Janeiro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024', 
    '2025',
]
last_sep_close = []

for year in lst_years:
    last_close = micron_close[f'{year}-09'].iloc[-1]
    last_sep_close.append(last_close)

# Transformando em uma série pandas
micron_close_sep = pd.Series(last_sep_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
micron_close_sep = micron_close_sep.reindex(index=micron_close_sep.index[::-1])

# Arredondamento de duas casas decimais
micron_close_sep = round(micron_close_sep, 2)

# Não realizou split recentemente (https://br.investing.com/equities/micron-tech-historical-data-splits)

# Transformando o index em int
micron_close_sep.index = micron_close_sep.index.astype(int)

micron_close_sep

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = micron_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=micron_close_sep, df_is=micron_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=micron_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=micron_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=micron_close_sep, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=micron_close_sep, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=micron_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=micron_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=micron_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=micron_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=micron_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=micron_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=micron_bs, df_is=micron_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=micron_close_sep, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents, at Carrying Value', 'Marketable Securities, Current']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=micron_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Debt, Current', 'Long-term Debt and Lease Obligation', 'Operating Lease, Liability, Noncurrent']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=micron_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=micron_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=micron_is, df_bs=micron_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=micron_is, df_bs=micron_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=micron_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=micron_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=micron_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=micron_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=micron_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=micron_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=micron_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Other Current Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=micron_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=micron_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=micron_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=micron_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=micron_is, idx=idx)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=micron_is,
    idx=idx
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=micron_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=micron_cf, df_is=micron_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=micron_cf, df_is=micron_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=micron_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=micron_bs, df_is=micron_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=micron_bs, df_is=micron_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=micron_bs, df_is=micron_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=micron_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=micron_bs, df_is=micron_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=micron_is, df_bs=micron_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=micron_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10q,
    fcff_10q,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
micron_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
micron_indicadores_10k.columns = nomes_col
micron_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
micron_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

micron_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

micron_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
micron_bs_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in micron_bs_10q.columns]
micron_is_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in micron_is_10q.columns]
micron_cf_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in micron_cf_10q.columns]

In [ ]:
# Preços da MU
micron_close = yf.download('MU', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Dezembro
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025',
]
lst_months = ['03', '06', '12']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = micron_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
micron_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
micron_close_months = micron_close_months.reindex(index=micron_close_months.index[::-1])

# Retirando os preços de '06-2020' e '03-2020'
micron_close_months = micron_close_months[:-2]


# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Dezembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06',
    # '12'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = micron_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
micron_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
micron_close_months_atual = micron_close_months_atual.reindex(index=micron_close_months_atual.index[::-1])

# Juntando as duas series pandas
micron_close_months = pd.concat([micron_close_months_atual, micron_close_months])

# Arredondamento de duas casas decimais
micron_close_months = round(micron_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/micron-tech-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
micron_close_months.index = micron_bs_10q.columns[:-3]

micron_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = micron_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=micron_close_months, df_is=micron_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=micron_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=micron_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=micron_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=micron_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=micron_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=micron_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=micron_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=micron_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=micron_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=micron_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=micron_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=micron_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=micron_bs_10q, df_is=micron_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=micron_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities, Current']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=micron_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Debt, Current', 'Long-term Debt and Lease Obligation', 'Operating Lease, Liability, Noncurrent']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=micron_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=micron_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=micron_is_10q, df_bs=micron_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=micron_is_10q, df_bs=micron_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=micron_cf_10q, first_quarter='12')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=micron_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=micron_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=micron_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=micron_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Current Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Other Current Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=micron_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=micron_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=micron_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=micron_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=micron_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=micron_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=micron_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=micron_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=micron_cf_10q, first_quarter='12')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=micron_cf_10q, df_is=micron_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=micron_cf_10q, df_is=micron_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=micron_cf_10q,  first_quarter='12')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=micron_bs_10q, df_is=micron_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=micron_bs_10q, df_is=micron_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=micron_bs_10q, df_is=micron_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=micron_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=micron_bs_10q, df_is=micron_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=micron_is_10q, df_bs=micron_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=micron_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
micron_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
micron_indicadores_10q.columns = nomes_col
micron_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//micron//mu_indicators.xlsx') as writer:
    micron_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    micron_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Broadcom

* 1Q -> Lançamento em Feveiro (02);
* 2Q -> Lançamento em Maio (05);
* 3Q -> Lançamento em Agosto (08);
* 10K -> Lançamento em Novembro (11).

In [ ]:
ticker = 'avgo'
f_sec.cik_matching_ticker(ticker)

### Scraping Broadcom 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_broadcom = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_broadcom.index = pd.to_datetime(df_lst_acc_num_broadcom.index, format='%Y-%m-%d')
df_lst_acc_num_broadcom

* No site da SEC não possui o 'acc_num' do ano de 2017. Para pegar os dados deste ano, eu tive que usar o 'accession_number' de 2018.

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst_2 = []

for acc_num in df_lst_acc_num_broadcom['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst_2.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10k = pd.concat(balance_sheet_lst_2, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Long-term Debt and Lease Obligation, Current' nas colunas abaixo estão zeradas
# A informação está na linha 'Long-term Debt, Current Maturities'
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation, Current', '2021-10-31'] = df_balance_sheet_10k.loc['Long-term Debt, Current Maturities', '2021-10-31'] 
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation, Current', '2020-11-01'] = df_balance_sheet_10k.loc['Long-term Debt, Current Maturities', '2020-11-01'] 
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation, Current', '2019-11-03'] = df_balance_sheet_10k.loc['Long-term Debt, Current Maturities', '2019-11-03'] 

# A linha 'Long-term Debt and Lease Obligation' nas colunas abaixo estão zeradas
# A informação está na linha 'Long-term Debt, Excluding Current Maturities'
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation', '2021-10-31'] = df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2021-10-31'] 
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation', '2020-11-01'] = df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2020-11-01'] 
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation', '2019-11-03'] = df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2019-11-03'] 

# A linha 'Additional Paid in Capital' na coluna abaixo está zerada
# A informação está na linha 'Common Stocks, Including Additional Paid in Capital'
df_balance_sheet_10k.loc['Additional Paid in Capital', '2018-11-04'] = df_balance_sheet_10k.loc['Common Stocks, Including Additional Paid in Capital', '2018-11-04'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Common Stocks, Including Additional Paid in Capital',
    'Long-term Debt, Current Maturities',
    'Long-term Debt, Excluding Current Maturities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    "Stockholders' Equity Attributable to Parent",
    "Stockholders' Equity Attributable to Noncontrolling Interest"
])

# Renomeando as linhas do índice que estão sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'avgo_TemporaryEquityPreferredStockDividendObligation': 'Temporary Equity Preferred Stock Dividend Obligation'
})


# Para pegar os dados de 2017, eu tive que usar o 'accession_number' de 2018
# Dados do 'balance_sheet' do ano de 2017
df_balance_sheet_2017 = f_sec.process_one_statement(ticker=ticker, accession_number='000173016818000084', statement_name='balance_sheet')
df_balance_sheet_2017  = f_sec.rename_statement(df_balance_sheet_2017, label_dictionary=labels_dict)
# Selecionando apenas a coluna de 2017
df_balance_sheet_2017 = df_balance_sheet_2017.iloc[:, 1:] 
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_2017 = df_balance_sheet_2017.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued'
])

# Lista com os dfs do 'balance_shhet'
balance_sheet_lst_2 = [
    df_balance_sheet_10k, 
    df_balance_sheet_2017
]

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst_2]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k_final = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k_final  = df_balance_sheet_10k_final .fillna(0)

# A linha 'Long-term Debt and Lease Obligation, Current' na coluna abaixo está zerada
# A informação está na linha 'Long-term Debt, Current Maturities'
df_balance_sheet_10k_final.loc['Long-term Debt and Lease Obligation, Current', '2017-10-29'] = df_balance_sheet_10k_final.loc['Long-term Debt, Current Maturities', '2017-10-29'] 

# A linha 'Long-term Debt and Lease Obligation' na coluna abaixo está zerada
# A informação está na linha 'Long-term Debt, Excluding Current Maturities'
df_balance_sheet_10k_final.loc['Long-term Debt and Lease Obligation', '2017-10-29'] = df_balance_sheet_10k_final.loc['Long-term Debt, Excluding Current Maturities', '2017-10-29'] 

# A linha 'Additional Paid in Capital' na coluna abaixo está zerada
# A informação está na linha 'Common Stocks, Including Additional Paid in Capital'
df_balance_sheet_10k_final.loc['Additional Paid in Capital', '2017-10-29'] = df_balance_sheet_10k_final.loc['Common Stocks, Including Additional Paid in Capital', '2017-10-29'] 

# A linha 'Temporary Equity Preferred Stock Dividend Obligation' na coluna abaixo está zerada
# A informação está na linha 'Stockholders' Equity Attributable to Noncontrolling Interest'
df_balance_sheet_10k_final.loc['Temporary Equity Preferred Stock Dividend Obligation', '2017-10-29'] = df_balance_sheet_10k_final.loc["Stockholders' Equity Attributable to Noncontrolling Interest", '2017-10-29'] 

#  Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k_final = df_balance_sheet_10k_final.drop([
    'Long-term Debt, Current Maturities',
    'Long-term Debt, Excluding Current Maturities',
    'Common Stocks, Including Additional Paid in Capital',
    "Stockholders' Equity Attributable to Noncontrolling Interest"
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k_final = df_balance_sheet_10k_final.drop([
    "Stockholders' Equity Attributable to Parent",
    'Common Stock, Value, Issued',
    'Temporary Equity Preferred Stock Dividend Obligation'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k_final.loc['Long-term Debt and Lease Obligation', '2018-11-04'] = 17493

df_balance_sheet_10k_final

In [ ]:
# Nos anos de 2019 e 2018, o 'income_statement' retorna a tabela do 'R5.htm' que não é do 'income_statement'
# Para retornar os dados corretos do 'income_statement'- eu tenho que passar o statement_name='income_statement_2'. Isso faz com que retorne a tabela do 'R4.htm'
# Para que statement_name='income_statement_2' funcione, ...
# eu tive que adicionar essa chave e o valor 'consolidated statements of operations consolidated statements of operations' no dicionário 'statement_keys_map'

# Dados do 'income_statement' dos anos de 2018 e 2017
income_statement_2018_2017 = f_sec.process_one_statement(ticker='avgo', accession_number='000173016818000084', statement_name='income_statement_2')
income_statement_2018_2017 = f_sec.rename_statement(income_statement_2018_2017, label_dictionary=labels_dict)
# Selecionando as colunas dos anos de 2018 e 2017
income_statement_2018_2017 = income_statement_2018_2017.iloc[:,8:10]
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_2018_2017 = income_statement_2018_2017.drop('us-gaap_IncomeStatementAbstract')

# Dados do 'income_statement' do ano de 2021, 2020 e 2019
income_statement_2021_2020_2019 = f_sec.process_one_statement(ticker='avgo', accession_number='000173016821000153', statement_name='income_statement')
income_statement_2021_2020_2019 = f_sec.rename_statement(income_statement_2021_2020_2019, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_2021_2020_2019 = income_statement_2021_2020_2019.drop('srt_CondensedIncomeStatementsCaptionsLineItems')

# Dados do 'income_statement' do ano de 2024, 2023 e 2022
income_statement_2024_2023_2022 = f_sec.process_one_statement(ticker='avgo', accession_number='000173016824000139', statement_name='income_statement')
income_statement_2024_2023_2022 = f_sec.rename_statement(income_statement_2024_2023_2022, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_2024_2023_2022 = income_statement_2024_2023_2022.drop('srt_CondensedIncomeStatementsCaptionsLineItems')

# Dados do 'income_statement' do ano de 2025
income_statement_2025 = f_sec.process_one_statement(ticker='avgo', accession_number='000173016825000121', statement_name='income_statement')
income_statement_2025 = f_sec.rename_statement(income_statement_2025, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_2025 = income_statement_2025.drop('srt_CondensedIncomeStatementsCaptionsLineItems')
# Selecionando a coluna do ano de 2025
income_statement_2025 = income_statement_2025.iloc[:,0:1]

# Lista com os dfs do 'income_statement'
income_statement_lst = [
    income_statement_2025,
    income_statement_2024_2023_2022, 
    income_statement_2021_2020_2019, 
    income_statement_2018_2017
]

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# A informação está na linha 'Long-term Debt, Current Maturities'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-11-04'] = df_income_statement_10k.loc['Revenues', '2018-11-04'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-10-29'] = df_income_statement_10k.loc['Revenues', '2017-10-29'] 

# A linha 'avgo_CostofProductsSold' nas colunas abaixo estão zeradas
# A informação está na linha 'avgo_CostOfProductsSold'
df_income_statement_10k.loc['avgo_CostofProductsSold', '2018-11-04'] = df_income_statement_10k.loc['avgo_CostOfProductsSold', '2018-11-04'] 
df_income_statement_10k.loc['avgo_CostofProductsSold', '2017-10-29'] = df_income_statement_10k.loc['avgo_CostOfProductsSold', '2017-10-29'] 

# A linha 'Cost of Revenue' nas colunas abaixo estão zeradas
# A informação está na linha 'Cost of Goods and Services Sold'
df_income_statement_10k.loc['Cost of Revenue', '2018-11-04'] = df_income_statement_10k.loc['Cost of Goods and Services Sold', '2018-11-04'] 
df_income_statement_10k.loc['Cost of Revenue', '2017-10-29'] = df_income_statement_10k.loc['Cost of Goods and Services Sold', '2017-10-29'] 

# A linha 'Net Income (Loss) Available to Common Stockholders, Basic' nas colunas abaixo estão zeradas
# A informação está na linha 'Net Income (Loss) Attributable to Parent'
df_income_statement_10k.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2018-11-04'] = df_income_statement_10k.loc['Net Income (Loss) Attributable to Parent', '2018-11-04'] 
df_income_statement_10k.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2017-10-29'] = df_income_statement_10k.loc['Net Income (Loss) Attributable to Parent', '2017-10-29'] 

# A linha 'Interest Expense' na coluna abaixo está zerada
# A informação está na linha 'InterestExpenseNonoperating'
df_income_statement_10k.loc['Interest Expense', '2025-11-02'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2025-11-02'] 


#  Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Revenues',
    'avgo_CostOfProductsSold',
    'Cost of Goods and Services Sold',
    'Net Income (Loss) Attributable to Parent',
    'InterestExpenseNonoperating',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Diluted Share',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'avgo_Amortizationofinventoryvaluationstepup',
    'Litigation Settlement, Expense',
    'Cost-method Investments, Other than Temporary Impairment',
    'Gain (Loss) on Extinguishment of Debt',
    'Net Income (Loss) Attributable to Noncontrolling Interest'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['avgo_CostofSubscriptionsandServices', '2017-10-29'] = 44
df_income_statement_10k.loc['avgo_CostofSubscriptionsandServices', '2018-11-04'] = 97
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-10-30'] = 409
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-10-30'] = 423
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-10-29'] = 415
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-10-29'] = 427
df_income_statement_10k.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2025-11-02'] = 23126		

# Renomeando as linhas do índice que estão sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'avgo_CostofProductsSold': 'Cost Of Products Sold',
    'avgo_CostofSubscriptionsandServices': 'Cost Of Subscriptions And Services',
    'avgo_Amortizationofacquisitionrelatedintangibleassetscostofproductssold': 'Amortization Of Acquisition Related Intangible Assets Cost Of Products Sold',
    'avgo_RestructuringChargesCostOfProductsSold': 'Restructuring Charges Cost Of Products Sold',
    'avgo_Amortizationofacquisitionrelatedintangibleassetsoperatingexpenses': 'Amortization Of Acquisition Related Intangible Assets Operating Expenses',
})

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_broadcom['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop('us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract')


# Para pegar os dados de 2017, eu tive que usar o 'accession_number' de 2018
# Dados do 'cash_flow_statement' do ano de 2017
df_cash_flow_statement_2017 = f_sec.process_one_statement(ticker=ticker, accession_number='000173016818000084', statement_name='cash_flow_statement')
df_cash_flow_statement_2017 = f_sec.rename_statement(df_cash_flow_statement_2017, label_dictionary=labels_dict)
# Selecionando a coluna de 2017
df_cash_flow_statement_2017 = df_cash_flow_statement_2017.iloc[:, 1:2]
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_statement_2017 = df_cash_flow_statement_2017.drop('us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract')


# Lista com os dfs do 'cash_flow_statement'
cash_flow_statement_lst_2 = [df_cash_flow_10k, df_cash_flow_statement_2017]

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst_2]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k_final = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k_final = df_cash_flow_10k_final.fillna(0)

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-10-31'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, at Carrying Value', '2021-10-31'] 
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-11-01'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, at Carrying Value', '2020-11-01'] 
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2019-11-03'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, at Carrying Value', '2019-11-03'] 
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-11-04'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, at Carrying Value', '2018-11-04'] 
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-10-29'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, at Carrying Value', '2017-10-29'] 

# A linha 'avgo_Amortizationofintangibleandrightofuseassets' nas colunas abaixo estão zeradas
# As informações estão na linha 'Amortization of Intangible Assets'
df_cash_flow_10k_final.loc['avgo_Amortizationofintangibleandrightofuseassets', '2019-11-03'] = df_cash_flow_10k_final.loc['Amortization of Intangible Assets', '2019-11-03'] 
df_cash_flow_10k_final.loc['avgo_Amortizationofintangibleandrightofuseassets', '2018-11-04'] = df_cash_flow_10k_final.loc['Amortization of Intangible Assets', '2018-11-04'] 
df_cash_flow_10k_final.loc['avgo_Amortizationofintangibleandrightofuseassets', '2017-10-29'] = df_cash_flow_10k_final.loc['Amortization of Intangible Assets', '2017-10-29'] 

# A linha 'Proceeds from Issuance of Common Stock' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Long-term Capital Lease Obligations'
df_cash_flow_10k_final.loc['Proceeds from Issuance of Common Stock', '2018-11-04'] = df_cash_flow_10k_final.loc['Repayments of Long-term Capital Lease Obligations', '2018-11-04'] 
df_cash_flow_10k_final.loc['Proceeds from Issuance of Common Stock', '2017-10-29'] = df_cash_flow_10k_final.loc['Repayments of Long-term Capital Lease Obligations', '2017-10-29'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-11-04'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-11-04'] 
df_cash_flow_10k_final.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-10-29'] = df_cash_flow_10k_final.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-10-29'] 

# A linha 'Proceeds from (Repayments of) Other Debt' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Other Debt'
df_cash_flow_10k_final.loc['Proceeds from (Repayments of) Other Debt', '2019-11-03'] = df_cash_flow_10k_final.loc['Proceeds from Other Debt', '2019-11-03'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k_final = df_cash_flow_10k_final.drop([
    'Amortization of Intangible Assets',
    'Cash and Cash Equivalents, at Carrying Value',
    'Proceeds from Other Debt',
    'Repayments of Long-term Capital Lease Obligations',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k_final = df_cash_flow_10k_final.drop([
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'Unrealized Gain (Loss) on Investments',
    'avgo_ProceedsforStockIssuedDuringPeriodValueSharebasedCompensationNetofSharesWithheldforTaxes',
    'avgo_Noncashportionofdebtextinguishmentgainloss',
    'Proceeds from Issuance of Convertible Preferred Stock'
])

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k_final = df_cash_flow_10k_final.rename(index={
    'avgo_Amortizationofintangibleandrightofuseassets': 'Amortization Of Intangible And Right Of Use Assets',
    'avgo_DeferredIncomeTaxesandOtherNoncashTaxExpense': 'Deferred Income Taxes And Other Non Cash Tax Expense',
})

df_cash_flow_10k_final

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k_final = df_balance_sheet_10k_final.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Available to Common Stockholders, Basic': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k_final = df_cash_flow_10k_final.rename(index={
    'Depreciation': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10k.xlsx') as writer:
    df_balance_sheet_10k_final.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k_final.to_excel(writer, sheet_name='cash_flow')

### Scraping Broadcom 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_broadcom = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_broadcom.index = pd.to_datetime(df_lst_acc_num_10q_broadcom.index, format='%Y-%m-%d')
df_lst_acc_num_10q_broadcom

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2020 p/ iteração
df_lst_acc_num_10q_broadcom_sliced = df_lst_acc_num_10q_broadcom.loc['2020-02-02':]
df_lst_acc_num_10q_broadcom_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_broadcom_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Juntando todos os dfs que estão em listas em apenas um df
df_balance_sheet_10q = pd.concat(balance_sheet_lst, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Long-term Debt and Lease Obligation, Current' nas colunas abaixo estão zeradas
# A informação está na linha 'Long-term Debt, Current Maturities'
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2022-01-30'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2022-01-30']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2021-08-01'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2021-08-01']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2021-01-31'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2021-01-31']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2020-08-02'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2020-08-02']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2020-05-03'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2020-05-03']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2020-02-02'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2020-02-02']

# A linha 'Long-term Debt and Lease Obligation' nas colunas abaixo estão zeradas
# A informação está na linha 'Long-term Debt, Excluding Current Maturities'
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2022-01-30'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2022-01-30']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2021-08-01'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2021-08-01']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2021-01-31'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2021-01-31']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2020-08-02'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-08-02']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2020-05-03'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-05-03']
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2020-02-02'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-02-02']

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Long-term Debt, Current Maturities',
    'Long-term Debt, Excluding Current Maturities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Preferred Stock, Shares Authorized',
    'Preferred Stock, Par or Stated Value Per Share',
    'Preferred Stock, Dividend Rate, Percentage',
    'Preferred Stock, Shares Issued',
    'Preferred Stock, Liquidation Preference, Value',
    'Common Stock, Shares Authorized',
    'Common Stock, Shares, Issued',
    'Common Stock, Value, Issued',
    'avgo_TemporaryEquityPreferredStockDividendObligation'

])

# Arrumando a formatação da coluna '2020-08-02' (os nº estão com zeros a mais)
df_balance_sheet_10q['2020-08-02'] = df_balance_sheet_10q['2020-08-02'] / 1000000

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_broadcom_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_RevenuesAbstract',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Diluted Share',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Basic Share',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Preferred Stock Dividends, Income Statement Impact'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-08-02'] = 4887
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-08-02'] = 4766
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-05-03'] = 4876
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-05-03'] = 4747
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-02-01'] = 4888
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-02-01'] = 4741

df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2026-08-02'] = 13088
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2026-05-03'] = 9310
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2026-02-01'] = 7349
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2025-08-03'] = 4140
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2025-05-04'] = 4965
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2025-02-02'] = 5503
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2024-08-04'] = -1875
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2024-05-05'] = 2121
df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2024-02-04'] = 1325

# Renomeando as linhas do índice que estão sem formato 
df_income_statement_10q = df_income_statement_10q.rename(index={
    'avgo_CostofProductsSold': 'Cost Of Products Sold',
    'avgo_CostofSubscriptionsandServices': 'Cost Of Subscriptions And Services',
    'avgo_Amortizationofacquisitionrelatedintangibleassetscostofproductssold': 'Amortization Of Acquisition Related Intangible Assets Cost Of Products Sold',
    'avgo_RestructuringChargesCostOfProductsSold': 'Restructuring Charges Cost Of Products Sold',
    'avgo_Amortizationofacquisitionrelatedintangibleassetsoperatingexpenses': 'Amortization Of Acquisition Related Intangible Assets Operating Expenses'
})

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_broadcom_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# A informação está na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2022-07-31'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2022-07-31'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2022-05-01'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2022-05-01'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2022-01-30'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2022-01-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-08-01'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-08-01'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-05-02'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-05-02'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-01-31'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2021-01-31'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-08-02'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-08-02'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-05-03'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-05-03'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-02-02'] = df_cash_flow_10q.loc['Cash and Cash Equivalents, at Carrying Value', '2020-02-02'] 

# A linha 'Gain (Loss) on Investments' nas colunas abaixo estão zeradas
# A informação está na linha 'Unrealized Gain (Loss) on Investments'
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2021-05-02'] = df_cash_flow_10q.loc['Unrealized Gain (Loss) on Investments', '2021-05-02'] 
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2021-01-31'] = df_cash_flow_10q.loc['Unrealized Gain (Loss) on Investments', '2021-01-31'] 

# A linha 'Proceeds from (Repayments of) Other Debt	' nas colunas abaixo estão zeradas
# A informação está na linha 'Proceeds from Other Debt'
df_cash_flow_10q.loc['Proceeds from (Repayments of) Other Debt', '2020-05-03'] = df_cash_flow_10q.loc['Proceeds from Other Debt', '2020-05-03'] 
df_cash_flow_10q.loc['Proceeds from (Repayments of) Other Debt', '2020-02-02'] = df_cash_flow_10q.loc['Proceeds from Other Debt', '2020-02-02'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Cash and Cash Equivalents, at Carrying Value',
    'Unrealized Gain (Loss) on Investments',
    'Proceeds from Other Debt',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Proceeds from Divestiture of Businesses',
    'Gain (Loss) on Investments',
    'Restructuring Costs and Asset Impairment Charges',
    'Proceeds from Sale of Property, Plant, and Equipment',
    'Proceeds from (Repayments of) Other Debt'

])

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'avgo_Amortizationofintangibleandrightofuseassets': 'Amortization Of Intangible And Right Of Use Assets',
    'avgo_DeferredIncomeTaxesandOtherNoncashTaxExpense': 'Deferred Income Taxes And Other Non Cash Tax Expense'
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Available to Common Stockholders, Basic': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Businesses, Net of Cash Acquired': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

# Confirmando que as colunas estão em datetime - esse passo é necessário p/ não dar problema na hora da aplicação da função 'ajustar_mes_02_05_08'
df_balance_sheet_10q.columns = pd.to_datetime(df_balance_sheet_10q.columns, format='%Y-%m-%d')
df_income_statement_10q.columns = pd.to_datetime(df_income_statement_10q.columns, format='%Y-%m-%d')
df_cash_flow_10q.columns = pd.to_datetime(df_cash_flow_10q.columns, format='%Y-%m-%d')

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
broadcom_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

broadcom_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

broadcom_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
broadcom_bs.columns = pd.to_datetime(broadcom_bs.columns)
broadcom_is.columns = pd.to_datetime(broadcom_is.columns)
broadcom_cf.columns = pd.to_datetime(broadcom_cf.columns)

# Transformando as colunas em apenas o ano
broadcom_bs.columns = broadcom_bs.columns.year
broadcom_is.columns = broadcom_is.columns.year
broadcom_cf.columns = broadcom_cf.columns.year

In [ ]:
# Preços da AVGO
broadcom_close = yf.download('AVGO', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Novembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025'
]
last_nov_close = []

for year in lst_years:
    last_close = broadcom_close[f'{year}-11'].iloc[-1]
    last_nov_close.append(last_close)

# Transformando em uma série pandas
broadcom_close_nov = pd.Series(last_nov_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
broadcom_close_nov = broadcom_close_nov.reindex(index=broadcom_close_nov.index[::-1])

# Arredondamento de duas casas decimais
broadcom_close_nov = round(broadcom_close_nov, 2)

# Teve um split de 10:1 em 15/07/2024 (https://br.investing.com/equities/avago-technologies-historical-data-splits)
broadcom_close_nov.loc['2023'] = broadcom_close_nov.loc['2023'] * 10
broadcom_close_nov.loc['2022'] = broadcom_close_nov.loc['2022'] * 10
broadcom_close_nov.loc['2021'] = broadcom_close_nov.loc['2021'] * 10
broadcom_close_nov.loc['2020'] = broadcom_close_nov.loc['2020'] * 10
broadcom_close_nov.loc['2019'] = broadcom_close_nov.loc['2019'] * 10
broadcom_close_nov.loc['2018'] = broadcom_close_nov.loc['2018'] * 10
broadcom_close_nov.loc['2017'] = broadcom_close_nov.loc['2017'] * 10

# Transformando o index em int
broadcom_close_nov.index = broadcom_close_nov.index.astype(int)

broadcom_close_nov

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = broadcom_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=broadcom_close_nov, df_is=broadcom_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=broadcom_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=broadcom_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=broadcom_close_nov, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=broadcom_close_nov, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=broadcom_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=broadcom_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=broadcom_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=broadcom_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=broadcom_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=broadcom_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=broadcom_bs, df_is=broadcom_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=broadcom_close_nov, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=broadcom_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Long-term Debt and Lease Obligation, Current', 'Long-term Debt and Lease Obligation']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=broadcom_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=broadcom_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=broadcom_is, df_bs=broadcom_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=broadcom_is, df_bs=broadcom_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=broadcom_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=broadcom_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=broadcom_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=broadcom_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=broadcom_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=broadcom_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=broadcom_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=broadcom_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes And Other Non Cash Tax Expense',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Other Current Assets and Liabilities, Net',
    'Increase (Decrease) in Other Noncurrent Assets and Liabilities, Net'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=broadcom_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=broadcom_is, idx=idx)

# New borrowing             
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=broadcom_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=broadcom_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=broadcom_is, idx=idx)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=broadcom_is,
    idx=idx
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=broadcom_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=broadcom_cf, df_is=broadcom_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=broadcom_cf, df_is=broadcom_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=broadcom_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=broadcom_bs, df_is=broadcom_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=broadcom_bs, df_is=broadcom_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=broadcom_bs, df_is=broadcom_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=broadcom_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=broadcom_bs, df_is=broadcom_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=broadcom_is, df_bs=broadcom_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=broadcom_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10q,
    fcff_10q,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
broadcom_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
broadcom_indicadores_10k.columns = nomes_col
broadcom_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
broadcom_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

broadcom_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

broadcom_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando o datetime em uma string para retirar os dias - 
# Faço isso para retirar os dias '20XX-01-31' p/ conseguir aplicar a função 'ajustar_mes_02_05_08'
# Se eu não faço isso, a função não funciona, porque não existe '20XX-02-31' (Fevereiro vai até 28 ou 29)
broadcom_bs_10q.columns = broadcom_bs_10q.columns.strftime('%Y-%m')
broadcom_is_10q.columns = broadcom_is_10q.columns.strftime('%Y-%m')
broadcom_cf_10q.columns = broadcom_cf_10q.columns.strftime('%Y-%m')

# Retransformando em datetime - agora todos os dias são '01'
broadcom_bs_10q.columns = pd.to_datetime(broadcom_bs_10q.columns, format='%Y-%m')
broadcom_is_10q.columns = pd.to_datetime(broadcom_is_10q.columns, format='%Y-%m')
broadcom_cf_10q.columns = pd.to_datetime(broadcom_cf_10q.columns, format='%Y-%m')

# Aplicando o ajuste nas colunas
broadcom_bs_10q.columns = [f_sec.ajustar_mes_02_05_08(col) for col in broadcom_bs_10q.columns]
broadcom_is_10q.columns = [f_sec.ajustar_mes_02_05_08(col) for col in broadcom_is_10q.columns]
broadcom_cf_10q.columns = [f_sec.ajustar_mes_02_05_08(col) for col in broadcom_cf_10q.columns]

In [ ]:
# Preços da AVGO
broadcom_close = yf.download('AVGO', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Fevereiro, Maio e Agosto
lst_years = [
    '2021', '2022', '2023', '2024', 
    '2025',
]
lst_months = ['02', '05', '08']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = broadcom_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
broadcom_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
broadcom_close_months = broadcom_close_months.reindex(index=broadcom_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Fevereiro, Maio e Agosto)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '02',
    '05',
    '08'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = broadcom_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
broadcom_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
broadcom_close_months_atual = broadcom_close_months_atual.reindex(index=broadcom_close_months_atual.index[::-1])

# Juntando as duas series pandas
broadcom_close_months = pd.concat([broadcom_close_months_atual, broadcom_close_months])

# Arredondamento de duas casas decimais
broadcom_close_months = round(broadcom_close_months, 2)

# Teve um split de 10:1 em 15/07/2024 (https://br.investing.com/equities/avago-technologies-historical-data-splits)
broadcom_close_months.loc['05-2024'] = broadcom_close_months.loc['05-2024'] * 10
broadcom_close_months.loc['02-2024'] = broadcom_close_months.loc['02-2024'] * 10
broadcom_close_months.loc['08-2023'] = broadcom_close_months.loc['08-2023'] * 10
broadcom_close_months.loc['05-2023'] = broadcom_close_months.loc['05-2023'] * 10
broadcom_close_months.loc['02-2023'] = broadcom_close_months.loc['02-2023'] * 10
broadcom_close_months.loc['08-2022'] = broadcom_close_months.loc['08-2022'] * 10
broadcom_close_months.loc['05-2022'] = broadcom_close_months.loc['05-2022'] * 10
broadcom_close_months.loc['02-2022'] = broadcom_close_months.loc['02-2022'] * 10
broadcom_close_months.loc['08-2021'] = broadcom_close_months.loc['08-2021'] * 10
broadcom_close_months.loc['05-2021'] = broadcom_close_months.loc['05-2021'] * 10
broadcom_close_months.loc['02-2021'] = broadcom_close_months.loc['02-2021'] * 10

# Substituindo o index para ficar igual ao dos dados fundamentalistas
broadcom_close_months.index = broadcom_bs_10q.columns[:-3]

broadcom_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = broadcom_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=broadcom_close_months, df_is=broadcom_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=broadcom_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=broadcom_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=broadcom_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=broadcom_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=broadcom_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=broadcom_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=broadcom_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=broadcom_bs_10q, df_is=broadcom_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=broadcom_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=broadcom_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Debt, Current', 'Long-term Debt and Lease Obligation']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=broadcom_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=broadcom_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=broadcom_is_10q, df_bs=broadcom_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=broadcom_is_10q, df_bs=broadcom_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02')[2] 

# CAPEX
lst_capex_10q = ['Payments to Acquire Property, Plant, and Equipment']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=broadcom_cf_10q, first_quarter='02', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=broadcom_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes And Other Non Cash Tax Expense',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Other Current Assets and Liabilities, Net',
    'Increase (Decrease) in Other Noncurrent Assets and Liabilities, Net'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=broadcom_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='02')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=broadcom_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='02')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=broadcom_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='02')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=broadcom_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=broadcom_cf_10q, first_quarter='02', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=broadcom_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=broadcom_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=broadcom_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=broadcom_cf_10q, first_quarter='02')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=broadcom_cf_10q, df_is=broadcom_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=broadcom_cf_10q, df_is=broadcom_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=broadcom_cf_10q,  first_quarter='02')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=broadcom_bs_10q, df_is=broadcom_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=broadcom_bs_10q, df_is=broadcom_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=broadcom_bs_10q, df_is=broadcom_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=broadcom_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=broadcom_bs_10q, df_is=broadcom_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=broadcom_is_10q, df_bs=broadcom_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=broadcom_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
broadcom_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
broadcom_indicadores_10q.columns = nomes_col
broadcom_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//broadcom//avgo_indicators.xlsx') as writer:
    broadcom_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    broadcom_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Marvell

* 1Q -> Lançamento em Maio (05);
* 2Q -> Lançamento em Agosto (08);
* 3Q -> Lançamento em Novembro (11).
* 10K -> Lançamento em Fevereiro (02).

In [ ]:
ticker = 'mrvl'
f_sec.cik_matching_ticker(ticker)

### Scraping Marvell 10-K

* De 2017 a 2021, a Marvell era chamada de "MARVELL TECHNOLOGY GROUP LTD (CIK 0001058057)". Eu cheguei a adicionar os 'acc_num' de 2017 a 2021, mas não retornava nenhum dados desses anos.

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_mrvl = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_mrvl.index = pd.to_datetime(df_lst_acc_num_mrvl.index, format='%Y-%m-%d')
df_lst_acc_num_mrvl

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_mrvl['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Accrued Liabilities, Current' nas colunas abaixo estão zeradas
# A informação está na linha 'mrvl_AccruedAndContractLiabilitiesCurrent'
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2023-01-28'] = df_balance_sheet_10k.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2023-01-28'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2022-01-29'] = df_balance_sheet_10k.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2022-01-29'] 

# A linha 'Other Long-term Debt, Noncurrent' nas colunas abaixo estão zeradas
# A informação está na linha 'Long-term Debt, Excluding Current Maturities'
df_balance_sheet_10k.loc['Other Long-term Debt, Noncurrent', '2023-01-28'] = df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2023-01-28'] 
df_balance_sheet_10k.loc['Other Long-term Debt, Noncurrent', '2022-01-29'] = df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2022-01-29'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'mrvl_AccruedAndContractLiabilitiesCurrent',
    'Long-term Debt, Excluding Current Maturities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued'
])

# Arrumando a escala da coluna '2022-01-29'
df_balance_sheet_10k['2022-01-29'] = df_balance_sheet_10k['2022-01-29'] / 1000

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_mrvl['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Selling, General and Administrative Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'Selling and Marketing Expense'
df_income_statement_10k.loc['Selling, General and Administrative Expense', '2023-01-28'] = df_income_statement_10k.loc['Selling and Marketing Expense', '2023-01-28'] 
df_income_statement_10k.loc['Selling, General and Administrative Expense', '2022-01-29'] = df_income_statement_10k.loc['Selling and Marketing Expense', '2022-01-29'] 

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'
df_income_statement_10k.loc['Interest Expense', '2026-01-31'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2026-01-31'] 
df_income_statement_10k.loc['Interest Expense', '2025-02-01'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2025-02-01'] 

# A linha 'Restructuring Costs' na coluna abaixo está zerada
# As informações estão na linha 'Restructuring Charges'
df_income_statement_10k.loc['Restructuring Costs', '2024-02-03'] = df_income_statement_10k.loc['Restructuring Charges', '2024-02-03'] 

# A linha 'Nonoperating Income (Expense)' na coluna abaixo está zerada
# As informações estão na linha 'mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense'
df_income_statement_10k.loc['Nonoperating Income (Expense)', '2024-02-03'] = df_income_statement_10k.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2024-02-03'] 

# A linha 'Investment Income, Nonoperating' na coluna abaixo está zerada
# As informações estão na linha 'Investment Income, Nonoperating'
df_income_statement_10k.loc['Investment Income, Nonoperating', '2025-02-01'] = df_income_statement_10k.loc['Investment Income, Nonoperating', '2025-02-01'] 

# A linha 'Other Nonoperating Income (Expense)' na coluna abaixo está zerada
# As informações estão na linha 'Interest and Other Income'
df_income_statement_10k.loc['Other Nonoperating Income (Expense)', '2025-02-01'] = df_income_statement_10k.loc['Interest and Other Income', '2025-02-01'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Selling and Marketing Expense',
    'InterestExpenseNonoperating',
    'Restructuring Charges',
    'mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense',
    'Investment Income, Nonoperating',
    'Interest and Other Income'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'Litigation Settlement, Expense',
])

# Arrumando a escala das colunas '2022-01-29' e '2023-01-28'
df_income_statement_10k['2023-01-28'] = df_income_statement_10k['2023-01-28'] / 1000
df_income_statement_10k['2022-01-29'] = df_income_statement_10k['2022-01-29'] / 1000

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-02-01'] = 865.5 
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-02-03'] = 861.3
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-01-28'] = 851.4

df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-01-28'] = 851.4

df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2026-01-31'] = 3046.6
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2025-02-01'] = -894.7			
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2024-02-03'] = -758.7

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_mrvl['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Proceeds from Issuance of Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Issuance of Long-term Debt'
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2024-02-03'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2024-02-03'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2022-01-29'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2022-01-29'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2022-01-29'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2022-01-29'] 

# A linha 'Other Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Depreciation, Depletion and Amortization, Nonproduction'
df_cash_flow_10k.loc['Other Depreciation and Amortization', '2023-01-28'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2023-01-28'] 
df_cash_flow_10k.loc['Other Depreciation and Amortization', '2022-01-29'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2022-01-29'] 

# A linha 'Amortization of Intangible Assets' nas colunas abaixo estão zeradas
# As informações estão na linha 'mrvl_AmortizationAndImpairmentOfIntangibleAssets'
df_cash_flow_10k.loc['Amortization of Intangible Assets', '2023-01-28'] = df_cash_flow_10k.loc['mrvl_AmortizationAndImpairmentOfIntangibleAssets', '2023-01-28'] 
df_cash_flow_10k.loc['Amortization of Intangible Assets', '2022-01-29'] = df_cash_flow_10k.loc['mrvl_AmortizationAndImpairmentOfIntangibleAssets', '2022-01-29'] 

# A linha 'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accrued Liabilities'
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities', '2023-01-28'] = df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities', '2023-01-28'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities', '2022-01-29'] = df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities', '2022-01-29'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Proceeds from Issuance of Long-term Debt',
    'Depreciation, Depletion and Amortization, Nonproduction',
    'mrvl_AmortizationAndImpairmentOfIntangibleAssets',
    'Increase (Decrease) in Accrued Liabilities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'mrvl_GainLossOnDispositionOfBusinessDiscontinuedOperations',
    'Proceeds from Sale of Debt Securities, Available-for-sale',
    'mrvl_ProceedsFromPaymentsOfDivestitureOfBusinesses',
    'mrvl_AmortizationOfInventoryFairValueAdjustmentRelatedWithAcquisition',
    'Amortization of Debt Issuance Costs and Discounts',
    'mrvl_PaymentsForRepurchaseAndSettlementOfConvertibleDebt',
    'mrvl_ProceedsFromCappedCalls',
    'Payment of Financing and Stock Issuance Costs'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'mrvl_NonCashRestructuringAndRelatedChargesIncome': 'Non Cash Restructuring And Related Charges Income',
    'mrvl_PaymentOnTechnologyLicenseObligation': 'Payment On Technology License Obligation',
})

# Arrumando a escala das colunas '2022-01-29', '2023-01-28' e '2024-02-03'
df_cash_flow_10k['2024-02-03'] = df_cash_flow_10k['2024-02-03'] / 1000
df_cash_flow_10k['2023-01-28'] = df_cash_flow_10k['2023-01-28'] / 1000
df_cash_flow_10k['2022-01-29'] = df_cash_flow_10k['2022-01-29'] / 1000

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2023-01-28'] = 200

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Other Depreciation and Amortization': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Marvell 10-Q

* Os dados trimestrais da Marvell começam em '2021-05-01'.

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_mrvl = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_mrvl.index = pd.to_datetime(df_lst_acc_num_10q_mrvl.index, format='%Y-%m-%d')

df_lst_acc_num_10q_mrvl

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_mrvl['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Accrued Liabilities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'mrvl_AccruedAndContractLiabilitiesCurrent' 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2023-10-28'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2023-10-28'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2023-07-29'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2023-07-29'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2023-04-29'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2023-04-29'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2022-10-29'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2022-10-29'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2022-07-30'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2022-07-30'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2022-04-30'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2022-04-30'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2021-10-30'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2021-10-30'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2021-07-31'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2021-07-31'] 
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2021-05-01'] = df_balance_sheet_10q.loc['mrvl_AccruedAndContractLiabilitiesCurrent', '2021-05-01'] 

# A linha 'Other Long-term Debt, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt, Excluding Current Maturities' 
df_balance_sheet_10q.loc['Other Long-term Debt, Noncurrent', '2026-08-01'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2026-08-01'] 
df_balance_sheet_10q.loc['Other Long-term Debt, Noncurrent', '2026-05-02'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2026-05-02'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'mrvl_AccruedAndContractLiabilitiesCurrent',
    'Long-term Debt, Excluding Current Maturities',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Disposal Group, Including Discontinued Operation, Assets, Current',
    'Accumulated Other Comprehensive Income (Loss), Net of Tax',
    'Convertible Debt, Current',
    'Convertible Debt, Noncurrent'
])

# Arrumando a escala das colunas '2021-05-01', '2021-07-31' e '2021-10-30'
df_balance_sheet_10q['2021-10-30'] = df_balance_sheet_10q['2021-10-30'] / 1000
df_balance_sheet_10q['2021-07-31'] = df_balance_sheet_10q['2021-07-31'] / 1000
df_balance_sheet_10q['2021-05-01'] = df_balance_sheet_10q['2021-05-01'] / 1000

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_mrvl['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Restructuring Costs' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Restructuring Charges' e 'Restructuring Costs and Asset Impairment Charges'
df_income_statement_10q.loc['Restructuring Costs', '2024-08-03'] = df_income_statement_10q.loc['Restructuring Charges', '2024-08-03'] 
df_income_statement_10q.loc['Restructuring Costs', '2024-05-04'] = df_income_statement_10q.loc['Restructuring Charges', '2024-05-04'] 
df_income_statement_10q.loc['Restructuring Costs', '2023-10-28'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2023-10-28'] 
df_income_statement_10q.loc['Restructuring Costs', '2023-07-29'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2023-07-29'] 
df_income_statement_10q.loc['Restructuring Costs', '2023-04-29'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2023-04-29'] 
df_income_statement_10q.loc['Restructuring Costs', '2022-10-29'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2022-10-29'] 
df_income_statement_10q.loc['Restructuring Costs', '2022-07-30'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2022-07-30'] 
df_income_statement_10q.loc['Restructuring Costs', '2022-04-30'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2022-04-30'] 
df_income_statement_10q.loc['Restructuring Costs', '2021-10-30'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2021-10-30'] 
df_income_statement_10q.loc['Restructuring Costs', '2021-07-31'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2021-07-31'] 
df_income_statement_10q.loc['Restructuring Costs', '2021-05-01'] = df_income_statement_10q.loc['Restructuring Costs and Asset Impairment Charges', '2021-05-01'] 

# A linha 'Nonoperating Income (Expense)' nas colunas abaixo estão zeradas
# As informações estão na linha 'mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense'
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2023-10-28'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2023-10-28'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2023-07-29'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2023-07-29'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2023-04-29'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2023-04-29'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2022-10-29'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2022-10-29'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2022-07-30'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2022-07-30'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2022-04-30'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2022-04-30'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2021-10-30'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2021-10-30'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2021-07-31'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2021-07-31'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2021-05-01'] = df_income_statement_10q.loc['mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense', '2021-05-01'] 

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'
df_income_statement_10q.loc['Interest Expense', '2026-08-01'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-08-01'] 
df_income_statement_10q.loc['Interest Expense', '2026-05-02'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-05-02'] 
df_income_statement_10q.loc['Interest Expense', '2025-11-01'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-11-01'] 
df_income_statement_10q.loc['Interest Expense', '2025-08-02'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-08-02'] 
df_income_statement_10q.loc['Interest Expense', '2025-05-03'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-05-03'] 
df_income_statement_10q.loc['Interest Expense', '2024-11-02'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-11-02'] 
df_income_statement_10q.loc['Interest Expense', '2024-08-03'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-08-03'] 
							
# A linha 'Other Nonoperating Income (Expense)' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'mrvl_InterestAndOtherIncomeNet' e 'Interest and Other Income'
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2024-11-02'] = df_income_statement_10q.loc['mrvl_InterestAndOtherIncomeNet', '2024-11-02'] 
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2024-08-03'] = df_income_statement_10q.loc['Interest and Other Income', '2024-08-03'] 
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2024-05-04'] = df_income_statement_10q.loc['Interest and Other Income', '2024-05-04'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Restructuring Charges',
    'Restructuring Costs and Asset Impairment Charges',
    'mrvl_NonoperatingIncomeExpenseAndInterestIncomeExpense',
    'InterestExpenseNonoperating',
    'mrvl_InterestAndOtherIncomeNet',
    'Interest and Other Income'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Litigation Settlement, Expense',
    'Investment Income, Nonoperating'
])

# Arrumando a escala das colunas '2021-05-01', '2021-07-31' e '2021-10-30'
df_income_statement_10q['2021-10-30'] = df_income_statement_10q['2021-10-30'] / 1000
df_income_statement_10q['2021-07-31'] = df_income_statement_10q['2021-07-31'] / 1000
df_income_statement_10q['2021-05-01'] = df_income_statement_10q['2021-05-01'] / 1000

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-11-02'] = 865.7 
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-08-03'] = 865.7 
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-05-04'] = 865
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-04-29'] = 856.7
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-04-30'] = 848
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2021-10-30'] = 828.6
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2021-07-31'] = 821
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2021-05-01'] = 693.378

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_mrvl['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Proceeds from Issuance of Debt' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Proceeds from Lines of Credit' e 'Proceeds from Issuance of Long-term Debt'
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2025-05-03'] = df_cash_flow_10q.loc['Proceeds from Lines of Credit', '2025-05-03'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2023-10-28'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2023-10-28'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2023-07-29'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2023-07-29'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2023-04-29'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2023-04-29'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2022-10-29'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2022-10-29'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2022-07-30'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2022-07-30'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2021-10-30'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2021-10-30'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2021-07-31'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2021-07-31'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2021-05-01'] = df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2021-05-01'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Proceeds from Lines of Credit',
    'Proceeds from Issuance of Long-term Debt',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract',
    'Gain (Loss) on Disposition of Business',
    'Proceeds from Divestiture of Businesses, Net of Cash Divested',
    'mrvl_AmortizationOfInventoryFairValueAdjustmentRelatedWithAcquisition',
    'Payment of Financing and Stock Issuance Costs',
    'mrvl_PaymentsForRepurchaseAndSettlementOfConvertibleDebt',
    'mrvl_ProceedsFromCappedCalls',
    'Amortization of Debt Issuance Costs and Discounts'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'mrvl_IncreaseDecreaseInFairValueOfForwardStockPurchaseContract': 'Increase (Decrease) In Fair Value Of Forward Stock Purchase Contract',
    'mrvl_NonCashRestructuringAndRelatedChargesIncome': 'Non Cash Restructuring And Related Charges Income',
    'mrvl_PaymentOnTechnologyLicenseObligation': 'Payment On Technology License Obligation',
})

# Arrumando a escala das colunas '2021-05-01', '2021-07-31', '2021-10-30' e '2022-04-30'
df_cash_flow_10q['2022-04-30'] = df_cash_flow_10q['2022-04-30'] / 1000
df_cash_flow_10q['2021-10-30'] = df_cash_flow_10q['2021-10-30'] / 1000
df_cash_flow_10q['2021-07-31'] = df_cash_flow_10q['2021-07-31'] / 1000
df_cash_flow_10q['2021-05-01'] = df_cash_flow_10q['2021-05-01'] / 1000

df_cash_flow_10q

In [ ]:
# O 'df_income_statement_10q' não conseguiu puxar o dado da linha 'Income Before Provision for Income Taxes' 

# Linhas 'Income Before Provision for Income Taxes' a ser adicionada 
new_row_income_before_taxes_is_10q = [
    # 2026-08-01	
    378.3,	
    # 2026-05-02
    83.3,	
    # 2025-11-01	
    2215.4 ,	
    # 2025-08-02
    233.7,	
    # 2025-05-03
    215.9,	
    # 2024-11-02
    -750.5,	
    # 2024-08-03
    -146.2,	
    # 2024-05-04
    -197.8,	
    # 2023-10-28	
    -187.5,	
    # 2023-07-29
    -251.6,	
    # 2023-04-29
    -232.3,	
    # 2022-10-29
    65.3,	
    # 2022-07-30	
    3.8,	
    # 2022-04-30
    39.2,	
    # 2021-10-30	
    67.576,	
    # 2021-07-31	
    301.986,	
    # 2021-05-01
    116.007,	
]

# Adicionando as novas linhas
df_income_statement_10q.loc['Income Before Provision for Income Taxes'] = new_row_income_before_taxes_is_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Other Depreciation and Amortization': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
mrvl_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

mrvl_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

mrvl_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
mrvl_bs.columns = pd.to_datetime(mrvl_bs.columns)
mrvl_is.columns = pd.to_datetime(mrvl_is.columns)
mrvl_cf.columns = pd.to_datetime(mrvl_cf.columns)

# Transformando as colunas em apenas o ano
mrvl_bs.columns = mrvl_bs.columns.year
mrvl_is.columns = mrvl_is.columns.year
mrvl_cf.columns = mrvl_cf.columns.year

In [ ]:
# Preços da MRVL
mrvl_close = yf.download('MRVL', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Novembro de cada ano 
lst_years = [ 
    '2022', '2023', '2024','2025', 
    '2026'
]
last_fev_close = []

for year in lst_years:
    last_close = mrvl_close[f'{year}-02'].iloc[-1]
    last_fev_close.append(last_close)

# Transformando em uma série pandas
mrvl_close_fev = pd.Series(last_fev_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
mrvl_close_fev = mrvl_close_fev.reindex(index=mrvl_close_fev.index[::-1])

# Arredondamento de duas casas decimais
mrvl_close_fev = round(mrvl_close_fev, 2)

# Não realizou split recentemente (https://br.investing.com/equities/marvell-technology-group-ltd-historical-data-splits)

# Transformando o index em int
mrvl_close_fev.index = mrvl_close_fev.index.astype(int)

mrvl_close_fev

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = mrvl_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=mrvl_close_fev, df_is=mrvl_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=mrvl_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=mrvl_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=mrvl_close_fev, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=mrvl_close_fev, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=mrvl_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=mrvl_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=mrvl_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=mrvl_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=mrvl_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=mrvl_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=mrvl_bs, df_is=mrvl_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=mrvl_close_fev, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents, at Carrying Value']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=mrvl_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Short-term Debt',
    'Other Long-term Debt, Noncurrent'
]
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=mrvl_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda =  f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=mrvl_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=mrvl_is, df_bs=mrvl_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=mrvl_is, df_bs=mrvl_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=mrvl_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=mrvl_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=mrvl_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=mrvl_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=mrvl_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=mrvl_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=mrvl_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=mrvl_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=mrvl_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=mrvl_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=mrvl_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayments of Long-term Debt']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=mrvl_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=mrvl_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=mrvl_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=mrvl_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=mrvl_cf, df_is=mrvl_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=mrvl_cf, df_is=mrvl_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=mrvl_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=mrvl_bs, df_is=mrvl_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=mrvl_bs, df_is=mrvl_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=mrvl_bs, df_is=mrvl_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=mrvl_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=mrvl_bs, df_is=mrvl_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=mrvl_is, df_bs=mrvl_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=mrvl_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
mrvl_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
mrvl_indicadores_10k.columns = nomes_col
mrvl_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
mrvl_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

mrvl_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

mrvl_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
mrvl_bs_10q.columns = [f_sec.ajustar_mes_05_08_11(col) for col in mrvl_bs_10q.columns]
mrvl_is_10q.columns = [f_sec.ajustar_mes_05_08_11(col) for col in mrvl_is_10q.columns]
mrvl_cf_10q.columns = [f_sec.ajustar_mes_05_08_11(col) for col in mrvl_cf_10q.columns]

In [ ]:
# Preços da MRVL
mrvl_close = yf.download('MRVL', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Abril, Julho e Outubro
lst_years = [
    '2022', '2023', '2024', '2025',
]
lst_months = ['05', '08', '11']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = mrvl_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
mrvl_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
mrvl_close_months = mrvl_close_months.reindex(index=mrvl_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Fevereiro, Maio e Agosto)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '05', 
    '08', 
    # '10'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = mrvl_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
mrvl_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
mrvl_close_months_atual = mrvl_close_months_atual.reindex(mrvl_close_months_atual.index[::-1])

# Juntando as duas series pandas
mrvl_close_months = pd.concat([mrvl_close_months_atual, mrvl_close_months])

# Arredondamento de duas casas decimais
mrvl_close_months = round(mrvl_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/marvell-technology-group-ltd-historical-data-splits)

# # Substituindo o index para ficar igual ao dos dados fundamentalistas - NÃO PRECISO CORTAR, porque na MRVL começa em 2021
# mrvl_close_months.index = mrvl_bs_10q.columns[:-3]

mrvl_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = mrvl_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=mrvl_close_months, df_is=mrvl_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=mrvl_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=mrvl_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=mrvl_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=mrvl_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=mrvl_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=mrvl_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=mrvl_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=mrvl_bs_10q, df_is=mrvl_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=mrvl_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents, at Carrying Value']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=mrvl_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Short-term Debt',
    'Other Long-term Debt, Noncurrent'
]
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=mrvl_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q =  f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=mrvl_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=mrvl_is_10q, df_bs=mrvl_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=mrvl_is_10q, df_bs=mrvl_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=mrvl_cf_10q, first_quarter='05', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=mrvl_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=mrvl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='05')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=mrvl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='05')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=mrvl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='05')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=mrvl_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayments of Long-term Debt']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=mrvl_cf_10q, first_quarter='05', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=mrvl_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=mrvl_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=mrvl_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=mrvl_cf_10q, first_quarter='05')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=mrvl_cf_10q, df_is=mrvl_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=mrvl_cf_10q, df_is=mrvl_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=mrvl_cf_10q,  first_quarter='05')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=mrvl_bs_10q, df_is=mrvl_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=mrvl_bs_10q, df_is=mrvl_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=mrvl_bs_10q, df_is=mrvl_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=mrvl_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=mrvl_bs_10q, df_is=mrvl_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=mrvl_is_10q, df_bs=mrvl_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=mrvl_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_sliced,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
mrvl_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
mrvl_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
mrvl_indicadores_10q = mrvl_indicadores_10q.fillna(0)

mrvl_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//marvell//mrvl_indicators.xlsx') as writer:
    mrvl_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    mrvl_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Qualcomm

* 1Q -> Lançamento em Dezembro (12);
* 2Q -> Lançamento em Março (03);
* 3Q -> Lançamento em Junho (06).
* 10K -> Lançamento em Setembro (09).

In [ ]:
ticker = 'qcom'
f_sec.cik_matching_ticker(ticker)

### Scraping Qualcomm 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_qcom = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000123445217000190', # 2017
        ]
    },
    index=pd.to_datetime([
        '2017-09-30',
    ])
)

# Concatenando os dfs
df_lst_acc_num_qcom = pd.concat([df_lst_acc_num_qcom, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_qcom.index = pd.to_datetime(df_lst_acc_num_qcom.index, format='%Y-%m-%d')
df_lst_acc_num_qcom

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_qcom['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Deferred Income Tax Assets, Net' nas colunas abaixo estão zeradas
# A informação está na linha 'Deferred Tax Assets, Net, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2019-09-29'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net, Noncurrent', '2019-09-29'] 
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2018-09-30'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net, Noncurrent', '2018-09-30'] 
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2017-09-24'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net, Noncurrent', '2017-09-24'] 

# A linha 'Other Liabilities' nas colunas abaixo estão zeradas
# A informação está na linha 'Other Liabilities, Noncurrent'
df_balance_sheet_10k.loc['Other Liabilities', '2018-09-30'] = df_balance_sheet_10k.loc['Other Liabilities, Noncurrent', '2018-09-30'] 
df_balance_sheet_10k.loc['Other Liabilities', '2017-09-24'] = df_balance_sheet_10k.loc['Other Liabilities, Noncurrent', '2017-09-24'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Deferred Tax Assets, Net, Noncurrent',
    'Other Liabilities, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Preferred Stock, Par or Stated Value Per Share',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    'Disposal Group, Including Discontinued Operation, Assets, Current',
    'Disposal Group, Including Discontinued Operation, Assets, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Current',
    'Disposal Group, Including Discontinued Operation, Liabilities, Noncurrent'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2025-09-28'] = 21206
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2024-09-29'] = 26274 
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2023-09-24'] = 21581
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2022-09-25'] = 18013 	
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2021-09-26'] = 9950
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2020-09-27'] = 6077
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2019-09-29'] = 4909
df_balance_sheet_10k.loc["Stockholders' Equity Attributable to Parent", '2018-09-30'] = 807

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_qcom['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Investment Income, Nonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Nonoperating Income (Expense)'
df_income_statement_10k.loc['Investment Income, Nonoperating', '2025-09-28'] = df_income_statement_10k.loc['Nonoperating Income (Expense)', '2025-09-28'] 
df_income_statement_10k.loc['Investment Income, Nonoperating', '2024-09-29'] = df_income_statement_10k.loc['Nonoperating Income (Expense)', '2024-09-29'] 
df_income_statement_10k.loc['Investment Income, Nonoperating', '2023-09-24'] = df_income_statement_10k.loc['Nonoperating Income (Expense)', '2023-09-24'] 

# A linha 'qcom_LicensingRevenues' na coluna abaixo está zerada
# As informações estão na linha 'Licenses Revenue (Deprecated 2018-01-31)'
df_income_statement_10k.loc['qcom_LicensingRevenues', '2017-09-24'] = df_income_statement_10k.loc['Licenses Revenue (Deprecated 2018-01-31)', '2017-09-24'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Nonoperating Income (Expense)',
    'Licenses Revenue (Deprecated 2018-01-31)',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_RevenuesAbstract',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Basic Share',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Common Stock, Dividends, Per Share, Declared',
    'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'qcom_EquipmentAndServices': 'Equipment And Services',
    'qcom_LicensingRevenues': 'Licensing Revenues'
})

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenues'] - df_income_statement_10k.loc['Cost of Revenue']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_qcom['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10k.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2021-09-26'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-09-26'] 
df_cash_flow_10k.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2020-09-27'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-09-27'] 
df_cash_flow_10k.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2019-09-29'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-09-29'] 
df_cash_flow_10k.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2018-09-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2018-09-30'] 
df_cash_flow_10k.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2017-09-24'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2017-09-24'] 

# A linha 'Gain (Loss) on Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Gain (Loss) on Investments, Excluding Other than Temporary Impairments'
df_cash_flow_10k.loc['Gain (Loss) on Investments', '2020-09-27'] = df_cash_flow_10k.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2020-09-27'] 
df_cash_flow_10k.loc['Gain (Loss) on Investments', '2019-09-29'] = df_cash_flow_10k.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2019-09-29'] 
df_cash_flow_10k.loc['Gain (Loss) on Investments', '2018-09-30'] = df_cash_flow_10k.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2018-09-30'] 
df_cash_flow_10k.loc['Gain (Loss) on Investments', '2017-09-24'] = df_cash_flow_10k.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2017-09-24'] 

# A linha 'Repayments of Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Other Long-term Debt'
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2025-09-28'] = df_cash_flow_10k.loc['Repayments of Other Long-term Debt', '2025-09-28'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2024-09-29'] = df_cash_flow_10k.loc['Repayments of Other Long-term Debt', '2024-09-29'] 

# A linha 'Proceeds from Sale and Maturity of Marketable Securities' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale'
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2017-09-24'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2017-09-24'] 

# A linha 'Other than Temporary Impairment Losses, Investments' na coluna abaixo está zerada
# As informações estão na linha 'qcom_ImpairmentLossesOnOtherInvestmentsWithoutReadilyDeterminableFairValue'
df_cash_flow_10k.loc['Other than Temporary Impairment Losses, Investments', '2025-09-28'] = df_cash_flow_10k.loc['qcom_ImpairmentLossesOnOtherInvestmentsWithoutReadilyDeterminableFairValue', '2025-09-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Gain (Loss) on Investments, Excluding Other than Temporary Impairments',
    'Repayments of Other Long-term Debt',
    'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale',
    'qcom_ImpairmentLossesOnOtherInvestmentsWithoutReadilyDeterminableFairValue'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Cash Provided by (Used in) Operating Activities, Discontinued Operations',
    'Cash Provided by (Used in) Investing Activities, Discontinued Operations',
    'Cash Provided by (Used in) Financing Activities, Discontinued Operations',
    'Restricted Cash and Cash Equivalents',
    'Gain (Loss) on Disposition of Intangible Assets',
    'Payments to Acquire Trading Securities Held-for-investment',
    'Proceeds from Sale and Maturity of Debt and Equity Securities, FV-NI, Held-for-investment',
    'Proceeds from Sale of Intangible Assets',
    'Restricted Cash, Current',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'Payments to Acquire Restricted Investments',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'Disposal Group, Including Discontinued Operation, Cash and Cash Equivalents',
    'qcom_Releasedepositsofinvestmentsdesignatedascollateral',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Payments to Acquire Available-for-sale Securities',
    'Cash and Cash Equivalents, at Carrying Value',
    'Increase (Decrease) in Employee Related Liabilities',
    'Payments to Acquire Available-for-sale Securities'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'qcom_IncomeTaxProvisionLessThanInExcessOfIncomeTaxPayments': 'Income Tax Provision Less Than In Excess Of Income Tax Payments',
    'qcom_AcquisitionsAndOtherInvestmentsNetofCashAcquired': 'Acquisitions And Other Investments Net Of Cash Acquired',
    'qcom_Proceedsfromotherinvestments': 'Proceeds From Other Investments',
    
})

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities', '2018-09-30'] = 1005
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Liabilities', '2017-09-24'] = 2341

df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2017-09-24'] = 268

df_cash_flow_10k.loc['Repayments of Long-term Debt', '2023-09-24'] = -1446

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts and Other Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Research and Development Expense': 'Research and Development',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments of Ordinary Dividends': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Qualcomm 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_qcom = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_qcom.index = pd.to_datetime(df_lst_acc_num_10q_qcom.index, format='%Y-%m-%d')

df_lst_acc_num_10q_qcom

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2019 p/ iteração
df_lst_acc_num_10q_qcom_sliced = df_lst_acc_num_10q_qcom.loc['2019-12-29':]
df_lst_acc_num_10q_qcom_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_qcom_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)
					
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Preferred Stock, Par or Stated Value Per Share',
    'Disposal Group, Including Discontinued Operation, Assets, Current',
    'Disposal Group, Including Discontinued Operation, Assets, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Current',
    'Disposal Group, Including Discontinued Operation, Liabilities, Noncurrent',
    'Common Stocks, Including Additional Paid in Capital',
    'Deferred Tax Assets, Net, Noncurrent'
])

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_qcom_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# # A linha 'Nonoperating Income (Expense)' nas colunas abaixo estão zeradas
# # As informações estão na linha 'Investment Income, Nonoperating'  
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2022-12-25'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2022-12-25'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2022-06-26'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2022-06-26'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2022-03-27'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2022-03-27'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2021-12-26'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2021-12-26'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2021-06-27'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2021-06-27'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2021-03-28'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2021-03-28'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2020-12-27'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2020-12-27'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2020-06-28'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2020-06-28'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2020-03-29'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2020-03-29'] 
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2019-12-29'] = df_income_statement_10q.loc['Investment Income, Nonoperating', '2019-12-29'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Investment Income, Nonoperating',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_RevenuesAbstract',
    'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Diluted Share'
    
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10q = df_income_statement_10q.rename(index={
    'qcom_EquipmentAndServices': 'Equipment And Services',
    'qcom_LicensingRevenues': 'Licensing Revenues'
})

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Cost of Revenue']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_qcom_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2022-06-26'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-06-26'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2022-03-27'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-03-27'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2021-12-26'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-12-26'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2021-06-27'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-06-27'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2021-03-28'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-03-28'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2020-12-27'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-12-27'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2020-06-28'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-06-28'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2020-03-29'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-03-29'] 
df_cash_flow_10q.loc['Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent', '2019-12-29'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-12-29'] 

# A linha 'Gain (Loss) on Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Gain (Loss) on Investments, Excluding Other than Temporary Impairments'
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2021-06-27'] = df_cash_flow_10q.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2021-06-27'] 
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2021-03-28'] = df_cash_flow_10q.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2021-03-28'] 
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2020-12-27'] = df_cash_flow_10q.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2020-12-27'] 
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2020-06-28'] = df_cash_flow_10q.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2020-06-28'] 
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2020-03-29'] = df_cash_flow_10q.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2020-03-29'] 
df_cash_flow_10q.loc['Gain (Loss) on Investments', '2019-12-29'] = df_cash_flow_10q.loc['Gain (Loss) on Investments, Excluding Other than Temporary Impairments', '2019-12-29'] 

# A linha 'Repayments of Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Other Long-term Debt'
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2025-06-29'] = df_cash_flow_10q.loc['Repayments of Other Long-term Debt', '2025-06-29'] 
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2024-06-23'] = df_cash_flow_10q.loc['Repayments of Other Long-term Debt', '2024-06-23'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Gain (Loss) on Investments, Excluding Other than Temporary Impairments',
    'Repayments of Other Long-term Debt',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract',
    'Asset Impairment Charges',
    'qcom_CashAndCashEquivalentsHeldForSalePeriodIncreaseDecrease',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Restricted Cash, Current',
    'Cash Provided by (Used in) Operating Activities, Discontinued Operations',
    'Disposal Group, Including Discontinued Operation, Cash and Cash Equivalents',
    'Cash Provided by (Used in) Investing Activities, Discontinued Operations',
    'Cash Provided by (Used in) Financing Activities, Discontinued Operations',
    'Effect of Exchange Rate on Cash and Cash Equivalents'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'qcom_IncomeTaxProvisionLessThanInExcessOfIncomeTaxPayments': 'Income Tax Provision Less Than In Excess Of Income Tax Payments',
    'qcom_ImpairmentLossesOnOtherInvestmentsWithoutReadilyDeterminableFairValue': 'Impairment Losses On Other Investments Without Readily Determinable Fair Value',
    'qcom_AcquisitionsAndOtherInvestmentsNetofCashAcquired': 'Acquisitions And Other Investments Net Of Cash Acquired',
    'qcom_Proceedsfromotherinvestments': 'Proceeds From Other Investments'
})

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2023-06-25'] = -1446
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2023-03-26'] = -1446

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts and Other Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments of Ordinary Dividends': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
qcom_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

qcom_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

qcom_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
qcom_bs.columns = pd.to_datetime(qcom_bs.columns)
qcom_is.columns = pd.to_datetime(qcom_is.columns)
qcom_cf.columns = pd.to_datetime(qcom_cf.columns)

# Transformando as colunas em apenas o ano
qcom_bs.columns = qcom_bs.columns.year
qcom_is.columns = qcom_is.columns.year
qcom_cf.columns = qcom_cf.columns.year

In [ ]:
# Preços da QCOM
qcom_close = yf.download('QCOM', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Janeiro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024', 
    '2025',
]
last_sep_close = []

for year in lst_years:
    last_close = qcom_close[f'{year}-09'].iloc[-1]
    last_sep_close.append(last_close)

# Transformando em uma série pandas
qcom_close_sep = pd.Series(last_sep_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
qcom_close_sep = qcom_close_sep.reindex(index=qcom_close_sep.index[::-1])

# Arredondamento de duas casas decimais
qcom_close_sep = round(qcom_close_sep, 2)

# Não realizou split recentemente (https://br.investing.com/equities/qualcomm-inc-historical-data-splits)

# Transformando o index em int
qcom_close_sep.index = qcom_close_sep.index.astype(int)

qcom_close_sep

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = qcom_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=qcom_close_sep, df_is=qcom_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=qcom_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=qcom_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=qcom_close_sep, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=qcom_close_sep, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=qcom_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=qcom_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=qcom_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=qcom_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=qcom_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=qcom_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=qcom_bs, df_is=qcom_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=qcom_close_sep, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Marketable Securities, Current'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=qcom_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Debt, Current',
    'Long-term Debt'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=qcom_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=qcom_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=qcom_is, df_bs=qcom_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=qcom_is, df_bs=qcom_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=qcom_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=qcom_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=qcom_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Productive Assets',
    'Acquisitions And Other Investments Net Of Cash Acquired'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=qcom_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=qcom_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=qcom_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=qcom_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=qcom_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable, Trade',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Deferred Revenue'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=qcom_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=qcom_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Commercial Paper',
    'Proceeds from Issuance of Long-term Debt'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=qcom_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Commercial Paper',
    'Repayments of Long-term Debt',
    'Repayments of Assumed Debt'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=qcom_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=qcom_is, idx=idx)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=qcom_is,
    idx=idx
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=qcom_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=qcom_cf, df_is=qcom_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=qcom_cf, df_is=qcom_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=qcom_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=qcom_bs, df_is=qcom_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=qcom_bs, df_is=qcom_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=qcom_bs, df_is=qcom_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=qcom_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=qcom_bs, df_is=qcom_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=qcom_is, df_bs=qcom_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=qcom_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10q,
    fcff_10q,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
qcom_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
qcom_indicadores_10k.columns = nomes_col
qcom_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
qcom_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

qcom_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

qcom_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
qcom_bs_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in qcom_bs_10q.columns]
qcom_is_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in qcom_is_10q.columns]
qcom_cf_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in qcom_cf_10q.columns]

In [ ]:
# Preços da QCOM
qcom_close = yf.download('QCOM', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Dezembro
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025',
]
lst_months = ['03', '06', '12']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = qcom_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
qcom_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
qcom_close_months = qcom_close_months.reindex(index=qcom_close_months.index[::-1])

# Retirando os preços de '06-2020' e '03-2020'
qcom_close_months = qcom_close_months[:-2]


# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Dezembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06',
    # '12'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = qcom_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
micron_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
micron_close_months_atual = micron_close_months_atual.reindex(index=micron_close_months_atual.index[::-1])

# Juntando as duas series pandas
qcom_close_months = pd.concat([micron_close_months_atual, qcom_close_months])

# Arredondamento de duas casas decimais
qcom_close_months = round(qcom_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/qualcomm-inc-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
qcom_close_months.index = qcom_bs_10q.columns[:-3]

qcom_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = qcom_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=qcom_close_months, df_is=qcom_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=qcom_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=qcom_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=qcom_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=qcom_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=qcom_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=qcom_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=qcom_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=qcom_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=qcom_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=qcom_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=qcom_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=qcom_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=qcom_bs_10q, df_is=qcom_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=qcom_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Marketable Securities, Current'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=qcom_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Debt, Current',
    'Long-term Debt'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=qcom_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=qcom_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=qcom_is_10q, df_bs=qcom_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=qcom_is_10q, df_bs=qcom_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Productive Assets',
    'Acquisitions And Other Investments Net Of Cash Acquired'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=qcom_cf_10q, first_quarter='12', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=qcom_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=qcom_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=qcom_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=qcom_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable, Trade',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Deferred Revenue'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=qcom_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=qcom_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=qcom_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=qcom_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Commercial Paper',
    'Proceeds from Issuance of Long-term Debt'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Commercial Paper',
    'Repayments of Long-term Debt',
    'Repayments of Assumed Debt'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=qcom_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=qcom_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=qcom_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=qcom_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=qcom_cf_10q, first_quarter='12')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=qcom_cf_10q, df_is=qcom_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=qcom_cf_10q, df_is=qcom_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=qcom_cf_10q,  first_quarter='12')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=qcom_bs_10q, df_is=qcom_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=qcom_bs_10q, df_is=qcom_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=qcom_bs_10q, df_is=qcom_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=qcom_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=qcom_bs_10q, df_is=qcom_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=qcom_is_10q, df_bs=qcom_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=qcom_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
qcom_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
qcom_indicadores_10q.columns = nomes_col
qcom_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//semicondutores//qualcomm//qcom_indicators.xlsx') as writer:
    qcom_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    qcom_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

# **Setor de Electronic Design Automation (EDA)**

## Cadence

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'cdns'
f_sec.cik_matching_ticker(ticker)

### Scraping Cadence 10-K

* Os 'acc_num' de '2020-12-31' e '2021-12-31' estão vindo nas datas erradas ('2021-01-02' e '2022-01-01').

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_cdns = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017 e 2018
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000081367219000008', # 2018
            '000081367218000008', # 2017
        ]
    },
    index=pd.to_datetime([
        '2018-12-31',
        '2017-12-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_cdns = pd.concat([df_lst_acc_num_cdns, df_acc_num])

# Corrigindo as datas de fechamento do exercicio
df_lst_acc_num_cdns = df_lst_acc_num_cdns.rename(index={
    '2021-01-02': '2020-12-31',
    '2022-01-01': '2021-12-31',
})

# Transformando em datetime o index
df_lst_acc_num_cdns.index = pd.to_datetime(df_lst_acc_num_cdns.index, format='%Y-%m-%d')

df_lst_acc_num_cdns

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_cdns['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Other Assets' na coluna abaixo está zerada
# As informações estão nas linhas 'Other Assets, Noncurrent'
df_balance_sheet_10k.loc['Other Assets', '2017-12-30'] = df_balance_sheet_10k.loc['Other Assets, Noncurrent', '2017-12-30'] 

# A linha 'Deferred Income Tax Assets, Net' na coluna abaixo está zerada
# As informações estão nas linhas 'Deferred Tax Assets, Net, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2019-12-28'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net, Noncurrent', '2019-12-28'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Other Assets, Noncurrent',
    'Deferred Tax Assets, Net, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2018-12-29'] = 154894

# Padronizando as datas de fechamento das colunas no formato YYYY-MM-DD, retirando o horário 00:00:00
df_balance_sheet_10k.columns = [
    {
        # Renomeado as datas erradas
        '2022-01-01': '2021-12-31',
        '2021-01-02': '2020-12-31',
        # Renomeando os dias para o dia 31 
        '2019-12-28': '2019-12-31',
        '2018-12-29': '2018-12-31',
        '2017-12-30': '2017-12-31'
    }.get(str(col)[:10], str(col)[:10])
    for col in df_balance_sheet_10k.columns
]

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_cdns['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' na coluna abaixo está zerada
# As informações estão na linha 'Revenue, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-30'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-12-30'] 

# A linha 'us-gaap_CostOfGoodsAndServicesSold' na coluna abaixo está zerada
# As informações estão na linha 'cdns_CostOfProductAndMaintenance'
df_income_statement_10k.loc['us-gaap_CostOfGoodsAndServicesSold', '2017-12-30'] = df_income_statement_10k.loc['cdns_CostOfProductAndMaintenance', '2017-12-30'] 

# # Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Revenue, Net (Deprecated 2018-01-31)',
    'cdns_CostOfProductAndMaintenance'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_RevenuesAbstract',
    'cdns_ProductAndMaintenanceRevenue',
    'Technology Services Revenue (Deprecated 2018-01-31)',
    'Technology Services Costs (Deprecated 2018-01-31)'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'us-gaap_CostOfGoodsAndServicesSold': 'Cost Of Goods And Services Sold',
})

# Padronizando as datas de fechamento das colunas no formato YYYY-MM-DD, retirando o horário 00:00:00
df_income_statement_10k.columns = [
    {
        # Renomeado as datas erradas
        '2022-01-01': '2021-12-31',
        '2021-01-02': '2020-12-31',
        # Renomeando os dias para o dia 31 
        '2019-12-28': '2019-12-31',
        '2018-12-29': '2018-12-31',
        '2017-12-30': '2017-12-31'
    }.get(str(col)[:10], str(col)[:10])
    for col in df_income_statement_10k.columns
]

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10k.loc['Cost Of Goods And Services Sold']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_cdns['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2022-01-01'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2022-01-01'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-01-02'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2021-01-02'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2019-12-28'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2019-12-28'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-12-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-12-29'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-12-30'] 

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2022-01-01'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2022-01-01'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-01-02'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-01-02'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2019-12-28'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2019-12-28'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-12-29'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2018-12-29'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-30'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2017-12-30'] 

# A linha 'Payment, Tax Withholding, Share-based Payment Arrangement' nas colunas abaixo estão zeradas
# As informações estão na linha 'cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock'
df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2019-12-28'] = df_cash_flow_10k.loc['cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock', '2019-12-28'] 
df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2018-12-29'] = df_cash_flow_10k.loc['cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock', '2018-12-29'] 
df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2017-12-30'] = df_cash_flow_10k.loc['cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock', '2017-12-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2019-12-28'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2019-12-28'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-12-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-12-29'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-12-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-12-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Cash and Cash Equivalents, at Carrying Value',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock',
    'Cash and Cash Equivalents, Period Increase (Decrease)'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'Gain (Loss) on Disposition of Property Plant Equipment',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale',
    'Proceeds from Sale of Property, Plant, and Equipment',
    'Repayments of Convertible Debt',
    'Payments for Derivative Instrument, Financing Activities',
    'Proceeds from Derivative Instrument, Financing Activities',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'Increase (Decrease) in Book Overdrafts',
    'Proceeds from Sale of Available-for-sale Securities',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'cdns_ROUassetamortizationandchangeinoperatingleaseliabilities': 'ROU Asset Amortization and Change in Operating Lease Liabilities',
})

# Padronizando as datas de fechamento das colunas no formato YYYY-MM-DD, retirando o horário 00:00:00
df_cash_flow_10k.columns = [
    {
        # Renomeado as datas erradas
        '2022-01-01': '2021-12-31',
        '2021-01-02': '2020-12-31',
        # Renomeando os dias para o dia 31 
        '2019-12-28': '2019-12-31',
        '2018-12-29': '2018-12-31',
        '2017-12-30': '2017-12-31'
    }.get(str(col)[:10], str(col)[:10])
    for col in df_cash_flow_10k.columns
]

df_cash_flow_10k

In [ ]:
# O 'df_cash_flow_10k' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10k = [
    # 2025-12-31
    0,
    # 2024-12-31
    0,
    # 2023-12-31
    0,
    # 2022-12-31
    0,
    # 2021-12-31
    0,	
    # 2020-12-31	
    0,	
    # 2019-12-31	
    0,	
    # 2018-12-31	
    0,	
    # 2017-12-31	
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10k.loc['Payments of Dividends'] = new_row_div_cf_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost Of Goods And Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense, Software (Excluding Acquired in Process Cost)': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Cadence 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_cdns = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_cdns.index = pd.to_datetime(df_lst_acc_num_10q_cdns.index, format='%Y-%m-%d')

df_lst_acc_num_10q_cdns

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_cdns['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Contract with Customer, Liability, Current' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Revenue, Current' 
df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2020-03-28'] = df_balance_sheet_10q.loc['Deferred Revenue, Current', '2020-03-28'] 

# A linha 'Contract with Customer, Liability, Noncurrent' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Revenue, Noncurrent' 
df_balance_sheet_10q.loc['Contract with Customer, Liability, Noncurrent', '2020-03-28'] = df_balance_sheet_10q.loc['Deferred Revenue, Noncurrent', '2020-03-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Deferred Revenue, Current',
    'Deferred Revenue, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
])

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_cdns['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Research and Development Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'Research and Development Expense, Software (Excluding Acquired in Process Cost)'  
df_income_statement_10q.loc['Research and Development Expense', '2020-09-26'] = df_income_statement_10q.loc['Research and Development Expense, Software (Excluding Acquired in Process Cost)', '2020-09-26'] 
df_income_statement_10q.loc['Research and Development Expense', '2020-06-27'] = df_income_statement_10q.loc['Research and Development Expense, Software (Excluding Acquired in Process Cost)', '2020-06-27'] 
df_income_statement_10q.loc['Research and Development Expense', '2020-03-28'] = df_income_statement_10q.loc['Research and Development Expense, Software (Excluding Acquired in Process Cost)', '2020-03-28'] 

# A linha 'Other Nonoperating Income (Expense)' na coluna abaixo está zerada
# As informações estão na linha 'Nonoperating Income (Expense)'  
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2026-06-30'] = df_income_statement_10q.loc['Nonoperating Income (Expense)', '2026-06-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Research and Development Expense, Software (Excluding Acquired in Process Cost)',
    'Nonoperating Income (Expense)'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_RevenuesAbstract',
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10q = df_income_statement_10q.rename(index={
    'us-gaap_CostOfGoodsAndServicesSold': 'Cost Of Goods And Services Sold',
})

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10q.loc['Cost Of Goods And Services Sold']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_cdns['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-10-02'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-10-02'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-07-03'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-07-03'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2021-04-03'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-04-03'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-09-26'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-09-26'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-06-27'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-06-27'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-03-28'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-03-28'] 

# A linha 'Payment, Tax Withholding, Share-based Payment Arrangement' nas colunas abaixo estão zeradas
# As informações estão na linha 'cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock'
df_cash_flow_10q.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2020-06-27'] = df_cash_flow_10q.loc['cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock', '2020-06-27'] 
df_cash_flow_10q.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2020-03-28'] = df_cash_flow_10q.loc['cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock', '2020-03-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'cdns_StockReceivedforPaymentofEmployeeTaxesonVestingofRestrictedStock',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Cash and Cash Equivalents, at Carrying Value'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'cdns_ROUassetamortizationandchangeinoperatingleaseliabilities': 'ROU Asset Amortization And Change In Operating Lease Liabilities',
})

df_cash_flow_10q

In [ ]:
# O 'df_cash_flow_10q' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10q = [
    # 2026-06-30	
    0,	
    # 2026-03-31
    0,	
    # 2025-09-30	
    0,	
    # 2025-06-30	
    0,	
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
    # 2024-03-31
    0,	
    # 2023-09-30	
    0,	
    # 2023-06-30	
    0,	
    # 2023-03-31
    0,	
    # 2022-09-30	
    0,	
    # 2022-06-30	
    0,	
    # 2022-03-31
    0,	
    # 2021-09-30	
    0,	
    # 2021-06-30	
    0,	
    # 2021-03-31
    0,	
    # 2020-09-30	
    0,	
    # 2020-06-30	
    0,	
    # 2020-03-31
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10q.loc['Payments of Dividends'] = new_row_div_cf_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost Of Goods And Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
cdns_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

cdns_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

cdns_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
cdns_bs.columns = pd.to_datetime(cdns_bs.columns)
cdns_is.columns = pd.to_datetime(cdns_is.columns)
cdns_cf.columns = pd.to_datetime(cdns_cf.columns)

# Transformando as colunas em apenas o ano
cdns_bs.columns = cdns_bs.columns.year
cdns_is.columns = cdns_is.columns.year
cdns_cf.columns = cdns_cf.columns.year

In [ ]:
# Preços da CDNS
cdns_close = yf.download('CDNS', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_dec_close = []

for year in lst_years:
    last_close = cdns_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
cdns_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
cdns_close_dec = cdns_close_dec.reindex(index=cdns_close_dec.index[::-1])

# Arredondamento de duas casas decimais
cdns_close_dec = round(cdns_close_dec, 2)

# Não realizou split recentemente (https://br.investing.com/equities/cadence-design-system-inc-historical-data-splits)

# Transformando o index em int
cdns_close_dec .index = cdns_close_dec .index.astype(int)

cdns_close_dec

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = cdns_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=cdns_close_dec, df_is=cdns_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=cdns_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=cdns_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=cdns_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=cdns_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=cdns_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=cdns_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=cdns_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=cdns_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=cdns_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=cdns_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=cdns_bs, df_is=cdns_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=cdns_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Short-term Investments'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=cdns_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Unsecured Long-term Debt, Noncurrent']

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=cdns_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=cdns_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=cdns_is, df_bs=cdns_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=cdns_is, df_bs=cdns_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=cdns_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=cdns_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=cdns_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired',
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=cdns_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=cdns_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=cdns_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=cdns_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=cdns_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts and Other Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Deferred Revenue',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=cdns_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=cdns_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Lines of Credit',
    'Proceeds from Issuance of Unsecured Debt'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=cdns_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Lines of Credit',
    'Repayments of Unsecured Debt',
    'Payments of Debt Issuance Costs'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=cdns_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=cdns_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=cdns_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=cdns_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=cdns_cf, df_is=cdns_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=cdns_cf, df_is=cdns_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=cdns_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=cdns_bs, df_is=cdns_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=cdns_bs, df_is=cdns_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=cdns_bs, df_is=cdns_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=cdns_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=cdns_bs, df_is=cdns_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=cdns_is, df_bs=cdns_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=cdns_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
cdns_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
cdns_indicadores_10k.columns = nomes_col
cdns_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
cdns_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

cdns_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

cdns_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
cdns_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in cdns_bs_10q.columns]
cdns_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in cdns_is_10q.columns]
cdns_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in cdns_cf_10q.columns]

In [ ]:
# Preços da CDNS
cdns_close = yf.download('CDNS', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025'
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = cdns_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
cdns_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
cdns_close_months = cdns_close_months.reindex(index=cdns_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = cdns_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
cdns_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
cdns_close_months_atual = cdns_close_months_atual.reindex(index=cdns_close_months_atual.index[::-1])

# Juntando as duas series pandas
cdns_close_months = pd.concat([cdns_close_months_atual, cdns_close_months])

# Arredondamento de duas casas decimais
cdns_close_months = round(cdns_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/cadence-design-system-inc-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
cdns_close_months.index = cdns_bs_10q.columns[:-3]

cdns_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = cdns_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=cdns_close_months, df_is=cdns_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=cdns_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=cdns_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=cdns_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=cdns_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=cdns_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=cdns_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=cdns_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=cdns_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=cdns_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=cdns_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=cdns_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=cdns_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=cdns_bs_10q, df_is=cdns_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=cdns_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents, at Carrying Value']

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=cdns_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta 
lst_divida = ['Unsecured Long-term Debt, Noncurrent']

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=cdns_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=cdns_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=cdns_is_10q, df_bs=cdns_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=cdns_is_10q, df_bs=cdns_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired',
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC  
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=cdns_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=cdns_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=cdns_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=cdns_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=cdns_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts and Other Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Deferred Revenue',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=cdns_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=cdns_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=cdns_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=cdns_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Lines of Credit',
    'Proceeds from Issuance of Unsecured Debt'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Lines of Credit',
    'Repayments of Unsecured Debt',
    'Payments of Debt Issuance Costs'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=cdns_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=cdns_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=cdns_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=cdns_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=cdns_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=cdns_cf_10q, df_is=cdns_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=cdns_cf_10q, df_is=cdns_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=cdns_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=cdns_bs_10q, df_is=cdns_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=cdns_bs_10q, df_is=cdns_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=cdns_bs_10q, df_is=cdns_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=cdns_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=cdns_bs_10q, df_is=cdns_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=cdns_is_10q, df_bs=cdns_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=cdns_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
cdns_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
cdns_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
cdns_indicadores_10q = cdns_indicadores_10q.fillna(0)

cdns_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//cadence//cdns_indicators.xlsx') as writer:
    cdns_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    cdns_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Synopsys

* 1Q -> Lançamento em Janeiro (01);
* 2Q -> Lançamento em Abril (04);
* 3Q -> Lançamento em Julho (07);
* 10K -> Lançamento em Outubro (10).

In [ ]:
ticker = 'snps'
f_sec.cik_matching_ticker(ticker)

### Scraping Synopsys 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_snps = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_snps.index = pd.to_datetime(df_lst_acc_num_snps.index, format='%Y-%m-%d')

df_lst_acc_num_snps

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2017 p/ iteração
df_lst_acc_num_snps_sliced = df_lst_acc_num_snps.loc['2017-10-31':]
df_lst_acc_num_snps_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_snps_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Treasury Stock, Common, Value' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Treasury Stock, Value'
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2021-10-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2021-10-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2020-10-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2020-10-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2019-10-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2019-10-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2018-10-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2018-10-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2017-10-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2017-10-31'] 

# A linha 'Deferred Income Tax Assets, Net' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Deferred Tax Assets, Net of Valuation Allowance, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2019-10-31'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net of Valuation Allowance, Noncurrent', '2019-10-31'] 
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2018-10-31'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net of Valuation Allowance, Noncurrent', '2018-10-31'] 
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2017-10-31'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net of Valuation Allowance, Noncurrent', '2017-10-31'] 

# A linha 'Contract with Customer, Liability, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Deferred Revenue, Noncurrent' 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Noncurrent', '2018-10-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Noncurrent', '2018-10-31'] 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Noncurrent', '2017-10-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Noncurrent', '2017-10-31'] 

# A linha 'Contract with Customer, Liability, Current' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Deferred Revenue, Current' 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2018-10-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Current', '2018-10-31'] 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2017-10-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Current', '2017-10-31'] 

# A linha 'Debt, Current' na coluna abaixo está zerada
# As informações estão nas linhas 'Long-term Debt, Current Maturities' 
df_balance_sheet_10k.loc['Debt, Current', '2025-10-31'] = df_balance_sheet_10k.loc['Long-term Debt, Current Maturities', '2025-10-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Treasury Stock, Value',
    'Deferred Tax Assets, Net of Valuation Allowance, Noncurrent',
    'Deferred Revenue, Noncurrent',
    'Deferred Revenue, Current',
    'Long-term Debt, Current Maturities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Disposal Group, Including Discontinued Operation, Assets, Current',
    'Disposal Group, Including Discontinued Operation, Assets, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Current',
    'Disposal Group, Including Discontinued Operation, Liabilities, Noncurrent'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'snps_IncomeTaxReceivableAndPrepaidTax': 'Income Tax Receivable And Prepaid Tax',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_snps_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-10-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-10-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-10-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-10-31']
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-10-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-10-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-10-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-10-31']

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenues'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-10-31'] = df_income_statement_10k.loc['Revenues', '2018-10-31'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-10-31'] = df_income_statement_10k.loc['Revenues', '2017-10-31'] 

# A linha 'us-gaap_CostOfGoodsAndServicesSold' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cost of Services, Licenses and Maintenance Agreements (Deprecated 2018-01-31)'
df_income_statement_10k.loc['us-gaap_CostOfGoodsAndServicesSold', '2018-10-31'] = df_income_statement_10k.loc['Cost of Services, Licenses and Maintenance Agreements (Deprecated 2018-01-31)', '2018-10-31'] 
df_income_statement_10k.loc['us-gaap_CostOfGoodsAndServicesSold', '2017-10-31'] = df_income_statement_10k.loc['Cost of Services, Licenses and Maintenance Agreements (Deprecated 2018-01-31)', '2017-10-31'] 

# A linha 'Other Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Amortization of Intangible Assets'
df_income_statement_10k.loc['Other Depreciation and Amortization', '2025-10-31'] = df_income_statement_10k.loc['Amortization of Intangible Assets', '2025-10-31'] 
df_income_statement_10k.loc['Other Depreciation and Amortization', '2024-10-31'] = df_income_statement_10k.loc['Amortization of Intangible Assets', '2024-10-31'] 

# A linha 'Cost, Depreciation, Amortization and Depletion' na coluna abaixo está zerada
# As informações estão na linha 'Cost of Goods Sold, Depreciation, Depletion and Amortization (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Cost, Depreciation, Amortization and Depletion', '2017-10-31'] = df_income_statement_10k.loc['Cost of Goods Sold, Depreciation, Depletion and Amortization (Deprecated 2018-01-31)', '2017-10-31'] 

# # Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Revenues',
    'Cost of Services, Licenses and Maintenance Agreements (Deprecated 2018-01-31)',
    'Amortization of Intangible Assets',
    'Cost of Goods Sold, Depreciation, Depletion and Amortization (Deprecated 2018-01-31)'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_RevenuesAbstract',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Diluted Share',
    'License and Maintenance Revenue (Deprecated 2018-01-31)',
    'Licenses Revenue (Deprecated 2018-01-31)',
    'Technology Services Revenue (Deprecated 2018-01-31)',
    'Technology Services Costs (Deprecated 2018-01-31)'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['InterestExpenseNonoperating', '2024-10-31'] = -36829
df_income_statement_10k.loc['InterestExpenseNonoperating', '2023-10-31'] = -2703

df_income_statement_10k.loc['us-gaap_CostOfGoodsAndServicesSold', '2018-10-31'] = 448430

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'us-gaap_CostOfGoodsAndServicesSold': 'Cost Of Goods And Services Sold',
})

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_snps_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss) Attributable to Parent'
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-10-31'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2021-10-31'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-10-31'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2020-10-31'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-10-31'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2019-10-31'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2018-10-31'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2018-10-31'] 
df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2017-10-31'] = df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2017-10-31'] 

# A linha 'Proceeds from Issuance of Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss) Attributable to Parent'
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2020-10-31'] = df_cash_flow_10k.loc['Proceeds from Lines of Credit', '2020-10-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2019-10-31'] = df_cash_flow_10k.loc['Proceeds from Lines of Credit', '2019-10-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2018-10-31'] = df_cash_flow_10k.loc['Proceeds from Lines of Credit', '2018-10-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2017-10-31'] = df_cash_flow_10k.loc['Proceeds from Lines of Credit', '2017-10-31'] 

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations' e 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2025-10-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2025-10-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-10-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2018-10-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-10-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2017-10-31']

# A linha 'Net Cash Provided by (Used in) Operating Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Operating Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2018-10-31'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities, Continuing Operations', '2018-10-31'] 
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2017-10-31'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities, Continuing Operations', '2017-10-31'] 

# A linha 'Net Cash Provided by (Used in) Investing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Investing Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2018-10-31'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities, Continuing Operations', '2018-10-31'] 
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2017-10-31'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities, Continuing Operations', '2017-10-31'] 

# A linha 'Net Cash Provided by (Used in) Financing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Financing Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2018-10-31'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities, Continuing Operations', '2018-10-31'] 
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2017-10-31'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities, Continuing Operations', '2017-10-31']

# A linha 'Interest Paid, Excluding Capitalized Interest, Operating Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Paid, Including Capitalized Interest, Operating and Investing Activities'
df_cash_flow_10k.loc['Interest Paid, Excluding Capitalized Interest, Operating Activities', '2018-10-31'] = df_cash_flow_10k.loc['Interest Paid, Including Capitalized Interest, Operating and Investing Activities', '2018-10-31'] 
df_cash_flow_10k.loc['Interest Paid, Excluding Capitalized Interest, Operating Activities', '2017-10-31'] = df_cash_flow_10k.loc['Interest Paid, Including Capitalized Interest, Operating and Investing Activities', '2017-10-31'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-10-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-10-31'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-10-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-10-31'] 

# A linha 'Increase (Decrease) in Deferred Revenue' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Contract with Customer, Liability'
df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue', '2025-10-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2025-10-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue', '2024-10-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2024-10-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Net Income (Loss) Attributable to Parent',
    'Proceeds from Lines of Credit',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Financing Activities, Continuing Operations',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities',
    'Cash and Cash Equivalents, at Carrying Value',
    'Increase (Decrease) in Contract with Customer, Liability'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Disposal Group, Including Discontinued Operations',
    'Gain (Loss) on Investments',
    'Other than Temporary Impairment Losses, Investments',
    'Payments for Repurchase of Equity',
    'Noncash or Part Noncash Divestiture, Amount of Consideration Received',
    'snps_GainLossOnSaleofPropertyAndInvestment',
    'snps_Snps_GainLossOnSaleofPropertyAndInvestment',
    'Debt Conversion, Converted Instrument, Amount',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Inventories', '2017-10-31'] = -20137

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'snps_ReductionofOperatingLeaseRightofUseAssets': 'Reduction Of Operating Lease Right Of Use Assets',
    'snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts': 'Amortization Of Capitalized Costs To Obtain Revenue Contracts',
    'snps_IncreaseDecreaseinOperatingLeaseLiabilities': 'Increase (Decrease) in Operating Lease Liabilities',
    'snps_NoncashOrPartNoncashAcquisitionReplacementAwards': 'Noncash Or Part Noncash Acquisition Replacement Awards'
})

df_cash_flow_10k

In [ ]:
# O 'df_cash_flow_10k' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10k = [
    # 2025-10-31
    0,
    # 2024-10-31
    0,
    # 2023-10-31
    0,
    # 2022-10-31
    0,
    # 2021-10-31
    0,	
    # 2020-10-31	
    0,	
    # 2019-10-31	
    0,	
    # 2018-10-31	
    0,	
    # 2017-10-31	
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10k.loc['Payments of Dividends'] = new_row_div_cf_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Synopsys 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_snps = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_snps.index = pd.to_datetime(df_lst_acc_num_10q_snps.index, format='%Y-%m-%d')

df_lst_acc_num_10q_snps

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2020 p/ iteração
df_lst_acc_num_10q_snps_sliced = df_lst_acc_num_10q_snps.loc['2020-01-31':]
df_lst_acc_num_10q_snps_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_snps_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)
					
# A linha 'Treasury Stock, Value' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Common, Value' 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2026-07-31'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2026-07-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2026-04-30'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2026-04-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2026-01-31'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2026-01-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2025-07-31'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2025-07-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2025-04-30'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2025-04-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2025-01-31'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2025-01-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2024-07-31'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2024-07-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2024-04-30'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2024-04-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2024-01-31'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2024-01-31'] 

# A linha 'Deferred Income Tax Assets, Net' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Tax Assets, Net of Valuation Allowance, Noncurrent' 
df_balance_sheet_10q.loc['Deferred Income Tax Assets, Net', '2020-01-31'] = df_balance_sheet_10q.loc['Deferred Tax Assets, Net of Valuation Allowance, Noncurrent', '2020-01-31'] 

# A linha 'Short-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'Debt, Current' 
df_balance_sheet_10q.loc['Short-term Debt', '2020-01-31'] = df_balance_sheet_10q.loc['Debt, Current', '2020-01-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Treasury Stock, Common, Value',
    'Deferred Tax Assets, Net of Valuation Allowance, Noncurrent',
    'Debt, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Disposal Group, Including Discontinued Operation, Assets, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Noncurrent'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'snps_IncomeTaxReceivableAndPrepaidTax': 'Income Tax Receivable And Prepaid Tax',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_snps_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'  
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-07-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-07-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-04-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-04-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-01-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-01-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-07-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-07-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-04-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-04-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-01-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-01-31'] 

# A linha 'Other Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Amortization of Intangible Assets'  
df_income_statement_10q.loc['Other Depreciation and Amortization', '2026-07-31'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2026-07-31'] 
df_income_statement_10q.loc['Other Depreciation and Amortization', '2026-04-30'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2026-04-30'] 
df_income_statement_10q.loc['Other Depreciation and Amortization', '2026-01-31'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2026-01-31'] 
df_income_statement_10q.loc['Other Depreciation and Amortization', '2025-07-31'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2025-07-31'] 
df_income_statement_10q.loc['Other Depreciation and Amortization', '2025-04-30'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2025-04-30'] 
df_income_statement_10q.loc['Other Depreciation and Amortization', '2025-01-31'] = df_income_statement_10q.loc['Amortization of Intangible Assets', '2025-01-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Amortization of Intangible Assets',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_RevenuesAbstract',
    'Income (Loss) from Discontinued Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Income (Loss) from Discontinued Operations and Disposal of Discontinued Operations, Net of Tax, Per Diluted Share',
    'Income (Loss) from Continuing Operations, Net of Tax, Attributable to Parent'
    
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10q = df_income_statement_10q.rename(index={
    'us-gaap_CostOfGoodsAndServicesSold': 'Cost Of Goods And Services Sold',
})

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_snps_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss) Attributable to Parent'
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-07-31'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-07-31'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-04-30'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-04-30'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-01-31'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-01-31'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-07-31'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-07-31'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-04-30'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-04-30'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-01-31'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-01-31'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-07-31'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-07-31'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-04-30'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-04-30'] 
df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-01-31'] = df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-01-31'] 
	
# A linha 'Capitalized Contract Cost, Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts'
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2026-01-31'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2026-01-31'] 
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2025-07-31'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2025-07-31'] 
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2025-04-30'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2025-04-30'] 
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2025-01-31'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2025-01-31'] 
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2024-07-31'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2024-07-31'] 
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2024-04-30'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2024-04-30'] 
df_cash_flow_10q.loc['Capitalized Contract Cost, Amortization', '2024-01-31'] = df_cash_flow_10q.loc['snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts', '2024-01-31'] 

# A linha 'Proceeds from Sale and Maturity of Marketable Securities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Maturities, Prepayments and Calls of Short-term Investments'
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2026-07-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2026-07-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2026-04-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2026-04-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2026-01-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2026-01-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2025-07-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2025-07-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2025-04-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2025-04-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2025-01-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Short-term Investments', '2025-01-31'] 

# A linha 'Proceeds from Issuance of Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Lines of Credit'
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2020-07-31'] = df_cash_flow_10q.loc['Proceeds from Lines of Credit', '2020-07-31'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2020-04-30'] = df_cash_flow_10q.loc['Proceeds from Lines of Credit', '2020-04-30'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Debt', '2020-01-31'] = df_cash_flow_10q.loc['Proceeds from Lines of Credit', '2020-01-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Net Income (Loss) Attributable to Parent',
    'snps_AmortizationOfCapitalizedCostsToObtainRevenueContracts',
    'Proceeds from Maturities, Prepayments and Calls of Short-term Investments',
    'Proceeds from Lines of Credit'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Unrealized Gain (Loss) on Derivatives',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract',
    'snps_GainLossOnSaleofPropertyAndInvestment',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Disposal Group, Including Discontinued Operations',
    'Payments to Acquire Other Productive Assets',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Gain (Loss) on Derivative Instruments, Net, Pretax'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'snps_ReductionofOperatingLeaseRightofUseAssets': 'Reduction Of Operating Lease Right Of Use Assets',
    'snps_IncreaseDecreaseinOperatingLeaseLiabilities': 'Increase (Decrease) in Operating Lease Liabilities',
    'snps_Paymentsforcapitalizedsoftwaredevelopmentcosts': 'Payments For Capitalized Software Development Costs'
})

df_cash_flow_10q

In [ ]:
# O 'df_cash_flow_10q' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10q = [
    # 2026-07-31	
    0,	
    # 2026-04-30	
    0,	
    # 2026-01-31
    0,	
    # 2025-07-31	
    0,	
    # 2025-04-30	
    0,	
    # 2025-01-31
    0,	
    # 2024-07-31	
    0,	
    # 2024-04-30	
    0,	
    # 2024-01-31
    0,	
    # 2023-07-31	
    0,	
    # 2023-04-30	
    0,	
    # 2023-01-31
    0,	
    # 2022-07-31	
    0,	
    # 2022-04-30	
    0,	
    # 2022-01-31
    0,	
    # 2021-07-31	
    0,	
    # 2021-04-30	
    0,	
    # 2021-01-31
    0,	
    # 2020-07-31	
    0,	
    # 2020-04-30	
    0,	
    # 2020-01-31
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10q.loc['Payments of Dividends'] = new_row_div_cf_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
snps_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

snps_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

snps_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
snps_bs.columns = pd.to_datetime(snps_bs.columns)
snps_is.columns = pd.to_datetime(snps_is.columns)
snps_cf.columns = pd.to_datetime(snps_cf.columns)

# Transformando as colunas em apenas o ano
snps_bs.columns = snps_bs.columns.year
snps_is.columns = snps_is.columns.year
snps_cf.columns = snps_cf.columns.year

In [ ]:
# Preços da SNPS
snps_close = yf.download('SNPS', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_oct_close = []

for year in lst_years:
    last_close = snps_close[f'{year}-10'].iloc[-1]
    last_oct_close.append(last_close)

# Transformando em uma série pandas
snps_close_oct = pd.Series(last_oct_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
snps_close_oct = snps_close_oct.reindex(index=snps_close_oct.index[::-1])

# Arredondamento de duas casas decimais
snps_close_oct = round(snps_close_oct, 2)

# Não realizou split recentemente (https://br.investing.com/equities/synopsys-inc-historical-data-splits)

# Transformando o index em int
snps_close_oct .index = snps_close_oct .index.astype(int)

snps_close_oct

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = snps_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=snps_close_oct, df_is=snps_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=snps_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=snps_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=snps_close_oct, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=snps_close_oct, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=snps_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=snps_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=snps_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=snps_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=snps_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=snps_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=snps_bs, df_is=snps_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=snps_close_oct, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Short-term Investments'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=snps_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Operating Lease, Liability, Current',
    'Debt, Current',
    'Operating Lease, Liability, Noncurrent',
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=snps_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=snps_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=snps_is, df_bs=snps_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=snps_is, df_bs=snps_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=snps_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=snps_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=snps_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Intangible Assets',
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=snps_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=snps_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=snps_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=snps_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=snps_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Operating Lease Liabilities',
    'Increase (Decrease) in Income Taxes',
    'Increase (Decrease) in Deferred Revenue'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=snps_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=snps_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=snps_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Debt',
    'Payments of Financing Costs'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=snps_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=snps_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=snps_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=snps_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=snps_cf, df_is=snps_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=snps_cf, df_is=snps_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=snps_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=snps_bs, df_is=snps_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=snps_bs, df_is=snps_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=snps_bs, df_is=snps_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=snps_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=snps_bs, df_is=snps_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=snps_is, df_bs=snps_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=snps_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
snps_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
snps_indicadores_10k.columns = nomes_col
snps_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
snps_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

snps_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

snps_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas - não precisei aplicar a função 'ajustar_mes_01_04_07' para arrumar os meses

In [ ]:
# Preços da SNPS
snps_close = yf.download('SNPS', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025'
]
lst_months = ['01', '04', '07']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = snps_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
snps_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
snps_close_months = snps_close_months.reindex(index=snps_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '01',
    '04', 
    '07'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = snps_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
snps_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
snps_close_months_atual = snps_close_months_atual.reindex(index=snps_close_months_atual.index[::-1])

# Juntando as duas series pandas
snps_close_months = pd.concat([snps_close_months_atual, snps_close_months])

# Arredondamento de duas casas decimais
snps_close_months = round(snps_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/synopsys-inc-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
snps_close_months.index = snps_bs_10q.columns[:-3]

snps_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = snps_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=snps_close_months, df_is=snps_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=snps_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=snps_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=snps_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=snps_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=snps_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=snps_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=snps_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=snps_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=snps_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=snps_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=snps_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=snps_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=snps_bs_10q, df_is=snps_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=snps_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Short-term Investments'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=snps_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta 
lst_divida = [
    'Operating Lease, Liability, Current',
    'Long-term Debt, Current Maturities',
    'Operating Lease, Liability, Noncurrent',
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=snps_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=snps_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=snps_is_10q, df_bs=snps_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=snps_is_10q, df_bs=snps_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=snps_cf_10q, first_quarter='01')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Intangible Assets',
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum =f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=snps_cf_10q, first_quarter='01', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=snps_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=snps_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=snps_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=snps_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Operating Lease Liabilities',
    'Increase (Decrease) in Income Taxes',
    'Increase (Decrease) in Contract with Customer, Liability'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=snps_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='01')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=snps_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='01')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=snps_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='01')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=snps_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Debt',
    'Payments of Financing Costs'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=snps_cf_10q, first_quarter='01', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=snps_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=snps_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=snps_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=snps_cf_10q, first_quarter='01')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=snps_cf_10q, df_is=snps_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=snps_cf_10q, df_is=snps_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=snps_cf_10q,  first_quarter='01')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=snps_bs_10q, df_is=snps_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=snps_bs_10q, df_is=snps_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=snps_bs_10q, df_is=snps_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=snps_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=snps_bs_10q, df_is=snps_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=snps_is_10q, df_bs=snps_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=snps_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran, 
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_sliced,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
snps_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
snps_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
snps_indicadores_10q = snps_indicadores_10q.fillna(0)

snps_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//electronic_design_automation//synopsys//snps_indicators.xlsx') as writer:
    snps_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    snps_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

# **Setor de Fabricantes de Equipamentos de Semicondutores**

## Applied Materials

* 1Q -> Lançamento em Janeiro (01);
* 2Q -> Lançamento em Abril (04);
* 3Q -> Lançamento em Julho (07);
* 10K -> Lançamento em Outubro (10).

In [ ]:
ticker = 'amat'
f_sec.cik_matching_ticker(ticker)

### Scraping Applied Materials 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_amat = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_amat.index = pd.to_datetime(df_lst_acc_num_amat.index, format='%Y-%m-%d')

df_lst_acc_num_amat

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2017 p/ iteração
df_lst_acc_num_amat_sliced = df_lst_acc_num_amat.loc['2017-10-29':]
df_lst_acc_num_amat_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_amat_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A Treasury Stock, Common, Value, Value' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Treasury Stock, Value'
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2022-10-30'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2022-10-30'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2021-10-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2021-10-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2020-10-25'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2020-10-25'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2019-10-27'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2019-10-27'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2018-10-28'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2018-10-28'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2017-10-29'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2017-10-29'] 

# A linha 'Other Liabilities, Noncurrent' na coluna abaixo está zerada
# As informações estão nas linhas 'Other Liabilities' e 'Liabilities, Other than Long-term Debt, Noncurrent
df_balance_sheet_10k.loc['Other Liabilities, Noncurrent', '2020-10-25'] = df_balance_sheet_10k.loc['Other Liabilities', '2020-10-25'] 
df_balance_sheet_10k.loc['Other Liabilities, Noncurrent', '2019-10-27'] = df_balance_sheet_10k.loc['Liabilities, Other than Long-term Debt, Noncurrent', '2019-10-27'] 
df_balance_sheet_10k.loc['Other Liabilities, Noncurrent', '2018-10-28'] = df_balance_sheet_10k.loc['Liabilities, Other than Long-term Debt, Noncurrent', '2018-10-28'] 
df_balance_sheet_10k.loc['Other Liabilities, Noncurrent', '2017-10-29'] = df_balance_sheet_10k.loc['Liabilities, Other than Long-term Debt, Noncurrent', '2017-10-29'] 

# A linha 'Accrued Income Taxes, Noncurrent' na coluna abaixo está zerada
# As informações estão nas linhas 'Accrued Income Taxes' 
df_balance_sheet_10k.loc['Accrued Income Taxes, Noncurrent', '2018-10-28'] = df_balance_sheet_10k.loc['Accrued Income Taxes', '2018-10-28'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Treasury Stock, Value',
    'Other Liabilities',
    'Liabilities, Other than Long-term Debt, Noncurrent',
    'Accrued Income Taxes',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Long-term Debt, Current Maturities'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'amat_CustomerDepositsAndDeferredRevenueCurrent': 'Customer Deposits And Deferred Revenue Current',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_amat_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest' 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-10-25'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-10-25'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-10-27'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-10-27'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-10-28'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-10-28']
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-10-29'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-10-29']

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenues' e 'Revenue, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2019-10-27'] = df_income_statement_10k.loc['Revenues', '2019-10-27'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-10-28'] = df_income_statement_10k.loc['Revenues', '2018-10-28']
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-10-29'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-10-29'] 

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'
df_income_statement_10k.loc['Interest Expense', '2025-10-26'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2025-10-26'] 
df_income_statement_10k.loc['Interest Expense', '2024-10-27'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2024-10-27'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Revenues',
    'Revenue, Net (Deprecated 2018-01-31)',
    'InterestExpenseNonoperating'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'Derivative Instruments Not Designated as Hedging Instruments, Gain (Loss), Net',
    'Gain (Loss) on Contract Termination'

])

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_amat_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Proceeds from Sale and Maturity of Other Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale, Maturity and Collection of Investments'
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2022-10-30'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Investments', '2022-10-30']
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2021-10-31'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Investments', '2021-10-31']
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2020-10-25'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Investments', '2020-10-25']
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2019-10-27'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Investments', '2019-10-27']
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2018-10-28'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Investments', '2018-10-28']
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2017-10-29'] = df_cash_flow_10k.loc['Proceeds from Sale, Maturity and Collection of Investments', '2017-10-29']

# A linha 'Depreciation, Depletion and Amortization, Nonproduction' nas colunas abaixo estão zeradas
# As informações estão na linha 'Depreciation, Depletion and Amortization'
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2022-10-30'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2022-10-30'] 
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization, Nonproduction', '2021-10-31'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2021-10-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Proceeds from Sale, Maturity and Collection of Investments',
    'Depreciation, Depletion and Amortization',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'amat_FinanceLeasePrincipalPaymentsNet',
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash and Cash Equivalents, at Carrying Value',
    'Restricted Cash Equivalents'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2018-10-28'] = 75
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-10-29'] = 133

df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2017-10-29'] = -125

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation, Depletion and Amortization, Nonproduction': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Applied Materials 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_amat = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_amat.index = pd.to_datetime(df_lst_acc_num_10q_amat.index, format='%Y-%m-%d')

df_lst_acc_num_10q_amat

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2020 p/ iteração
df_lst_acc_num_10q_amat_sliced = df_lst_acc_num_10q_amat.loc['2020-01-26':]
df_lst_acc_num_10q_amat_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_amat_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Treasury Stock, Value' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Common, Value' 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2026-07-26'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2026-07-26'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2026-04-26'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2026-04-26'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2026-01-25'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2026-01-25'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2025-07-27'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2025-07-27'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2025-04-27'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2025-04-27'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2025-01-26'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2025-01-26'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2024-07-28'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2024-07-28'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2024-04-28'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2024-04-28'] 
df_balance_sheet_10q.loc['Treasury Stock, Value', '2024-01-28'] = df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2024-01-28'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Treasury Stock, Common, Value',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
])

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_amat_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'  
df_income_statement_10q.loc['Interest Expense', '2026-07-26'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-07-26'] 
df_income_statement_10q.loc['Interest Expense', '2026-04-26'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-04-26'] 
df_income_statement_10q.loc['Interest Expense', '2026-01-25'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-01-25'] 
df_income_statement_10q.loc['Interest Expense', '2025-07-27'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-07-27'] 
df_income_statement_10q.loc['Interest Expense', '2025-04-27'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-04-27'] 
df_income_statement_10q.loc['Interest Expense', '2025-01-26'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-01-26'] 
df_income_statement_10q.loc['Interest Expense', '2024-07-28'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-07-28'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'  
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-08-01'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-08-01'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-05-02'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-05-02'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-01-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-01-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-07-26'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-07-26'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-04-26'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-04-26'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-01-26'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-01-26'] 

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenues'  
df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2021-01-31'] = df_income_statement_10q.loc['Revenues', '2021-01-31'] 
df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-07-26'] = df_income_statement_10q.loc['Revenues', '2020-07-26'] 
df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-04-26'] = df_income_statement_10q.loc['Revenues', '2020-04-26'] 
df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-01-26'] = df_income_statement_10q.loc['Revenues', '2020-01-26'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'InterestExpenseNonoperating',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Revenues',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Litigation Settlement, Expense',
    'Severance Costs',
    'Gain (Loss) on Contract Termination',
    'Restructuring Charges'
])

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_amat_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Proceeds from Sale and Maturity of Other Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale, Maturity and Collection of Investments'
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2023-04-30'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2023-04-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2023-01-29'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2023-01-29'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2022-07-31'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2022-07-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2022-05-01'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2022-05-01'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2022-01-30'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2022-01-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2021-08-01'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2021-08-01'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2021-05-02'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2021-05-02'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2021-01-31'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2021-01-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2020-07-26'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2020-07-26'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2020-04-26'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2020-04-26'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Other Investments', '2020-01-26'] = df_cash_flow_10q.loc['Proceeds from Sale, Maturity and Collection of Investments', '2020-01-26'] 

# A linha 'Finance Lease, Principal Payments' nas colunas abaixo estão zeradas
# As informações estão na linha 'amat_FinanceLeasePrincipalPaymentsNet' e 'Repayments of Debt'
df_cash_flow_10q.loc['Finance Lease, Principal Payments', '2024-04-28'] = df_cash_flow_10q.loc['amat_FinanceLeasePrincipalPaymentsNet', '2024-04-28'] 
df_cash_flow_10q.loc['Finance Lease, Principal Payments', '2024-01-28'] = df_cash_flow_10q.loc['amat_FinanceLeasePrincipalPaymentsNet', '2024-01-28'] 
df_cash_flow_10q.loc['Finance Lease, Principal Payments', '2020-07-26'] = df_cash_flow_10q.loc['Repayments of Debt', '2020-07-26'] 

# A linha 'Proceeds from Issuance of Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Debt, Net of Issuance Costs' 
df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2020-07-26'] = df_cash_flow_10q.loc['Proceeds from Debt, Net of Issuance Costs', '2020-07-26'] 
df_cash_flow_10q.loc['Proceeds from Issuance of Long-term Debt', '2020-04-26'] = df_cash_flow_10q.loc['Proceeds from Debt, Net of Issuance Costs', '2020-04-26'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Proceeds from Sale, Maturity and Collection of Investments',
    'amat_FinanceLeasePrincipalPaymentsNet',
    'Repayments of Debt',
    'Proceeds from Debt, Net of Issuance Costs'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Litigation Settlement, Expense',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash and Cash Equivalents, at Carrying Value',
    'Restricted Cash Equivalents'
])

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation, Depletion and Amortization, Nonproduction': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
amat_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

amat_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

amat_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
amat_bs.columns = pd.to_datetime(amat_bs.columns)
amat_is.columns = pd.to_datetime(amat_is.columns)
amat_cf.columns = pd.to_datetime(amat_cf.columns)

# Transformando as colunas em apenas o ano
amat_bs.columns = amat_bs.columns.year
amat_is.columns = amat_is.columns.year
amat_cf.columns = amat_cf.columns.year

In [ ]:
# Preços da AMAT
amat_close = yf.download('AMAT', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_oct_close = []

for year in lst_years:
    last_close = amat_close[f'{year}-10'].iloc[-1]
    last_oct_close.append(last_close)

# Transformando em uma série pandas
amat_close_oct = pd.Series(last_oct_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amat_close_oct = amat_close_oct.reindex(index=amat_close_oct.index[::-1])

# Arredondamento de duas casas decimais
amat_close_oct = round(amat_close_oct, 2)

# Não realizou split recentemente (https://br.investing.com/equities/applied-matls-inc-historical-data-splits)

# Transformando o index em int
amat_close_oct.index = amat_close_oct.index.astype(int)

amat_close_oct

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = amat_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=amat_close_oct, df_is=amat_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=amat_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=amat_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=amat_close_oct, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=amat_close_oct, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=amat_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=amat_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=amat_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=amat_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=amat_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=amat_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=amat_bs, df_is=amat_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=amat_close_oct, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Short-term Investments'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=amat_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Short-term Debt',
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=amat_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=amat_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=amat_is, df_bs=amat_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=amat_is, df_bs=amat_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=amat_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=amat_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=amat_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=amat_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=amat_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = [
    'Payment, Tax Withholding, Share-based Payment Arrangement',
    'Finance Lease, Principal Payments'
]

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=amat_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=amat_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=amat_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Deferred Income Taxes',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Income Taxes Payable',
    'Increase (Decrease) in Other Operating Liabilities',
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=amat_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=amat_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Long-term Debt',
    'Proceeds from Issuance of Commercial Paper'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amat_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt',
    'Repayments of Commercial Paper',
    'Finance Lease, Principal Payments'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amat_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=amat_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=amat_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=amat_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=amat_cf, df_is=amat_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=amat_cf, df_is=amat_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=amat_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=amat_bs, df_is=amat_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=amat_bs, df_is=amat_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=amat_bs, df_is=amat_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=amat_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=amat_bs, df_is=amat_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=amat_is, df_bs=amat_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=amat_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
amat_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
amat_indicadores_10k.columns = nomes_col
amat_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
amat_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

amat_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

amat_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
amat_bs_10q.columns = [f_sec.ajustar_mes_01_04_07(col) for col in amat_bs_10q.columns]
amat_is_10q.columns = [f_sec.ajustar_mes_01_04_07(col) for col in amat_is_10q.columns]
amat_cf_10q.columns = [f_sec.ajustar_mes_01_04_07(col) for col in amat_cf_10q.columns]

In [ ]:
# Preços da AMAT
amat_close = yf.download('AMAT', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025'
]
lst_months = ['01', '04', '07']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = amat_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
amat_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amat_close_months = amat_close_months.reindex(index=amat_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '01',
    '04', 
    '07'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = amat_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
amat_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amat_close_months_atual = amat_close_months_atual.reindex(index=amat_close_months_atual.index[::-1])

# Juntando as duas series pandas
amat_close_months = pd.concat([amat_close_months_atual, amat_close_months])

# Arredondamento de duas casas decimais
amat_close_months = round(amat_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/applied-matls-inc-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
amat_close_months.index = amat_bs_10q.columns[:-3]

amat_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = amat_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=amat_close_months, df_is=amat_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=amat_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=amat_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=amat_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=amat_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=amat_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=amat_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=amat_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=amat_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=amat_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=amat_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=amat_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=amat_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=amat_bs_10q, df_is=amat_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=amat_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Short-term Investments'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=amat_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta 
lst_divida = [
    'Short-term Debt',
    'Long-term Debt, Excluding Current Maturities',
    'Long-term Debt, Current Maturities'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=amat_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=amat_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=amat_is_10q, df_bs=amat_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=amat_is_10q, df_bs=amat_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=amat_cf_10q, first_quarter='01')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = [
    'Payment, Tax Withholding, Share-based Payment Arrangement',
    'Finance Lease, Principal Payments'
]

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=amat_cf_10q, first_quarter='01', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=amat_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=amat_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=amat_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=amat_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Deferred Income Taxes',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Income Taxes Payable',
    'Increase (Decrease) in Other Operating Liabilities',
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=amat_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='01')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=amat_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='01')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=amat_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='01')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=amat_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Long-term Debt',
    'Proceeds from Issuance of Commercial Paper'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Commercial Paper',
    'Finance Lease, Principal Payments'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amat_cf_10q, first_quarter='01', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=amat_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=amat_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=amat_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=amat_cf_10q, first_quarter='01')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=amat_cf_10q, df_is=amat_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=amat_cf_10q, df_is=amat_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=amat_cf_10q,  first_quarter='01')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=amat_bs_10q, df_is=amat_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=amat_bs_10q, df_is=amat_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=amat_bs_10q, df_is=amat_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=amat_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=amat_bs_10q, df_is=amat_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=amat_is_10q, df_bs=amat_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=amat_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran, 
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
amat_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado',
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
amat_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
amat_indicadores_10q = amat_indicadores_10q.fillna(0)

amat_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//applied_materials//amat_indicators.xlsx') as writer:
    amat_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    amat_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## KLA Corporation

* 1Q -> Lançamento em Setembro (09);
* 2Q -> Lançamento em Dezembro (12);
* 3Q -> Lançamento em Março (03);
* 10K -> Lançamento em Junho (06).

In [ ]:
ticker = 'klac'
f_sec.cik_matching_ticker(ticker)

### Scraping KLA Corporation 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_klac = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_klac.index = pd.to_datetime(df_lst_acc_num_klac.index, format='%Y-%m-%d')

df_lst_acc_num_klac

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_klac['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)
		
# A 'Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Unsecured Long-term Debt, Noncurrent'
df_balance_sheet_10k.loc['Long-term Debt', '2020-06-30'] = df_balance_sheet_10k.loc['Unsecured Long-term Debt, Noncurrent', '2020-06-30'] 
df_balance_sheet_10k.loc['Long-term Debt', '2019-06-30'] = df_balance_sheet_10k.loc['Unsecured Long-term Debt, Noncurrent', '2019-06-30'] 
df_balance_sheet_10k.loc['Long-term Debt', '2018-06-30'] = df_balance_sheet_10k.loc['Unsecured Long-term Debt, Noncurrent', '2018-06-30'] 
df_balance_sheet_10k.loc['Long-term Debt', '2017-06-30'] = df_balance_sheet_10k.loc['Unsecured Long-term Debt, Noncurrent', '2017-06-30'] 

# A 'klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Debt Securities, Available-for-sale, Current' e 'Marketable Securities, Current'
df_balance_sheet_10k.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2020-06-30'] = df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2020-06-30'] 
df_balance_sheet_10k.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2019-06-30'] = df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2019-06-30'] 
df_balance_sheet_10k.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2018-06-30'] = df_balance_sheet_10k.loc['Marketable Securities, Current', '2018-06-30'] 
df_balance_sheet_10k.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2017-06-30'] = df_balance_sheet_10k.loc['Marketable Securities, Current', '2017-06-30'] 

# A 'klac_ContractWithCustomerLiabilityCurrentServiceRevenue' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Deferred Revenue and Credits, Current'
df_balance_sheet_10k.loc['klac_ContractWithCustomerLiabilityCurrentServiceRevenue', '2018-06-30'] = df_balance_sheet_10k.loc['Deferred Revenue and Credits, Current', '2018-06-30'] 
df_balance_sheet_10k.loc['klac_ContractWithCustomerLiabilityCurrentServiceRevenue', '2017-06-30'] = df_balance_sheet_10k.loc['Deferred Revenue and Credits, Current', '2017-06-30'] 

# A 'Contract with Customer, Liability, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Deferred Revenue and Credits, Noncurrent'
df_balance_sheet_10k.loc['Contract with Customer, Liability, Noncurrent', '2018-06-30'] = df_balance_sheet_10k.loc['Deferred Revenue and Credits, Noncurrent', '2018-06-30'] 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Noncurrent', '2017-06-30'] = df_balance_sheet_10k.loc['Deferred Revenue and Credits, Noncurrent', '2017-06-30'] 

# A linha 'Cash and Cash Equivalents, at Carrying Value' na coluna abaixo está zerada
# As informações estão nas linhas 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' 
df_balance_sheet_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2020-06-30'] = df_balance_sheet_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2020-06-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Unsecured Long-term Debt, Noncurrent',
    'Debt Securities, Available-for-sale, Current',
    'Marketable Securities, Current',
    'Deferred Revenue and Credits, Current',
    'Deferred Revenue and Credits, Noncurrent',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'klac_ContractWithCustomerLiabilityCurrentSystemProfit',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest"
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue': 'Debt Securities Available For Sale And Equity Securities Fair Value',
    'klac_ContractWithCustomerLiabilityCurrentSystemRevenue': 'Contract With Customer Liability Current System Revenue',
    'klac_ContractWithCustomerLiabilityCurrentServiceRevenue': 'Contract With Customer Liability Current Service Revenue',
    'klac_DeferredSystemProfit': 'Deferred System Profit'
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_klac['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest' 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-06-30'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-06-30']
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-06-30']
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-06-30']

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'
df_income_statement_10k.loc['Interest Expense', '2026-06-30'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2026-06-30'] 
df_income_statement_10k.loc['Interest Expense', '2025-06-30'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2025-06-30']
df_income_statement_10k.loc['Interest Expense', '2024-06-30'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2024-06-30']

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenue, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-06-30'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2018-06-30'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-06-30'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-06-30']

# A linha 'Other Nonoperating Income (Expense)' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest and Other Income'
df_income_statement_10k.loc['Other Nonoperating Income (Expense)', '2018-06-30'] = df_income_statement_10k.loc['Interest and Other Income', '2018-06-30'] 
df_income_statement_10k.loc['Other Nonoperating Income (Expense)', '2017-06-30'] = df_income_statement_10k.loc['Interest and Other Income', '2017-06-30']

# A linha 'Asset Impairment Charges' na coluna abaixo está zerada
# As informações estão na linha 'Goodwill, Impairment Loss'
df_income_statement_10k.loc['Asset Impairment Charges', '2020-06-30'] = df_income_statement_10k.loc['Goodwill, Impairment Loss', '2020-06-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'InterestExpenseNonoperating',
    'Revenue, Net (Deprecated 2018-01-31)',
    'Interest and Other Income',
    'Goodwill, Impairment Loss'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_RevenueFromContractWithCustomerAbstract',
    'us-gaap_RevenuesAbstract',
    'klac_GainsLossesonExtinguishmentofDebtandOtherNet',
    'Common Stock, Dividends, Per Share, Declared',
    'Sales Revenue, Goods, Net (Deprecated 2018-01-31)',
    'Sales Revenue, Services, Net (Deprecated 2018-01-31)',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Gain (Loss) on Extinguishment of Debt'
])

# Calculando a coluna 'Operating Income'
df_income_statement_10k.loc['Operating Income'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10k.loc['Cost of Revenue'] - df_income_statement_10k.loc['Research and Development Expense'] - df_income_statement_10k.loc['Selling, General and Administrative Expense']

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['Cost of Revenue', '2019-06-30'] = 1869377
df_income_statement_10k.loc['Research and Development Expense', '2019-06-30'] = 711030
df_income_statement_10k.loc['Selling, General and Administrative Expense', '2019-06-30'] = 599124 
df_income_statement_10k.loc['Other Nonoperating Income (Expense)', '2019-06-30'] = -31462
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-06-30'] = 1296231
df_income_statement_10k.loc['Income Tax Expense (Benefit)', '2019-06-30'] = 121214
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic', '2019-06-30'] = 156053
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2019-06-30'] = 156949
df_income_statement_10k.loc['Interest Expense', '2019-06-30'] = 124604 

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10k.loc['Cost of Revenue']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_klac['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Net Income (Loss) Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2025-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2025-06-30']
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2024-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2024-06-30']
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2023-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2023-06-30']
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2022-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-06-30']
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2021-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-06-30']
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2020-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-06-30']
df_cash_flow_10k.loc['Net Income (Loss) Attributable to Parent', '2019-06-30'] = df_cash_flow_10k.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-06-30']

# A linha 'klac_ProceedsFromSaleOfTradingSecurities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale and Maturity of Marketable Securities'
df_cash_flow_10k.loc['klac_ProceedsFromSaleOfTradingSecurities', '2022-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2022-06-30']
df_cash_flow_10k.loc['klac_ProceedsFromSaleOfTradingSecurities', '2021-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2021-06-30']
df_cash_flow_10k.loc['klac_ProceedsFromSaleOfTradingSecurities', '2020-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Debt and Equity Securities, FV-NI, Held-for-investment', '2020-06-30']
df_cash_flow_10k.loc['klac_ProceedsFromSaleOfTradingSecurities', '2019-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2019-06-30']
df_cash_flow_10k.loc['klac_ProceedsFromSaleOfTradingSecurities', '2018-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2018-06-30']
df_cash_flow_10k.loc['klac_ProceedsFromSaleOfTradingSecurities', '2017-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2017-06-30']

# A linha 'klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accounts Receivable'
df_cash_flow_10k.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2019-06-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Receivable', '2019-06-30']
df_cash_flow_10k.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2018-06-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Receivable', '2018-06-30']
df_cash_flow_10k.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2017-06-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Receivable', '2017-06-30']

# A linha 'Payments of Ordinary Dividends, Common Stock' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments of Dividends'
df_cash_flow_10k.loc['Payments of Ordinary Dividends, Common Stock', '2019-06-30'] = df_cash_flow_10k.loc['Payments of Dividends', '2019-06-30']
df_cash_flow_10k.loc['Payments of Ordinary Dividends, Common Stock', '2018-06-30'] = df_cash_flow_10k.loc['Payments of Dividends', '2018-06-30']
df_cash_flow_10k.loc['Payments of Ordinary Dividends, Common Stock', '2017-06-30'] = df_cash_flow_10k.loc['Payments of Dividends', '2017-06-30']

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities'
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2018-06-30'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2018-06-30']
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2017-06-30'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2017-06-30']

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities'
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2018-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2018-06-30']
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-06-30']

# A linha 'Proceeds from Sale and Maturity of Other Investments' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale of Other Investments'
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2020-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Other Investments', '2020-06-30']

# A linha 'Goodwill and Intangible Asset Impairment' na coluna abaixo está zerada
# As informações estão na linha 'Goodwill, Impairment Loss'
df_cash_flow_10k.loc['Goodwill and Intangible Asset Impairment', '2020-06-30'] = df_cash_flow_10k.loc['Goodwill, Impairment Loss', '2020-06-30']

# A linha 'Proceeds from Debt, Net of Issuance Costs' na coluna abaixo está zerada
# As informações estão na linha 'klac_ProceedsFromRepaymentsOfDebtIssuanceNetOfIssuanceCosts'
df_cash_flow_10k.loc['Proceeds from Debt, Net of Issuance Costs', '2026-06-30'] = df_cash_flow_10k.loc['klac_ProceedsFromRepaymentsOfDebtIssuanceNetOfIssuanceCosts', '2026-06-30']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Proceeds from Sale and Maturity of Marketable Securities',
    'Proceeds from Sale of Debt and Equity Securities, FV-NI, Held-for-investment',
    'Increase (Decrease) in Accounts Receivable',
    'Payments of Dividends',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Sale of Available-for-sale Securities',

    'Proceeds from Sale of Other Investments',
    'Goodwill, Impairment Loss',
    'klac_ProceedsFromRepaymentsOfDebtIssuanceNetOfIssuanceCosts',
    'Gain (Loss) on Disposition of Business',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'klac_AcquisitionOfNonMarketableSecurities',
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'klac_GainsLossesonExtinguishmentofDebtandOtherNet',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash and Cash Equivalents, at Carrying Value',
    'Proceeds from Sale of Property, Plant, and Equipment',
    'Cost-method Investments, Other than Temporary Impairment',
    'Marketable Securities, Gain (Loss)',
    'Payments to Acquire Investments',
    'klac_NoncashOrPartNoncashAcquisitionContingentConsiderationPayableReceivable',
    'Dividends Payable',
    'klac_NoncashOrPartNoncashAcquisitionHoldbackConsiderationPayable',
    'Stock Issued',
    'klac_NoncashOrPartNoncashAcquisitionContingentConsiderationPayable',
    'Equity Securities, FV-NI, Unrealized Gain (Loss)',
    'Payments of Ordinary Dividends, Noncontrolling Interest',
    'klac_PaymentsForForwardContractForAcceleratedShareRepurchases',
    'Payments to Noncontrolling Interests',
    'klac_ProceedsFromDisposalOfNoncontrollingInterest',
    'Gain (Loss) on Extinguishment of Debt',
    'klac_IncreaseDecreaseInDeferredSystemProfit',
    'Proceeds from Divestiture of Businesses',
    'Payments to Acquire Intangible Assets',
    'klac_NoncashTransactionIncreaseDecreaseInDividendsPayable',
    'klac_StockRepurchaseProgramUnsettledCommonStockRepurchase',
    'klac_ContingentConsiderationPayableAndOtherNet',
    'Payment for Contingent Consideration Liability, Financing Activities',
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated': 'Increase (Decrease) In Accounts Receivable Excluding Acquisition Related',
    'klac_IncreaseDecreaseInContractWithCustomerLiabilitySystemRevenue': 'Increase (Decrease) In Contract With Customer Liability System Revenue',
    'klac_IncreaseDecreaseInContractWithCustomerLiabilityServiceRevenue': 'Increase (Decrease) In Contract With Customer Liability Service Revenue',
    'klac_ProceedsFromCapitalRelatedGovernmentAssistance': 'Proceeds From Capital Related Government Assistance',
    'klac_ProceedsFromSaleOfTradingSecurities': 'Proceeds From Sale Of Trading Securities',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Debt Securities Available For Sale And Equity Securities Fair Value': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping KLA Corporation 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_klac = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_klac.index = pd.to_datetime(df_lst_acc_num_10q_klac.index, format='%Y-%m-%d')

df_lst_acc_num_10q_klac

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de '2019-09-30' p/ iteração
df_lst_acc_num_10q_klac_sliced = df_lst_acc_num_10q_klac.loc['2019-09-30':]
df_lst_acc_num_10q_klac_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_klac_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)
				
# A linha 'klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue' nas colunas abaixo estão zeradas
# As informações estão na linha 'Debt Securities, Available-for-sale, Current' 
df_balance_sheet_10q.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2021-03-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2021-03-31'] 
df_balance_sheet_10q.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2020-12-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2020-12-31'] 
df_balance_sheet_10q.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2020-09-30'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2020-09-30'] 
df_balance_sheet_10q.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2020-03-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2020-03-31'] 
df_balance_sheet_10q.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2019-12-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2019-12-31'] 
df_balance_sheet_10q.loc['klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue', '2019-09-30'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2019-09-30'] 

# A linha 'Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Unsecured Long-term Debt, Noncurrent' 
df_balance_sheet_10q.loc['Long-term Debt', '2021-03-31'] = df_balance_sheet_10q.loc['Unsecured Long-term Debt, Noncurrent', '2021-03-31'] 
df_balance_sheet_10q.loc['Long-term Debt', '2020-12-31'] = df_balance_sheet_10q.loc['Unsecured Long-term Debt, Noncurrent', '2020-12-31'] 
df_balance_sheet_10q.loc['Long-term Debt', '2020-09-30'] = df_balance_sheet_10q.loc['Unsecured Long-term Debt, Noncurrent', '2020-09-30'] 
df_balance_sheet_10q.loc['Long-term Debt', '2020-03-31'] = df_balance_sheet_10q.loc['Unsecured Long-term Debt, Noncurrent', '2020-03-31'] 
df_balance_sheet_10q.loc['Long-term Debt', '2019-12-31'] = df_balance_sheet_10q.loc['Unsecured Long-term Debt, Noncurrent', '2019-12-31'] 
df_balance_sheet_10q.loc['Long-term Debt', '2019-09-30'] = df_balance_sheet_10q.loc['Unsecured Long-term Debt, Noncurrent', '2019-09-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Debt Securities, Available-for-sale, Current',
    'Unsecured Long-term Debt, Noncurrent',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest",
    "Stockholders' Equity Attributable to Noncontrolling Interest"
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'klac_DebtSecuritiesAvailableForSaleAndEquitySecuritiesFairValue': 'Debt Securities Available For Sale And Equity Securities Fair Value',
    'klac_ContractWithCustomerLiabilityCurrentSystemRevenue': 'Contract With Customer Liability Current System Revenue',
    'klac_ContractWithCustomerLiabilityCurrentServiceRevenue': 'Contract With Customer Liability Current Service Revenue',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_klac_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'  
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-03-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-12-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-12-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-09-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-03-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-12-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-12-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-09-30'] 

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'  
df_income_statement_10q.loc['Interest Expense', '2026-03-31'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-03-31'] 
df_income_statement_10q.loc['Interest Expense', '2025-12-31'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-12-31'] 
df_income_statement_10q.loc['Interest Expense', '2025-09-30'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-09-30'] 
df_income_statement_10q.loc['Interest Expense', '2025-03-31'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-03-31'] 
df_income_statement_10q.loc['Interest Expense', '2024-12-31'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-12-31'] 
df_income_statement_10q.loc['Interest Expense', '2024-09-30'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-09-30'] 

# A linha 'Other Nonoperating Income (Expense)' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest and Other Income'  
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2020-03-31'] = df_income_statement_10q.loc['Interest and Other Income', '2020-03-31'] 
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2019-12-31'] = df_income_statement_10q.loc['Interest and Other Income', '2019-12-31'] 
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2019-09-30'] = df_income_statement_10q.loc['Interest and Other Income', '2019-09-30'] 

# A linha 'Asset Impairment Charges' nas colunas abaixo estão zeradas
# As informações estão na linha 'Goodwill, Impairment Loss'  
df_income_statement_10q.loc['Asset Impairment Charges', '2020-03-31'] = df_income_statement_10q.loc['Goodwill, Impairment Loss', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'InterestExpenseNonoperating',
    'Interest and Other Income',
    'Goodwill, Impairment Loss'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_RevenueFromContractWithCustomerAbstract',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest'
])

# Calculando a coluna 'Operating Income'
df_income_statement_10q.loc['Operating Income'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10q.loc['Cost of Revenue'] - df_income_statement_10q.loc['Research and Development Expense'] - df_income_statement_10q.loc['Selling, General and Administrative Expense']

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10q.loc['Cost of Revenue']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_klac_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Net Income (Loss) Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2024-03-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2024-03-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2023-12-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2023-12-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2023-09-30'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2023-09-30'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2023-03-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2023-03-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-12-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-12-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-09-30'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-09-30'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2022-03-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2022-03-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-12-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-12-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-09-30'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-09-30'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2021-03-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2021-03-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-12-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-12-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-09-30'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-09-30'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2020-03-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2020-03-31'] 
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2019-12-31'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2019-12-31'] 

# A linha 'Payments to Acquire Trading Securities Held-for-investment' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Other Investments'
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2023-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2023-03-31'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2022-12-31'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2022-12-31'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2022-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2022-09-30'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2022-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2022-03-31'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2021-12-31'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2021-12-31'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2021-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2021-09-30'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2021-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2021-03-31'] 
df_cash_flow_10q.loc['Payments to Acquire Trading Securities Held-for-investment', '2020-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Other Investments', '2020-09-30'] 

# A linha 'klac_ProceedsFromSaleOfTradingSecurities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale and Maturity of Marketable Securities'
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2023-03-31'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2023-03-31'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2022-12-31'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2022-12-31'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2022-09-30'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2022-09-30'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2022-03-31'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2022-03-31'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2021-12-31'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2021-12-31'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2021-09-30'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2021-09-30'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2021-03-31'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2021-03-31'] 
df_cash_flow_10q.loc['klac_ProceedsFromSaleOfTradingSecurities', '2020-09-30'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2020-09-30'] 
 
# A linha 'Income Taxes Paid, Net' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest' 
df_cash_flow_10q.loc['Income Taxes Paid, Net', '2021-09-30'] = df_cash_flow_10q.loc['Income Taxes Paid', '2021-09-30'] 
df_cash_flow_10q.loc['Income Taxes Paid, Net', '2021-03-31'] = df_cash_flow_10q.loc['Income Taxes Paid', '2021-03-31'] 
df_cash_flow_10q.loc['Income Taxes Paid, Net', '2020-09-30'] = df_cash_flow_10q.loc['Income Taxes Paid', '2020-09-30'] 

# A linha 'Asset Impairment Charges' nas colunas abaixo estão zeradas
# As informações estão na linha 'Goodwill, Impairment Loss'
df_cash_flow_10q.loc['Asset Impairment Charges', '2020-03-31'] = df_cash_flow_10q.loc['Goodwill, Impairment Loss', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Payments to Acquire Other Investments',
    'Proceeds from Sale and Maturity of Marketable Securities',
    'Income Taxes Paid',
    'Goodwill, Impairment Loss',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Increase (Decrease) in Derivative Assets and Liabilities',
    'Payment for Contingent Consideration Liability, Financing Activities',
    'Debt Issuance Costs Incurred During Noncash or Partial Noncash Transaction',
    'klac_PaymentsToAcquireNonMarketableSecurities',
    'Payments of Dividends',
    'Stock Issued',
    'klac_NoncashOrPartNoncashAcquisitionContingentConsiderationPayable',
    'klac_NoncashOrPartNoncashAcquisitionHoldbackConsiderationPayable',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Increase (Decrease) in Accounts Receivable',
    'Gain (Loss) on Disposition of Assets',
    'Dividends Payable, Current',
    'klac_NoncashTransactionIncreaseDecreaseInDividendsPayable',
    'Payments to Noncontrolling Interests',
    'Proceeds from Divestiture of Businesses',
    'klac_ProceedsFromDisposalOfNonControllingInterest',
    'Gain (Loss) on Extinguishment of Debt',
    'Payments to Acquire Intangible Assets',
    'klac_ProceedsFromSaleOfAssetsAcquisitionOfIntellectualPropertyAndOtherInvestments',
    'klac_StockRepurchaseProgramUnsettledCommonStockRepurchase',
    'klac_ContingentConsiderationPayableAndOtherNet',
    'klac_NoncashOrPartNoncashAcquisitionContingentConsiderationPayableReceivable'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2019-09-30'] = 1413414

df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2020-12-31'] = 164323
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2020-03-31'] = 269112
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2019-12-31'] = 187122
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization', '2019-09-30'] = 98588

df_cash_flow_10q.loc['Share-based Payment Arrangement, Noncash Expense', '2020-12-31'] = 53819 
df_cash_flow_10q.loc['Share-based Payment Arrangement, Noncash Expense', '2020-03-31'] = 85003
df_cash_flow_10q.loc['Share-based Payment Arrangement, Noncash Expense', '2019-12-31'] = 53733
df_cash_flow_10q.loc['Share-based Payment Arrangement, Noncash Expense', '2019-09-30'] = 26944

df_cash_flow_10q.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2020-12-31'] = -117189
df_cash_flow_10q.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2020-03-31'] = -128793
df_cash_flow_10q.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2019-12-31'] = -201896
df_cash_flow_10q.loc['klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated', '2019-09-30'] = -75214

df_cash_flow_10q.loc['Increase (Decrease) in Inventories', '2020-12-31'] = -112206
df_cash_flow_10q.loc['Increase (Decrease) in Inventories', '2020-03-31'] = -18208
df_cash_flow_10q.loc['Increase (Decrease) in Inventories', '2019-12-31'] = -6568
df_cash_flow_10q.loc['Increase (Decrease) in Inventories', '2019-09-30'] = -5091

df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Assets', '2020-12-31'] = -51287
df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Assets', '2020-03-31'] = -29271
df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Assets', '2019-12-31'] = -5372
df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Assets', '2019-09-30'] = -8930

df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2020-12-31'] = -1783
df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2020-03-31'] = 41239
df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2019-12-31'] = 54143
df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable', '2019-09-30'] = 18885

df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilitySystemRevenue', '2020-12-31'] = -61595
df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilitySystemRevenue', '2020-03-31'] = 54035
df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilitySystemRevenue', '2019-12-31'] = -35245
df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilitySystemRevenue', '2019-09-30'] = -4833

df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilityServiceRevenue', '2020-12-31'] = -1431
df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilityServiceRevenue', '2020-03-31'] = 7574
df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilityServiceRevenue', '2019-12-31'] = -3117
df_cash_flow_10q.loc['klac_IncreaseDecreaseInContractWithCustomerLiabilityServiceRevenue', '2019-09-30'] = -4337

df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Liabilities', '2020-12-31'] = 341181 
df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Liabilities', '2020-03-31'] = -18460
df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Liabilities', '2019-12-31'] = 107131
df_cash_flow_10q.loc['Increase (Decrease) in Other Operating Liabilities', '2019-09-30'] = 91043

df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2020-12-31'] = 1073252 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2020-03-31'] = 1326004
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2019-12-31'] = 883976
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2019-09-30'] = 496245

df_cash_flow_10q.loc['Payments to Acquire Property, Plant, and Equipment', '2020-12-31'] = -115069 
df_cash_flow_10q.loc['Payments to Acquire Property, Plant, and Equipment', '2020-03-31'] = -110885
df_cash_flow_10q.loc['Payments to Acquire Property, Plant, and Equipment', '2019-12-31'] = -67440
df_cash_flow_10q.loc['Payments to Acquire Property, Plant, and Equipment', '2019-09-30'] = -32566

df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2020-03-31'] = -78600
df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2019-12-31'] = -78530
df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2019-09-30'] = -78530

df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2020-12-31'] = -230212
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2020-03-31'] = -153053
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2019-12-31'] = -154841
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2019-09-30'] = -146693

df_cash_flow_10q.loc['Proceeds from Debt, Net of Issuance Costs', '2020-12-31'] = 40343 
df_cash_flow_10q.loc['Proceeds from Debt, Net of Issuance Costs', '2020-03-31'] = 742004

df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2020-03-31'] = 250000
df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2019-12-31'] = 250000

df_cash_flow_10q.loc['Repayments of Long-term Debt', '2020-12-31'] = -50000
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2020-03-31'] = -996033
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2019-12-31'] = -275000

df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2020-12-31'] = -365389
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2020-03-31'] = -829084
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2019-12-31'] = -513089
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2019-09-30'] = -228496

df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock', '2020-12-31'] = -280748
df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock', '2020-03-31'] = -389659
df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock', '2019-12-31'] = -256332
df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock', '2019-09-30'] = -121636

df_cash_flow_10q.loc['Proceeds from Issuance of Common Stock', '2020-12-31'] = 26356 
df_cash_flow_10q.loc['Proceeds from Issuance of Common Stock', '2020-03-31'] = 25285
df_cash_flow_10q.loc['Proceeds from Issuance of Common Stock', '2019-12-31'] = 24613
df_cash_flow_10q.loc['Proceeds from Issuance of Common Stock', '2019-09-30'] = 114

df_cash_flow_10q.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2020-12-31'] = -36145
df_cash_flow_10q.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2020-03-31'] = -40733
df_cash_flow_10q.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2019-12-31'] = -35775
df_cash_flow_10q.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2019-09-30'] = -23538

df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2020-12-31'] = -665583
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2020-03-31'] = -1238280
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2019-12-31'] = -805643
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2019-09-30'] = -373613

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'klac_IncreaseDecreaseInAccountsReceivableExcludingAcquisitionRelated': 'Increase (Decrease) In Accounts Receivable Excluding Acquisition Related',
    'klac_IncreaseDecreaseInContractWithCustomerLiabilitySystemRevenue': 'Increase (Decrease) In Contract With Customer Liability System Revenue',
    'klac_IncreaseDecreaseInContractWithCustomerLiabilityServiceRevenue': 'Increase (Decrease) In Contract With Customer Liability Service Revenue',
    'klac_ProceedsFromCapitalRelatedGovernmentAssistance': 'Proceeds From Capital Related Government Assistance',
    'klac_ProceedsFromSaleOfTradingSecurities': 'Proceeds From Sale Of Trading Securities'
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Debt Securities Available For Sale And Equity Securities Fair Value': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
klac_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

klac_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

klac_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
klac_bs.columns = pd.to_datetime(klac_bs.columns)
klac_is.columns = pd.to_datetime(klac_is.columns)
klac_cf.columns = pd.to_datetime(klac_cf.columns)

# Transformando as colunas em apenas o ano
klac_bs.columns = klac_bs.columns.year
klac_is.columns = klac_is.columns.year
klac_cf.columns = klac_cf.columns.year

In [ ]:
# Preços da KLAC
klac_close = yf.download('KLAC', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024', 
    '2025', '2026'
]

last_dec_close = []

for year in lst_years:
    last_close = klac_close[f'{year}-06'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
klac_close_jun = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
klac_close_jun = klac_close_jun.reindex(index=klac_close_jun.index[::-1])

# Arredondamento de duas casas decimais
klac_close_jun = round(klac_close_jun, 2)

# Teve um split de 10:1 em 11/06/2026 (https://br.investing.com/equities/kla-tencor-corp-historical-data-splits)
klac_close_jun.loc['2025'] = klac_close_jun.loc['2025'] * 10
klac_close_jun.loc['2024'] = klac_close_jun.loc['2024'] * 10
klac_close_jun.loc['2023'] = klac_close_jun.loc['2023'] * 10
klac_close_jun.loc['2022'] = klac_close_jun.loc['2022'] * 10
klac_close_jun.loc['2021'] = klac_close_jun.loc['2021'] * 10
klac_close_jun.loc['2020'] = klac_close_jun.loc['2020'] * 10
klac_close_jun.loc['2019'] = klac_close_jun.loc['2019'] * 10
klac_close_jun.loc['2018'] = klac_close_jun.loc['2018'] * 10
klac_close_jun.loc['2017'] = klac_close_jun.loc['2017'] * 10

# Transformando o index em int
klac_close_jun .index = klac_close_jun .index.astype(int)

klac_close_jun

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = klac_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=klac_close_jun, df_is=klac_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=klac_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=klac_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=klac_close_jun, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=klac_close_jun, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=klac_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=klac_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=klac_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=klac_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=klac_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=klac_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=klac_bs, df_is=klac_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=klac_close_jun, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Marketable Securities'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=klac_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt',
    'Long-term Debt, Current Maturities',
    'Short-term Debt'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=klac_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=klac_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=klac_is, df_bs=klac_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=klac_is, df_bs=klac_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=klac_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=klac_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=klac_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=klac_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=klac_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=klac_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=klac_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=klac_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Derivative Assets and Liabilities',
    'Increase (Decrease) In Accounts Receivable Excluding Acquisition Related',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) In Contract With Customer Liability System Revenue',
    'Increase (Decrease) In Contract With Customer Liability Service Revenue',
    'Increase (Decrease) in Other Operating Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=klac_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=klac_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Debt, Net of Issuance Costs',
    'Proceeds from Long-term Lines of Credit'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=klac_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt',
    'Payments of Debt Issuance Costs'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=klac_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=klac_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=klac_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=klac_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=klac_cf, df_is=klac_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=klac_cf, df_is=klac_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=klac_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=klac_bs, df_is=klac_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=klac_bs, df_is=klac_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=klac_bs, df_is=klac_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=klac_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=klac_bs, df_is=klac_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=klac_is, df_bs=klac_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=klac_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
klac_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
klac_indicadores_10k.columns = nomes_col
klac_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
klac_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

klac_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

klac_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
klac_bs_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in klac_bs_10q.columns]
klac_is_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in klac_is_10q.columns]
klac_cf_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in klac_cf_10q.columns]

In [ ]:
# Preços da KLAC
klac_close = yf.download('KLAC', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Dezembro
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025',
]
lst_months = ['03', '09', '12']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = klac_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
klac_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
klac_close_months = klac_close_months.reindex(index=klac_close_months.index[::-1])

# Retirando o preço de '03-2020' 
klac_close_months = klac_close_months.drop(index='03-2020')


# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Dezembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    # '09',
    # '12'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = klac_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
klac_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
klac_close_months_atual = klac_close_months_atual.reindex(index=klac_close_months_atual.index[::-1])

# Juntando as duas series pandas
klac_close_months = pd.concat([klac_close_months_atual, klac_close_months])

# Arredondamento de duas casas decimais
klac_close_months = round(klac_close_months, 2)

# Teve um split de 10:1 em 11/06/2026 (https://br.investing.com/equities/kla-tencor-corp-historical-data-splits)
klac_close_months.loc['03-2026'] = klac_close_months.loc['03-2026'] * 10
klac_close_months.loc['12-2025'] = klac_close_months.loc['12-2025'] * 10
klac_close_months.loc['09-2025'] = klac_close_months.loc['09-2025'] * 10
klac_close_months.loc['03-2025'] = klac_close_months.loc['03-2025'] * 10
klac_close_months.loc['12-2024'] = klac_close_months.loc['12-2024'] * 10
klac_close_months.loc['09-2024'] = klac_close_months.loc['09-2024'] * 10
klac_close_months.loc['03-2024'] = klac_close_months.loc['03-2024'] * 10
klac_close_months.loc['12-2023'] = klac_close_months.loc['12-2023'] * 10
klac_close_months.loc['09-2023'] = klac_close_months.loc['09-2023'] * 10
klac_close_months.loc['03-2023'] = klac_close_months.loc['03-2023'] * 10
klac_close_months.loc['12-2022'] = klac_close_months.loc['12-2022'] * 10
klac_close_months.loc['09-2022'] = klac_close_months.loc['09-2022'] * 10
klac_close_months.loc['03-2022'] = klac_close_months.loc['03-2022'] * 10
klac_close_months.loc['12-2021'] = klac_close_months.loc['12-2021'] * 10
klac_close_months.loc['09-2021'] = klac_close_months.loc['09-2021'] * 10
klac_close_months.loc['03-2021'] = klac_close_months.loc['03-2021'] * 10
klac_close_months.loc['12-2020'] = klac_close_months.loc['12-2020'] * 10
klac_close_months.loc['09-2020'] = klac_close_months.loc['09-2020'] * 10

# Substituindo o index para ficar igual ao dos dados fundamentalistas
klac_close_months.index = klac_bs_10q.columns[:-3]

klac_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = klac_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=klac_close_months, df_is=klac_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=klac_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=klac_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=klac_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=klac_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=klac_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=klac_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=klac_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=klac_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=klac_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=klac_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=klac_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=klac_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=klac_bs_10q, df_is=klac_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=klac_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Marketable Securities'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=klac_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt',
    'Long-term Debt, Current Maturities',
    'Short-term Debt'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=klac_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=klac_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=klac_is_10q, df_bs=klac_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=klac_is_10q, df_bs=klac_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=klac_cf_10q, first_quarter='09')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=klac_cf_10q, first_quarter='09', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=klac_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=klac_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=klac_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=klac_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) In Accounts Receivable Excluding Acquisition Related',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) In Contract With Customer Liability System Revenue',
    'Increase (Decrease) In Contract With Customer Liability Service Revenue',
    'Increase (Decrease) in Other Operating Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=klac_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='09')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=klac_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='09')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=klac_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='09')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=klac_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Debt, Net of Issuance Costs',
    'Proceeds from Long-term Lines of Credit'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt',
    'Payments of Debt Issuance Costs'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=klac_cf_10q, first_quarter='09', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=klac_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=klac_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=klac_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=klac_cf_10q, first_quarter='09')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=klac_cf_10q, df_is=klac_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=klac_cf_10q, df_is=klac_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=klac_cf_10q,  first_quarter='09')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=klac_bs_10q, df_is=klac_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=klac_bs_10q, df_is=klac_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=klac_bs_10q, df_is=klac_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=klac_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=klac_bs_10q, df_is=klac_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=klac_is_10q, df_bs=klac_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=klac_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
klac_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
klac_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
klac_indicadores_10q = klac_indicadores_10q.fillna(0)

klac_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//kla_corporation//klac_indicators.xlsx') as writer:
    klac_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    klac_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## LAM Research

* 1Q -> Lançamento em Setembro (09);
* 2Q -> Lançamento em Dezembro (12);
* 3Q -> Lançamento em Março (03);
* 10K -> Lançamento em Junho (06).

In [ ]:
ticker = 'lrcx'
f_sec.cik_matching_ticker(ticker)

### Scraping LAM Research 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_lrcx = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_lrcx.index = pd.to_datetime(df_lst_acc_num_lrcx.index, format='%Y-%m-%d')

df_lst_acc_num_lrcx

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de 2017 p/ iteração
df_lst_acc_num_lrcx_sliced = df_lst_acc_num_lrcx.loc['2017-06-25':]
df_lst_acc_num_lrcx_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_lrcx_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A 'Treasury Stock, Common, Value' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Treasury Stock, Value'
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2022-06-26'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2022-06-26'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2021-06-27'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2021-06-27'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2020-06-28'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2020-06-28'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2019-06-30'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2019-06-30'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2018-06-24'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2018-06-24'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2017-06-25'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2017-06-25'] 

# A 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization' e 'Property, Plant and Equipment, Net'
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-06-28'] = df_balance_sheet_10k.loc['lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization', '2020-06-28'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-06-30'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2019-06-30'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2018-06-24'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2018-06-24'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2017-06-25'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2017-06-25'] 

# A 'Long-term Debt and Lease Obligation, Current' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Debt, Current'
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation, Current', '2020-06-28'] = df_balance_sheet_10k.loc['Debt, Current', '2020-06-28'] 
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation, Current', '2019-06-30'] = df_balance_sheet_10k.loc['Debt, Current', '2019-06-30'] 
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation, Current', '2018-06-24'] = df_balance_sheet_10k.loc['Debt, Current', '2018-06-24'] 

# A 'Contract with Customer, Liability, Current' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Other Deferred Credits, Current'
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2019-06-30'] = df_balance_sheet_10k.loc['Other Deferred Credits, Current', '2019-06-30'] 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2018-06-24'] = df_balance_sheet_10k.loc['Other Deferred Credits, Current', '2018-06-24'] 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2017-06-25'] = df_balance_sheet_10k.loc['Other Deferred Credits, Current', '2017-06-25'] 

# A 'Goodwill' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Intangible Assets, Net (Including Goodwill)'
df_balance_sheet_10k.loc['Goodwill', '2026-06-28'] = df_balance_sheet_10k.loc['Intangible Assets, Net (Including Goodwill)', '2026-06-28'] 
df_balance_sheet_10k.loc['Goodwill', '2025-06-29'] = df_balance_sheet_10k.loc['Intangible Assets, Net (Including Goodwill)', '2025-06-29'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Treasury Stock, Value',
    'lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization',
    'Property, Plant and Equipment, Net',
    'Debt, Current',
    'Other Deferred Credits, Current',
    'Intangible Assets, Net (Including Goodwill)',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsAbstract',
    'Preferred Stock, Value, Issued'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization': 'Property, Plant, and Equipment',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_lrcx_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

			
# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest' 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-06-27'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-06-27'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-06-28'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-06-28'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-06-30'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-06-24'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-06-24'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-06-25'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-06-25']

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenue, Net (Deprecated 2018-01-31)' 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-06-24'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2018-06-24'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-06-25'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-06-25']

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Revenue, Net (Deprecated 2018-01-31)',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'Goodwill, Impairment Loss',
    'lrcx_CostOfGoodsAndServicesSoldExcludingRestructuringCharges',
    'lrcx_RestructuringChargesCostOfGoodsNet',
    'lrcx_RestructuringChargesOperatingExpenseNet'
])

# Arrumando a escala das colunas '2017-06-25', '2025-06-29' e '2026-06-28' em linhas específicas
list_items = [
    'Revenue from Contract with Customer, Excluding Assessed Tax',
    'Cost of Goods and Services Sold',
    'Gross Profit',
    'Research and Development Expense',
    'Selling, General and Administrative Expense',
    'Operating Expenses',
    'Operating Income (Loss)',
    'Other Nonoperating Income (Expense)',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest',
    'Income Tax Expense (Benefit)',
    'Net Income (Loss) Attributable to Parent'
]

df_income_statement_10k.loc[list_items, '2026-06-28'] /= 1000
df_income_statement_10k.loc[list_items, '2025-06-29'] /= 1000
df_income_statement_10k.loc[list_items, '2017-06-25'] /= 1000

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_lrcx_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Repayments of Debt and Lease Obligation' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security'
df_cash_flow_10k.loc['Repayments of Debt and Lease Obligation', '2020-06-28'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2020-06-28']
df_cash_flow_10k.loc['Repayments of Debt and Lease Obligation', '2019-06-30'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2019-06-30']
df_cash_flow_10k.loc['Repayments of Debt and Lease Obligation', '2018-06-24'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2018-06-24']
df_cash_flow_10k.loc['Repayments of Debt and Lease Obligation', '2017-06-25'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2017-06-25']

# A linha 'lrcx_TransferOfInventoryToPropertyAndEquipment' nas colunas abaixo estão zeradas
# As informações estão na linha 'lrcx_TransferOfInventoryToPropertyAndEquipmentNet'
df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipment', '2020-06-28'] = df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipmentNet', '2020-06-28']
df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipment', '2019-06-30'] = df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipmentNet', '2019-06-30']
df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipment', '2018-06-24'] = df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipmentNet', '2018-06-24']
df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipment', '2017-06-25'] = df_cash_flow_10k.loc['lrcx_TransferOfInventoryToPropertyAndEquipmentNet', '2017-06-25']

# A linha 'Net Cash Provided by (Used in) Operating Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Operating Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2018-06-24'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities, Continuing Operations', '2018-06-24']
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2017-06-25'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities, Continuing Operations', '2017-06-25']

# A linha 'Net Cash Provided by (Used in) Investing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Investing Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2018-06-24'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities, Continuing Operations', '2018-06-24']
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2017-06-25'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities, Continuing Operations', '2017-06-25']

# A linha 'Net Cash Provided by (Used in) Financing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Cash Provided by (Used in) Financing Activities, Continuing Operations'
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2018-06-24'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities, Continuing Operations', '2018-06-24']
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2017-06-25'] = df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities, Continuing Operations', '2017-06-25']

# A linha 'Interest Paid, Excluding Capitalized Interest, Operating Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Paid, Including Capitalized Interest, Operating and Investing Activities'
df_cash_flow_10k.loc['Interest Paid, Excluding Capitalized Interest, Operating Activities', '2018-06-24'] = df_cash_flow_10k.loc['Interest Paid, Including Capitalized Interest, Operating and Investing Activities', '2018-06-24']
df_cash_flow_10k.loc['Interest Paid, Excluding Capitalized Interest, Operating Activities', '2017-06-25'] = df_cash_flow_10k.loc['Interest Paid, Including Capitalized Interest, Operating and Investing Activities', '2017-06-25']

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities'
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2018-06-24'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2018-06-24']
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2017-06-25'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2017-06-25']

# A linha 'Proceeds from Issuance of Long-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Issuance of Commercial Paper'
df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2018-06-24'] = df_cash_flow_10k.loc['Proceeds from Issuance of Commercial Paper', '2018-06-24']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security',
    'lrcx_TransferOfInventoryToPropertyAndEquipmentNet',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Financing Activities, Continuing Operations',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Issuance of Commercial Paper'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract',
    'Other-than-temporary Impairment Loss, Debt Securities, Portion Recognized in Earnings',
    'Asset Impairment Charges',
    'Gain (Loss) on Disposition of Business',
    'Goodwill, Impairment Loss',
    'Payments to Acquire Other Investments',
    'Proceeds from Divestiture of Businesses',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Increase (Decrease) in Restricted Cash',
    'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale',
    'Proceeds from Sale of Debt Securities, Available-for-sale',
    'Proceeds from Sale of Available-for-sale Securities',
    'Restricted Cash and Cash Equivalents',
    'Cash and Cash Equivalents, at Carrying Value',
    'Other than Temporary Impairment Losses, Investments, Portion Recognized in Earnings, Net',
    'lrcx_DeferredIncomeTaxExpenseBenefitShareBasedCompensation',
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'Gain (Loss) on Extinguishment of Debt',
    'Gain (Loss) on Disposition of Assets',
    'Proceeds from Sale of Property, Plant, and Equipment',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale'
])

# Arrumando a escala das colunas '2017-06-25', '2018-06-24', '2019-06-30' e '2020-06-28' em linhas específicas
df_cash_flow_10k['2020-06-28'] /= 1000
df_cash_flow_10k['2019-06-30'] /= 1000
df_cash_flow_10k['2018-06-24'] /= 1000
df_cash_flow_10k['2017-06-25'] /= 1000

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'lrcx_TransferOfInventoryToPropertyAndEquipment': 'Transfer Of Inventory To Property And Equipment',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation, Depletion and Amortization, Nonproduction': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping LAM Research 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_lrcx = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_lrcx.index = pd.to_datetime(df_lst_acc_num_10q_lrcx.index, format='%Y-%m-%d')

df_lst_acc_num_10q_lrcx

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de '2019-09-29' p/ iteração
df_lst_acc_num_10q_lrcx_sliced = df_lst_acc_num_10q_lrcx.loc['2019-09-29':]
df_lst_acc_num_10q_lrcx_sliced

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_lrcx_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Intangible Assets, Net (Including Goodwill)' nas colunas abaixo estão zeradas
# As informações estão na linha 'Intangible Assets, Net (Excluding Goodwill)' e 'Finite-Lived Intangible Assets, Net'
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2024-03-31'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2024-03-31'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2023-12-24'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2023-12-24'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2023-09-24'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2023-09-24'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2023-03-26'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2023-03-26'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2022-12-25'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2022-12-25'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2022-09-25'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2022-09-25'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2022-03-27'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2022-03-27'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2021-12-26'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2021-12-26'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2021-09-26'] = df_balance_sheet_10q.loc['Intangible Assets, Net (Excluding Goodwill)', '2021-09-26'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2021-03-28'] = df_balance_sheet_10q.loc['Finite-Lived Intangible Assets, Net', '2021-03-28'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2020-12-27'] = df_balance_sheet_10q.loc['Finite-Lived Intangible Assets, Net', '2020-12-27'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2020-09-27'] = df_balance_sheet_10q.loc['Finite-Lived Intangible Assets, Net', '2020-09-27'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2020-03-29'] = df_balance_sheet_10q.loc['Finite-Lived Intangible Assets, Net', '2020-03-29'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2019-12-29'] = df_balance_sheet_10q.loc['Finite-Lived Intangible Assets, Net', '2019-12-29'] 
df_balance_sheet_10q.loc['Intangible Assets, Net (Including Goodwill)', '2019-09-29'] = df_balance_sheet_10q.loc['Finite-Lived Intangible Assets, Net', '2019-09-29'] 

# A linha 'Treasury Stock, Common, Value' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Value' 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2022-03-27'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2022-03-27'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-12-26'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-12-26'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-09-26'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-09-26'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-03-28'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-03-28'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2020-12-27'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2020-12-27'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2020-09-27'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2020-09-27'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2020-03-29'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2020-03-29'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2019-12-29'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2019-12-29'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2019-09-29'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2019-09-29'] 

# A linha 'Additional Paid in Capital' nas colunas abaixo estão zeradas
# As informações estão na linha 'Additional Paid in Capital, Common Stock' 
df_balance_sheet_10q.loc['Additional Paid in Capital', '2021-03-28'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2021-03-28'] 
df_balance_sheet_10q.loc['Additional Paid in Capital', '2020-12-27'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2020-12-27'] 
df_balance_sheet_10q.loc['Additional Paid in Capital', '2020-09-27'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2020-09-27'] 
df_balance_sheet_10q.loc['Additional Paid in Capital', '2020-03-29'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2020-03-29'] 
df_balance_sheet_10q.loc['Additional Paid in Capital', '2019-12-29'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2019-12-29'] 
df_balance_sheet_10q.loc['Additional Paid in Capital', '2019-09-29'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2019-09-29'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization' e 'Property, Plant and Equipment, Net'
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-03-29'] = df_balance_sheet_10q.loc['lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization', '2020-03-29'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-12-29'] = df_balance_sheet_10q.loc['lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization', '2019-12-29'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-09-29'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2019-09-29'] 

# A linha 'Contract with Customer, Liability, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'lrcx_ContractWithCustomerLiabilitiesNetCurrent' 
df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2023-09-24'] = df_balance_sheet_10q.loc['lrcx_ContractWithCustomerLiabilitiesNetCurrent', '2023-09-24'] 
df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2023-03-26'] = df_balance_sheet_10q.loc['lrcx_ContractWithCustomerLiabilitiesNetCurrent', '2023-03-26'] 
df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2022-12-25'] = df_balance_sheet_10q.loc['lrcx_ContractWithCustomerLiabilitiesNetCurrent', '2022-12-25']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Intangible Assets, Net (Excluding Goodwill)',
    'Finite-Lived Intangible Assets, Net',
    'Treasury Stock, Value',
    'Additional Paid in Capital, Common Stock',
    'lrcx_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization',
    'Property, Plant and Equipment, Net',
    'lrcx_ContractWithCustomerLiabilitiesNetCurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsAbstract',
    'Preferred Stock, Value, Issued',
    'Temporary Equity, Carrying Amount, Attributable to Parent'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization': 'Property, Plant, and Equipment',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_lrcx_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Other Nonoperating Income (Expense)' nas colunas abaixo estão zeradas
# As informações estão na linha 'Other Nonoperating Expense'  
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2019-12-29'] = df_income_statement_10q.loc['Other Nonoperating Expense', '2019-12-29'] 
df_income_statement_10q.loc['Other Nonoperating Income (Expense)', '2019-09-29'] = df_income_statement_10q.loc['Other Nonoperating Expense', '2019-09-29'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Other Nonoperating Expense',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'lrcx_RestructuringChargesOperatingExpenseNet',
    'lrcx_CostOfGoodsAndServicesSoldExcludingRestructuringCharges',
    'lrcx_RestructuringChargesCostOfGoodsNet'
])

# Arrumando a escala das colunas '2023-09-24', '2023-12-24', '2024-03-31', '2024-09-29', '2024-12-29' e '2025-03-30' em linhas específicas
list_items = [
    'Revenue from Contract with Customer, Excluding Assessed Tax',
    'Cost of Goods and Services Sold',
    'Gross Profit',
    'Research and Development Expense',
    'Selling, General and Administrative Expense',
    'Operating Expenses',
    'Operating Income (Loss)',
    'Other Nonoperating Income (Expense)',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest',
    'Income Tax Expense (Benefit)',
    'Net Income (Loss) Attributable to Parent'
]

df_income_statement_10q.loc[list_items, '2025-03-30'] /= 1000
df_income_statement_10q.loc[list_items, '2024-12-29'] /= 1000
df_income_statement_10q.loc[list_items, '2024-09-29'] /= 1000
df_income_statement_10q.loc[list_items, '2023-12-24'] /= 1000
df_income_statement_10q.loc[list_items, '2023-09-24'] /= 1000

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Cost of Goods and Services Sold', '2026-03-29'] = 2930961 
df_income_statement_10q.loc['Cost of Goods and Services Sold', '2025-12-28'] = 2693629
df_income_statement_10q.loc['Cost of Goods and Services Sold', '2025-09-28'] = 2639294

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_lrcx_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Repayments of Debt and Lease Obligation' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security'
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2023-09-24'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2023-09-24'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2023-03-26'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2023-03-26'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2022-12-25'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2022-12-25'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2022-09-25'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2022-09-25'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2021-09-26'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2021-09-26'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2021-03-28'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2021-03-28'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2020-12-27'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2020-12-27'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2020-09-27'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2020-09-27'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2020-03-29'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2020-03-29'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2019-12-29'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2019-12-29'] 
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2019-09-29'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2019-09-29'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash and Cash Equivalents, at Carrying Value',
    'Restricted Cash and Cash Equivalents',
    'lrcx_TransferOfInventoryToPropertyAndEquipment',
    'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale',
    'Proceeds from Sale of Debt Securities, Available-for-sale',
    'lrcx_TransferOfInventoryToPropertyAndEquipmentNet',
    'Amortization of Debt Issuance Costs and Discounts',
    'Dividends Payable',
    'Proceeds from (Repayments of) Commercial Paper',
    'Proceeds from Debt, Net of Issuance Costs',
    'Payments to Acquire Debt Securities, Available-for-sale'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2026-03-29'] = 321891 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2025-12-28'] = 205569 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2025-03-30'] = 287838 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2024-12-29'] = 190495 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2024-03-31'] = 271342 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2023-12-24'] = 181420 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2022-03-27'] = 245807 
df_cash_flow_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2021-12-26'] = 161579 

df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2026-03-29'] = -113310
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2025-12-28'] = -93832
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2025-03-30'] = -211568
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2024-12-29'] = -191576
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2024-03-31'] = -137606
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2023-12-24'] = -112985
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2022-03-27'] = -83451
df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2021-12-26'] = -26573

# 'Changes in operating assets and liabilities'
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2026-03-29'] = -1053956
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2025-12-28'] = -179311
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2025-03-30'] = -337013
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2024-12-29'] = -148889
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2024-03-31'] = 620405
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2023-12-24'] = 353760 
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2022-03-27'] = -1014119
df_cash_flow_10q.loc['Increase (Decrease) in Operating Capital', '2021-12-26'] = -657279

df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2026-03-29'] = 4400429 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2025-12-28'] = 3259009 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2025-03-30'] = 3619076
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2024-12-29'] = 2310413 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2024-03-31'] = 3789839 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2023-12-24'] = 2405003 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2022-03-27'] = 2655740 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Operating Activities', '2021-12-26'] = 1898030 

# 'Capital expenditures and intangible assets'
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2026-03-29'] = -777604
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2025-12-28'] = -446000
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2025-03-30'] = -586995
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2024-12-29'] = -298937
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2024-03-31'] = -295922
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2023-12-24'] = -192268
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2022-03-27'] = -420288
df_cash_flow_10q.loc['Payments to Acquire Productive Assets', '2021-12-26'] = -274920

df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2026-03-29'] = -778411
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2025-12-28'] = -443831
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2025-03-30'] = -578841
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2024-12-29'] = -285926
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2024-03-31'] = -269001
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2023-12-24'] = -176641
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2022-03-27'] = 688212 
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Investing Activities', '2021-12-26'] = 782776 

# 'Principal payments on debt, including finance lease obligations and payments for debt issuance costs'
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2026-03-29'] = -754073
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2025-12-28'] = -2879
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2025-03-30'] = -506003
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2024-12-29'] = -1966
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2024-03-31'] = -255155
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2023-12-24'] = -254095
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2022-03-27'] = -9857
df_cash_flow_10q.loc['Repayments of Debt and Lease Obligation', '2021-12-26'] = -8036

df_cash_flow_10q.loc['Payments of Dividends', '2026-03-29'] = -945317
df_cash_flow_10q.loc['Payments of Dividends', '2026-03-29'] = -619488
df_cash_flow_10q.loc['Payments of Dividends', '2025-03-30'] = -854335
df_cash_flow_10q.loc['Payments of Dividends', '2024-12-29'] = -558619
df_cash_flow_10q.loc['Payments of Dividends', '2024-03-31'] = -757453
df_cash_flow_10q.loc['Payments of Dividends', '2023-12-24'] = -494746
df_cash_flow_10q.loc['Payments of Dividends', '2022-03-27'] = -607234
df_cash_flow_10q.loc['Payments of Dividends', '2021-12-26'] = -396647

df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2026-03-29'] = -5237478
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2025-12-28'] = -3006840
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2025-03-30'] = -3427106
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2024-12-29'] = -2194551
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2024-03-31'] = -3421699
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2023-12-24'] = -2185906
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2022-03-27'] = -3555403
df_cash_flow_10q.loc['Net Cash Provided by (Used in) Financing Activities', '2021-12-26'] = -2005695

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation, Depletion and Amortization, Nonproduction': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
lrcx_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

lrcx_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

lrcx_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
lrcx_bs.columns = pd.to_datetime(lrcx_bs.columns)
lrcx_is.columns = pd.to_datetime(lrcx_is.columns)
lrcx_cf.columns = pd.to_datetime(lrcx_cf.columns)

# Transformando as colunas em apenas o ano
lrcx_bs.columns = lrcx_bs.columns.year
lrcx_is.columns = lrcx_is.columns.year
lrcx_cf.columns = lrcx_cf.columns.year

In [ ]:
# Preços da LRCX
lrcx_close = yf.download('LRCX', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024', 
    '2025', '2026'
]

last_dec_close = []

for year in lst_years:
    last_close = lrcx_close[f'{year}-06'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
lrcx_close_jun = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
lrcx_close_jun = lrcx_close_jun.reindex(index=lrcx_close_jun.index[::-1])

# Arredondamento de duas casas decimais
lrcx_close_jun = round(lrcx_close_jun, 2)

# Teve um split de 10:1 em 02/10/2024 (https://br.investing.com/equities/lam-research-corp-historical-data-splits)
lrcx_close_jun.loc['2023'] = lrcx_close_jun.loc['2023'] * 10
lrcx_close_jun.loc['2022'] = lrcx_close_jun.loc['2022'] * 10
lrcx_close_jun.loc['2021'] = lrcx_close_jun.loc['2021'] * 10
lrcx_close_jun.loc['2020'] = lrcx_close_jun.loc['2020'] * 10
lrcx_close_jun.loc['2019'] = lrcx_close_jun.loc['2019'] * 10
lrcx_close_jun.loc['2018'] = lrcx_close_jun.loc['2018'] * 10
lrcx_close_jun.loc['2017'] = lrcx_close_jun.loc['2017'] * 10

# Transformando o index em int
lrcx_close_jun .index = lrcx_close_jun .index.astype(int)

lrcx_close_jun

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = lrcx_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=lrcx_close_jun, df_is=lrcx_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=lrcx_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=lrcx_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=lrcx_close_jun, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=lrcx_close_jun, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=lrcx_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=lrcx_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=lrcx_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=lrcx_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=lrcx_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=lrcx_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=lrcx_bs, df_is=lrcx_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=lrcx_close_jun, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=lrcx_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current',
    'Long-term Debt and Lease Obligation'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=lrcx_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=lrcx_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=lrcx_is, df_bs=lrcx_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=lrcx_is, df_bs=lrcx_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=lrcx_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=lrcx_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=lrcx_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Productive Assets',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=lrcx_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=lrcx_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=lrcx_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=lrcx_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Accounts Payable, Trade',
    'Increase (Decrease) in Deferred Revenue'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=lrcx_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=lrcx_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Long-term Debt',
    'Proceeds from Lines of Credit'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=lrcx_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Debt and Lease Obligation',
    'Repayments of Lines of Credit',
    'Proceeds from (Repayments of) Commercial Paper'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=lrcx_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=lrcx_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=lrcx_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=lrcx_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=lrcx_cf, df_is=lrcx_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=lrcx_cf, df_is=lrcx_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=lrcx_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=lrcx_bs, df_is=lrcx_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=lrcx_bs, df_is=lrcx_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=lrcx_bs, df_is=lrcx_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=lrcx_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=lrcx_bs, df_is=lrcx_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=lrcx_is, df_bs=lrcx_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=lrcx_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
lrcx_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
lrcx_indicadores_10k.columns = nomes_col
lrcx_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
lrcx_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

lrcx_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

lrcx_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
lrcx_bs_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in lrcx_bs_10q.columns]
lrcx_is_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in lrcx_is_10q.columns]
lrcx_cf_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in lrcx_cf_10q.columns]

In [ ]:
# Preços da LRCX
lrcx_close = yf.download('LRCX', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Dezembro
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025',
]
lst_months = ['03', '09', '12']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = lrcx_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
lrcx_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
lrcx_close_months = lrcx_close_months.reindex(index=lrcx_close_months.index[::-1])

# Retirando o preço de '03-2020' 
lrcx_close_months = lrcx_close_months.drop(index='03-2020')


# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Dezembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    # '09',
    # '12'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = lrcx_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
lrcx_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
lrcx_close_months_atual = lrcx_close_months_atual.reindex(index=lrcx_close_months_atual.index[::-1])

# Juntando as duas series pandas
lrcx_close_months = pd.concat([lrcx_close_months_atual, lrcx_close_months])

# Arredondamento de duas casas decimais
lrcx_close_months = round(lrcx_close_months, 2)

# Teve um split de 10:1 em 02/10/2024 (https://br.investing.com/equities/lam-research-corp-historical-data-splits)
lrcx_close_months.loc['09-2024'] = lrcx_close_months.loc['09-2024'] * 10
lrcx_close_months.loc['03-2024'] = lrcx_close_months.loc['03-2024'] * 10
lrcx_close_months.loc['12-2023'] = lrcx_close_months.loc['12-2023'] * 10
lrcx_close_months.loc['09-2023'] = lrcx_close_months.loc['09-2023'] * 10
lrcx_close_months.loc['03-2023'] = lrcx_close_months.loc['03-2023'] * 10
lrcx_close_months.loc['12-2022'] = lrcx_close_months.loc['12-2022'] * 10
lrcx_close_months.loc['09-2022'] = lrcx_close_months.loc['09-2022'] * 10
lrcx_close_months.loc['03-2022'] = lrcx_close_months.loc['03-2022'] * 10
lrcx_close_months.loc['12-2021'] = lrcx_close_months.loc['12-2021'] * 10
lrcx_close_months.loc['09-2021'] = lrcx_close_months.loc['09-2021'] * 10
lrcx_close_months.loc['03-2021'] = lrcx_close_months.loc['03-2021'] * 10
lrcx_close_months.loc['12-2020'] = lrcx_close_months.loc['12-2020'] * 10
lrcx_close_months.loc['09-2020'] = lrcx_close_months.loc['09-2020'] * 10

# Substituindo o index para ficar igual ao dos dados fundamentalistas
lrcx_close_months.index = lrcx_bs_10q.columns[:-3]

lrcx_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = lrcx_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=lrcx_close_months, df_is=lrcx_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=lrcx_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=lrcx_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=lrcx_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=lrcx_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=lrcx_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=lrcx_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=lrcx_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=lrcx_bs_10q, df_is=lrcx_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=lrcx_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=lrcx_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current',
    'Long-term Debt and Lease Obligation'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=lrcx_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=lrcx_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=lrcx_is_10q, df_bs=lrcx_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=lrcx_is_10q, df_bs=lrcx_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Productive Assets',
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[2]

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=lrcx_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Operating Capital',
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=lrcx_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='09')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=lrcx_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='09')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=lrcx_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='09')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=lrcx_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Debt, Maturing in More than Three Months',
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Debt and Lease Obligation',
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=lrcx_cf_10q, first_quarter='09', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=lrcx_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=lrcx_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=lrcx_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=lrcx_cf_10q, first_quarter='09')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=lrcx_cf_10q, df_is=lrcx_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=lrcx_cf_10q, df_is=lrcx_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=lrcx_cf_10q,  first_quarter='09')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=lrcx_bs_10q, df_is=lrcx_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=lrcx_bs_10q, df_is=lrcx_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=lrcx_bs_10q, df_is=lrcx_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=lrcx_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=lrcx_bs_10q, df_is=lrcx_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=lrcx_is_10q, df_bs=lrcx_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=lrcx_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_sliced,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
lrcx_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
lrcx_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
lrcx_indicadores_10q = lrcx_indicadores_10q.fillna(0)

lrcx_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//equipamentos_semicondutores//lam_research//lrcx_indicators.xlsx') as writer:
    lrcx_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    lrcx_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

# **Setor de Energia Elétrica**

## Constellation Energy

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'ceg'
f_sec.cik_matching_ticker(ticker)

### Scraping Constellation 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_constellation = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_constellation.index = pd.to_datetime(df_lst_acc_num_constellation.index, format='%Y-%m-%d')

# Selecionando os 'acc_num' dos 10-k a partir de 2022 p/ iteração
df_lst_acc_num_constellation = df_lst_acc_num_constellation.loc['2022-12-31':]

df_lst_acc_num_constellation

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_constellation['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Liability, Defined Benefit Plan, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Liability, Defined Benefit Pension Plan, Noncurrent'
df_balance_sheet_10k.loc['Liability, Defined Benefit Plan, Noncurrent', '2023-12-31'] = df_balance_sheet_10k.loc['Liability, Defined Benefit Pension Plan, Noncurrent', '2023-12-31'] 
df_balance_sheet_10k.loc['Liability, Defined Benefit Plan, Noncurrent', '2022-12-31'] = df_balance_sheet_10k.loc['Liability, Defined Benefit Pension Plan, Noncurrent', '2022-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop('Liability, Defined Benefit Pension Plan, Noncurrent')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Accounts Receivable, Related Parties, Current',
    'Assets for Plan Benefits, Defined Benefit Plan',
    'Accounts Payable, Related Parties, Current',
    'Due to Affiliate, Noncurrent',
    'Accounts Payable, Related Parties, Noncurrent'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc['Goodwill', '2022-12-31'] = 47
df_balance_sheet_10k.loc['Accounts Payable and Accrued Liabilities, Current', '2022-12-31'] = 3734 

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'ceg_RenewableEnergyCreditsCurrent': 'Renewable Energy Credits Current',
    'ceg_AssetRetirementObligationsExcludingSpentNuclearFuelNoncurrent': 'Asset Retirement Obligations Excluding Spent Nuclear Fuel Non current',
    'ceg_PayableToRegulatoryAgreementUnitsNoncurrent': 'Payable To Regulatory Agreement Units Non current',
    'us-gaap_MembersEquity': 'Members Equity',
    'us-gaap_MembersEquityAttributableToNoncontrollingInterest': 'Members Equity Attributable To Non controlling Interest',
    'us-gaap_AccountsReceivableGrossCurrent': 'Accounts Receivable Gross Current',
    'us-gaap_OtherReceivablesGrossCurrent': 'Other Receivables Gross Current',
    'us-gaap_AssetsOfDisposalGroupIncludingDiscontinuedOperationCurrent': 'Assets Of Disposal Group Including Discontinued Operation Current',
    'us-gaap_LiabilitiesOfDisposalGroupIncludingDiscontinuedOperationCurrent': 'Liabilities Of Disposal Group Including Discontinued Operation Current',
    'us-gaap_AssetRetirementObligationsNoncurrent': 'Asset Retirement Obligations Non current',  
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_constellation['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10k.loc['InterestExpenseNonoperating', '2023-12-31'] = df_income_statement_10k.loc['Interest Expense', '2023-12-31'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2022-12-31'] = df_income_statement_10k.loc['Interest Expense', '2022-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop('Interest Expense')

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['Revenues', '2025-12-31'] = 25533

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'ceg_RelatedPartyCostsOperatingAndMaintenance': 'Related Party Costs Operating And Maintenance',
    'ceg_RelatedPartyTransactionInterestExpense': 'Related Party Transaction Interest Expense',
    'us-gaap_RelatedPartyTransactionExpensesFromTransactionsWithRelatedParty': 'Related Party Transaction Expenses From Transactions With Related Party',
    'us-gaap_InterestExpenseRelatedParty': 'Interest Expense Related Party',
    'us-gaap_IncomeLossFromEquityMethodInvestmentsNetOfDividendsOrDistributions': 'Income Loss From Equity Method Investments Net Of Dividends Or Distributions',
})

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop('us-gaap_RevenuesAbstract')

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Including Assessed Tax'] - df_income_statement_10k.loc['Cost, Direct Material']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_constellation['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'ceg_IncreaseDecreaseInMoneyPoolWithAffiliate',
    'ceg_PaymentsToAcquireNoncontrollingInterests',
    'Impairment of Long-Lived Assets Held-for-use'
])

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'ceg_RealizedAndUnrealizedGainLossOnInvestments': 'Realized And Unrealized Gain Loss On Investments',
    'ceg_IncreaseDecreaseInOptionPremiumsCollectedReceived': 'Increase Decrease In Option Premiums Collected Received',
    'ceg_RetirementOfLongTermDebtDueToAffiliate': 'Retirement Of Long Term Debt Due To Affiliate',
    'ceg_ChangeinCapitalExpendituresIncurredButNotYetPaid': 'Change in Capital Expenditures Incurred But Not Yet Paid',
    'ceg_OilAndGasNoncashAssetRetirementObligationIncreaseDecrease': 'Oil And Gas Non cash Asset Retirement Obligation Increase Decrease',
    'us-gaap_PaymentsToAcquireBusinessesGross': 'Payments To Acquire Businesses Gross',
    'us-gaap_GainLossOnSalesOfAssetsAndAssetImpairmentCharges': 'Gain Loss On Sales Of Assets And Asset Impairment Charges',
    'us-gaap_GainLossOnInvestments': 'Gain Loss On Investments',
    'us-gaap_DebtAndEquitySecuritiesUnrealizedGainLoss': 'Debt And Equity Securities Unrealized Gain Loss',
    'ceg_ChangeinReceivablesFromPayablesToAffiliatesNet': 'Change in Receivables From Payables To Affiliates Net',
    'ceg_ChangesInOptionPremiumsCollectedReceived': 'Changes In Option Premiums Collected Received',
    'us-gaap_IncreaseDecreaseInDueToAffiliatesCurrent': 'Increase Decrease In Due To Affiliates Current',
    'us-gaap_PaymentsToAcquireAdditionalInterestInSubsidiaries': 'Payments To Acquire Additional Interest In Subsidiaries',
})

df_cash_flow_10k

In [ ]:
# O 'df_income_statement_10k' não conseguiu puxar os dados da linha 'Weighted Average Number of Shares Outstanding, Basic' e não tem a linha 'Research and Development Expense'

# Linha 'Weighted Average Number of Shares Outstanding, Basic' a ser adicionada 
new_row_shares_basic_is_10k = [
    #2025
    313, 
    #2024
    315, 
    #2023
    323, 
    #2022
    328,
]

# Linha 'Weighted Average Number of Shares Outstanding, Diluted' a ser adicionada 
new_row_shares_diluted_is_10k = [
    #2025
    314, 
    #2024
    315, 
    #2023
    324, 
    #2022
    329,
]

# Linha 'Research and Development Expense' a ser adicionada 
new_row_rd_is_10k = [
    #2025
    0, 
    #2024
    0, 
    #2023
    0, 
    #2022
    0,
]

# Adicionando a nova linha
df_income_statement_10k.loc['Number of Shares - Basic'] = new_row_shares_basic_is_10k
df_income_statement_10k.loc['Number of Shares - Diluted'] = new_row_shares_diluted_is_10k
df_income_statement_10k.loc['Research and Development'] = new_row_rd_is_10k

In [ ]:
# O 'df_balance_sheet_10k' não conseguiu puxar os dados da linha 'Total Shareholders Equity'

# Linha 'Total Shareholders Equity' a ser adicionada 
new_row_bs_10k = [
    #2025
    14517, 
    #2024
    13166, 
    #2023
    10925, 
    #2022
    11018,
]

# Adicionando a nova linha
df_balance_sheet_10k.loc['Total Shareholders Equity'] = new_row_bs_10k

In [ ]:
# O 'df_cash_flow_10k' não conseguiu puxar os dados das linhas 'Acquisitions of Assets and Businesses', 'Payments of Dividends' e 'Payments for Repurchase of Common Stock'

# Linhas 'Acquisitions of Assets and Businesses' a ser adicionada 
new_acquisitions_div_cf_10k = [
    #2025
    14, 
    #2024
    32, 
    #2023
    1690, 
    #2022
    29,
]

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10k = [
    #2025
    486, 
    #2024
    444, 
    #2023
    366, 
    #2022
    185,
]

# Linhas 'Payments for Repurchase of Common Stock' a ser adicionada 
new_row_repurchase_cf_10k = [
    #2025
    400, 
    #2024
    999, 
    #2023
    992, 
    #2022
    0,
]

# Adicionando as novas linhas
df_cash_flow_10k.loc['Acquisitions of Assets and Businesses'] = new_acquisitions_div_cf_10k
df_cash_flow_10k.loc['Payments of Dividends'] = new_row_div_cf_10k
df_cash_flow_10k.loc['Payments for Repurchase of Common Stock'] = new_row_repurchase_cf_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Cost, Direct Material': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'InterestExpenseNonoperating': 'Interest Expense',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Constellation 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_ceg = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_ceg.index = pd.to_datetime(df_lst_acc_num_10q_ceg.index, format='%Y-%m-%d')
df_lst_acc_num_10q_ceg

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_ceg['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Liability, Defined Benefit Plan, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Liability, Other Postretirement Defined Benefit Plan, Noncurrent'
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2024-09-30'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2024-09-30'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2024-06-30'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2024-06-30'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2024-03-31'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2024-03-31'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2023-09-30'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2023-09-30'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2023-06-30'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2023-06-30'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2023-03-31'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2023-03-31'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2022-09-30'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2022-09-30'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2022-06-30'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2022-06-30'] 
df_balance_sheet_10q.loc['Liability, Defined Benefit Plan, Noncurrent', '2022-03-31'] = df_balance_sheet_10q.loc['Liability, Other Postretirement Defined Benefit Plan, Noncurrent', '2022-03-31'] 

# A linha 'Accounts Payable and Accrued Liabilities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Accrued Liabilities, Current'
df_balance_sheet_10q.loc['Accounts Payable and Accrued Liabilities, Current', '2023-06-30'] = df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2023-06-30'] 
df_balance_sheet_10q.loc['Accounts Payable and Accrued Liabilities, Current', '2023-03-31'] = df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2023-03-31'] 
df_balance_sheet_10q.loc['Accounts Payable and Accrued Liabilities, Current', '2022-09-30'] = df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2022-09-30'] 
df_balance_sheet_10q.loc['Accounts Payable and Accrued Liabilities, Current', '2022-06-30'] = df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2022-06-30'] 
df_balance_sheet_10q.loc['Accounts Payable and Accrued Liabilities, Current', '2022-03-31'] = df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2022-03-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Liability, Other Postretirement Defined Benefit Plan, Noncurrent',
    'Accrued Liabilities, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Assets for Plan Benefits, Defined Benefit Plan',
    'Due to Affiliate, Noncurrent',
    'Accounts Payable, Related Parties, Noncurrent',
    'Accounts Receivable, Related Parties, Current',
    'Accounts Payable, Related Parties, Current'
])

# Renomeando algumas linhas do índice
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'ceg_RenewableEnergyCreditsCurrent': 'Renewable Energy Credits Current',
    'ceg_AssetRetirementObligationsExcludingSpentNuclearFuelNoncurrent': 'Asset Retirement Obligations Excluding Spent Nuclear Fuel Noncurrent',
    'ceg_PayableToRegulatoryAgreementUnitsNoncurrent': 'Payable To Regulatory Agreement Units Noncurrent',
    'us-gaap_MembersEquity': 'Members Equity',
    'us-gaap_MembersEquityAttributableToNoncontrollingInterest': 'Members Equity Attributable To Noncontrolling Interest',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_ceg['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-03-31'] = df_income_statement_10q.loc['Interest Expense', '2024-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-09-30'] = df_income_statement_10q.loc['Interest Expense', '2023-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-06-30'] = df_income_statement_10q.loc['Interest Expense', '2023-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-03-31'] = df_income_statement_10q.loc['Interest Expense', '2023-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-09-30'] = df_income_statement_10q.loc['Interest Expense', '2022-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-06-30'] = df_income_statement_10q.loc['Interest Expense', '2022-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-03-31'] = df_income_statement_10q.loc['Interest Expense', '2022-03-31'] 

# A linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest' na coluna abaixo está zerada
# As informações estão na linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest'
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2025-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2025-03-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Interest Expense',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_OperatingExpensesAbstract',
    'us-gaap_RevenuesAbstract',
    'Related Party Transaction, Amounts of Transaction',
    'ceg_RelatedPartyCostsOperatingAndMaintenance',
    'ceg_RelatedPartyTransactionInterestExpense',
    'Revenue from Related Parties',
    'Related Party Transaction, Purchases from Related Party'
])

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Cost, Direct Material']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_ceg['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Equity Securities, FV-NI, Gain (Loss)' nas colunas abaixo estão zeradas
# As informações estão na linha 'Equity Securities, FV-NI, Unrealized Gain (Loss)'
df_cash_flow_10q.loc['Equity Securities, FV-NI, Gain (Loss)', '2022-09-30'] = df_cash_flow_10q.loc['Equity Securities, FV-NI, Unrealized Gain (Loss)', '2022-09-30'] 
df_cash_flow_10q.loc['Equity Securities, FV-NI, Gain (Loss)', '2022-06-30'] = df_cash_flow_10q.loc['Equity Securities, FV-NI, Unrealized Gain (Loss)', '2022-06-30'] 
df_cash_flow_10q.loc['Equity Securities, FV-NI, Gain (Loss)', '2022-03-31'] = df_cash_flow_10q.loc['Equity Securities, FV-NI, Unrealized Gain (Loss)', '2022-03-31'] 

# A linha 'Repayments of Short-term Debt, Maturing in More than Three Months' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from (Repayments of) Short-term Debt, Maturing in More than Three Months'
df_cash_flow_10q.loc['Repayments of Short-term Debt, Maturing in More than Three Months', '2022-06-30'] = df_cash_flow_10q.loc['Proceeds from (Repayments of) Short-term Debt, Maturing in More than Three Months', '2022-06-30'] 
df_cash_flow_10q.loc['Repayments of Short-term Debt, Maturing in More than Three Months', '2022-03-31'] = df_cash_flow_10q.loc['Proceeds from (Repayments of) Short-term Debt, Maturing in More than Three Months', '2022-03-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Equity Securities, FV-NI, Unrealized Gain (Loss)',
    'Proceeds from (Repayments of) Short-term Debt, Maturing in More than Three Months'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Impairment of Long-Lived Assets Held-for-use',
    'Increase (Decrease) in Due to Affiliates',
    'ceg_PaymentsToAcquireNoncontrollingInterests'
])

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'ceg_RealizedAndUnrealizedGainLossOnInvestments': 'Realized And Unrealized Gain Loss On Investments',
    'ceg_IncreaseDecreaseInOptionPremiumsCollectedReceived': 'Increase Decrease In Option Premiums Collected Received',
    'ceg_ChangeinCapitalExpendituresIncurredButNotYetPaid': 'Change in Capital Expenditures Incurred But Not Yet Paid',
    'ceg_PropertyPlantAndEquipmentPeriodIncreaseDecreaseRelatedToAssetRetirementObligationAdjustment': 'Property Plant And Equipment Period Increase Decrease Related To Asset Retirement Obligation Adjustment',
    'ceg_RetirementOfLongTermDebtDueToAffiliate': 'Retirement Of Long Term Debt Due To Affiliate',
})

df_cash_flow_10q

In [ ]:
# O 'df_income_statement_10q' não conseguiu puxar os dados da linha 'Weighted Average Number of Shares Outstanding, Basic' e não tem a linha 'Research and Development Expense'

# Linha 'Weighted Average Number of Shares Outstanding, Basic' a ser adicionada 
new_row_shares_basic_is_10q = [
    # 2026-06-30
    360,
    # 2026-03-31
    354,
    # 2025-09-30
    313,
    # 2025-06-30
    314,
    # 2025-03-31
    313,	
    # 2024-09-30	
    313,	
    # 2024-06-30	
    315,	
    # 2024-03-31	
    317,	
    # 2023-09-30	
    322,	
    # 2023-06-30	
    324,	
    # 2023-03-31	
    328,	
    # 2022-09-30	
    327,	
    # 2022-06-30	
    327,	
    # 2022-03-31
    327,	
]

new_row_shares_diluted_is_10q = [
    # 2026-06-30
    360,
    # 2026-03-31
    354,
    # 2025-09-30
    313,
    # 2025-06-30
    314,
    # 2025-03-31
    314,	
    # 2024-09-30	
    314,	
    # 2024-06-30	
    316,	
    # 2024-03-31	
    318,	
    # 2023-09-30	
    323,	
    # 2023-06-30	
    325,	
    # 2023-03-31	
    328,	
    # 2022-09-30	
    328,	
    # 2022-06-30	
    328,	
    # 2022-03-31
    327,	
]

# Linha 'Research and Development Expense' a ser adicionada 
new_row_rd_is_10q = [
    # 2026-06-30
    0,
    # 2026-03-31
    0,
    # 2025-09-30
    0,    
    # 2025-06-30
    0,
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
    # 2024-03-31	
    0,	
    # 2023-09-30	
    0,	
    # 2023-06-30	
    0,	
    # 2023-03-31	
    0,	
    # 2022-09-30	
    0,	
    # 2022-06-30	
    0,	
    # 2022-03-31
    0,	
]

# Adicionando a nova linha
df_income_statement_10q.loc['Number of Shares - Basic'] = new_row_shares_basic_is_10q
df_income_statement_10q.loc['Number of Shares - Diluted'] = new_row_shares_diluted_is_10q
df_income_statement_10q.loc['Research and Development'] = new_row_rd_is_10q

In [ ]:
# O 'df_balance_sheet_10q' não conseguiu puxar os dados da linha "Stockholders' Equity Attributable to Parent"

# Linha "Stockholders' Equity Attributable to Parent" a ser adicionada 
new_row_bs_10q = [
    # 2026-06-30
    31977,
    # 2026-03-31
    33483,
    # 2025-09-30
    14350,
    # 2025-06-30
    13446,
    # 2025-03-31
    12956,	
    # 2024-09-30	
    12570,	
    # 2024-06-30	
    11425,	
    # 2024-03-31	
    11199,	
    # 2023-09-30	
    11666,	
    # 2023-06-30	
    11256,	
    # 2023-03-31	
    10728,	
    # 2022-09-30	
    10803,	
    # 2022-06-30	
    11000,	
    # 2022-03-31
    11105,	
]

# Adicionando a nova linha
df_balance_sheet_10q.loc['Total Shareholders Equity'] = new_row_bs_10q

In [ ]:
# O 'df_cash_flow_10q' não conseguiu puxar os dados das linhas 'Payments of Dividends' e 'Payments for Repurchase of Common Stock'

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10q = [
    # 2026-06-30
    309,
    # 2026-03-31
    155,
    # 2025-09-30
    366,
    # 2025-06-30
    244,
    # 2025-03-31
    122,	
    # 2024-09-30	
    333,	
    # 2024-06-30	
    222,	
    # 2024-03-31	
    112,	
    # 2023-09-30	
    277,	
    # 2023-06-30	
    185,	
    # 2023-03-31	
    93,	
    # 2022-09-30	
    139,	
    # 2022-06-30	
    93,	
    # 2022-03-31
    46,	
]

# Linhas 'Payments for Repurchase of Common Stock' a ser adicionada 
new_row_repurchase_cf_10q = [
    # 2026-06-30
    1971,
    # 2026-03-31
    0,
    # 2025-09-30
    400,
    # 2025-06-30
    400,
    # 2025-03-31
    0,	
    # 2024-09-30	
    999000,	
    # 2024-06-30	
    999000,	
    # 2024-03-31	
    499000,	
    # 2023-09-30	
    750000,	
    # 2023-06-30	
    499000,	
    # 2023-03-31	
    231000,	
    # 2022-09-30	
    0,	
    # 2022-06-30	
    0,	
    # 2022-03-31
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10q.loc['Payments of Dividends'] = new_row_div_cf_10q
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock'] = new_row_repurchase_cf_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Accrued Liabilities, Current': 'Accounts Payable',
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Cost, Direct Material': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'InterestExpenseNonoperating': 'Interest Expense',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
ceg_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

ceg_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

ceg_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
ceg_bs.columns = pd.to_datetime(ceg_bs.columns)
ceg_is.columns = pd.to_datetime(ceg_is.columns)
ceg_cf.columns = pd.to_datetime(ceg_cf.columns)

# Transformando as colunas em apenas o ano
ceg_bs.columns = ceg_bs.columns.year
ceg_is.columns = ceg_is.columns.year
ceg_cf.columns = ceg_cf.columns.year

In [ ]:
# Preços da CEG
ceg_close = yf.download('CEG', auto_adjust=True, multi_level_index=False, start='2022-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2022', '2023', '2024', '2025'
]

last_dec_close = []

for year in lst_years:
    last_close = ceg_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
ceg_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
ceg_close_dec = ceg_close_dec.reindex(index=ceg_close_dec.index[::-1])

# Arredondamento de duas casas decimais
ceg_close_dec = round(ceg_close_dec, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Transformando o index em int
ceg_close_dec.index = ceg_close_dec.index.astype(int)

ceg_close_dec

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = ceg_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=ceg_close_dec, df_is=ceg_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=ceg_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=ceg_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=ceg_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=ceg_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=ceg_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=ceg_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=ceg_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=ceg_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=ceg_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=ceg_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=ceg_bs, df_is=ceg_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=ceg_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Restricted Cash and Cash Equivalents, Current'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=ceg_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Short-term Debt', 
    'Long-term Debt and Lease Obligation, Current', 
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=ceg_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=ceg_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=ceg_is, df_bs=ceg_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=ceg_is, df_bs=ceg_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=ceg_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=ceg_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=ceg_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Payments to Acquire Property, Plant, and Equipment']

capex= f_eua.indicador_capex(ten_k=True, df_cf=ceg_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC - não possui SBC

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow - não preciso calcular o ajustado

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=ceg_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=ceg_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits', 
    'Increase (Decrease) in Receivables', 
    'Increase (Decrease) in Due to Related Parties',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase Decrease In Option Premiums Collected Received',
    'Increase (Decrease) Cash Collateral from Counterparties',
    'Increase (Decrease) in Income Taxes Payable',
    'Increase (Decrease) in Obligation, Pension and Other Postretirement Benefits',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=ceg_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=ceg_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Short-term Debt, Maturing in More than Three Months', 
    'Proceeds from Issuance of Long-term Debt'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=ceg_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Short-term Debt, Maturing in More than Three Months', 
    'Repayments of Long-term Debt'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=ceg_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=ceg_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=ceg_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=ceg_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=ceg_cf, df_is=ceg_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=ceg_cf, df_is=ceg_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=ceg_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=ceg_bs, df_is=ceg_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=ceg_bs, df_is=ceg_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=ceg_bs, df_is=ceg_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=ceg_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=ceg_bs, df_is=ceg_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=ceg_is, df_bs=ceg_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=ceg_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    # sbc - não possui SBC
    # adjusted_free_cash_flow - não preciso calcular o ajustado
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
ceg_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    # 'SBC' - não possui SBC
    # 'Adjusted Free Cash Flow' - não preciso calcular o ajustado
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
ceg_indicadores_10k.columns = nomes_col
ceg_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
ceg_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

ceg_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

ceg_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
ceg_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in ceg_bs_10q.columns]
ceg_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in ceg_is_10q.columns]
ceg_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in ceg_cf_10q.columns]

In [ ]:
# Preços da CEG
ceg_close = yf.download('CEG', auto_adjust=True, multi_level_index=False, start='2023-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = ['2023', '2024', '2025']
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = ceg_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
ceg_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
ceg_close_months = ceg_close_months.reindex(index=ceg_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = ceg_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
ceg_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
ceg_close_months_atual = ceg_close_months_atual.reindex(index=ceg_close_months_atual.index[::-1])

# Juntando as duas series pandas
ceg_close_months = pd.concat([ceg_close_months_atual, ceg_close_months])

# Arredondamento de duas casas decimais
ceg_close_months = round(ceg_close_months, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
ceg_close_months.index = ceg_bs_10q.columns[:-3]

ceg_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = ceg_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=ceg_close_months, df_is=ceg_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=ceg_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=ceg_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=ceg_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=ceg_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=ceg_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=ceg_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=ceg_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=ceg_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=ceg_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=ceg_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=ceg_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=ceg_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=ceg_bs_10q, df_is=ceg_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=ceg_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Restricted Cash and Cash Equivalents, Current'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=ceg_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current', 
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=ceg_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q =  f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=ceg_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=ceg_is_10q, df_bs=ceg_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=ceg_is_10q, df_bs=ceg_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = ['Payments to Acquire Property, Plant, and Equipment']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=ceg_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC - não possui SBC

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow - não preciso calcular o ajustado

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=ceg_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=ceg_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=ceg_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=ceg_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase Decrease In Option Premiums Collected Received',
    'Increase (Decrease) Cash Collateral from Counterparties',
    'Increase (Decrease) in Income Taxes Payable',
    'Increase (Decrease) in Obligation, Pension and Other Postretirement Benefits',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=ceg_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=ceg_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=ceg_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=ceg_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Short-term Debt, Maturing in More than Three Months', 
    'Proceeds from Issuance of Long-term Debt'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Short-term Debt, Maturing in More than Three Months', 
    'Repayments of Long-term Debt'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=ceg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=ceg_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=ceg_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=ceg_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=ceg_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=ceg_cf_10q, df_is=ceg_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=ceg_cf_10q, df_is=ceg_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=ceg_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=ceg_bs_10q, df_is=ceg_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=ceg_bs_10q, df_is=ceg_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=ceg_bs_10q, df_is=ceg_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=ceg_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=ceg_bs_10q, df_is=ceg_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=ceg_is_10q, df_bs=ceg_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=ceg_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    # sbc_10q_acum - não possui SBC
    # adjusted_free_cash_flow_10q - não preciso calcular o ajustado
    free_cash_flow_yield_10q,
    capex_10q_sliced,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
ceg_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    # 'SBC' - não possui SBC
    # 'Adjusted Free Cash Flow' - não preciso calcular o ajustado
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
ceg_indicadores_10q.columns = nomes_col
ceg_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//constellation//ceg_indicators.xlsx') as writer:
    ceg_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    ceg_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Vistra

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'vst'
f_sec.cik_matching_ticker(ticker)

### Scraping Vistra 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_vistra = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_vistra.index = pd.to_datetime(df_lst_acc_num_vistra.index, format='%Y-%m-%d')

# Selecionando os 'acc_num' dos 10-k a partir de 2020 p/ iteração
df_lst_acc_num_vistra = df_lst_acc_num_vistra.loc['2020-12-31':]

df_lst_acc_num_vistra

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_vistra['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Restricted Cash, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Restricted Cash and Investments, Current'
df_balance_sheet_10k.loc['Restricted Cash, Current', '2023-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Current', '2023-12-31'] 
df_balance_sheet_10k.loc['Restricted Cash, Current', '2022-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Current', '2022-12-31'] 
df_balance_sheet_10k.loc['Restricted Cash, Current', '2021-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Current', '2021-12-31'] 
df_balance_sheet_10k.loc['Restricted Cash, Current', '2020-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Current', '2020-12-31'] 

# A linha 'Restricted Cash, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Restricted Cash and Investments, Noncurrent'
df_balance_sheet_10k.loc['Restricted Cash, Noncurrent', '2023-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Noncurrent', '2023-12-31'] 
df_balance_sheet_10k.loc['Restricted Cash, Noncurrent', '2022-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Noncurrent', '2022-12-31'] 
df_balance_sheet_10k.loc['Restricted Cash, Noncurrent', '2021-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Noncurrent', '2021-12-31'] 
df_balance_sheet_10k.loc['Restricted Cash, Noncurrent', '2020-12-31'] = df_balance_sheet_10k.loc['Restricted Cash and Investments, Noncurrent', '2020-12-31'] 
                                                                              
# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Restricted Cash and Investments, Current',
    'Restricted Cash and Investments, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Equity Method Investments',
    'Preferred Stock, Shares Outstanding',
    'Preferred Stock, Liquidation Preference Per Share'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'vistra_MarginDepositsPostedUnderAffiliateFinancingAgreementAsset': 'Margin Deposits Posted Under Affiliate Financing Agreement Asset',
    'vistra_AccountsReceivableSecuritizationProgramAmountsBorrowed': 'Accounts Receivable Securitization Program Amounts Borrowed',
    'vistra_ForwardRepurchaseObligationToBePaidCurrent': 'Forward Repurchase Obligation To Be Paid Current',
    'vistra_MarginDepositLiabilities': 'Margin Deposit Liabilities',
    'vistra_ForwardRepurchaseObligationToBePaidNoncurrent': 'Forward Repurchase Obligation To Be Paid Noncurrent',
    'vistra_DerivativeAndHedgeLiabilitiesNoncurrent': 'Derivative And Hedge Liabilities Noncurrent',
    'vistra_TaxReceivableAgreementObligationNoncurrent': 'Tax Receivable Agreement Obligation Noncurrent',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_vistra['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10k.loc['InterestExpenseNonoperating', '2023-12-31'] = df_income_statement_10k.loc['Interest Expense', '2023-12-31'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2022-12-31'] = df_income_statement_10k.loc['Interest Expense', '2022-12-31'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2021-12-31'] = df_income_statement_10k.loc['Interest Expense', '2021-12-31'] 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2020-12-31'] = df_income_statement_10k.loc['Interest Expense', '2020-12-31'] 
                                                                              
# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop('Interest Expense')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'Income (Loss) from Equity Method Investments'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'vistra_CostOfFuelPurchasedPowerAndDelivery': 'Cost Of Fuel Purchased Power And Delivery',
    'vistra_ImpactsOfTaxReceivableAgreement': 'Impacts Of Tax Receivable Agreement',
})

# Arrumando a escala da linha 'Weighted Average Number of Shares Outstanding, Basic' e 'Weighted Average Number of Shares Outstanding, Diluted'
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic'] = round(df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic'] / 1000, 0)
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted'] = round(df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted'] / 1000, 0)

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenues'] - df_income_statement_10k.loc['Cost Of Fuel Purchased Power And Delivery']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_vistra['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'vistra_UnrealizedGainLossOnInterestRateSwapDerivatives' nas colunas abaixo estão zeradas
# As informações estão na linha 'vistra_UnrealizedGainLossOnInterestRateSwapsDerivatives'
df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapDerivatives', '2023-12-31'] = df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapsDerivatives', '2023-12-31'] 
df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapDerivatives', '2022-12-31'] = df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapsDerivatives', '2022-12-31'] 
df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapDerivatives', '2021-12-31'] = df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapsDerivatives', '2021-12-31'] 
df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapDerivatives', '2020-12-31'] = df_cash_flow_10k.loc['vistra_UnrealizedGainLossOnInterestRateSwapsDerivatives', '2020-12-31'] 

# A linha 'Proceeds from Issuance of Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Issuance of Long-term Debt'
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2023-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2023-12-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2022-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2022-12-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2021-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2021-12-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2020-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2020-12-31'] 

# A linha 'Repayments of Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security'
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2023-12-31'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2023-12-31'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2022-12-31'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2022-12-31'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2021-12-31'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2021-12-31'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2020-12-31'] = df_cash_flow_10k.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2020-12-31'] 

# A linha 'vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from (Repayments of) Accounts Receivable Securitization'
df_cash_flow_10k.loc['vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing', '2023-12-31'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Accounts Receivable Securitization', '2023-12-31'] 
df_cash_flow_10k.loc['vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing', '2022-12-31'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Accounts Receivable Securitization', '2022-12-31'] 
df_cash_flow_10k.loc['vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing', '2021-12-31'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Accounts Receivable Securitization', '2021-12-31'] 
df_cash_flow_10k.loc['vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing', '2020-12-31'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Accounts Receivable Securitization', '2020-12-31'] 

# A linha 'Increase (Decrease) in Accrued Taxes Payable' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Property and Other Taxes Payable'
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Taxes Payable', '2023-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Property and Other Taxes Payable', '2023-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Taxes Payable', '2022-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Property and Other Taxes Payable', '2022-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Taxes Payable', '2021-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Property and Other Taxes Payable', '2021-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accrued Taxes Payable', '2020-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Property and Other Taxes Payable', '2020-12-31'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2022-12-31'] = df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2022-12-31'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2021-12-31'] = df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2021-12-31'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2020-12-31'] = df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2020-12-31'] 

# A linha 'vistra_GainLossOnTaxReceivableAgreementRepurchaseAndTenderOffers' na coluna abaixo está zerada
# As informações estão na linha 'vistra_GainLossTaxReceivableAgreementSettlement'
df_cash_flow_10k.loc['vistra_GainLossOnTaxReceivableAgreementRepurchaseAndTenderOffers', '2023-12-31'] = df_cash_flow_10k.loc['vistra_GainLossTaxReceivableAgreementSettlement', '2023-12-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'vistra_UnrealizedGainLossOnInterestRateSwapsDerivatives',
    'Proceeds from Issuance of Long-term Debt',
    'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security',
    'Proceeds from (Repayments of) Accounts Receivable Securitization',
    'Increase (Decrease) in Property and Other Taxes Payable',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect',
    'vistra_GainLossTaxReceivableAgreementSettlement'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Gain (Loss) on Sale of Properties',
    'Payments to Acquire Business Two, Net of Cash Acquired',
    'Cash Acquired from Acquisition',
    'vistra_ProceedsFromDebtShortTermInNature',
    'vistra_RepaymentsOfDebtShortTermInNature',
    'Proceeds from Issuance of Preferred Stock and Preference Stock',
    'vistra_ProceedsFromForwardCapacityAgreement',
    'Equity Method Investment, Realized Gain (Loss) on Disposal',
    'Proceeds from Nuclear Fuel',
    'vistra_TaxReceivableAgreementRepurchasedRightDuringThePeriod',
    'Interest Paid, Excluding Capitalized Interest, Operating Activities',
    'Interest Costs Capitalized',
    'vistra_PaymentsOfOrdinaryDividendsNoncontrollingAndRedeemableNoncontrollingInterest',
    'Payments to Noncontrolling Interests',
    'vistra_PaymentsToTaxReceivableAgreementRightsHolders'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Proceeds from Lines of Credit', '2021-12-31'] = 1450
df_cash_flow_10k.loc['Proceeds from Lines of Credit', '2020-12-31'] = 1075
df_cash_flow_10k.loc['Repayments of Lines of Credit', '2021-12-31'] = -1450
df_cash_flow_10k.loc['Repayments of Lines of Credit', '2020-12-31'] = -1425

# Renomeando as linhas do índice que estão sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'vistra_UnrealizedGainLossOnCommodityRelatedDerivatives': 'Unrealized Gain Loss On Commodity Related Derivatives',
    'vistra_UnrealizedGainLossOnInterestRateSwapDerivatives': 'Unrealized Gain Loss On Interest Rate Swap Derivatives',
    'vistra_UnrealizedGainLossFromNuclearDecommissioningTrusts': 'Unrealized Gain Loss From Nuclear Decommissioning Trusts',
    'vistra_TaxReceivableAgreementAccretionExpense': 'Tax Receivable Agreement Accretion Expense',
    'vistra_GainLossOnTaxReceivableAgreementRepurchaseAndTenderOffers': 'Gain Loss On Tax Receivable Agreement Repurchase And Tender Offers',
    'vistra_IncreaseDecreaseInCommodityAndDerivativeAssetsAndLiabilities': 'Increase (Decrease) In Commodity And Derivative Assets And Liabilities',
    'vistra_IncreaseDecreaseInMarginDepositsNet': 'Increase (Decrease) In Margin Deposits Net',
    'vistra_PaymentsForSettlementOfAssetRetirementObligation': 'Payments For Settlement Of Asset Retirement Obligation',
    'vistra_ProceedsFromSaleOfInvestmentTaxCreditSoldUnderAgreements': 'Proceeds From Sale Of Investment Tax Credit Sold Under Agreements',
    'vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing': 'Proceeds From Repayments Of Accounts Receivable Financing',
    'vistra_ReturnOfCapitalTaxReceivableAgreementAndTenderOffer': 'Return Of Capital Tax Receivable Agreement And Tender Offer',
    'vistra_ProceedsFromForwardCapacityAgreement': 'Proceeds From Forward Capacity Agreement',
    'vistra_GainOnInvoluntaryConversion': 'Gain On Involuntary Conversion',	
})

df_cash_flow_10k

In [ ]:
# O 'df_income_statement_10k' não tem a linha 'Research and Development Expense'

# Linha 'Research and Development Expense' a ser adicionada 
new_row_rd_is_10k = [
    #2025
    0, 
    #2024
    0, 
    #2023
    0, 
    #2022
    0,
    #2021
    0,
    #2020
    0,
]

# Adicionando a nova linha
df_income_statement_10k.loc['Research and Development'] = new_row_rd_is_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity',
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Cost Of Fuel Purchased Power And Delivery': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'InterestExpenseNonoperating': 'Interest Expense',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Vistra 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_vst = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_vst.index = pd.to_datetime(df_lst_acc_num_10q_vst.index, format='%Y-%m-%d')

df_lst_acc_num_10q_vst

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2021 p/ iteração
df_lst_acc_num_10q_vst_sliced = df_lst_acc_num_10q_vst.loc['2021-03-31':]
df_lst_acc_num_10q_vst_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_vst_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Common Stock, Shares Authorized',
    'Common Stock, Shares, Outstanding',
    'Treasury Stock, Common, Shares',
    'Common Stock, Par or Stated Value Per Share',
    'Redeemable Noncontrolling Interest, Equity, Carrying Amount',
    'vistra_MarginDepositFinancingWithAffiliate'
])

# Renomeando algumas linhas do índice
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'vistra_MarginDepositsPostedUnderAffiliateFinancingAgreementAsset': 'Margin Deposits Posted Under Affiliate Financing Agreement Asset',
    'vistra_AccountsReceivableSecuritizationProgramAmountsBorrowed': 'Accounts Receivable Securitization Program Amounts Borrowed',
    'vistra_ForwardRepurchaseObligationToBePaidCurrent': 'Forward Repurchase Obligation To Be Paid Current',
    'vistra_ForwardRepurchaseObligationToBePaidNoncurrent': 'Forward Repurchase Obligation To Be Paid Noncurrent',
    'vistra_DerivativeAndHedgeLiabilitiesNoncurrent': 'Derivative And Hedge Liabilities Noncurrent',
    'vistra_TaxReceivableAgreementObligationNoncurrent': 'Tax Receivable Agreement Obligation Noncurrent',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_vst_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-03-31'] = df_income_statement_10q.loc['Interest Expense', '2024-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-09-30'] = df_income_statement_10q.loc['Interest Expense', '2023-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-06-30'] = df_income_statement_10q.loc['Interest Expense', '2023-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-03-31'] = df_income_statement_10q.loc['Interest Expense', '2023-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-09-30'] = df_income_statement_10q.loc['Interest Expense', '2022-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-06-30'] = df_income_statement_10q.loc['Interest Expense', '2022-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-03-31'] = df_income_statement_10q.loc['Interest Expense', '2022-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-09-30'] = df_income_statement_10q.loc['Interest Expense', '2021-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-06-30'] = df_income_statement_10q.loc['Interest Expense', '2021-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-03-31'] = df_income_statement_10q.loc['Interest Expense', '2021-03-31'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) Attributable to Parent, before Tax'
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2026-06-30'] = df_income_statement_10q.loc['Income (Loss) Attributable to Parent, before Tax', '2026-06-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2026-03-31'] = df_income_statement_10q.loc['Income (Loss) Attributable to Parent, before Tax', '2026-03-31'] 

                                                                              
# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Interest Expense',
    'Income (Loss) Attributable to Parent, before Tax'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Income (Loss) from Equity Method Investments'
])

# Renomeando algumas linhas do índice
df_income_statement_10q = df_income_statement_10q.rename(index={
    'vistra_CostOfFuelPurchasedPowerAndDelivery': 'Cost Of Fuel Purchased Power And Delivery',
    'vistra_ImpactsOfTaxReceivableAgreement': 'Impacts Of Tax Receivable Agreement',
})

# Arrumando a escala das linhas 'Weighted Average Number of Shares Outstanding, Basic' e 'Weighted Average Number of Shares Outstanding, Diluted'
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted'] / 1000, 0)

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Cost Of Fuel Purchased Power And Delivery']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_vst_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect'
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2023-09-30'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2023-09-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2023-06-30'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2023-06-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2023-03-31'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2023-03-31'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2022-09-30'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2022-09-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2022-06-30'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2022-06-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2022-03-31'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2022-03-31'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2021-09-30'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2021-09-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2021-06-30'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2021-06-30'] 
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2021-03-31'] = df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect', '2021-03-31'] 

# A linha 'Repayments of Long-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security'
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2021-03-31'] = df_cash_flow_10q.loc['Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security', '2021-03-31'] 

# A linha 'Repayments of Short-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'Repayments of Other Short-term Debt'
df_cash_flow_10q.loc['Repayments of Short-term Debt', '2021-09-30'] = df_cash_flow_10q.loc['Repayments of Other Short-term Debt', '2021-09-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Excluding Exchange Rate Effect',
    'Repayment of Long-term Debt, Long-term Lease Obligation, and Capital Security',
    'Repayments of Other Short-term Debt'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Proceeds from Issuance of Secured Debt',
    'vistra_RepaymentOfTermLoan',
    'Proceeds from Other Short-term Debt',
    'Equity Method Investment, Realized Gain (Loss) on Disposal',
    'vistra_PaymentsOfOrdinaryDividendsNoncontrollingAndRedeemableNoncontrollingInterest',
    'Gain (Loss) on Sale of Properties',
    'vistra_ProceedsFromForwardCapacityAgreement',
    'Payments of Ordinary Dividends, Noncontrolling Interest'
])

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'vistra_GainOnInvoluntaryConversion': 'Gain On Involuntary Conversion',
    'vistra_RedeemableNoncontrollingInterestPrincipalPayment': 'Redeemable Noncontrolling Interest Principal Payment',
    'vistra_UnrealizedGainLossOnCommodityRelatedDerivatives': 'Unrealized Gain Loss On Commodity Related Derivatives',
    'vistra_UnrealizedGainLossOnInterestRateSwapDerivatives': 'Unrealized Gain Loss On Interest Rate Swap Derivatives',
    'vistra_UnrealizedGainLossFromNuclearDecommissioningTrusts': 'Unrealized Gain Loss From Nuclear Decommissioning Trusts',
    'vistra_IncreaseDecreaseInMarginDepositsNet': 'Increase (Decrease) In Margin Deposits, Net',
    'vistra_ProceedsFromRepaymentsOfAccountsReceivableFinancing': 'Proceeds From Repayments Of Accounts Receivable Financing',
    'vistra_ReturnOfCapitalTaxReceivableAgreementAndTenderOffer': 'Return Of Capital Tax Receivable Agreement And Tender Offer',
    'vistra_TaxReceivableAgreementAccretionExpense': 'Tax Receivable Agreement Accretion Expense',
    'vistra_GainLossOnTaxReceivableAgreementRepurchaseAndTenderOffers': 'Gain Loss On Tax Receivable Agreement Repurchase And Tender Offers',
})

df_cash_flow_10q

In [ ]:
# O 'df_income_statement_10q' não tem a linha 'Research and Development Expense'

# Linha 'Research and Development Expense' a ser adicionada 
new_row_rd_is_10q = [
    # 2026-06-30
    0,
    # 2026-03-31
    0,
    # 2025-09-30
    0,
    # 2025-06-30
    0,
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
    # 2024-03-31	
    0,	
    # 2023-09-30	
    0,	
    # 2023-06-30	
    0,	
    # 2023-03-31	
    0,	
    # 2022-09-30	
    0,	
    # 2022-06-30	
    0,	
    # 2022-03-31
    0,	
	# 2021-09-30	
	0,
    # 2021-06-30	
	0,
    # 2021-03-31
	0,
]

# Adicionando a nova linha
df_income_statement_10q.loc['Research and Development'] = new_row_rd_is_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity',
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Cost Of Fuel Purchased Power And Delivery': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'InterestExpenseNonoperating': 'Interest Expense',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [ ]:
# Lendo os arquivos 10k
vst_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

vst_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

vst_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
vst_bs.columns = pd.to_datetime(vst_bs.columns)
vst_is.columns = pd.to_datetime(vst_is.columns)
vst_cf.columns = pd.to_datetime(vst_cf.columns)

# Transformando as colunas em apenas o ano
vst_bs.columns = vst_bs.columns.year
vst_is.columns = vst_is.columns.year
vst_cf.columns = vst_cf.columns.year

In [ ]:
# Preços da VST
vst_close = yf.download('VST', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025'
]

last_dec_close = []

for year in lst_years:
    last_close = vst_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
vst_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
vst_close_dec = vst_close_dec.reindex(index=vst_close_dec.index[::-1])

# Arredondamento de duas casas decimais
vst_close_dec = round(vst_close_dec, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Transformando o index em int
vst_close_dec.index = vst_close_dec.index.astype(int)

vst_close_dec

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = vst_bs.columns

# Valor de Mercado - utilizando a função 'indicador_vm_2', porque o nº de ações está em escala diferente
vm = f_eua.indicador_vm_2(ten_k=True, price=vst_close_dec, df_is=vst_is) 

# LPA - utilizando a função 'indicador_lpa_2', porque o nº de ações está em escala diferente
lpa = f_eua.indicador_lpa_2(ten_k=True, df_is=vst_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=vst_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=vst_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=vst_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=vst_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=vst_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=vst_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=vst_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=vst_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=vst_is)

# VPA - utilizando a função 'indicador_vpa_2', porque o nº de ações está em escala diferente
vpa = f_eua.indicador_vpa_2(ten_k=True, df_bs=vst_bs, df_is=vst_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=vst_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Restricted Cash, Current'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=vst_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current', 
    'Long-term Debt and Lease Obligation'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=vst_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=vst_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=vst_is, df_bs=vst_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=vst_is, df_bs=vst_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=vst_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=vst_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=vst_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Payments to Acquire Property, Plant, and Equipment']

capex= f_eua.indicador_capex(ten_k=True, df_cf=vst_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=vst_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=vst_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=vst_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Other Receivables',	
    'Increase (Decrease) in Interest Payable, Net',	
    'Increase (Decrease) in Accrued Taxes Payable',	
    'Increase (Decrease) in Employee Related Liabilities',
    'Payments For Settlement Of Asset Retirement Obligation',
    'Increase (Decrease) in Deferred Charges',
    'Increase (Decrease) in Other Operating Assets',	
    'Increase (Decrease) in Other Operating Liabilities',
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=vst_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=vst_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Debt', 
    'Proceeds from Lines of Credit', 
    'Proceeds from Short-term Debt'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=vst_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt', 
    'Repayments of Lines of Credit', 
    'Repayments of Short-term Debt'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=vst_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=vst_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=vst_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=vst_is,
        idx=idx
)

# Dividendo por Ação - utilizando a função 'indicador_dpa_2', porque o nº de ações está em escala diferente
dpa = f_eua.indicador_dpa_2(ten_k=True, df_cf=vst_cf, df_is=vst_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=vst_cf, df_is=vst_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=vst_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=vst_bs, df_is=vst_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=vst_bs, df_is=vst_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=vst_bs, df_is=vst_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=vst_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=vst_bs, df_is=vst_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=vst_is, df_bs=vst_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=vst_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
vst_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
vst_indicadores_10k.columns = nomes_col
vst_indicadores_10k

In [ ]:
# Lendo os arquivos 10q
vst_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

vst_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

vst_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
vst_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in vst_bs_10q.columns]
vst_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in vst_is_10q.columns]
vst_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in vst_cf_10q.columns]

In [ ]:
# Preços da VST
vst_close = yf.download('VST', auto_adjust=True, multi_level_index=False, start='2022-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2022','2023', '2024', '2025'
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = vst_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
vst_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
vst_close_months = vst_close_months.reindex(index=vst_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = vst_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
vst_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
vst_close_months_atual = vst_close_months_atual.reindex(index=vst_close_months_atual.index[::-1])

# Juntando as duas series pandas
vst_close_months = pd.concat([vst_close_months_atual, vst_close_months])

# Arredondamento de duas casas decimais
vst_close_months = round(vst_close_months, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
vst_close_months.index = vst_bs_10q.columns[:-3]

vst_close_months

In [ ]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = vst_bs_10q.columns

# Valor de Mercado - utilizando a função 'indicador_vm_2', porque o nº de ações está em escala diferente
vm_10q = f_eua.indicador_vm_2(ten_k=False, price=vst_close_months, df_is=vst_is_10q)

# LPA - utilizando a função 'indicador_lpa_2', porque o nº de ações está em escala diferente
lpa_acum = f_eua.indicador_lpa_2(ten_k=False, df_is=vst_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa_2(ten_k=False, df_is=vst_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=vst_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=vst_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=vst_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=vst_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=vst_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=vst_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=vst_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=vst_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=vst_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=vst_is_10q)

# VPA - utilizando a função 'indicador_vpa_2', porque o nº de ações está em escala diferente
vpa_10q = f_eua.indicador_vpa_2(ten_k=False, df_bs=vst_bs_10q, df_is=vst_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=vst_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Restricted Cash, Current', 
    'Restricted Cash, Noncurrent'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=vst_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current', 
    'Long-term Debt and Lease Obligation'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=vst_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=vst_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=vst_is_10q, df_bs=vst_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=vst_is_10q, df_bs=vst_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=vst_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment' , 
    'Payments to Acquire Businesses, Net of Cash Acquired'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=vst_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=vst_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=vst_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=vst_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) In Margin Deposits, Net',
    'Increase (Decrease) in Interest Payable, Net',
    'Increase (Decrease) in Accrued Taxes Payable',
    'Increase (Decrease) in Employee Related Liabilities',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net',
    'Increase (Decrease) in Other Receivables'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=vst_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=vst_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=vst_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=vst_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Debt', 
    'Proceeds from Short-term Debt', 
    'Proceeds from Lines of Credit'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Long-term Debt', 
    'Repayments of Lines of Credit', 
    'Repayments of Short-term Debt'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=vst_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=vst_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=vst_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=vst_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=vst_cf_10q, first_quarter='03')

# Dividendo por Ação - utilizando a função 'indicador_dpa_2', porque o nº de ações está em escala diferente
dpa_10q = f_eua.indicador_dpa_2(ten_k=False, df_cf=vst_cf_10q, df_is=vst_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=vst_cf_10q, df_is=vst_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=vst_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=vst_bs_10q, df_is=vst_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=vst_bs_10q, df_is=vst_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=vst_bs_10q, df_is=vst_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=vst_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=vst_bs_10q, df_is=vst_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=vst_is_10q, df_bs=vst_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=vst_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
vst_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado',
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
vst_indicadores_10q.columns = nomes_col
vst_indicadores_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//vistra//vst_indicators.xlsx') as writer:
    vst_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    vst_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Talen

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'tln'
f_sec.cik_matching_ticker(ticker)

### Scraping Talen 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_talen = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_talen.index = pd.to_datetime(df_lst_acc_num_talen.index, format='%Y-%m-%d')

df_lst_acc_num_talen

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2024 p/ iteração
df_lst_acc_num_talen_sliced = df_lst_acc_num_talen.loc['2024-12-31':]
df_lst_acc_num_talen_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_talen_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    # balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Removendo as colunas duplicadas, mantendo a primeira ocorrência
df_balance_sheet_10k = df_balance_sheet_10k.loc[:, ~df_balance_sheet_10k.columns.duplicated(keep='first')]

# Ordenando as colunas
df_balance_sheet_10k = df_balance_sheet_10k.sort_index(axis=1, ascending=False)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsAbstract',
    'Common Stock, Value, Issued',
    "Stockholders' Equity Attributable to Noncontrolling Interest"
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'tln_AssetRetirementObligationAndAccruedEnvironmentalCostsNoncurrent': 'Asset Retirement Obligation And Accrued Environmental Costs Noncurrent',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_talen_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # # Selecionando apenas a primeira coluna do df
    # income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Removendo as colunas duplicadas, mantendo a primeira ocorrência
df_income_statement_10k = df_income_statement_10k.loc[:, ~df_income_statement_10k.columns.duplicated(keep='first')]

# Removendo as colunas '2023-05-17' e'2022-12-31'
df_income_statement_10k = df_income_statement_10k.drop(columns=['2023-05-17', '2022-12-31'])

# Ordenando as colunas
df_income_statement_10k = df_income_statement_10k.sort_index(axis=1, ascending=False)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_OperatingExpensesAbstract',
    'Reorganization Items',
    'Restructuring Charges',
    'Variable Interest Entity, Initial Consolidation, Gain (Loss)',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Net Income (Loss) Available to Common Stockholders, Basic'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
     'tln_EnergyExpenses': 'Energy Expenses',
     'tln_OperatingExpenseFuelUsedAndPurchasedPower': 'Operating Expense Fuel Used And Purchased Power',
     'tln_UnrealizedGainLossOnCommodityContractsEnergyExpenses': 'Unrealized Gain Loss On Commodity Contracts Energy Expenses',
     'tln_OperationMaintenanceAndDevelopmentExpense': 'Operation Maintenance And Development Expense',
     'tln_GainLossOnNuclearDecommissioningTrustFundsNet': 'Gain Loss On Nuclear Decommissioning Trust Funds Net',
     'tln_GainLossOnDispositionOfAssetsAndOtherMiscellaneousExpensesNet': 'Gain Loss On Disposition Of Assets And Other Miscellaneous Expenses Net',
})

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenues'] - df_income_statement_10k.loc['Operating Expense Fuel Used And Purchased Power']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_talen_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # # Selecionando apenas a primeira coluna do df
    # cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Removendo as colunas duplicadas, mantendo a primeira ocorrência
df_cash_flow_10k = df_cash_flow_10k.loc[:, ~df_cash_flow_10k.columns.duplicated(keep='first')]

# Removendo as colunas '2023-05-17' e'2022-12-31'
df_cash_flow_10k = df_cash_flow_10k.drop(columns=['2023-05-17', '2022-12-31'])

# Ordenando as colunas
df_cash_flow_10k = df_cash_flow_10k.sort_index(axis=1, ascending=False)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'tln_ReorganizationItemsCashFlowImpact',
    'tln_ProceedsFromExitFinancingsNet',
    'Repayments of Secured Debt',
    'Proceeds from Contributions from Affiliates',
    'Payment for Debt Extinguishment or Debt Prepayment Cost',
    'Payments for Derivative Instrument, Financing Activities',
    'Restructuring Charges',
    'Variable Interest Entity, Initial Consolidation, Gain (Loss)',
    'tln_ProceedsFromConsolidationOfSubsidiaries',
    'tln_ProceedsFromDebtorInPossessionCreditFacilities',
    'tln_RepaymentsOfPrepetitionDeferredCapacityObligations',
    'tln_PaymentsForPrepetitionInventoryRepurchaseObligationsNet'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'tln_GainLossOnDispositionOfNonCoreAssets': 'Gain Loss On Disposition Of Non Core Assets',
    'tln_RepaymentOfTermLoan2': 'Repayment Of Term Loan (2)',
    'tln_PaymentForSettlementOfRestrictedStockUnits': 'Payment For Settlement Of Restricted Stock Units',
    'tln_RepaymentOfTermLoan': 'Repayment Of Term Loan'
})

df_cash_flow_10k

In [ ]:
# O 'df_income_statement_10k' não tem a linha 'Research and Development Expense'

# Linha 'Research and Development Expense' a ser adicionada 
new_row_rd_is_10k = [
    # 2025
    0, 
    # 2024
    0, 
    # 2023
    0, 
]

# Adicionando a nova linha
df_income_statement_10k.loc['Research and Development'] = new_row_rd_is_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts and Other Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Other Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity',
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Operating Expense Fuel Used And Purchased Power': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Talen 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_tln = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_tln.index = pd.to_datetime(df_lst_acc_num_10q_tln.index, format='%Y-%m-%d')

df_lst_acc_num_10q_tln

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de 2024 p/ iteração
df_lst_acc_num_10q_tln_sliced = df_lst_acc_num_10q_tln.loc['2024-06-30':]
df_lst_acc_num_10q_tln_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_tln_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsAbstract',
    'Common Stock, Value, Issued'
])

# Renomeando algumas linhas do índice
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'tln_AssetRetirementObligationAndAccruedEnvironmentalCostsNoncurrent': 'Asset Retirement Obligation And Accrued Environmental Costs Noncurrent',
    'tln_UnfavorableContractLiabilities': 'Unfavorable Contract Liabilities'
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_tln_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Removendo a coluna '2023-06-30'
df_income_statement_10q = df_income_statement_10q.drop('2023-06-30', axis=1)

# Dados de '2024-06-30' - no loop for não estava conseguindo puxar os dados desse trimestre
income_statement_202406 = f_sec.process_one_statement(ticker=ticker, accession_number='000162828024036935', statement_name='income_statement').iloc[:, 2]
income_statement_202406 = f_sec.rename_statement(income_statement_202406, label_dictionary=labels_dict)
income_statement_202406 = income_statement_202406[~income_statement_202406.index.duplicated(keep='first')]

# Juntandos os dfs
df_income_statement_10q = pd.concat([df_income_statement_10q, income_statement_202406], axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Depreciation, Depletion and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Depreciation, Depletion and Amortization, Nonproduction'
df_income_statement_10q.loc['Depreciation, Depletion and Amortization', '2024-09-30'] = df_income_statement_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2024-09-30'] 
df_income_statement_10q.loc['Depreciation, Depletion and Amortization', '2024-06-30'] = df_income_statement_10q.loc['Depreciation, Depletion and Amortization, Nonproduction', '2024-06-30'] 

# A linha 'Net Income (Loss) Attributable to Parent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Net Income (Loss) Available to Common Stockholders, Basic'
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2024-09-30'] = df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2024-09-30'] 
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2024-06-30'] = df_income_statement_10q.loc['Net Income (Loss) Available to Common Stockholders, Basic', '2024-06-30'] 
                                                                   
# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop('Depreciation, Depletion and Amortization, Nonproduction')
df_income_statement_10q = df_income_statement_10q.drop('Net Income (Loss) Available to Common Stockholders, Basic')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_OperatingExpensesAbstract',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Impairment of Long-Lived Assets Held-for-use',
    'Reorganization Items',
    'Other Cost and Expense, Operating'
])

# Renomeando algumas linhas do índice
df_income_statement_10q = df_income_statement_10q.rename(index={
    'tln_OperatingExpenseFuelUsedAndPurchasedPower': 'Operating Expense Fuel Used And Purchased Power',
    'tln_UnrealizedGainLossOnCommodityContractsEnergyExpenses': 'Unrealized Gain Loss On Commodity Contracts Energy Expenses',
    'tln_EnergyExpenses': 'Energy Expenses',
    'tln_OperationMaintenanceAndDevelopmentExpense': 'Operation Maintenance And Development Expense',
    'tln_GainLossOnNuclearDecommissioningTrustFundsNet': 'Gain Loss On Nuclear Decommissioning Trust Funds Net',
    'tln_GainLossOnDispositionOfAssetsAndOtherMiscellaneousExpensesNet': 'Gain Loss On Disposition Of Assets And Other Miscellaneous Expenses Net',
})

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2026-06-30'] = -92
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2026-03-31'] = 63

# Arrumando a escala das linhas 'Weighted Average Number of Shares Outstanding, Basic' e 'Weighted Average Number of Shares Outstanding, Diluted'
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic'] / 1000, 2)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted'] / 1000, 2)

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Operating Expense Fuel Used And Purchased Power']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_tln_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Removendo as colunas '2023-09-30' e '2023-06-30'
df_cash_flow_10q = df_cash_flow_10q.drop(['2023-09-30', '2023-06-30'], axis=1)

# Dados de '2024-09-30' - no loop for não estava conseguindo puxar os dados desse trimestre
cash_flow_statement_202409 = f_sec.process_one_statement(ticker=ticker, accession_number='000162828024047751', statement_name='cash_flow_statement').iloc[:, 2]
cash_flow_statement_202409 = f_sec.rename_statement(cash_flow_statement_202409, label_dictionary=labels_dict)
cash_flow_statement_202409 = cash_flow_statement_202409[~cash_flow_statement_202409.index.duplicated(keep='first')]

# Dados de '2024-06-30' - no loop for não estava conseguindo puxar os dados desse trimestre
cash_flow_statement_202406 = f_sec.process_one_statement(ticker=ticker, accession_number='000162828024036935', statement_name='cash_flow_statement').iloc[:, 2]
cash_flow_statement_202406 = f_sec.rename_statement(cash_flow_statement_202406, label_dictionary=labels_dict)
cash_flow_statement_202406 = cash_flow_statement_202406[~cash_flow_statement_202406.index.duplicated(keep='first')]

# Juntandos os dfs
df_cash_flow_10q = pd.concat([df_cash_flow_10q, cash_flow_statement_202409, cash_flow_statement_202406], axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'tln_AmortizationOfNuclearFuelIncludingRoundingDifference',
    'Impairment of Long-Lived Assets Held-for-use',
    'tln_ReorganizationItemsCashFlowImpact',
    'Proceeds from Contributions from Affiliates',
    'tln_ProceedsFromExitFinancingsNet',
    'Repayments of Secured Debt',
    'Payment for Debt Extinguishment or Debt Prepayment Cost',
    'Proceeds from Issuance of Secured Debt',
    'tln_RepaymentOfTermLoan',
    'Payments for Repurchase of Warrants',
    'Payments for Derivative Instrument, Financing Activities'
])

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'tln_GainLossOnDispositionOfNonCoreAssets': 'Gain Loss On Disposition Of Non Core Assets',
    'tln_RepaymentOfTermLoan2': 'Repayment Of Term Loan',
    'tln_PaymentForSettlementOfRestrictedStockUnits': 'Payment For Settlement Of Restricted Stock Units'
})

df_cash_flow_10q

In [ ]:
# O 'df_income_statement_10q' não tem a linha 'Research and Development Expense'

# Linha 'Research and Development Expense' a ser adicionada 
new_row_rd_is_10q = [
    # 2026-06-30
    0,
    # 2026-03-31
    0,
    # 2025-09-30
    0,
    # 2025-06-30
    0,
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
]

# Adicionando a nova linha
df_income_statement_10q.loc['Research and Development'] = new_row_rd_is_10q

In [ ]:
# O 'df_cash_flow_10q' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10q = [
    # 2026-06-30
    0,
    # 2026-03-31
    0,
    # 2025-09-30
    0,
    # 2025-06-30
    0,
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10q.loc['Payments of Dividends'] = new_row_div_cf_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts and Other Receivables, Net, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable and Other Accrued Liabilities, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity',
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Operating Expense Fuel Used And Purchased Power': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'Interest and Debt Expense': 'Interest Expense',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [165]:
# Lendo os arquivos 10k
tln_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

tln_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

tln_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
tln_bs.columns = pd.to_datetime(tln_bs.columns)
tln_is.columns = pd.to_datetime(tln_is.columns)
tln_cf.columns = pd.to_datetime(tln_cf.columns)

# Transformando as colunas em apenas o ano
tln_bs.columns = tln_bs.columns.year
tln_is.columns = tln_is.columns.year
tln_cf.columns = tln_cf.columns.year

In [166]:
# Preços da TLN
tln_close = yf.download('TLN', auto_adjust=True, multi_level_index=False, start='2023-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2023', '2024', '2025'
]

last_dec_close = []

for year in lst_years:
    last_close = tln_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
tln_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
tln_close_dec = tln_close_dec.reindex(index=tln_close_dec.index[::-1])

# Arredondamento de duas casas decimais
tln_close_dec = round(tln_close_dec, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Transformando o index em int
tln_close_dec.index = tln_close_dec.index.astype(int)

tln_close_dec

[*********************100%***********************]  1 of 1 completed

2025    374.84
2024    201.47
2023     64.00
dtype: float64

In [167]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = tln_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=tln_close_dec, df_is=tln_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=tln_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=tln_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=tln_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=tln_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=tln_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=tln_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=tln_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=tln_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=tln_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=tln_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=tln_bs, df_is=tln_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=tln_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Restricted Cash and Cash Equivalents, Current'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=tln_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt, Current Maturities', 
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=tln_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=tln_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=tln_is, df_bs=tln_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=tln_is, df_bs=tln_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=tln_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=tln_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=tln_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment', 
    'Payments to Acquire Interest in Subsidiaries and Affiliates'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=tln_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=tln_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm) * 1000

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=tln_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=tln_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts and Other Receivables',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Interest Payable, Net',
    'Increase (Decrease) in Other Operating Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=tln_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=tln_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Other Long-term Debt', 
    'Proceeds from Issuance of Secured Debt'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=tln_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Other Long-term Debt', 
    'Repayment Of Term Loan (2)', 
    'Payments of Debt Issuance Costs', 
    'Repayment Of Term Loan'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=tln_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=tln_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=tln_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=tln_is,
        idx=idx
)

# DPA e Payout - Talen não paga dividendo

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=tln_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=tln_bs, df_is=tln_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=tln_bs, df_is=tln_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=tln_bs, df_is=tln_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=tln_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=tln_bs, df_is=tln_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=tln_is, df_bs=tln_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=tln_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
tln_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
tln_indicadores_10k.columns = nomes_col
tln_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,-78206.34,0.0,-0.00,189.0,-8.49,135.18,-3.49,7.32,18742.00,1.712719e+10,...,103,27.717939,-111.751101,-112.957048,-3.214612,0.075940,-0.108518,3.724868,-2.767123,0.351254
2024,10952.46,10073.5,0.01,511.0,47.19,132.81,10.69,24.16,6715.67,1.093055e+10,...,1958,21.226950,-158.832853,-139.899135,0.256513,0.058156,0.112195,0.500978,0.171343,0.298246
2023,28192.96,0.0,0.00,317.0,9.97,131.55,11.90,23.59,1600.00,3.777856e+09,...,0,37.206101,-322.818396,-296.132075,3.000000,0.101935,NaN,1.268139,2.134328,0.738854

In [168]:
# Lendo os arquivos 10q
tln_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

tln_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

tln_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
tln_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in tln_bs_10q.columns]
tln_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in tln_is_10q.columns]
tln_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in tln_cf_10q.columns]

# Removendo as colunas '2024-09-30' e '2024-06-30'
tln_bs_10q = tln_bs_10q.drop(columns=['2024-09-30', '2024-06-30'])
tln_is_10q = tln_is_10q.drop(columns=['2024-09-30', '2024-06-30'])
tln_cf_10q = tln_cf_10q.drop(columns=['2024-09-30', '2024-06-30'])

In [169]:
# Preços da Talen
tln_close = yf.download('TLN', auto_adjust=True, multi_level_index=False, start='2026-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2026'
]

lst_months = [
    '03', 
    '06', 
    # '09'
]
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = tln_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
tln_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
tln_close_months = tln_close_months.reindex(index=tln_close_months.index[::-1])

### ------------------------------------------- ###
### ATIVAR O CÓDIGO ABAIXO QUANDO LANÇAR O 1Q27 ###
### ------------------------------------------- ###

# # No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
# actual_year_int = datetime.now().year  
# actual_year_str = str(actual_year_int) 

# lst_actual_months = [
#     # '03',
#     # '06', 
#     # '09'
# ] 

# last_close_actual_months = []

# for month in lst_actual_months:
#     last_close = tln_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
#     last_close_actual_months.append(last_close)

# # Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
# lst_idx_actual = []

# for month in lst_actual_months:
#     lst_idx_actual.append(f"{month}-{actual_year_str}")

# # Transformando em uma série pandas
# tln_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# # Revertendo o index da série p/ ficar igual com os dos indicadores
# tln_close_months_atual = tln_close_months_atual.reindex(index=tln_close_months_atual.index[::-1])

# # Juntando as duas series pandas
# tln_close_months = pd.concat([tln_close_months_atual, tln_close_months])

# # Arredondamento de duas casas decimais
# tln_close_months = round(tln_close_months, 2)

# # Não realizou split recentemente (https://br.investing.com/equities/talen-energy-corp)

# # Substituindo o index para ficar igual ao dos dados fundamentalistas
# tln_close_months.index = tln_bs_10q.columns[:-3]

tln_close_months

[*********************100%***********************]  1 of 1 completed

06-2026    384.260010
03-2026    319.230011
dtype: float64

In [170]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = tln_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=tln_close_months, df_is=tln_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=tln_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=tln_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=tln_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=tln_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=tln_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=tln_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=tln_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=tln_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=tln_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=tln_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=tln_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=tln_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=tln_bs_10q, df_is=tln_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=tln_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Restricted Cash and Cash Equivalents, Current'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=tln_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt, Current Maturities',
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=tln_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=tln_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=tln_is_10q, df_bs=tln_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=tln_is_10q, df_bs=tln_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=tln_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments for Nuclear Fuel'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=tln_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=tln_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=tln_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=tln_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts and Other Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable and Accrued Liabilities',
    'Increase (Decrease) in Interest Payable, Net',
    'Increase (Decrease) Cash Collateral from Counterparties',
    'Increase (Decrease) in Other Operating Liabilities',
]


change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=tln_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=tln_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=tln_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=tln_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Lines of Credit'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Lines of Credit',
    'Repayments of Other Long-term Debt',
    'Payments of Debt Issuance Costs',
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=tln_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=tln_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=tln_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=tln_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=tln_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=tln_cf_10q, df_is=tln_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=tln_cf_10q, df_is=tln_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=tln_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=tln_bs_10q, df_is=tln_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=tln_bs_10q, df_is=tln_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=tln_bs_10q, df_is=tln_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=tln_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=tln_bs_10q, df_is=tln_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=tln_is_10q, df_bs=tln_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=tln_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
tln_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
tln_indicadores_10q.columns = nomes_col
tln_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,-191.71,69.99,1.43,20.0,761.0,-12.32,147.79,-9.64,2.68,10.91,...,198.0,143.654618,-304.677871,-354.775910,4.717391,0.393574,0.032735,-21.70000,0.184783,1.934783
2026-03-31,231.11,70.16,1.43,276.0,707.0,5.58,149.87,18.60,24.45,13.57,...,100.0,51.080602,-158.188277,-160.781528,7.317460,0.139947,-0.047218,1.67029,10.317460,1.045455

In [173]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//talen//tln_indicators.xlsx') as writer:
    tln_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    tln_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Oklo

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'oklo'
f_sec.cik_matching_ticker(ticker)

### Scraping Oklo 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_oklo = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_oklo.index = pd.to_datetime(df_lst_acc_num_oklo.index, format='%Y-%m-%d')

df_lst_acc_num_oklo

In [ ]:
# Selecionando os 'acc_num' dos 10-k a partir de 2024 p/ iteração
df_lst_acc_num_oklo_sliced = df_lst_acc_num_oklo.loc['2024-12-31':]
df_lst_acc_num_oklo_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_oklo_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Financial Instruments Subject to Mandatory Redemption, Settlement Terms, Share Value, Amount, Noncurrent',
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'DebtSecuritiesAvailableForSaleExcludingAccruedInterestCurrent': 'Debt Securities Available For Sale Excluding Accrued Interest Current',
    'DebtSecuritiesAvailableForSaleExcludingAccruedInterestNoncurrent': 'Debt Securities Available For Sale Excluding Accrued Interest Noncurrent',
    'oklo_RightOfFirstRefusalLiability': 'Right Of First Refusal Liability'
})

# Arrumando a escala da coluna '2025-12-31'
df_balance_sheet_10k['2025-12-31'] = df_balance_sheet_10k['2025-12-31'] / 1000

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_oklo_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_OperatingExpensesAbstract',
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
     'oklo_FinancialInstrumentsSubjectToMandatoryRedemptionSettlementTermsChangeInFairValueOfShares': 'Financial Instruments Subject To Mandatory Redemption Settlement Terms Change In Fair Value Of Shares',
})

# Arrumando a escala da coluna 
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic'] = df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Basic'] / 1000

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_oklo_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities',
    'oklo_DeferredIssuanceCostsIncludedInAccruedExpenseAndOther',
    'oklo_ReclassificationOfSimpleAgreementsForFutureEquityInConnectionWithRecapitalization'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'oklo_FinancialInstrumentsSubjectToMandatoryRedemptionSettlementTermsChangeInFairValueOfShares': 'Financial Instruments Subject To Mandatory Redemption Settlement Terms Change In Fair Value Of Shares',
    'oklo_IncreaseDecreaseInOperatingLeaseRightOfUseAssetsAndLiability': 'Increase (Decrease) In Operating Lease Right Of Use Assets And Liability',
    'oklo_CashAcquiredThroughReverseRecapitalization': 'Cash Acquired Through Reverse Recapitalization',
    'oklo_ProceedsFromRightOfFirstRefusalLiability': 'Proceeds From Right Of First Refusal Liability',
    'oklo_ReclassificationOfDeferredIssuanceCostsInConnectionWithBusinessCombination': 'Reclassification Of Deferred Issuance Costs In Connection With Business Combination',
    'oklo_ReclassificationOfSimpleAgreementsForFutureEquityInConnectionWithBusinessCombination': 'Reclassification Of Simple Agreements For Future Equity In Connection With Business Combination',
    'oklo_DeferredIssuanceCostsIncludedInAccountsPayable': 'Deferred Issuance Costs Included In Accounts Payable',
    'oklo_InterestIncomeAndAccretionAmortizationOfDiscountsAndPremiumsInvestments': 'Interest Income And Accretion Amortization Of Discounts And Premiums Investments',
    'oklo_OfferingCostsIncludedInAccountsPayable': 'Offering Costs Included In Accounts Payable',
    'oklo_OfferingCostsIncludedInAccruedExpensesAndOther': 'Offering Costs Included In Accrued Expenses And Other'
})

# Arrumando a escala da coluna '2025-12-31'
df_cash_flow_10k['2025-12-31'] = df_cash_flow_10k['2025-12-31'] / 1000

df_cash_flow_10k

In [ ]:
# O 'df_income_statement_10k' não tem as linhas 'Revenues' e 'Operating Income'

# Linha 'Revenues' a ser adicionada 
new_row_revenues_is_10k = [
    # 2025
    0,
    # 2024
    0,
]

# Linha 'Cost of Goods and Services Sold' a ser adicionada 
new_row_cogs_is_10k = [
    # 2025
    0,
    # 2024
    0,
]

# Linha 'Gross Profit' a ser adicionada 
new_row_gross_profit_is_10k = [
    # 2025
    0,
    # 2024
    0,
]

# Linha 'Operating Income' a ser adicionada 
new_row_operating_income_is_10k = [
    # 2025
    0, 
    # 2024
    0, 
]

# Adicionando as novas linhas
df_income_statement_10k.loc['Revenues'] = new_row_revenues_is_10k
df_income_statement_10k.loc['Cost of Goods Sold'] = new_row_cogs_is_10k
df_income_statement_10k.loc['Gross Profit'] = new_row_gross_profit_is_10k
df_income_statement_10k.loc['Operating Income'] = new_row_operating_income_is_10k

In [ ]:
# O 'df_cash_flow_10k' não tem a linha 'Proceeds from Issuance'

# Linha 'Proceeds from Issuance' a ser adicionada 
new_row_proceeds_is_10k = [
    # 2025
    0, 
    # 2024
    0, 
]

# Linha 'Repayment of Debt' a ser adicionada
new_row_repayment_is_10k = [
    # 2025
    0, 
    # 2024
    0, 
]

# Adicionando as novas linhas
df_cash_flow_10k.loc['Proceeds from Issuance'] = new_row_proceeds_is_10k 
df_cash_flow_10k.loc['Repayment of Debt'] = new_row_repayment_is_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity',
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Research and Development Expense': 'Research and Development',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Oklo 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_oklo = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_oklo.index = pd.to_datetime(df_lst_acc_num_10q_oklo.index, format='%Y-%m-%d')

df_lst_acc_num_10q_oklo

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de 2024 p/ iteração
df_lst_acc_num_10q_oklo_sliced = df_lst_acc_num_10q_oklo.loc['2024-06-30':]
df_lst_acc_num_10q_oklo_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_oklo_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'DebtSecuritiesAvailableForSaleExcludingAccruedInterestCurrent' na  coluna abaixo está zerada
# As informações estão na linha 'Marketable Securities, Current'
df_balance_sheet_10q.loc['DebtSecuritiesAvailableForSaleExcludingAccruedInterestCurrent', '2024-06-30'] = df_balance_sheet_10q.loc['Marketable Securities, Current', '2024-06-30'] 

# A linha 'DebtSecuritiesAvailableForSaleExcludingAccruedInterestNoncurrent' na  coluna abaixo está zerada
# As informações estão na linha 'Marketable Securities, Noncurrent'
df_balance_sheet_10q.loc['DebtSecuritiesAvailableForSaleExcludingAccruedInterestNoncurrent', '2024-06-30'] = df_balance_sheet_10q.loc['Marketable Securities, Noncurrent', '2024-06-30'] 

# A linha 'Accrued Liabilities, Current' na  coluna abaixo está zerada
# As informações estão na linha 'oklo_AccruedAndOtherLiabilitiesCurrent'
df_balance_sheet_10q.loc['Accrued Liabilities, Current', '2024-06-30'] = df_balance_sheet_10q.loc['oklo_AccruedAndOtherLiabilitiesCurrent', '2024-06-30'] 

# A linha 'oklo_RightOfFirstRefusalLiability' na  coluna abaixo está zerada
# As informações estão na linha 'oklo_RightOfFirstRefusalLiabilityNoncurrent'
df_balance_sheet_10q.loc['oklo_RightOfFirstRefusalLiability', '2024-06-30'] = df_balance_sheet_10q.loc['oklo_RightOfFirstRefusalLiabilityNoncurrent', '2024-06-30'] 

# A linha 'Additional Paid in Capital' na  coluna abaixo está zerada
# As informações estão na linha 'Additional Paid in Capital, Common Stock'
df_balance_sheet_10q.loc['Additional Paid in Capital', '2024-06-30'] = df_balance_sheet_10q.loc['Additional Paid in Capital, Common Stock', '2024-06-30'] 
                                                                   
# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Marketable Securities, Current',
    'Marketable Securities, Noncurrent',
    'oklo_AccruedAndOtherLiabilitiesCurrent',
    'oklo_RightOfFirstRefusalLiabilityNoncurrent',
    'Additional Paid in Capital, Common Stock',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Financial Instruments Subject to Mandatory Redemption, Settlement Terms, Share Value, Amount, Noncurrent',
    'oklo_SimpleAgreementForFutureEquity',
])

# Renomeando algumas linhas do índice
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'DebtSecuritiesAvailableForSaleExcludingAccruedInterestCurrent': 'Debt Securities Available For Sale Excluding Accrued Interest Current',
    'DebtSecuritiesAvailableForSaleExcludingAccruedInterestNoncurrent': 'Debt Securities Available For Sale Excluding Accrued Interest Noncurrent',
    'oklo_RightOfFirstRefusalLiability': 'Right Of First Refusal Liability'
})

# Arrumando a escala das colunas '2024-09-30' e '2024-06-30'
df_balance_sheet_10q['2024-09-30'] = df_balance_sheet_10q['2024-09-30'] / 1000
df_balance_sheet_10q['2024-06-30'] = df_balance_sheet_10q['2024-06-30'] / 1000

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_oklo_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_OperatingExpensesAbstract',
    'oklo_FinancialInstrumentsSubjectToMandatoryRedemptionSettlementTermsChangeInFairValueOfShares',
    'Redeemable Preferred Stock Dividends',
    'Net Income (Loss) Available to Common Stockholders, Basic',
    'oklo_EarningsPerShareAvailableToCommonStockholdersBasic',
    'oklo_ChangeInFairValueOfSimpleAgreementForFutureEquity',
    'oklo_FairValueRecognizedAsDeemed',
    'oklo_EarningsPerShareBasicAttributableToCommonStockholders',
    'us-gaap_IncomeStatementAbstract'
])

# Arrumando a escala das colunas abaixo
df_income_statement_10q['2024-09-30'] = df_income_statement_10q['2024-09-30'] / 1000
df_income_statement_10q['2024-06-30'] = df_income_statement_10q['2024-06-30'] / 1000

# Arrumando a escala da linha 'Weighted Average Number of Shares Outstanding, Basic'
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-06-30'] = df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-06-30']/1000
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-03-31'] = df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-03-31']/1000
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-06-30'] = df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-06-30']/1000
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-03-31'] = df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-03-31']/1000

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Nonoperating Income (Expense)', '2026-03-31'] = 21339 

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10q.loc['Operating Costs and Expenses']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_oklo_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'oklo_IncreaseDecreaseInOperatingLeaseRightOfUseAssetsAndLiability' nas colunas abaixo está zerada
# As informações estão na linha 'IncreaseDecreaseInOperatingLeaseLiability'
df_cash_flow_10q.loc['oklo_IncreaseDecreaseInOperatingLeaseRightOfUseAssetsAndLiability', '2024-09-30'] = df_cash_flow_10q.loc['IncreaseDecreaseInOperatingLeaseLiability', '2024-09-30'] 
df_cash_flow_10q.loc['oklo_IncreaseDecreaseInOperatingLeaseRightOfUseAssetsAndLiability', '2024-06-30'] = df_cash_flow_10q.loc['IncreaseDecreaseInOperatingLeaseLiability', '2024-06-30'] 

# A linha 'Net Income (Loss) Attributable to Parent' na coluna abaixo está zerada
# As informações estão na linha 'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest'
df_cash_flow_10q.loc['Net Income (Loss) Attributable to Parent', '2024-06-30'] = df_cash_flow_10q.loc['Net Income (Loss), Including Portion Attributable to Noncontrolling Interest', '2024-06-30'] 

# A linha 'Accretion (Amortization) of Discounts and Premiums, Investments' na coluna abaixo está zerada
# As informações estão na linha 'oklo_AccretionAmortizationOfDiscountsAndPremiumsMarketableSecurities'
df_cash_flow_10q.loc['Accretion (Amortization) of Discounts and Premiums, Investments', '2024-06-30'] = df_cash_flow_10q.loc['oklo_AccretionAmortizationOfDiscountsAndPremiumsMarketableSecurities', '2024-06-30'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Payments to Acquire Marketable Securities'
df_cash_flow_10q.loc['Payments to Acquire Debt Securities, Available-for-sale', '2024-06-30'] = df_cash_flow_10q.loc['Payments to Acquire Marketable Securities', '2024-06-30'] 

# A linha 'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale and Maturity of Marketable Securities'
df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2024-06-30'] = df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Marketable Securities', '2024-06-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' na coluna abaixo está zerada
# As informações estão na linha 'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffectContinuingOperations'
df_cash_flow_10q.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2024-06-30'] = df_cash_flow_10q.loc['CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffectContinuingOperations', '2024-06-30'] 

# A linha 'Proceeds from Issuance of Mandatory Redeemable Capital Securities' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Convertible Debt'
df_cash_flow_10q.loc['Proceeds from Issuance of Mandatory Redeemable Capital Securities', '2024-06-30'] = df_cash_flow_10q.loc['Proceeds from Convertible Debt', '2024-06-30'] 

# A linha 'oklo_FinancialInstrumentsSubjectToMandatoryRedemptionSettlementTermsChangeInFairValueOfShares' na coluna abaixo está zerada
# As informações estão na linha 'oklo_ChangeInFairValueOfSimpleAgreementForFutureEquity'
df_cash_flow_10q.loc['oklo_FinancialInstrumentsSubjectToMandatoryRedemptionSettlementTermsChangeInFairValueOfShares', '2024-06-30'] = df_cash_flow_10q.loc['oklo_ChangeInFairValueOfSimpleAgreementForFutureEquity', '2024-06-30'] 

# A linha 'oklo_CashAcquiredThroughReverseRecapitalization' na coluna abaixo está zerada
# As informações estão na linha 'oklo_ProceedsFromReverseRecapitalization'
df_cash_flow_10q.loc['oklo_CashAcquiredThroughReverseRecapitalization', '2024-06-30'] = df_cash_flow_10q.loc['oklo_ProceedsFromReverseRecapitalization', '2024-06-30'] 
                                                                   
# Removendo as linhas que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'IncreaseDecreaseInOperatingLeaseLiability',
    'Net Income (Loss), Including Portion Attributable to Noncontrolling Interest',
    'oklo_AccretionAmortizationOfDiscountsAndPremiumsMarketableSecurities',
    'Payments to Acquire Marketable Securities',
    'Proceeds from Sale and Maturity of Marketable Securities',
    'CashCashEquivalentsRestrictedCashAndRestrictedCashEquivalentsPeriodIncreaseDecreaseIncludingExchangeRateEffectContinuingOperations',
    'Proceeds from Convertible Debt',
    'oklo_ChangeInFairValueOfSimpleAgreementForFutureEquity',
    'oklo_ProceedsFromReverseRecapitalization',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'oklo_ReclassificationOfSimpleAgreementsForFutureEquityInConnectionWithRecapitalization',
    'oklo_ReclassificationOfDeferredIssuanceCostsInConnectionWithRecapitalization',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities',
    'oklo_DeferredIssuanceCostsIncludedInAccountsPayable',
    'oklo_DeferredIssuanceCostsIncludedInAccruedExpenseAndOther',
    'oklo_BusinessCombinationReclassificationOfDeferredIssuanceCost',
    'oklo_ReclassificationOfSimpleAgreementForFutureEquityInConnectionWithBusinessCombination',
    'oklo_ReclassificationOfSimpleAgreementsForFutureEquityInConnectionWithBusinessCombination',
    'oklo_ReclassificationOfDeferredIssuanceCostsInConnectionWithBusinessCombination',
])

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'oklo_InterestIncomeAndAccretionAmortizationOfDiscountsAndPremiumsInvestments': 'Interest Income And Accretion Amortization Of Discounts And Premiums Investments',
    'oklo_FinancialInstrumentsSubjectToMandatoryRedemptionSettlementTermsChangeInFairValueOfShares': 'Financial Instruments Subject To Mandatory Redemption Settlement Terms Change In Fair Value Of Shares',
    'oklo_CashAcquiredThroughReverseRecapitalization': 'Cash Acquired Through Reverse Recapitalization',
    'oklo_ProceedsFromRightOfFirstRefusalLiability': 'Proceeds From Right Of First Refusal Liability',
    'oklo_OfferingCostsIncludedInAccountsPayable': 'Offering Costs Included In Accounts Payable',
    'oklo_OfferingCostsIncludedInAccruedExpensesAndOther': 'Offering Costs Included In Accrued Expenses And Other',
    'oklo_IncreaseDecreaseInOperatingLeaseRightOfUseAssetsAndLiability': 'Increase (Decrease) In Operating Lease Right Of Use Assets And Liability',
    'oklo_NoncashOrPartNoncashAcquisitionHoldbackLiabilities': 'Non Cash Or Part Non Cash Acquisition Hold Back Liabilities',
    'oklo_NoncashOrPartNoncashAcquisitionContingentLiabilities': 'Non Cash Or Part Non Cash Acquisition Contingent Liabilities',
    'oklo_NoncashOrPartNoncashAcquisitionAccountsPayableSettlement': 'Non Cash Or Part Non Cash Acquisition Accounts Payable Settlement'
})

# Arrumando a escala das colunas
df_cash_flow_10q['2026-06-30'] = df_cash_flow_10q['2026-06-30'] / 1000
df_cash_flow_10q['2024-09-30'] = df_cash_flow_10q['2024-09-30'] / 1000
df_cash_flow_10q['2024-06-30'] = df_cash_flow_10q['2024-06-30'] / 1000

df_cash_flow_10q

In [ ]:
# O 'df_cash_flow_10q' não tem a linha 'Proceeds from Issuance'

# Linha 'Proceeds from Issuance' a ser adicionada 
new_row_proceeds_is_10q = [
    # 2026-06-30
    0,
    # 2026-03-31
    0,
    # 2025-09-30
    0,
    # 2025-06-30
    0,
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
]

# Linha 'Repayment of Debt' a ser adicionada
new_row_repayment_is_10q = [
    # 2026-06-30
    0,
    # 2026-03-31
    0,
    # 2025-09-30
    0,
    # 2025-06-30
    0,
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
]

# Adicionando a nova linha
df_cash_flow_10q.loc['Proceeds from Issuance'] = new_row_proceeds_is_10q 
df_cash_flow_10q.loc['Repayment of Debt'] = new_row_repayment_is_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity',
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Operating Costs and Expenses': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [174]:
# Lendo os arquivos 10k
oklo_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

oklo_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

oklo_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
oklo_bs.columns = pd.to_datetime(oklo_bs.columns)
oklo_is.columns = pd.to_datetime(oklo_is.columns)
oklo_cf.columns = pd.to_datetime(oklo_cf.columns)

# Transformando as colunas em apenas o ano
oklo_bs.columns = oklo_bs.columns.year
oklo_is.columns = oklo_is.columns.year
oklo_cf.columns = oklo_cf.columns.year

In [175]:
# Preços da OKLO
oklo_close = yf.download('OKLO', auto_adjust=True, multi_level_index=False, start='2023-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2024', '2025'
]

last_dec_close = []

for year in lst_years:
    last_close = oklo_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
oklo_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
oklo_close_dec = oklo_close_dec.reindex(index=oklo_close_dec.index[::-1])

# Arredondamento de duas casas decimais
oklo_close_dec = round(oklo_close_dec, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Transformando o index em int
oklo_close_dec.index = oklo_close_dec.index.astype(int)

oklo_close_dec

[*********************100%***********************]  1 of 1 completed

2025    71.76
2024    21.23
dtype: float64

In [176]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = oklo_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=oklo_close_dec, df_is=oklo_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=oklo_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=oklo_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=oklo_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=oklo_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=oklo_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=oklo_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=oklo_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=oklo_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=oklo_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=oklo_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=oklo_bs, df_is=oklo_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=oklo_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents, at Carrying Value']

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=oklo_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Operating Lease, Liability, Current', 
    'Operating Lease, Liability, Noncurrent'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=oklo_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=oklo_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=oklo_is, df_bs=oklo_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=oklo_is, df_bs=oklo_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=oklo_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=oklo_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=oklo_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Payments to Acquire Property, Plant, and Equipment']

capex= f_eua.indicador_capex(ten_k=True, df_cf=oklo_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=oklo_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=oklo_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=oklo_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=oklo_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Other Accrued Liabilities',
    'Increase (Decrease) In Operating Lease Right Of Use Assets And Liability'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=oklo_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=oklo_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=oklo_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayment of Debt']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=oklo_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=oklo_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=oklo_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=oklo_is,
        idx=idx
)

# DPA e Payout - Oklo não paga dividendo

# Buyback - Oklo não recompra ações

# DSO - não divulga o contas a receber no 10-k

# DIO - não divulga o invetário no 10-k

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=oklo_bs, df_is=oklo_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=oklo_is)

# Recebíveis/Receita - não divulga o contas a receber no 10-k

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=oklo_is, df_bs=oklo_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=oklo_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    # Buyback - não recompra ações
    # dso - não divulga o contas a receber no 10-k
    # dio - não divulga o invetário no 10-k
    dpo,
    fco_ll,
    # recebiveis_receita - não divulga o contas a receber no 10-k
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
oklo_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    # 'DPA' - não paga dividendo
    # 'Payout' - não paga dividendo
    # 'Buyback' - não recompra ações
    # 'DSO' - não divulga o contas a receber no 10-k
    # 'DIO' - não divulga o invetário no 10-k
    'DPO',
    'FCO/LL',
    # 'Recebíveis/Receita' - não divulga o contas a receber no 10-k
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
oklo_indicadores_10k.columns = nomes_col
oklo_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Working Capital,Reinvestment Rate,FCFE,FCFF,DPO,FCO/LL,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,-99.39,0.0,-1.00,522.0,0.0,0.0,0.0,0.0,7.11,1.050220e+10,...,1228223,-960.41,-149160.0,-43497.0,inf,0.777699,-0.025952,-157.421456,1.091953,63.611111
2024,-28.52,0.0,-3.49,268.0,0.0,0.0,0.0,0.0,8.36,2.099860e+09,...,226603,725.33,-78570.0,-4954.0,inf,0.521490,NaN,-143.246269,0.526271,1.313433

In [177]:
# Lendo os arquivos 10q
oklo_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

oklo_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

oklo_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
oklo_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in oklo_bs_10q.columns]
oklo_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in oklo_is_10q.columns]
oklo_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in oklo_cf_10q.columns]

# Removendo as colunas '2024-09-30' e '2024-06-30'
oklo_bs_10q = oklo_bs_10q.drop(columns=['2024-09-30', '2024-06-30'])
oklo_is_10q = oklo_is_10q.drop(columns=['2024-09-30', '2024-06-30'])
oklo_cf_10q = oklo_cf_10q.drop(columns=['2024-09-30', '2024-06-30'])

In [178]:
# Preços da Oklo
oklo_close = yf.download('OKLO', auto_adjust=True, multi_level_index=False, start='2026-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2026'
]

lst_months = [
    '03', 
    '06', 
    # '09'
]
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = oklo_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
oklo_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
oklo_close_months = oklo_close_months.reindex(index=oklo_close_months.index[::-1])

### ------------------------------------------- ###
### ATIVAR O CÓDIGO ABAIXO QUANDO LANÇAR O 1Q27 ###
### ------------------------------------------- ###

# # No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
# actual_year_int = datetime.now().year  
# actual_year_str = str(actual_year_int) 

# lst_actual_months = [
#     # '03',
#     # '06', 
#     # '09'
# ] 

# last_close_actual_months = []

# for month in lst_actual_months:
#     last_close = oklo_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
#     last_close_actual_months.append(last_close)

# # Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
# lst_idx_actual = []

# for month in lst_actual_months:
#     lst_idx_actual.append(f"{month}-{actual_year_str}")

# # Transformando em uma série pandas
# oklo_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# # Revertendo o index da série p/ ficar igual com os dos indicadores
# oklo_close_months_atual = oklo_close_months_atual.reindex(index=oklo_close_months_atual.index[::-1])

# # Juntando as duas series pandas
# oklo_close_months = pd.concat([oklo_close_months_atual, oklo_close_months])

# # Arredondamento de duas casas decimais
# oklo_close_months = round(oklo_close_months, 2)

# # Não realizou split recentemente (https://br.investing.com/equities/altc-acquisition)

# # Substituindo o index para ficar igual ao dos dados fundamentalistas
# oklo_close_months.index = tln_bs_10q.columns[:-3]

oklo_close_months

[*********************100%***********************]  1 of 1 completed

06-2026    52.330002
03-2026    49.590000
dtype: float64

In [179]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = oklo_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=oklo_close_months, df_is=oklo_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=oklo_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=oklo_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=oklo_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=oklo_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=oklo_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=oklo_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=oklo_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=oklo_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=oklo_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=oklo_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=oklo_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=oklo_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=oklo_bs_10q, df_is=oklo_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=oklo_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents, at Carrying Value']

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=oklo_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Operating Lease, Liability, Current',
    'Operating Lease, Liability, Noncurrent'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=oklo_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=oklo_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=oklo_is_10q, df_bs=oklo_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=oklo_is_10q, df_bs=oklo_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired',
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=oklo_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=oklo_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=oklo_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=oklo_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=oklo_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Other Accrued Liabilities',
    'Increase (Decrease) In Operating Lease Right Of Use Assets And Liability'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=oklo_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=oklo_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=oklo_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=oklo_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Repayment of Debt',
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=oklo_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=oklo_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=oklo_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
    ten_k=False, 
    taxes_operating_income=taxes_operating_income_10q,
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    df_is=oklo_is_10q,
    idx=idx_10q
)

# DPA e Payout - Oklo não paga dividendo

# Buyback - Oklo não recompra ações

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=oklo_bs_10q, df_is=oklo_is_10q)

# DIO - não divulga o invetário no 10-k

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=oklo_bs_10q, df_is=oklo_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=oklo_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=oklo_bs_10q, df_is=oklo_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=oklo_is_10q, df_bs=oklo_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=oklo_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    # Buyback - não recompra ações
    dso_10q,
    # dio_10q - não divulga o invetário no 10-k
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
oklo_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    # Buyback - não recompra ações
    'DSO',
    # 'DIO' - não divulga o invetário no 10-k
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
oklo_indicadores_10q.columns = nomes_col
oklo_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,FCFE,FCFF,DSO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,-190.00,0.0,-1.24,-72853.0,-188014.0,-4011.24,40.41,-6048.76,-6020.91,2.82,...,-260905.0,-325174.0,596.971074,5300.346741,0.980551,1.635537,-0.000462,0.653261,4.307092,202.833828
2026-03-31,-255.46,0.0,-0.89,-51086.0,-132911.0,0.00,0.00,0.00,0.00,3.20,...,-144568.0,-180733.0,NaN,inf,0.540360,NaN,-0.010113,0.349744,3.223257,201.288344

In [182]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//oklo//oklo_indicators.xlsx') as writer:
    oklo_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    oklo_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## NRG

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'nrg'
f_sec.cik_matching_ticker(ticker)

### Scraping NRG 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_nrg = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000101387118000011', # 2017
        ]
    },
    index=pd.to_datetime([
        '2017-12-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_nrg = pd.concat([df_lst_acc_num_nrg, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_nrg.index = pd.to_datetime(df_lst_acc_num_nrg.index, format='%Y-%m-%d')

df_lst_acc_num_nrg

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_nrg['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Accrued Liabilities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Other Accrued Liabilities, Current'
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2023-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2023-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2022-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2022-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2021-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2021-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2020-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2020-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2019-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2019-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2018-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2018-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2017-12-31'] = df_balance_sheet_10k.loc['Other Accrued Liabilities, Current', '2017-12-31'] 

# A linha 'nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset' nas colunas abaixo estão zeradas
# As informações estão na linha 'Derivative, Collateral, Right to Reclaim Cash'
df_balance_sheet_10k.loc['nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset', '2021-12-31'] = df_balance_sheet_10k.loc['Derivative, Collateral, Right to Reclaim Cash', '2021-12-31'] 
df_balance_sheet_10k.loc['nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset', '2020-12-31'] = df_balance_sheet_10k.loc['Derivative, Collateral, Right to Reclaim Cash', '2020-12-31'] 
df_balance_sheet_10k.loc['nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset', '2019-12-31'] = df_balance_sheet_10k.loc['Derivative, Collateral, Right to Reclaim Cash', '2019-12-31'] 
df_balance_sheet_10k.loc['nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset', '2018-12-31'] = df_balance_sheet_10k.loc['Derivative, Collateral, Right to Reclaim Cash', '2018-12-31'] 
df_balance_sheet_10k.loc['nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset', '2017-12-31'] = df_balance_sheet_10k.loc['Derivative, Collateral, Right to Reclaim Cash', '2017-12-31'] 

# A linha 'Public Utilities, Property, Plant and Equipment, Net' nas colunas abaixo estão zeradas
# As informações estão na linha 'Property, Plant and Equipment, Net'
df_balance_sheet_10k.loc['Public Utilities, Property, Plant and Equipment, Net', '2018-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2018-12-31'] 
df_balance_sheet_10k.loc['Public Utilities, Property, Plant and Equipment, Net', '2017-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2017-12-31'] 

# A linha 'Deferred Income Tax Assets, Net' nas colunas abaixo estão zeradas
# As informações estão na linha 'Deferred Tax Assets, Net of Valuation Allowance, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2018-12-31'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net of Valuation Allowance, Noncurrent', '2018-12-31'] 
df_balance_sheet_10k.loc['Deferred Income Tax Assets, Net', '2017-12-31'] = df_balance_sheet_10k.loc['Deferred Tax Assets, Net of Valuation Allowance, Noncurrent', '2017-12-31'] 

# A linha 'Regulated Entity, Other Assets, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Assets, Noncurrent'
df_balance_sheet_10k.loc['Regulated Entity, Other Assets, Noncurrent', '2018-12-31'] = df_balance_sheet_10k.loc['Assets, Noncurrent', '2018-12-31'] 
df_balance_sheet_10k.loc['Regulated Entity, Other Assets, Noncurrent', '2017-12-31'] = df_balance_sheet_10k.loc['Assets, Noncurrent', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Other Accrued Liabilities, Current',
    'Derivative, Collateral, Right to Reclaim Cash',
    'Property, Plant and Equipment, Net',
    'Deferred Tax Assets, Net of Valuation Allowance, Noncurrent',
    'Assets, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Assets Held-for-sale, Not Part of Disposal Group, Current',
    'nrg_AssetsHeldForSaleNotPartOfDisposalGroupNoncurrent',
    'nrg_LiabilitiesHeldForSaleNotPartOfDisposalGroupOrDiscontinuedOperationsCurrent',
    'nrg_LiabilitiesHeldForSaleNotPartOfDisposalGroupOrDiscontinuedOperationsNonCurrent',
    'Due to Affiliate, Current',
    "Stockholders' Equity Attributable to Noncontrolling Interest",
    'Disposal Group, Including Discontinued Operation, Assets, Current',
    'Disposal Group, Including Discontinued Operation, Assets, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Current',
    'Disposal Group, Including Discontinued Operation, Other Liabilities, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Noncurrent',
    'Due from Related Parties, Current',
    'Disposal Group, Including Discontinued Operation, Other Assets, Current',
    'Disposal Group, Including Discontinued Operation, Other Assets, Noncurrent',
    'Accounts Payable, Related Parties, Current',
    'Disposal Group, Including Discontinued Operation, Accrued Liabilities, Current',
    'Liability, Pension and Other Postretirement and Postemployment Benefits, Noncurrent',
    'Off-market Lease, Unfavorable',
    'nrg_ReceivableFromGovernmentGrant',
    'Redeemable Noncontrolling Interest, Equity, Other, Carrying Amount'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'nrg_FundsDepositedByCounterparties': 'Funds Deposited By Counterparties',
    'nrg_DerivativeLiabilityNotSubjectToMasterNettingArrangementCollateralRightToReclaimCashNotOffset': 'Derivative Liability Not Subject To Master Netting Arrangement Collateral Right To Reclaim Cash Not Offset',
    'nrg_NuclearDecommissioningTrustFundLiabilityNoncurrent': 'Nuclear Decommissioning Trust Fund Liability Noncurrent',
})

df_balance_sheet_10k

In [ ]:
# Os dados do income statement da NRG de 2019 não estão aparecendo no loop com o 'acc_num'
# Para selecionar os dados de 2019, eu utilizei o 'acc_num' de 2020
income_statement_20_19_18 = f_sec.process_one_statement(ticker=ticker, accession_number='000101387121000005', statement_name='income_statement')
income_statement_20_19_18 = f_sec.rename_statement(income_statement_20_19_18, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_20_19_18 = income_statement_20_19_18.drop('us-gaap_RevenuesAbstract')


# Dados do income statement de 2017
income_statement_17 = f_sec.process_one_statement(ticker=ticker, accession_number='000101387118000011', statement_name='income_statement')
income_statement_17 = f_sec.rename_statement(income_statement_17, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_17 = income_statement_17.drop('us-gaap_RevenuesAbstract')
# Selecionando a coluna de 2017
income_statement_17 = income_statement_17.loc[:, '2017-12-31']


# Juntando os dfs ('income_statement_20_19_18' e 'income_statement_17')
income_statement_20_19_18_17 = pd.concat([income_statement_20_19_18, income_statement_17], axis=1)

# Substituindo os NaN por 0
income_statement_20_19_18_17 = income_statement_20_19_18_17.fillna(0)

# A linha 'Restructuring Costs' na coluna abaixo está zerada
# As informações estão na linha 'Reorganization Items'
income_statement_20_19_18_17.loc['Restructuring Costs', '2017-12-31'] = income_statement_20_19_18_17.loc['Reorganization Items', '2017-12-31'] 

# A linha 'Gain (Loss) on Disposition of Other Assets' na coluna abaixo está zerada
# As informações estão na linha 'Disposal Group, Not Discontinued Operation, Gain (Loss) on Disposal'
income_statement_20_19_18_17.loc['Gain (Loss) on Disposition of Other Assets', '2017-12-31'] = income_statement_20_19_18_17.loc['Disposal Group, Not Discontinued Operation, Gain (Loss) on Disposal', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
income_statement_20_19_18_17 = income_statement_20_19_18_17.drop([
    'Reorganization Items',
    'Disposal Group, Not Discontinued Operation, Gain (Loss) on Disposal'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
income_statement_20_19_18_17 = income_statement_20_19_18_17.drop([
    'Defined Benefit Plan, Net Periodic Benefit Cost (Credit), Gain (Loss) Due to Curtailment',
    'Equity Method Investment, Realized Gain (Loss) on Disposal',
    'Preferred Stock Dividends, Income Statement Impact',
    'nrg_GainonRedemptionofRedeemablePreferredStock',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Diluted Share'
])	

# # Arrumando e adicionando alguns números no df
income_statement_20_19_18_17.loc['Weighted Average Number of Shares Outstanding, Basic'] = round(income_statement_20_19_18_17.loc['Weighted Average Number of Shares Outstanding, Basic'] / 1000, 0)
income_statement_20_19_18_17.loc['Weighted Average Number of Shares Outstanding, Diluted'] = round(income_statement_20_19_18_17.loc['Weighted Average Number of Shares Outstanding, Diluted'] / 1000, 0)
income_statement_20_19_18_17.loc['Weighted Average Number of Shares Outstanding, Basic', '2017-12-31'] = 317000
income_statement_20_19_18_17.loc['Weighted Average Number of Shares Outstanding, Diluted', '2017-12-31'] = 317000

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_nrg['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Juntando todos os dfs que estão em listas em apenas um df
df_income_statement_10k = pd.concat(income_statement_lst, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# Selecionando as colunas a partir de 2021
df_income_statement_10k = df_income_statement_10k.loc[:, '2021-12-31':]

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_RevenuesAbstract',
    'Other than Temporary Impairment Losses, Investments',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
     'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Income (Loss) from Continuing Operations, Per Basic Share',		
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Basic Share',			
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Diluted Share',			
    'Cost of Revenue',		
    'Restructuring Costs',				
    'Research and Development Expense',				
    'us-gaap_StatementOfIncomeAndComprehensiveIncomeAbstract',			
    'Other Comprehensive Income (Loss), Cash Flow Hedge, Gain (Loss), before Reclassification, after Tax',				
    'Other Comprehensive Income (Loss), Foreign Currency Transaction and Translation Adjustment, Net of Tax',				
    'OCI, Debt Securities, Available-for-Sale, Gain (Loss), after Adjustment and Tax',				
    'Other Comprehensive (Income) Loss, Defined Benefit Plan, after Reclassification Adjustment, after Tax',				
    'Other Comprehensive Income (Loss), Net of Tax',			
    'Comprehensive Income (Loss), Net of Tax, Including Portion Attributable to Noncontrolling Interest',			
    'Comprehensive Income (Loss), Net of Tax, Attributable to Noncontrolling Interest',
    'Comprehensive Income (Loss), Net of Tax, Attributable to Parent',		
    'Reorganization Items',			
    'Related Party Transaction, Other Revenues from Transactions with Related Party',			
    'Disposal Group, Not Discontinued Operation, Gain (Loss) on Disposal',			
    'nrg_GainonRedemptionofRedeemablePreferredStock',			
    'Common Stock, Dividends, Per Share, Declared',			
    'Defined Benefit Plan, Net Periodic Benefit Cost (Credit), Gain (Loss) Due to Curtailment',			
    'Equity Method Investment, Realized Gain (Loss) on Disposal',
    'Earnings Per Share, Basic and Diluted',	
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Net Income (Loss) Available to Common Stockholders, Basic'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10k.loc['Net Income (Loss) Attributable to Parent', '2024-12-31'] = 1125
df_income_statement_10k.loc['Net Income (Loss) Attributable to Parent', '2023-12-31'] = -202
df_income_statement_10k.loc['Net Income (Loss) Attributable to Parent', '2022-12-31'] = 1221000
df_income_statement_10k.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-12-31'] = 228000

# Renomeando as linhas do índice que estão sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization': 'Cost of Revenue',
})


# Juntando os dfs 
df_income_statement_10k_final = pd.concat([df_income_statement_10k, income_statement_20_19_18_17], axis=1)

# Substituindo os NaN por 0
df_income_statement_10k_final = df_income_statement_10k_final.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k_final = df_income_statement_10k_final.drop([
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Related Party Transaction, Other Revenues from Transactions with Related Party',
    'Earnings Per Share, Basic and Diluted',
    'Common Stock, Dividends, Per Share, Declared',
    'Preferred Stock Dividends, Income Statement Impact',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
    'Net Income (Loss) Available to Common Stockholders, Basic'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k_final = df_income_statement_10k_final.rename(index={
    'nrg_BusinessCombinationAcquisitionAndIntegrationCosts': 'Business Combination Acquisition And Integration Costs',
})

# Arrumando a escala das linhas 'Weighted Average Number of Shares Outstanding, Basic' e 'Weighted Average Number of Shares Outstanding, Diluted'
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2017-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2017-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2018-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2018-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2019-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2019-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2020-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2020-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2021-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2021-12-31']/1000000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-12-31']/1000000, 2)

df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2017-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2017-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2018-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2018-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2019-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2019-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2020-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2020-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-12-31']/1000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2021-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2021-12-31']/1000000, 2)
df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-12-31'] = round(df_income_statement_10k_final.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-12-31']/1000000, 2)

# Calculando o 'Gross Profit'
df_income_statement_10k_final.loc['Gross Profit'] = df_income_statement_10k_final.loc['Revenues'] - df_income_statement_10k_final.loc['Cost of Revenue']

df_income_statement_10k_final

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_nrg['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Depreciation, Amortization and Accretion, Net' na coluna abaixo está zerada
# As informações estão na linha 'Depreciation, Depletion and Amortization'
df_cash_flow_10k.loc['Depreciation, Amortization and Accretion, Net', '2017-12-31'] = df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2017-12-31'] 

# A linha 'nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs' nas colunas abaixo estão zeradas
# As informações estão na linha 'nrg_AmortizationOfIntangiblesAndOutOfMarketContracts'
df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs', '2021-12-31'] = df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesAndOutOfMarketContracts', '2021-12-31'] 
df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs', '2020-12-31'] = df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesAndOutOfMarketContracts', '2020-12-31'] 
df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs', '2019-12-31'] = df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesAndOutOfMarketContracts', '2019-12-31'] 
df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs', '2018-12-31'] = df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesAndOutOfMarketContracts', '2018-12-31'] 
df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs', '2017-12-31'] = df_cash_flow_10k.loc['nrg_AmortizationOfIntangiblesAndOutOfMarketContracts', '2017-12-31'] 

# A linha 'Increase (Decrease) in Derivative Assets and Liabilities' nas colunas abaixo estão zeradas
# As informações estão na linha 'nrg_ChangesInDerivatives'
df_cash_flow_10k.loc['Increase (Decrease) in Derivative Assets and Liabilities', '2021-12-31'] = df_cash_flow_10k.loc['nrg_ChangesInDerivatives', '2021-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Derivative Assets and Liabilities', '2020-12-31'] = df_cash_flow_10k.loc['nrg_ChangesInDerivatives', '2020-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Derivative Assets and Liabilities', '2019-12-31'] = df_cash_flow_10k.loc['nrg_ChangesInDerivatives', '2019-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Derivative Assets and Liabilities', '2018-12-31'] = df_cash_flow_10k.loc['nrg_ChangesInDerivatives', '2018-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Derivative Assets and Liabilities', '2017-12-31'] = df_cash_flow_10k.loc['nrg_ChangesInDerivatives', '2017-12-31'] 

# A linha 'Payments for (Proceeds from) Derivative Instrument, Financing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from (Payments for) Other Financing Activities'
df_cash_flow_10k.loc['Payments for (Proceeds from) Derivative Instrument, Financing Activities', '2020-12-31'] = df_cash_flow_10k.loc['Proceeds from (Payments for) Other Financing Activities', '2020-12-31'] 
df_cash_flow_10k.loc['Payments for (Proceeds from) Derivative Instrument, Financing Activities', '2019-12-31'] = df_cash_flow_10k.loc['Proceeds from (Payments for) Other Financing Activities', '2019-12-31'] 
df_cash_flow_10k.loc['Payments for (Proceeds from) Derivative Instrument, Financing Activities', '2018-12-31'] = df_cash_flow_10k.loc['Proceeds from (Payments for) Other Financing Activities', '2018-12-31'] 
df_cash_flow_10k.loc['Payments for (Proceeds from) Derivative Instrument, Financing Activities', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from (Payments for) Other Financing Activities', '2017-12-31'] 

# A linha 'nrg_IncreaseDecreaseAccruedExpensesAndOtherCurrentLiabilitiesOperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'nrg_AccruedExpensesAndOtherCurrentLiabilitiesOperating'
df_cash_flow_10k.loc['nrg_IncreaseDecreaseAccruedExpensesAndOtherCurrentLiabilitiesOperating', '2019-12-31'] = df_cash_flow_10k.loc['nrg_AccruedExpensesAndOtherCurrentLiabilitiesOperating', '2019-12-31'] 
df_cash_flow_10k.loc['nrg_IncreaseDecreaseAccruedExpensesAndOtherCurrentLiabilitiesOperating', '2018-12-31'] = df_cash_flow_10k.loc['nrg_AccruedExpensesAndOtherCurrentLiabilitiesOperating', '2018-12-31'] 
df_cash_flow_10k.loc['nrg_IncreaseDecreaseAccruedExpensesAndOtherCurrentLiabilitiesOperating', '2017-12-31'] = df_cash_flow_10k.loc['nrg_AccruedExpensesAndOtherCurrentLiabilitiesOperating', '2017-12-31'] 

# A linha 'nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Businesses, Net of Cash Acquired'
df_cash_flow_10k.loc['nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired', '2019-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2019-12-31'] 
df_cash_flow_10k.loc['nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired', '2018-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2018-12-31'] 
df_cash_flow_10k.loc['nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired', '2017-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2017-12-31']

# A linha 'Proceeds from Issuance of Senior Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Proceeds from Other Debt' e 'Proceeds from Issuance of Long-term Debt'
df_cash_flow_10k.loc['Proceeds from Issuance of Senior Long-term Debt', '2019-12-31'] = df_cash_flow_10k.loc['Proceeds from Other Debt', '2019-12-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Senior Long-term Debt', '2018-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2018-12-31'] 
df_cash_flow_10k.loc['Proceeds from Issuance of Senior Long-term Debt', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2017-12-31']

# A linha 'nrg_AssetImpairmentChargesIncludingEquityMethodInvestments' nas colunas abaixo estão zeradas
# As informações estão na linha 'nrg_ImpairmentChargesAndAssetWriteDowns'
df_cash_flow_10k.loc['nrg_AssetImpairmentChargesIncludingEquityMethodInvestments', '2019-12-31'] = df_cash_flow_10k.loc['nrg_ImpairmentChargesAndAssetWriteDowns', '2019-12-31'] 
df_cash_flow_10k.loc['nrg_AssetImpairmentChargesIncludingEquityMethodInvestments', '2018-12-31'] = df_cash_flow_10k.loc['nrg_ImpairmentChargesAndAssetWriteDowns', '2018-12-31'] 
df_cash_flow_10k.loc['nrg_AssetImpairmentChargesIncludingEquityMethodInvestments', '2017-12-31'] = df_cash_flow_10k.loc['nrg_ImpairmentChargesAndAssetWriteDowns', '2017-12-31']

# A linha 'Proceeds from Sale of Other Productive Assets' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments for (Proceeds from) Productive Assets'
df_cash_flow_10k.loc['Proceeds from Sale of Other Productive Assets', '2018-12-31'] = df_cash_flow_10k.loc['Payments for (Proceeds from) Productive Assets', '2018-12-31'] 
df_cash_flow_10k.loc['Proceeds from Sale of Other Productive Assets', '2017-12-31'] = df_cash_flow_10k.loc['Payments for (Proceeds from) Productive Assets', '2017-12-31'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities'
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2018-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2018-12-31'] 
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2017-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2017-12-31'] 

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities'
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2018-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2018-12-31'] 
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-12-31'] 

# A linha 'Repayments of Other Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from (Repayments of) Debt'
df_cash_flow_10k.loc['Repayments of Other Debt', '2018-12-31'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Debt', '2018-12-31'] 
df_cash_flow_10k.loc['Repayments of Other Debt', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from (Repayments of) Debt', '2017-12-31'] 

# A linha 'Gain (Loss) on Disposition of Assets' nas colunas abaixo estão zeradas
# As informações estão na linha 'Gain (Loss) on Disposition of Other Assets'
df_cash_flow_10k.loc['Gain (Loss) on Disposition of Assets', '2018-12-31'] = df_cash_flow_10k.loc['Gain (Loss) on Disposition of Other Assets', '2018-12-31'] 
df_cash_flow_10k.loc['Gain (Loss) on Disposition of Assets', '2017-12-31'] = df_cash_flow_10k.loc['Gain (Loss) on Disposition of Other Assets', '2017-12-31'] 

# A linha 'nrg_ProceedsReceivedReceivableFromGovernmentGrant' na coluna abaixo está zerada
# As informações estão na linha 'nrg_GainLossOnStormSecuritization'
df_cash_flow_10k.loc['nrg_ProceedsReceivedReceivableFromGovernmentGrant', '2021-12-31'] = df_cash_flow_10k.loc['nrg_GainLossOnStormSecuritization', '2021-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'nrg_AmortizationOfIntangiblesAndOutOfMarketContracts',
    'nrg_ChangesInDerivatives',
    'Proceeds from (Payments for) Other Financing Activities',
    'Depreciation, Depletion and Amortization',
    'nrg_AccruedExpensesAndOtherCurrentLiabilitiesOperating',
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'Proceeds from Other Debt',
    'Proceeds from Issuance of Long-term Debt',
    'nrg_ImpairmentChargesAndAssetWriteDowns',
    'Payments for (Proceeds from) Productive Assets',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Sale of Available-for-sale Securities',
    'Proceeds from (Repayments of) Debt',
    'Gain (Loss) on Disposition of Other Assets',
    'nrg_GainLossOnStormSecuritization',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Payments of Distributions to Affiliates',
    'Payments for Repurchase of Redeemable Preferred Stock',
    'Defined Benefit Plan, Net Periodic Benefit Cost (Credit), Gain (Loss) Due to Curtailment',
    'nrg_Proceedsfromsaleofnoncontrollinginterestsinsubsidiaries',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Cash Provided by (Used in) Operating Activities, Discontinued Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',	
    'Cash Provided by (Used in) Investing Activities, Discontinued Operations',	
    'Net Cash Provided by (Used in) Financing Activities, Continuing Operations',	
    'Cash Provided by (Used in) Financing Activities, Discontinued Operations',
    'Net Cash Provided by (Used in) Discontinued Operations',
    'nrg_OilInventoryLowerOfCostOrMarketAdjustment',
    'Proceeds from Issuance of Preferred Stock and Preference Stock',
    'nrg_ProceedsFromRenewableEnergyGrants',
    'Gain (Loss) on Disposition of Intangible Assets',
    'Increase (Decrease) in Notes Receivables',
    'Payments to Acquire Intangible Assets',
    'nrg_PaymentsToSettleAcquiredDerivativesThatIncludeFinancingElements',
    'Deconsolidation, Gain (Loss), Amount',
    'Cash Divested from Deconsolidation',
    'Nondebtor Reorganization Items, Net (Gain) Loss on Settlement of Other Claims',
    'Proceeds from (Repayments of) Lines of Credit',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'nrg_ProceedsReceivedReceivableFromGovernmentGrant'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'nrg_AmortizationOfNuclearFuel': 'Amortization Of Nuclear Fuel',
    'nrg_GainsLossesOnExtinguishmentOfDebtNonCashPortion': 'Gains Losses On Extinguishment Of Debt Non Cash Portion',
    'nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs': 'Amortization Of Intangibles In The Money Contracts And Retirement Of RECs',
    'nrg_AssetImpairmentChargesIncludingEquityMethodInvestments': 'Asset Impairment Charges Including Equity Method Investments',
    'nrg_ChangesInCollateralDepositsSupportingEnergyRiskManagementActivities': 'Changes In Collateral Deposits Supporting Energy Risk Management Activities',
    'nrg_ChangesInNuclearDecommissioningTrustLiability': 'Changes In Nuclear Decommissioning Trust Liability',
    'nrg_IncreaseDecreaseAccruedExpensesAndOtherCurrentLiabilitiesOperating': 'Increase (Decrease) Accrued Expenses And Other Current Liabilities Operating',
    'nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired': 'Payments To Acquire Assets And Businesses Net Of Cash Acquired',
    'nrg_PaymentsForProceedsFromIntangibleAssets': 'Payments For Proceeds From Intangible Assets',
    'nrg_ProceedsFromInsuranceRecoveriesForPropertyPlantAndEquipmentNet': 'Proceeds From Insurance Recoveries For Property Plant And Equipment Net',
    'nrg_InvestmentsInProceedsFromSalesOfUnconsolidatedAffiliates': 'Investments In Proceeds From Sales Of Unconsolidated Affiliates',
    'nrg_NetContributionsToDistributionsFromDiscontinuedOperations': 'Net Contributions To Distributions From Discontinued Operations',
})

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2023-12-31'] = -22

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest": 'Total Shareholders Equity',
})

df_income_statement_10k_final = df_income_statement_10k_final.rename(index={
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k_final.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping NRG 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_nrg = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_nrg.index = pd.to_datetime(df_lst_acc_num_10q_nrg.index, format='%Y-%m-%d')

df_lst_acc_num_10q_nrg

In [ ]:
# Selecionando os 'acc_num' dos 10-Q a partir de '2020-03-31'
df_lst_acc_num_10q_nrg_sliced = df_lst_acc_num_10q_nrg.loc['2020-03-31':]
df_lst_acc_num_10q_nrg_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_nrg_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Long-term Debt and Lease Obligation, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt, Current Maturities'
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2020-09-30'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2020-09-30'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2020-06-30'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2020-06-30'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation, Current', '2020-03-31'] = df_balance_sheet_10q.loc['Long-term Debt, Current Maturities', '2020-03-31'] 

# A linha 'Long-term Debt and Lease Obligation' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt, Excluding Current Maturities'
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2020-09-30'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-09-30'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2020-06-30'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-06-30'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2020-03-31'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2020-03-31'] 

# # Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop('Long-term Debt, Current Maturities')
df_balance_sheet_10q = df_balance_sheet_10q.drop('Long-term Debt, Excluding Current Maturities')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Common Stock, Shares Authorized',
    'Common Stock, Par or Stated Value Per Share',
    'Disposal Group, Including Discontinued Operation, Liabilities, Noncurrent',
    'Treasury Stock, Common, Shares',
    'nrg_ReceivableFromGovernmentGrant',
    'Redeemable Noncontrolling Interest, Equity, Other, Carrying Amount',
    'Disposal Group, Including Discontinued Operation, Assets, Noncurrent',
    'Disposal Group, Including Discontinued Operation, Liabilities, Current',
    'Disposal Group, Including Discontinued Operation, Assets, Current'
])

# Renomeando algumas linhas do índice
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'nrg_FundsDepositedByCounterparties': 'Funds Deposited By Counterparties',
    'nrg_NuclearDecommissioningTrustFundLiabilityNoncurrent': 'Nuclear Decommissioning Trust Fund Liability Noncurrent',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_nrg_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# As linhas 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-03-31'] = df_income_statement_10q.loc['Interest Expense', '2024-03-31']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-09-30'] = df_income_statement_10q.loc['Interest Expense', '2023-09-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-06-30'] = df_income_statement_10q.loc['Interest Expense', '2023-06-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-03-31'] = df_income_statement_10q.loc['Interest Expense', '2023-03-31']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-09-30'] = df_income_statement_10q.loc['Interest Expense', '2022-09-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-06-30'] = df_income_statement_10q.loc['Interest Expense', '2022-06-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-03-31'] = df_income_statement_10q.loc['Interest Expense', '2022-03-31']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-09-30'] = df_income_statement_10q.loc['Interest Expense', '2021-09-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-06-30'] = df_income_statement_10q.loc['Interest Expense', '2021-06-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-03-31'] = df_income_statement_10q.loc['Interest Expense', '2021-03-31']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-09-30'] = df_income_statement_10q.loc['Interest Expense', '2020-09-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-06-30'] = df_income_statement_10q.loc['Interest Expense', '2020-06-30']
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-03-31'] = df_income_statement_10q.loc['Interest Expense', '2020-03-31']

# A linha 'Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cost of Revenue'
df_income_statement_10q.loc['Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization', '2021-06-30'] = df_income_statement_10q.loc['Cost of Revenue', '2021-06-30'] 
df_income_statement_10q.loc['Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization', '2021-03-31'] = df_income_statement_10q.loc['Cost of Revenue', '2021-03-31'] 
df_income_statement_10q.loc['Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization', '2020-09-30'] = df_income_statement_10q.loc['Cost of Revenue', '2020-09-30'] 
df_income_statement_10q.loc['Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization', '2020-06-30'] = df_income_statement_10q.loc['Cost of Revenue', '2020-06-30'] 
df_income_statement_10q.loc['Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization', '2020-03-31'] = df_income_statement_10q.loc['Cost of Revenue', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Cost of Revenue',
    'Interest Expense'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_RevenuesAbstract',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Diluted Share',
    'Discontinued Operation, Income (Loss) from Discontinued Operation, Net of Tax, Per Basic Share',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
    'Income (Loss) from Continuing Operations, Per Basic Share',
    'Income (Loss) from Continuing Operations, Per Diluted Share',
    'Net Income (Loss) Attributable to Noncontrolling Interest',
    'Other than Temporary Impairment Losses, Investments',
    'Restructuring Costs',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest'
])

# Arrumando e adicionando alguns números no df
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2021-03-31'] = -82
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2021-06-30'] = 1078
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2021-09-30'] = 1618
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2022-03-31'] = 1736
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2022-06-30'] = 513
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2022-09-30'] = 67
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2023-03-31'] = -1335
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2023-06-30'] = 308
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2023-09-30'] = 343
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2024-03-31'] = 511
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2024-06-30'] = 738
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2024-09-30'] = -767
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2025-03-31'] = 750
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2025-06-30'] = -104
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2025-09-30'] = 152
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2026-03-31'] = 125
df_income_statement_10q.loc['Net Income (Loss) Attributable to Parent', '2026-06-30'] = 506

df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-03-31'] = 242
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-06-30'] = 237
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2022-09-30'] = 235
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-03-31'] = 230

df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2022-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-03-31'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2023-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-03-31'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2024-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-03-31'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2025-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Basic', '2026-03-31'] / 1000, 0)

df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2023-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-03-31'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2024-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-03-31'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-06-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-06-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-09-30'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2025-09-30'] / 1000, 0)
df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-03-31'] = round(df_income_statement_10q.loc['Weighted Average Number of Shares Outstanding, Diluted', '2026-03-31'] / 1000, 0)

# Renomeando algumas linhas do índice
df_income_statement_10q = df_income_statement_10q.rename(index={
    'nrg_BusinessCombinationAcquisitionAndIntegrationCosts': 'Business Combination Acquisition And Integration Costs',
})

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_nrg_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Payments to Acquire Other Productive Assets' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Payments to Acquire Businesses, Net of Cash Acquired' e 'nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired'
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2024-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2024-09-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2024-06-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2024-06-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2024-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2024-03-31']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2023-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2023-09-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2023-06-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2023-06-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2023-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2023-03-31']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2022-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2022-09-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2022-06-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2022-06-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2022-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2022-03-31']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2021-09-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2021-09-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2021-06-30'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2021-06-30']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2021-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2021-03-31']
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets','2020-09-30'] = df_cash_flow_10q.loc['nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired', '2020-09-30']

# A linha 'nrg_GainLossOnSaleAndDispositionOfAssets' nas colunas abaixo estão zeradas
# As informações estão na linha 'Gain (Loss) on Disposition of Assets'
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2024-09-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2024-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2024-06-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2024-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2024-03-31'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2024-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2023-09-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2023-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2023-06-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2023-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2023-03-31'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2023-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2022-09-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2022-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2022-06-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2022-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2022-03-31'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2022-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2021-09-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2021-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2021-06-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2021-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2021-03-31'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2021-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2020-09-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2020-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2020-06-30'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2020-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnSaleAndDispositionOfAssets', '2020-03-31'] = df_cash_flow_10q.loc['Gain (Loss) on Disposition of Assets', '2020-03-31']

# A linha 'Payments of Ordinary Dividends' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Payments of Ordinary Dividends, Common Stock' e 'Payments of Ordinary Dividends, Preferred Stock and Preference Stock'
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2023-06-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2023-06-30']   
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2023-03-31'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2023-03-31']   
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2022-09-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2022-09-30']  
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2022-06-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2022-06-30']  
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2022-03-31'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2022-03-31']    
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2021-09-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2021-09-30']   
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2021-06-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2021-06-30']   
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2021-03-31'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Common Stock','2021-03-31']  
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2020-09-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Preferred Stock and Preference Stock','2020-09-30']   
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2020-06-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Preferred Stock and Preference Stock','2020-06-30']   
df_cash_flow_10q.loc['Payments of Ordinary Dividends','2020-03-31'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends, Preferred Stock and Preference Stock','2020-03-31']    
  
# A linha 'nrg_GainLossOnAccretionOfAssetRetirementObligations' nas colunas abaixo estão zeradas
# As informações estão na linha 'Accretion Expense, Including Asset Retirement Obligations'
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2024-09-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2024-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2024-06-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2024-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2024-03-31'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2024-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2023-09-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2023-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2023-06-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2023-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2023-03-31'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2023-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2022-09-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2022-09-30'] 
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2022-03-31'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2022-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2021-09-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2021-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2021-06-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2021-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2021-03-31'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2021-03-31']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2020-09-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2020-09-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2020-06-30'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2020-06-30']
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2020-03-31'] = df_cash_flow_10q.loc['Accretion Expense, Including Asset Retirement Obligations', '2020-03-31']

# A linha 'Payments for Repurchase of Common Stock' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments for Repurchase of Preferred Stock and Preference Stock'
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2020-09-30'] = df_cash_flow_10q.loc['Payments for Repurchase of Preferred Stock and Preference Stock', '2020-09-30']
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2020-06-30'] = df_cash_flow_10q.loc['Payments for Repurchase of Preferred Stock and Preference Stock', '2020-06-30']
df_cash_flow_10q.loc['Payments for Repurchase of Common Stock', '2020-03-31'] = df_cash_flow_10q.loc['Payments for Repurchase of Preferred Stock and Preference Stock', '2020-03-31']

# A linha 'Proceeds from Long-term Lines of Credit' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Lines of Credit'
df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2021-03-31'] = df_cash_flow_10q.loc['Proceeds from Lines of Credit', '2021-03-31']
df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2020-03-31'] = df_cash_flow_10q.loc['Proceeds from Lines of Credit', '2020-03-31']

# A linha 'Repayments of Long-term Lines of Credit' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Lines of Credit'
df_cash_flow_10q.loc['Repayments of Long-term Lines of Credit', '2020-09-30'] = df_cash_flow_10q.loc['Repayments of Lines of Credit', '2020-09-30']
df_cash_flow_10q.loc['Repayments of Long-term Lines of Credit', '2020-06-30'] = df_cash_flow_10q.loc['Repayments of Lines of Credit', '2020-06-30']

# A linha 'Payments to Acquire Other Productive Assets' na coluna abaixo está zerada
# As informações estão na linha 'nrg_PaymentsToAcquireBusinessesAndAssetAcquisitionsNet'
df_cash_flow_10q.loc['Payments to Acquire Other Productive Assets', '2025-06-30'] = df_cash_flow_10q.loc['nrg_PaymentsToAcquireBusinessesAndAssetAcquisitionsNet', '2025-06-30']

# A linha 'nrg_GainLossOnAccretionOfAssetRetirementObligations' na coluna abaixo está zerada
# As informações estão na linha 'Asset Retirement Obligation, Accretion Expense'
df_cash_flow_10q.loc['nrg_GainLossOnAccretionOfAssetRetirementObligations', '2025-06-30'] = df_cash_flow_10q.loc['Asset Retirement Obligation, Accretion Expense', '2025-06-30']

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'nrg_PaymentsToAcquireAssetsAndBusinessesNetOfCashAcquired',
    'Gain (Loss) on Disposition of Assets',
    'Payments of Ordinary Dividends, Common Stock',
    'Payments of Ordinary Dividends, Preferred Stock and Preference Stock',
    'Accretion Expense, Including Asset Retirement Obligations',
    'Payments for Repurchase of Preferred Stock and Preference Stock',
    'Proceeds from Lines of Credit',
    'Repayments of Lines of Credit',
    'nrg_PaymentsToAcquireBusinessesAndAssetAcquisitionsNet',
    'Asset Retirement Obligation, Accretion Expense'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Inventory Write-down',
    'Income (Loss) from Discontinued Operations, Net of Tax, Attributable to Parent',
    'Cash Provided by (Used in) Operating Activities, Discontinued Operations',
    'Proceeds from Collection of Notes Receivable',
    'nrg_NetContributionsToDistributionsFromDiscontinuedOperations',
    'Cash Provided by (Used in) Investing Activities, Discontinued Operations',
    'Cash Provided by (Used in) Financing Activities, Discontinued Operations',
    'Net Cash Provided by (Used in) Discontinued Operations',
    'Payments for (Proceeds from) Other Investing Activities',
    'Income (Loss) from Continuing Operations, Net of Tax, Including Portion Attributable to Noncontrolling Interest',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'nrg_ProceedsFromSaleOfAssetsAndSaleOfDiscontinuedOperationsNet',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Financing Activities, Continuing Operations',
    'nrg_ProceedsFromGovernmentGrant'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2023-03-31'] = 1050
df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2023-06-30'] = 1870
df_cash_flow_10q.loc['Proceeds from Long-term Lines of Credit', '2023-09-30'] = 3020

df_cash_flow_10q.loc['Payments of Debt Issuance Costs', '2020-06-30'] = -1
df_cash_flow_10q.loc['Payments of Debt Issuance Costs', '2020-09-30'] = -24

df_cash_flow_10q.loc['Repayments of Long-term Lines of Credit', '2023-03-31'] = -825
df_cash_flow_10q.loc['Repayments of Long-term Lines of Credit', '2023-06-30'] = -1670
df_cash_flow_10q.loc['Repayments of Long-term Lines of Credit', '2023-09-30'] = -3020

# Renomeando algumas linhas do índice
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'nrg_AmortizationOfIntangiblesInTheMoneyContractsAndRetirementOfRECs': 'Amortization Of Intangibles In The Money Contracts And Retirement Of RECs',
    'nrg_GainLossOnSaleAndDispositionOfAssets': 'Gain (Loss) On Sale And Disposition Of Assets',
    'nrg_ChangesInCollateralDepositsSupportingEnergyRiskManagementActivities': 'Changes In Collateral Deposits Supporting Energy Risk Management Activities',
    'nrg_PaymentsForProceedsFromIntangibleAssets': 'Payments For Proceeds From Intangible Assets',
    'nrg_ProceedsFromInsuranceRecoveryPropertyPlantAndEquipmentNet': 'Proceeds From Insurance Recovery Property Plant And Equipment, Net',
    'nrg_AssetImpairmentChargesIncludingEquityMethodInvestments': 'Asset Impairment Charges Including Equity Method Investments',
    'nrg_ChangesInNuclearDecommissioningTrustLiability': 'Changes In Nuclear Decommissioning Trust Liability',
    'nrg_GainsLossesOnExtinguishmentOfDebtNonCashPortion': 'Gains (Losses) On Extinguishment Of Debt Non Cash Portion',
    'nrg_InvestmentsInProceedsFromSalesOfUnconsolidatedAffiliates': 'Investments In Proceeds From Sales Of Unconsolidated Affiliates',
    'nrg_AmortizationOfIntangiblesAndOutOfMarketContracts': 'Amortization Of Intangibles And Out Of Market Contracts',
    'nrg_ProceedsFromSaleOfAssetsAndSaleOfDiscontinuedOperationsNet': 'Proceeds From Sale Of Assets And Sale Of Discontinued Operations, Net',
    'nrg_NetContributionsToDistributionsFromDiscontinuedOperations': 'Net Contributions To Distributions From Discontinued Operations',
    'nrg_GainLossOnAccretionOfAssetRetirementObligations': 'Gain (Loss) On Accretion Of Asset Retirement Obligations',
    'nrg_AssetRetirementObligationAccretionExpenseNet': 'Asset Retirement Obligation Accretion Expense Net',

})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity, Including Portion Attributable to Noncontrolling Interest": 'Total Shareholders Equity',
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Cost of Goods and Service, Excluding Depreciation, Depletion, and Amortization': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'InterestExpenseNonoperating': 'Interest Expense',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation, Amortization and Accretion, Net': 'Depreciation, Depletion and Amortization',
    'Payments of Ordinary Dividends': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [183]:
# Lendo os arquivos 10k
nrg_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

nrg_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

nrg_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
nrg_bs.columns = pd.to_datetime(nrg_bs.columns)
nrg_is.columns = pd.to_datetime(nrg_is.columns)
nrg_cf.columns = pd.to_datetime(nrg_cf.columns)

# Transformando as colunas em apenas o ano
nrg_bs.columns = nrg_bs.columns.year
nrg_is.columns = nrg_is.columns.year
nrg_cf.columns = nrg_cf.columns.year

In [184]:
# Preços da NRG
nrg_close = yf.download('NRG', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025'
]

last_dec_close = []

for year in lst_years:
    last_close = nrg_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
nrg_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nrg_close_dec = nrg_close_dec.reindex(index=nrg_close_dec.index[::-1])

# Arredondamento de duas casas decimais
nrg_close_dec = round(nrg_close_dec, 2)

# Não realizou split recentemente (https://br.investing.com/equities/nrg-energy-inc-historical-data-splits)

# Transformando o index em int
nrg_close_dec.index = nrg_close_dec.index.astype(int)

nrg_close_dec

[*********************100%***********************]  1 of 1 completed

2025    157.70
2024     88.15
2023     49.36
2022     29.14
2021     38.08
2020     32.12
2019     32.83
2018     32.60
2017     23.36
dtype: float64

In [185]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = nrg_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=nrg_close_dec, df_is=nrg_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=nrg_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=nrg_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=nrg_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=nrg_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=nrg_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=nrg_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=nrg_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=nrg_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=nrg_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=nrg_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=nrg_bs, df_is=nrg_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=nrg_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Restricted Cash and Cash Equivalents, Current'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=nrg_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current', 
    'Operating Lease, Liability, Current', 
    'Long-term Debt and Lease Obligation', 
    'Operating Lease, Liability, Noncurrent'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=nrg_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=nrg_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=nrg_is, df_bs=nrg_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=nrg_is, df_bs=nrg_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=nrg_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=nrg_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=nrg_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments To Acquire Assets And Businesses Net Of Cash Acquired', 
    'Payments to Acquire Property, Plant, and Equipment'
]

capex = f_eua.indicador_capex(ten_k=True, df_cf=nrg_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=nrg_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=nrg_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=nrg_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=nrg_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Accounts Receivable', 
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) Accrued Expenses And Other Current Liabilities Operating',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=nrg_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=nrg_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Senior Long-term Debt', 
    'Proceeds from Long-term Lines of Credit'
]

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nrg_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Other Debt', 
    'Payment for Debt Extinguishment or Debt Prepayment Cost', 
    'Repayments of Long-term Lines of Credit'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nrg_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=nrg_is, idx=idx)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=nrg_is,
    idx=idx
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=nrg_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=nrg_cf, df_is=nrg_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=nrg_cf, df_is=nrg_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=nrg_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=nrg_bs, df_is=nrg_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=nrg_bs, df_is=nrg_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=nrg_bs, df_is=nrg_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=nrg_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=nrg_bs, df_is=nrg_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=nrg_is, df_bs=nrg_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=nrg_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10q,
    fcff_10q,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
nrg_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
nrg_indicadores_10k.columns = nomes_col
nrg_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,inf,0.00,0.00,2741.0,0.00,19.38,6.01,8.92,15770.00,3.075150e+10,...,1311,48.309348,6.795566,41.775776,inf,0.132354,-0.071969,0.697920,inf,1.945312
2024,16.14,16.14,6.19,3495.0,4.00,21.44,8.62,12.42,7.33,1.815890e+07,...,935,45.258443,7.894570,41.504299,2.049778,0.123996,-0.047183,0.659800,1.596444,0.476190
2023,-55.71,0.00,-1.80,1511.0,-0.70,7.97,1.33,5.24,3.87,1.125408e+07,...,1172,44.854110,8.352371,31.992196,1.094059,0.122888,0.000689,-0.146261,16.544554,2.769299
2022,0.01,0.01,17754.74,2652.0,3870.91,12.99,6.40,8.41,1.80,6.877040e+06,...,606,55.230796,9.987430,48.447679,0.000295,0.151317,46.653417,0.135747,-0.000057,0.676656
2021,4.27,4.26,23.45,4126.0,8.10,24.11,12.38,15.29,2.59,9.329600e+06,...,48,43.885472,8.874622,40.523875,0.225423,0.120234,0.088961,0.119486,-1.524920,4.876433
2020,15.43,15.44,6.48,1540.0,5.61,28.08,12.15,16.94,4.68,7.869400e+06,...,229,36.287254,18.250000,36.220948,3.601961,0.099417,-0.096745,1.192857,2.594118,1.181609
2019,1.94,1.94,51.60,1663.0,45.19,25.64,13.14,16.93,5.19,8.601460e+06,...,1440,38.094390,19.142133,36.085170,0.318387,0.104368,0.261238,0.849669,0.187021,1.563003
2018,36.98,37.05,2.70,1441.0,2.83,25.01,10.36,15.20,0.00,9.910400e+06,...,1250,39.241929,21.156443,44.264209,5.138060,0.107512,-0.065339,0.955586,2.783582,1.374728
2017,-3.44,0.00,-29.07,469.0,-20.26,29.10,-5.52,4.41,3.76,7.405120e+06,...,0,37.052874,25.766985,42.670515,-0.644217,0.101515,NaN,2.957356,-0.109150,1.090909

In [186]:
# Lendo os arquivos 10q
nrg_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10q.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

nrg_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10q.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

nrg_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_10q.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
nrg_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in nrg_bs_10q.columns]
nrg_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in nrg_is_10q.columns]
nrg_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in nrg_cf_10q.columns]

In [187]:
# Preços da NRG
nrg_close = yf.download('NRG', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025'
]

lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = nrg_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
nrg_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nrg_close_months = nrg_close_months.reindex(index=nrg_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = nrg_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
nrg_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nrg_close_months_atual = nrg_close_months_atual.reindex(index=nrg_close_months_atual.index[::-1])

# Juntando as duas series pandas
nrg_close_months = pd.concat([nrg_close_months_atual, nrg_close_months])

# Arredondamento de duas casas decimais
nrg_close_months = round(nrg_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/nrg-energy-inc-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
nrg_close_months.index = nrg_bs_10q.columns[:-3]

nrg_close_months

[*********************100%***********************]  1 of 1 completed

2026-06-30    145.54
2026-03-31    145.18
2025-09-30    159.97
2025-06-30    158.20
2025-03-31     93.67
2024-09-30     88.61
2024-06-30     75.32
2024-03-31     65.12
2023-09-30     36.45
2023-06-30     35.02
2023-03-31     31.76
2022-09-30     34.78
2022-06-30     34.36
2022-03-31     34.21
2021-09-30     35.80
2021-06-30     35.06
2021-03-31     32.53
dtype: float64

In [188]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = nrg_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=nrg_close_months, df_is=nrg_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=nrg_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=nrg_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=nrg_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=nrg_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=nrg_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=nrg_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=nrg_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=nrg_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=nrg_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=nrg_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=nrg_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=nrg_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=nrg_bs_10q, df_is=nrg_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=nrg_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Restricted Cash and Cash Equivalents, Current'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=nrg_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Debt and Lease Obligation, Current', 
    'Long-term Debt and Lease Obligation', 
    'Operating Lease, Liability, Current',
    'Operating Lease, Liability, Noncurrent'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=nrg_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=nrg_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=nrg_is_10q, df_bs=nrg_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=nrg_is_10q, df_bs=nrg_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = [
    'Payments to Acquire Other Productive Assets', 
    'Payments to Acquire Property, Plant, and Equipment'
]

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=nrg_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=nrg_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=nrg_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=nrg_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=nrg_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Derivative Assets and Liabilities',
    'Increase (Decrease) in Income Taxes',
    'Changes In Collateral Deposits Supporting Energy Risk Management Activities',
    'Increase (Decrease) in Other Operating Assets and Liabilities, Net'
]


change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=nrg_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=nrg_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=nrg_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=nrg_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = [
    'Proceeds from Issuance of Debt', 
    'Proceeds from Long-term Lines of Credit', 
    'Proceeds from (Repayments of) Lines of Credit'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = [
    'Payments of Debt Issuance Costs', 
    'Repayments of Other Debt', 
    'Payment for Debt Extinguishment or Debt Prepayment Cost',
    'Repayments of Long-term Lines of Credit'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nrg_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=nrg_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=nrg_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=nrg_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=nrg_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=nrg_cf_10q, df_is=nrg_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=nrg_cf_10q, df_is=nrg_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=nrg_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=nrg_bs_10q, df_is=nrg_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=nrg_bs_10q, df_is=nrg_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=nrg_bs_10q, df_is=nrg_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=nrg_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=nrg_bs_10q, df_is=nrg_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=nrg_is_10q, df_bs=nrg_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=nrg_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_sliced,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
nrg_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
nrg_indicadores_10q.columns = nomes_col
nrg_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,60.69,44.64,2.24,1301.0,2769.0,6.76,26.88,13.05,17.39,6.33,...,450.0,172.424810,52.914991,172.090494,2.207510,0.472397,-0.019085,0.858570,1.217391,1.040000
2026-03-31,240.42,31.22,3.20,605.0,2820.0,1.22,13.63,3.20,5.90,6.16,...,481.0,134.419364,27.401784,102.396139,-1.352000,0.368272,0.009040,-0.279339,3.640000,1.144404
2025-09-30,203.12,470.50,0.21,637.0,1664.0,1.99,18.26,5.42,8.34,15.67,...,355.0,159.290111,26.434866,135.624900,3.184211,0.436411,-0.013922,0.759812,5.638158,-1.488789
2025-06-30,-298.15,51.03,1.96,226.0,2722.0,-1.54,16.48,0.00,3.35,13.56,...,289.0,185.261869,29.244093,164.960028,-4.336538,0.507567,-0.022267,1.995575,-9.461538,4.176991
2025-03-31,24.73,15.43,6.48,1352.0,3636.0,8.74,23.58,13.21,15.75,6.68,...,314.0,149.316249,20.750648,131.068435,1.140000,0.409086,-0.004167,0.632396,2.204000,1.087156
2024-09-30,-23.91,23.50,4.25,-551.0,3153.0,-10.62,-0.22,-11.24,-7.63,7.28,...,226.0,164.636578,27.227518,100.540130,-0.040417,0.451059,-0.030910,-0.056261,-1.861799,0.440613
2024-06-30,21.23,8.55,11.70,1695.0,4549.0,11.08,34.58,21.17,25.45,4.32,...,90.0,186.473945,52.202709,176.718320,1.430894,0.510888,-0.011616,0.623009,2.566396,0.396491
2024-03-31,26.63,0.00,-0.83,1140.0,1500.0,6.88,23.48,11.74,15.35,4.13,...,0.0,163.363171,37.302551,130.141601,0.522505,0.447570,0.008857,0.234211,-6.420744,0.339552
2023-09-30,24.44,0.00,-7.38,869.0,661.0,4.32,19.19,7.06,10.94,2.38,...,53.0,172.899572,35.812179,125.058402,1.650146,0.473697,-0.007414,0.651323,-14.562682,0.561688
2023-06-30,26.27,0.00,-5.77,845.0,703.0,4.85,21.83,8.35,13.31,2.43,...,8.0,188.249842,50.461507,154.988916,1.850649,0.515753,-0.008275,0.674556,-12.961039,0.596825
2023-03-31,-5.47,8.31,12.03,-1354.0,2466.0,-17.29,-13.68,-19.99,-17.53,2.37,...,8.0,166.334499,30.021645,96.884256,1.197004,0.455711,0.008889,1.180207,2.085393,13.863158
2022-09-30,121.99,2.14,46.64,301.0,6338.0,0.79,8.32,1.83,3.54,1.59,...,118.0,174.179201,36.116380,134.313638,-21.358209,0.477203,0.049761,-4.754153,42.343284,0.737931
2022-06-30,15.87,1.69,59.17,911.0,7647.0,7.04,19.16,10.35,12.51,1.54,...,178.0,193.577314,37.448616,181.848989,2.949318,0.530349,-0.035744,1.660812,10.818713,0.745223
2022-03-31,4.77,1.92,52.15,2608.0,6997.0,21.99,37.56,30.71,33.03,1.65,...,188.0,152.129559,26.208925,164.064909,0.965438,0.416793,0.002463,0.642638,-0.177419,0.469945
2021-09-30,5.42,3.06,32.65,2518.0,4881.0,24.48,44.14,35.09,38.10,2.15,...,0.0,170.985020,43.993770,194.462351,0.913473,0.468452,0.006967,0.586974,-0.946848,0.447236
2021-06-30,7.97,5.50,18.17,1610.0,2957.0,20.56,43.60,29.70,30.71,3.38,...,0.0,196.458135,45.054109,267.362191,1.200371,0.538241,-0.012722,0.803727,-2.307050,2.245283
2021-03-31,-97.19,13.22,7.56,261.0,1700.0,-1.01,15.16,-0.69,3.23,5.26,...,9.0,137.004697,16.803613,117.837995,11.182927,0.375355,0.052085,-3.513410,42.926829,11.182965

In [191]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//energia_eletrica//nrg//nrg_indicators.xlsx') as writer:
    nrg_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    nrg_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

# **Setor de Tecnologia**

## Amazon

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'amzn'
f_sec.cik_matching_ticker(ticker)

### Scraping Amazon 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_amzn = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017 e 2018
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000101872420000004', # 2019
            '000101872419000004', # 2018
            '000101872418000005', # 2017
        ]
    },
    index=pd.to_datetime([
        '2019-12-31',
        '2018-12-31',
        '2017-12-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_amzn = pd.concat([df_lst_acc_num_amzn, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_amzn.index = pd.to_datetime(df_lst_acc_num_amzn.index, format='%Y-%m-%d')

df_lst_acc_num_amzn

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_amzn['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Treasury Stock, Common, Value' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Value'
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2021-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2021-12-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2020-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2020-12-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2019-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2019-12-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2018-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2018-12-31'] 
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2017-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2017-12-31'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Property, Plant and Equipment, Net'
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2019-12-31'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2018-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2018-12-31'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2017-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2017-12-31'] 

# A linha 'Accrued Liabilities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'amzn_AccruedLiabilitiesAndOtherCurrent'
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2018-12-31'] = df_balance_sheet_10k.loc['amzn_AccruedLiabilitiesAndOtherCurrent', '2018-12-31'] 
df_balance_sheet_10k.loc['Accrued Liabilities, Current', '2017-12-31'] = df_balance_sheet_10k.loc['amzn_AccruedLiabilitiesAndOtherCurrent', '2017-12-31'] 

# A linha 'Contract with Customer, Liability, Current' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Revenue, Current'
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2017-12-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Current', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Treasury Stock, Value',
    'Property, Plant and Equipment, Net',
    'amzn_AccruedLiabilitiesAndOtherCurrent',
    'Deferred Revenue, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc['amzn_LeaseLiabilityNoncurrent', '2018-12-31'] = 9650

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'amzn_LeaseLiabilityNoncurrent': 'Lease Liability, Noncurrent'
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_amzn['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Interest Expense' 
df_income_statement_10k.loc['InterestExpenseNonoperating', '2023-12-31'] = df_income_statement_10k.loc['Interest Expense', '2023-12-31']
df_income_statement_10k.loc['InterestExpenseNonoperating', '2022-12-31'] = df_income_statement_10k.loc['Interest Expense', '2022-12-31']
df_income_statement_10k.loc['InterestExpenseNonoperating', '2021-12-31'] = df_income_statement_10k.loc['Interest Expense', '2021-12-31']
df_income_statement_10k.loc['InterestExpenseNonoperating', '2020-12-31'] = df_income_statement_10k.loc['Interest Expense', '2020-12-31']
df_income_statement_10k.loc['InterestExpenseNonoperating', '2019-12-31'] = df_income_statement_10k.loc['Interest Expense', '2019-12-31']
df_income_statement_10k.loc['InterestExpenseNonoperating', '2018-12-31'] = df_income_statement_10k.loc['Interest Expense', '2018-12-31']
df_income_statement_10k.loc['InterestExpenseNonoperating', '2017-12-31'] = df_income_statement_10k.loc['Interest Expense', '2017-12-31']

# A linha 'amzn_TechnologyAndInfrastructureExpense' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'amzn_TechnologyAndContentExpense' 
df_income_statement_10k.loc['amzn_TechnologyAndInfrastructureExpense', '2022-12-31'] = df_income_statement_10k.loc['amzn_TechnologyAndContentExpense', '2022-12-31']
df_income_statement_10k.loc['amzn_TechnologyAndInfrastructureExpense', '2021-12-31'] = df_income_statement_10k.loc['amzn_TechnologyAndContentExpense', '2021-12-31']
df_income_statement_10k.loc['amzn_TechnologyAndInfrastructureExpense', '2020-12-31'] = df_income_statement_10k.loc['amzn_TechnologyAndContentExpense', '2020-12-31']
df_income_statement_10k.loc['amzn_TechnologyAndInfrastructureExpense', '2019-12-31'] = df_income_statement_10k.loc['amzn_TechnologyAndContentExpense', '2019-12-31']
df_income_statement_10k.loc['amzn_TechnologyAndInfrastructureExpense', '2018-12-31'] = df_income_statement_10k.loc['amzn_TechnologyAndContentExpense', '2018-12-31']
df_income_statement_10k.loc['amzn_TechnologyAndInfrastructureExpense', '2017-12-31'] = df_income_statement_10k.loc['amzn_TechnologyAndContentExpense', '2017-12-31']

# A linha 'Other Operating Income (Expense), Net' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Other Cost and Expense, Operating' 
df_income_statement_10k.loc['Other Operating Income (Expense), Net', '2019-12-31'] = df_income_statement_10k.loc['Other Cost and Expense, Operating', '2019-12-31']
df_income_statement_10k.loc['Other Operating Income (Expense), Net', '2018-12-31'] = df_income_statement_10k.loc['Other Cost and Expense, Operating', '2018-12-31']
df_income_statement_10k.loc['Other Operating Income (Expense), Net', '2017-12-31'] = df_income_statement_10k.loc['Other Cost and Expense, Operating', '2017-12-31']

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' na coluna abaixo está zerada
# As informações estão nas linhas 'Revenue, Net (Deprecated 2018-01-31)' 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-31'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'amzn_TechnologyAndContentExpense',
    'Other Cost and Expense, Operating',
    'Revenue, Net (Deprecated 2018-01-31)',
    'Interest Expense'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_CostsAndExpensesAbstract',
    'us-gaap_IncomeStatementAbstract',
    'Sales Revenue, Goods, Net (Deprecated 2018-01-31)',
    'Sales Revenue, Services, Net (Deprecated 2018-01-31)'
])

# Renomeando a linha do índice que está sem formato 
df_income_statement_10k = df_income_statement_10k.rename(index={
    'amzn_FulfillmentExpense': 'Fulfillment Expense',
    'amzn_TechnologyAndInfrastructureExpense': 'Technology and Infrastructure Expense',
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
df_income_statement_10k.loc['Interest Expense'] = df_income_statement_10k.loc['Interest Expense'] * -1
df_income_statement_10k.loc['Income Tax Expense (Benefit)'] = df_income_statement_10k.loc['Income Tax Expense (Benefit)'] * -1

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10k.loc['Cost of Goods and Services Sold']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_amzn['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther' nas colunas abaixo estão zeradas
# As informações estão na linha 'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther'
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2022-12-31'] = df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther', '2022-12-31'] 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2021-12-31'] = df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther', '2021-12-31'] 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2020-12-31'] = df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther', '2020-12-31'] 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2019-12-31'] = df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther', '2019-12-31'] 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2018-12-31'] = df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther', '2018-12-31'] 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2017-12-31'] = df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther', '2017-12-31'] 

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations' nas colunas abaixo estão zeradas
# As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-12-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-12-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2019-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2019-12-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2018-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2018-12-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2017-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2017-12-31'] 

# A linha 'Repayments of Long-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Debt' 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2020-12-31'] = df_cash_flow_10k.loc['Repayments of Debt', '2020-12-31'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2019-12-31'] = df_cash_flow_10k.loc['Repayments of Debt', '2019-12-31'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2018-12-31'] = df_cash_flow_10k.loc['Repayments of Debt', '2018-12-31'] 
df_cash_flow_10k.loc['Repayments of Long-term Debt', '2017-12-31'] = df_cash_flow_10k.loc['Repayments of Debt', '2017-12-31'] 

# A linha 'amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives' nas colunas abaixo estão zeradas
# As informações estão na linha 'amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets'
df_cash_flow_10k.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2020-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2020-12-31'] 
df_cash_flow_10k.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2019-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2019-12-31'] 
df_cash_flow_10k.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2018-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2018-12-31'] 
df_cash_flow_10k.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2017-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2017-12-31'] 

# A linha 'Proceeds from Short-term Debt' nas colunas abaixo estão zeradas
# As informações estão na linha 'amzn_ProceedsFromShortTermDebtAndOtherFinancingActivities'
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2022-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromShortTermDebtAndOtherFinancingActivities', '2022-12-31'] 
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2021-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromShortTermDebtAndOtherFinancingActivities', '2021-12-31'] 
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2020-12-31'] = df_cash_flow_10k.loc['amzn_ProceedsFromShortTermDebtAndOtherFinancingActivities', '2020-12-31']

# A linha 'Repayments of Short-term Debt' nas colunas 'abaixo estão zeradas
# As informações estão na linha 'amzn_RepaymentsOfShortTermDebtAndOtherFinancingActivities'
df_cash_flow_10k.loc['Repayments of Short-term Debt', '2022-12-31'] = df_cash_flow_10k.loc['amzn_RepaymentsOfShortTermDebtAndOtherFinancingActivities', '2022-12-31'] 
df_cash_flow_10k.loc['Repayments of Short-term Debt', '2021-12-31'] = df_cash_flow_10k.loc['amzn_RepaymentsOfShortTermDebtAndOtherFinancingActivities', '2021-12-31'] 
df_cash_flow_10k.loc['Repayments of Short-term Debt', '2020-12-31'] = df_cash_flow_10k.loc['amzn_RepaymentsOfShortTermDebtAndOtherFinancingActivities', '2020-12-31'] 

# A linha 'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Businesses, Net of Cash Acquired' 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2019-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2019-12-31'] 
df_cash_flow_10k.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2018-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2018-12-31'] 

# A linha 'Finance Lease, Principal Payments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Repayments of Long-term Capital Lease Obligations' 
df_cash_flow_10k.loc['Finance Lease, Principal Payments', '2018-12-31'] = df_cash_flow_10k.loc['Repayments of Long-term Capital Lease Obligations', '2018-12-31'] 
df_cash_flow_10k.loc['Finance Lease, Principal Payments', '2017-12-31'] = df_cash_flow_10k.loc['Repayments of Long-term Capital Lease Obligations', '2017-12-31'] 

# A linha 'amzn_RepaymentsOfLongTermFinancingObligations' nas colunas abaixo estão zeradas
# As informações estão na linha 'amzn_RepaymentsOfLongTermFinanceLeaseObligations' 
df_cash_flow_10k.loc['amzn_RepaymentsOfLongTermFinancingObligations', '2018-12-31'] = df_cash_flow_10k.loc['amzn_RepaymentsOfLongTermFinanceLeaseObligations', '2018-12-31'] 
df_cash_flow_10k.loc['amzn_RepaymentsOfLongTermFinancingObligations', '2017-12-31'] = df_cash_flow_10k.loc['amzn_RepaymentsOfLongTermFinanceLeaseObligations', '2017-12-31'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' na coluna abaixo está zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-12-31'] 

# A linha 'Payments to Acquire Productive Assets' na coluna abaixo está zeradas
# As informações estão na linha 'Payments for (Proceeds from) Productive Assets'
df_cash_flow_10k.loc['Payments to Acquire Productive Assets', '2017-12-31'] = df_cash_flow_10k.loc['Payments for (Proceeds from) Productive Assets', '2017-12-31'] 

# A linha 'Increase (Decrease) in Contract with Customer, Liability' na coluna abaixo está zeradas
# As informações estão na linha 'Increase (Decrease) in Deferred Revenue'
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue', '2017-12-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndOther',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Repayments of Debt',
    'amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets',
    'amzn_ProceedsFromShortTermDebtAndOtherFinancingActivities',
    'amzn_RepaymentsOfShortTermDebtAndOtherFinancingActivities',
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'Repayments of Long-term Capital Lease Obligations',
    'amzn_RepaymentsOfLongTermFinanceLeaseObligations',
    'Cash and Cash Equivalents, at Carrying Value',
    'Payments for (Proceeds from) Productive Assets',
    'Increase (Decrease) in Deferred Revenue'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'amzn_InterestPaidOnCapitalLeaseObligations',
    'amzn_InterestPaidOnLongTermDebt',
    'Operating Lease, Payments',
    'Finance Lease, Interest Payment on Liability',
    'amzn_InterestPaidFinancingObligations',
    'Income Taxes Paid, Net',
    'Right-of-Use Asset Obtained in Exchange for Operating Lease Liability',
    'Lease Obligation Incurred',
    'Right-of-Use Asset Obtained in Exchange for Finance Lease Liability',
    'amzn_PropertyandEquipmentObtainedinExchangeforFinancingObligations',
    'amzn_InterestPaidOnCapitalAndFinanceLeaseObligations',
    'amzn_BuildToSuitLeaseObligationsIncurred',
    'Cash and Cash Equivalents, Period Increase (Decrease)'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Other Noncurrent Assets', '2022-12-31'] = -13275
df_cash_flow_10k.loc['Increase (Decrease) in Other Noncurrent Assets', '2021-12-31'] = -9018
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2019-12-31'] = 1402 
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2018-12-31'] = 886
df_cash_flow_10k.loc['Proceeds from Short-term Debt', '2017-12-31'] = 16228
df_cash_flow_10k.loc['Repayments of Short-term Debt', '2019-12-31'] = -1518
df_cash_flow_10k.loc['Repayments of Short-term Debt', '2018-12-31'] = -813

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives': 'Proceeds From Property Plant And Equipment Sales And Incentives',
    'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther': 'Payments To Acquire Businesses Net Of Cash Acquired And Payments To Acquire Nonmarketable Securities',
    'amzn_RepaymentsOfLongTermFinancingObligations': 'Repayments Of Long Term Financing Obligations',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Lease Liability, Noncurrent': 'Long-term Lease Liabilities',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Technology and Infrastructure Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments to Acquire Productive Assets': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# 'acc_num' entre 2019 e 2025
df_lst_acc_num_amzn_sorted = df_lst_acc_num_amzn.sort_index()
acc_num_list_amzn_sliced = df_lst_acc_num_amzn_sorted.loc['2019':'2025', 'acc_num']

# Fazendo o scraping do 'current portion of lease liabilities'
current_portion_lease_lst = []

for acc_num in acc_num_list_amzn_sliced:
    # Fazendo o scraping do 'current portion of lease liabilities' (10-K) -> 'Note 4 – Leases' 
    current_portion_lease_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='current_portion_lease')
    current_portion_lease_10k = f_sec.rename_statement(current_portion_lease_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    current_portion_lease_10k = current_portion_lease_10k.iloc[:, 0]
    current_portion_lease_lst.append(current_portion_lease_10k)

# Removendo duplicatas de índice em cada série
current_portion_lease_lst_clean = [df[~df.index.duplicated(keep='first')] for df in current_portion_lease_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_current_portion_lease_10k = pd.concat(current_portion_lease_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_current_portion_lease_10k = df_current_portion_lease_10k.drop('us-gaap_LeasesAbstract')

# Renomeando a linha do índice
df_current_portion_lease_10k = df_current_portion_lease_10k.rename(index={
    'amzn_LeaseLiabilityCurrent': 'Current Portion of Lease Liabilities',
})

# Formatando o número para ficar positivo
df_current_portion_lease_10k.loc['Current Portion of Lease Liabilities'] = df_current_portion_lease_10k.loc['Current Portion of Lease Liabilities'] * -1

# Selecionando a linha desejada
df_current_portion_lease_10k = df_current_portion_lease_10k.loc[['Current Portion of Lease Liabilities']]


################################################################################################################################################################
# Nos anos de 2018 e 2017, o 'current portion lease' está separado em dois ('current portion capital lease' e 'current portion finance lease')

# 'acc_num' de 2018
acc_num_2018 = '000101872419000004'

# Fazendo o scraping do 'current portion of capital lease' (10-K) -> 'Note 6 - other long-term liabilities' 
current_portion_capital_lease_10k_18_17 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2018, statement_name='current_portion_capital_lease')
current_portion_capital_lease_10k_18_17 = f_sec.rename_statement(current_portion_capital_lease_10k_18_17, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
current_portion_capital_lease_10k_18_17 = current_portion_capital_lease_10k_18_17.drop('us-gaap_OtherLiabilitiesDisclosureAbstract')
# Renomeando a linha do índice
current_portion_capital_lease_10k_18_17 = current_portion_capital_lease_10k_18_17.rename(index={
    'Capital Lease Obligations, Current': 'Current Portion of Capital Lease',
})
# Formatando o número para ficar positivo
current_portion_capital_lease_10k_18_17.loc['Current Portion of Capital Lease'] = current_portion_capital_lease_10k_18_17.loc['Current Portion of Capital Lease'] * -1
# Selecionando a linha desejada
current_portion_capital_lease_10k_18_17 = current_portion_capital_lease_10k_18_17.loc[['Current Portion of Capital Lease']]

# Fazendo o scraping do 'current portion of finance lease' (10-K) -> 'Note 6 - other long-term liabilities' 
current_portion_finance_lease_10k_18_17 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2018, statement_name='current_portion_finance_lease')
current_portion_finance_lease_10k_18_17 = f_sec.rename_statement(current_portion_finance_lease_10k_18_17, label_dictionary=labels_dict)
# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
current_portion_finance_lease_10k_18_17 = current_portion_finance_lease_10k_18_17.drop('us-gaap_OtherLiabilitiesDisclosureAbstract')
# Renomeando a linha do índice
current_portion_finance_lease_10k_18_17 = current_portion_finance_lease_10k_18_17.rename(index={
    'amzn_FinanceLeaseObligationsCurrent': 'Current Portion of Finance Lease',
})
# Formatando o número para ficar positivo
current_portion_finance_lease_10k_18_17.loc['Current Portion of Finance Lease'] = current_portion_finance_lease_10k_18_17.loc['Current Portion of Finance Lease'] * -1
# Selecionando a linha desejada
current_portion_finance_lease_10k_18_17 = current_portion_finance_lease_10k_18_17.loc[['Current Portion of Finance Lease']]

# Concatenando os dfs
current_portion_lease_10k_18_17 = pd.concat([current_portion_capital_lease_10k_18_17, current_portion_finance_lease_10k_18_17])
# Somando os itens ('current portion capital lease' e 'current portion finance lease') e criando um novo df
df_current_portion_lease_10k_18_17 = pd.DataFrame(current_portion_lease_10k_18_17.sum()).T
# Renomeando o index
df_current_portion_lease_10k_18_17 = df_current_portion_lease_10k_18_17.rename(index={0:'Current Portion of Lease Liabilities'})


################################################################################################################################################################
# Concatenando os dfs
df_current_portion_lease_10k = pd.concat([df_current_portion_lease_10k, df_current_portion_lease_10k_18_17], axis=1)

# Ordenando o df
df_current_portion_lease_10k = df_current_portion_lease_10k[sorted(df_current_portion_lease_10k.columns, reverse=True)]

df_current_portion_lease_10k

In [ ]:
# Fazendo o scraping do 'Current portion of long-term debt' (10-K)
current_portion_debt_lst = []

for acc_num in df_lst_acc_num_amzn['acc_num']:
    # Fazendo o scraping do 'Current portion of long-term debt' (10-K) -> # 'Note 6. Debt' 
    current_portion_debt_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='current_portion_debt')
    current_portion_debt_10k = f_sec.rename_statement(current_portion_debt_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    current_portion_debt_10k = current_portion_debt_10k.iloc[:, 0]
    current_portion_debt_lst.append(current_portion_debt_10k)

# Removendo duplicatas de índice em cada série
current_portion_debt_lst_clean = [df[~df.index.duplicated(keep='first')] for df in current_portion_debt_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_current_portion_debt_10k = pd.concat(current_portion_debt_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_current_portion_debt_10k = df_current_portion_debt_10k.drop('us-gaap_DebtInstrumentLineItems')

# Renomeando a linha do índice
df_current_portion_debt_10k = df_current_portion_debt_10k.rename(index={
    'Long-term Debt, Current Maturities': 'Current Portion of Long-term Debt',
})

# Formatando o número para ficar positivo
df_current_portion_debt_10k.loc['Current Portion of Long-term Debt'] = df_current_portion_debt_10k.loc['Current Portion of Long-term Debt'] * -1

# Arrumando a escala de algumas colunas
df_current_portion_debt_10k.loc[:, '2017-12-31'] = df_current_portion_debt_10k.loc[:, '2017-12-31'] / 1000000
df_current_portion_debt_10k.loc[:, '2020-12-31'] = df_current_portion_debt_10k.loc[:, '2020-12-31'] / 1000000
df_current_portion_debt_10k.loc[:, '2021-12-31'] = df_current_portion_debt_10k.loc[:, '2021-12-31'] / 1000000
df_current_portion_debt_10k.loc[:, '2022-12-31'] = df_current_portion_debt_10k.loc[:, '2022-12-31'] / 1000000

# Selecionando a linha desejada
df_current_portion_debt_10k = df_current_portion_debt_10k.loc[['Current Portion of Long-term Debt']]

df_current_portion_debt_10k

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')
    df_current_portion_lease_10k.to_excel(writer, sheet_name='current_portion_lease')
    df_current_portion_debt_10k.to_excel(writer, sheet_name='current_portion_debt')

### Scraping Amazon 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_amzn = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 1Q do ano de 2020
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000101872420000021', # 1Q 2020
            '000101872420000010', # 1Q 2020
        ]
    },
    index=pd.to_datetime([
        '2020-06-30',
        '2020-03-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_10q_amzn = pd.concat([df_lst_acc_num_10q_amzn, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_10q_amzn.index = pd.to_datetime(df_lst_acc_num_10q_amzn.index, format='%Y-%m-%d')

df_lst_acc_num_10q_amzn

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de '2020-03-31' p/ iteração
df_lst_acc_num_10q_amzn_sliced = df_lst_acc_num_10q_amzn.loc['2020-03-31':]
df_lst_acc_num_10q_amzn_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_amzn_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Treasury Stock, Common, Value' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Value' 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2022-06-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2022-06-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2022-03-31'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2022-03-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-09-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-09-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-06-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-06-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-03-31'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-03-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2020-09-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2020-09-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2020-06-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2020-06-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2020-03-31'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2020-03-31'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Property, Plant and Equipment, Net' 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-09-30'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-09-30'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-06-30'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-06-30'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-03-31'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-03-31'] 

# # Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Treasury Stock, Value',
    'Property, Plant and Equipment, Net'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'amzn_LeaseLiabilityNoncurrent': 'Lease Liability Noncurrent'
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_amzn_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'InterestExpenseNonoperating' nas colunas abaixo estao zeradas
# As informações estão na linha 'Interest Expense'
df_income_statement_10q.loc['InterestExpenseNonoperating', '2024-03-31'] = df_income_statement_10q.loc['Interest Expense', '2024-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-09-30'] = df_income_statement_10q.loc['Interest Expense', '2023-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-06-30'] = df_income_statement_10q.loc['Interest Expense', '2023-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2023-03-31'] = df_income_statement_10q.loc['Interest Expense', '2023-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-09-30'] = df_income_statement_10q.loc['Interest Expense', '2022-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-06-30'] = df_income_statement_10q.loc['Interest Expense', '2022-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2022-03-31'] = df_income_statement_10q.loc['Interest Expense', '2022-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-09-30'] = df_income_statement_10q.loc['Interest Expense', '2021-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-06-30'] = df_income_statement_10q.loc['Interest Expense', '2021-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2021-03-31'] = df_income_statement_10q.loc['Interest Expense', '2021-03-31'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-09-30'] = df_income_statement_10q.loc['Interest Expense', '2020-09-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-06-30'] = df_income_statement_10q.loc['Interest Expense', '2020-06-30'] 
df_income_statement_10q.loc['InterestExpenseNonoperating', '2020-03-31'] = df_income_statement_10q.loc['Interest Expense', '2020-03-31'] 

# A linha 'amzn_TechnologyAndInfrastructureExpense' nas colunas abaixo estao zeradas
# As informações estão na linha 'amzn_TechnologyAndContentExpense'
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2023-03-31'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2023-03-31'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2022-09-30'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2022-09-30'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2022-06-30'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2022-06-30'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2022-03-31'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2022-03-31'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2021-09-30'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2021-09-30'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2021-06-30'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2021-06-30'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2021-03-31'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2021-03-31'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2020-09-30'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2020-09-30'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2020-06-30'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2020-06-30'] 
df_income_statement_10q.loc['amzn_TechnologyAndInfrastructureExpense', '2020-03-31'] = df_income_statement_10q.loc['amzn_TechnologyAndContentExpense', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Interest Expense',
    'amzn_TechnologyAndContentExpense'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop('us-gaap_CostsAndExpensesAbstract')

# Renomeando a linha do índice que está sem formato 
df_income_statement_10q = df_income_statement_10q.rename(index={
    'amzn_FulfillmentExpense': 'Fulfillment Expense',
    'amzn_TechnologyAndInfrastructureExpense': 'Technology And Infrastructure Expense',
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
df_income_statement_10q.loc['Interest Expense'] = df_income_statement_10q.loc['Interest Expense'] * -1
df_income_statement_10q.loc['Income Tax Expense (Benefit)'] = df_income_statement_10q.loc['Income Tax Expense (Benefit)'] * -1

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10q.loc['Cost of Goods and Services Sold']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_amzn_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' e 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2022-03-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2022-03-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-09-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-09-30'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-06-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-06-30'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-03-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-03-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-09-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-09-30'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-06-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-06-30'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-03-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-03-31'] 

# A linha 'amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives' nas colunas abaixo estão zeradas
# As informações estão na linha 'amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets'
df_cash_flow_10q.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2021-03-31'] = df_cash_flow_10q.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2021-03-31'] 
df_cash_flow_10q.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2020-09-30'] = df_cash_flow_10q.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2020-09-30'] 
df_cash_flow_10q.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2020-06-30'] = df_cash_flow_10q.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2020-06-30'] 
df_cash_flow_10q.loc['amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives', '2020-03-31'] = df_cash_flow_10q.loc['amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets', '2020-03-31'] 

# A linha 'Payments to Acquire Businesses, Net of Cash Acquired' na coluna abaixo está zerada
# As informações estão na linha 'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther'
df_cash_flow_10q.loc['Payments to Acquire Businesses, Net of Cash Acquired', '2023-09-30'] = df_cash_flow_10q.loc['amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther', '2023-09-30'] 

# A linha 'Proceeds from Short-term Debt' na coluna abaixo está zerada
# As informações estão na linha 'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther'
df_cash_flow_10q.loc['Proceeds from Short-term Debt', '2020-03-31'] = df_cash_flow_10q.loc['Repayments of Debt', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'amzn_ProceedsFromRebatesOnPurchasesOfProductiveAssets',
    'amzn_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPaymentsToAcquireNonmarketableSecuritiesAndOther',
    'Repayments of Debt'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_StatementOfCashFlowsAbstract',
    'amzn_InterestPaidOnLongTermDebt',
    'Operating Lease, Payments',
    'Finance Lease, Interest Payment on Liability',
    'amzn_InterestPaidFinancingObligations',
    'Income Taxes Paid, Net',
    'Right-of-Use Asset Obtained in Exchange for Operating Lease Liability',
    'Right-of-Use Asset Obtained in Exchange for Finance Lease Liability',
    'amzn_PropertyandEquipmentObtainedinExchangeforFinancingObligations'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10q.loc['Repayments of Short-term Debt', '2020-03-31'] = -631
df_cash_flow_10q.loc['Repayments of Long-term Debt', '2020-03-31'] = -36

df_cash_flow_10q.loc['Increase (Decrease) in Other Noncurrent Assets', '2023-09-30'] = -3134
df_cash_flow_10q.loc['Increase (Decrease) in Other Noncurrent Assets', '2023-06-30'] = -3126
df_cash_flow_10q.loc['Increase (Decrease) in Other Noncurrent Assets', '2023-03-31'] = -3203

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'amzn_ProceedsFromPropertyPlantAndEquipmentSalesAndIncentives': 'Proceeds From Property Plant And Equipment Sales And Incentives',
    'amzn_RepaymentsOfLongTermFinancingObligations': 'Repayments Of Long Term Financing Obligations',
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Lease Liability Noncurrent': 'Long-term Lease Liabilities',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Technology And Infrastructure Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments to Acquire Productive Assets': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Fazendo o scraping do 'current portion of lease liabilities'
current_portion_lease_lst = []

for acc_num in df_lst_acc_num_10q_amzn_sliced['acc_num']:
    # Fazendo o scraping do 'current portion of lease liabilities' (10-K) -> 'Note 4 – Leases' 
    current_portion_lease_10q = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='current_portion_lease')
    current_portion_lease_10q = f_sec.rename_statement(current_portion_lease_10q, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    current_portion_lease_10q = current_portion_lease_10q.iloc[:, 0]
    current_portion_lease_lst.append(current_portion_lease_10q)

# Removendo duplicatas de índice em cada série
current_portion_lease_lst_clean = [df[~df.index.duplicated(keep='first')] for df in current_portion_lease_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_current_portion_lease_10q = pd.concat(current_portion_lease_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_current_portion_lease_10q = df_current_portion_lease_10q.drop('us-gaap_LeasesAbstract')

# Renomeando a linha do índice
df_current_portion_lease_10q = df_current_portion_lease_10q.rename(index={
    'amzn_LeaseLiabilityCurrent': 'Current Portion of Lease Liabilities',
})

# Formatando o número para ficar positivo
df_current_portion_lease_10q.loc['Current Portion of Lease Liabilities'] = df_current_portion_lease_10q.loc['Current Portion of Lease Liabilities'] * -1

# Selecionando a linha desejada
df_current_portion_lease_10q = df_current_portion_lease_10q.loc[['Current Portion of Lease Liabilities']]

df_current_portion_lease_10q

In [ ]:
# Fazendo o scraping do 'Current portion of long-term debt' (10-K)
current_portion_debt_lst = []

for acc_num in df_lst_acc_num_10q_amzn_sliced['acc_num']:
    # Fazendo o scraping do 'Current portion of long-term debt' (10-K) -> # 'Note 6. Debt' 
    current_portion_debt_10q = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='current_portion_debt')
    current_portion_debt_10q = f_sec.rename_statement(current_portion_debt_10q, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    current_portion_debt_10q = current_portion_debt_10q.iloc[:, 0]
    current_portion_debt_lst.append(current_portion_debt_10q)

# Removendo duplicatas de índice em cada série
current_portion_debt_lst_clean = [df[~df.index.duplicated(keep='first')] for df in current_portion_debt_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_current_portion_debt_10q = pd.concat(current_portion_debt_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_current_portion_debt_10q = df_current_portion_debt_10q.drop('us-gaap_DebtInstrumentLineItems')

# Renomeando a linha do índice
df_current_portion_debt_10q = df_current_portion_debt_10q.rename(index={
    'Long-term Debt, Current Maturities': 'Current Portion of Long-term Debt',
})

# Formatando o número para ficar positivo
df_current_portion_debt_10q.loc['Current Portion of Long-term Debt'] = df_current_portion_debt_10q.loc['Current Portion of Long-term Debt'] * -1

# Arrumando a escala de algumas colunas
df_current_portion_debt_10q.loc[:, '2020-03-31'] = df_current_portion_debt_10q.loc[:, '2020-03-31'] / 1000000
df_current_portion_debt_10q.loc[:, '2020-06-30'] = df_current_portion_debt_10q.loc[:, '2020-06-30'] / 1000000
df_current_portion_debt_10q.loc[:, '2020-09-30'] = df_current_portion_debt_10q.loc[:, '2020-09-30'] / 1000000
df_current_portion_debt_10q.loc[:, '2021-03-31'] = df_current_portion_debt_10q.loc[:, '2021-03-31'] / 1000000
df_current_portion_debt_10q.loc[:, '2021-06-30'] = df_current_portion_debt_10q.loc[:, '2021-06-30'] / 1000000
df_current_portion_debt_10q.loc[:, '2021-09-30'] = df_current_portion_debt_10q.loc[:, '2021-09-30'] / 1000000
df_current_portion_debt_10q.loc[:, '2022-03-31'] = df_current_portion_debt_10q.loc[:, '2022-03-31'] / 1000000

# Selecionando a linha desejada
df_current_portion_debt_10q = df_current_portion_debt_10q.loc[['Current Portion of Long-term Debt']]

# No 1T26 ('2026-03-31'), o 'acc_num' está retornando duas colunas iguais da data '2026-03-31'
df_current_portion_debt_10q.loc['Current Portion of Long-term Debt', '2026-03-31'] = 2.832

df_current_portion_debt_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')
    df_current_portion_lease_10q.to_excel(writer, sheet_name='current_portion_lease')
    df_current_portion_debt_10q.to_excel(writer, sheet_name='current_portion_debt')

### Indicadores Fundamentalistas

In [192]:
# Lendo os arquivos 10k
amzn_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

amzn_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

amzn_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

amzn_current_portion_lease = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10k.xlsx', 
    sheet_name='current_portion_lease', 
    index_col='Unnamed: 0'
)

amzn_current_portion_debt = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10k.xlsx', 
    sheet_name='current_portion_debt', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
amzn_bs.columns = pd.to_datetime(amzn_bs.columns)
amzn_is.columns = pd.to_datetime(amzn_is.columns)
amzn_cf.columns = pd.to_datetime(amzn_cf.columns)
amzn_current_portion_lease.columns = pd.to_datetime(amzn_current_portion_lease.columns)
amzn_current_portion_debt.columns = pd.to_datetime(amzn_current_portion_debt.columns)

# Transformando as colunas em apenas o ano
amzn_bs.columns = amzn_bs.columns.year
amzn_is.columns = amzn_is.columns.year
amzn_cf.columns = amzn_cf.columns.year
amzn_current_portion_lease.columns = amzn_current_portion_lease.columns.year
amzn_current_portion_debt.columns = amzn_current_portion_debt.columns.year

In [193]:
# Preços da AMZN
amzn_close = yf.download('AMZN', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_dec_close = []

for year in lst_years:
    last_close = amzn_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
amzn_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amzn_close_dec = amzn_close_dec.reindex(index=amzn_close_dec.index[::-1])

# Arredondamento de duas casas decimais
amzn_close_dec = round(amzn_close_dec, 2)

# Teve um split de 20:1 em 06/06/2022 (https://br.investing.com/equities/amazon-com-inc-historical-data-splits)
amzn_close_dec.loc['2021'] = amzn_close_dec.loc['2021'] * 20
amzn_close_dec.loc['2020'] = amzn_close_dec.loc['2020'] * 20
amzn_close_dec.loc['2019'] = amzn_close_dec.loc['2019'] * 20
amzn_close_dec.loc['2018'] = amzn_close_dec.loc['2018'] * 20
amzn_close_dec.loc['2017'] = amzn_close_dec.loc['2017'] * 20

# Transformando o index em int
amzn_close_dec .index = amzn_close_dec .index.astype(int)

amzn_close_dec

[*********************100%***********************]  1 of 1 completed

2025     230.82
2024     219.39
2023     151.94
2022      84.00
2021    3334.40
2020    3257.00
2019    1847.80
2018    1502.00
2017    1169.40
dtype: float64

In [194]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = amzn_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=amzn_close_dec, df_is=amzn_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=amzn_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=amzn_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=amzn_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=amzn_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=amzn_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=amzn_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=amzn_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=amzn_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=amzn_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=amzn_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=amzn_bs, df_is=amzn_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=amzn_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=amzn_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Long-term Lease Liabilities', 'Long-term Debt']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=amzn_bs, lst_itens_divida=lst_divida)
div_bruta_total = div_bruta.values + amzn_current_portion_lease.values + amzn_current_portion_debt.values
div_bruta_total = pd.Series(div_bruta_total[0], index=idx)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta_total, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=amzn_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=amzn_is, df_bs=amzn_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=amzn_is, df_bs=amzn_bs, div_bruta=div_bruta_total, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=amzn_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=amzn_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=amzn_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=amzn_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=amzn_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Finance Lease, Principal Payments']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=amzn_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=amzn_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=amzn_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Receivable and Other Operating Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=amzn_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=amzn_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Short-term Debt', 'Proceeds from Issuance of Long-term Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amzn_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Short-term Debt', 
    'Repayments of Long-term Debt', 
    'Finance Lease, Principal Payments', 
    'Repayments Of Long Term Financing Obligations'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amzn_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=amzn_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=amzn_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=amzn_is,
        idx=idx
)

# DPA e Payout - Amazon não paga dividendo

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=amzn_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=amzn_bs, df_is=amzn_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=amzn_bs, df_is=amzn_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=amzn_bs, df_is=amzn_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=amzn_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=amzn_bs, df_is=amzn_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=amzn_is, df_bs=amzn_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=amzn_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta_total,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
amzn_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
amzn_indicadores_10k.columns = nomes_col
amzn_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,31.67,31.66,3.16,145731.0,10.83,50.29,11.16,20.33,5.98,2.459618e+09,...,0,34.482156,39.248248,124.845783,1.796241,0.094472,-0.085720,0.957339,0.099073,2.004669
2024,38.78,38.76,2.58,121388.0,9.29,48.85,10.75,19.03,8.03,2.297671e+09,...,0,31.725573,38.273274,105.558571,1.955796,0.086919,-0.098250,0.954600,0.554922,1.572100
2023,51.46,51.51,1.94,85515.0,5.29,46.98,6.41,14.88,7.76,1.565590e+09,...,0,33.181703,39.906510,101.785676,2.791980,0.090909,-0.110085,0.993346,1.058899,1.083554
2022,-314.43,0.00,-0.32,54169.0,-0.53,43.81,2.38,10.54,5.86,8.558760e+08,...,6000,30.081540,43.478107,100.591695,-17.175606,0.082415,-0.112030,0.863077,6.206098,1.518213
2021,50.57,50.57,1.98,59175.0,7.10,42.03,5.30,12.60,12.20,1.687206e+09,...,0,25.552688,43.744676,105.426813,1.388533,0.070007,-0.034953,0.782881,-0.441374,1.780178
2020,76.34,76.35,1.31,48150.0,5.53,39.57,5.93,12.47,17.43,1.628500e+09,...,0,23.202966,37.226380,113.484529,3.097089,0.063570,-0.163724,1.372046,1.215320,1.589640
2019,78.77,78.76,1.27,36330.0,4.13,40.99,5.18,12.95,14.71,9.128132e+08,...,0,27.084649,45.195033,104.036554,3.323611,0.074205,-0.138831,1.060116,1.868571,0.773831
2018,72.62,72.63,1.38,27762.0,4.33,40.25,5.33,11.92,16.80,7.314740e+08,...,0,26.137590,45.046638,100.175918,3.050035,0.071610,-0.140496,1.106657,1.717065,0.875236
2017,185.07,185.03,0.54,15584.0,1.71,37.07,2.31,8.76,20.26,5.613120e+08,...,0,27.013932,52.326862,112.877589,6.077811,0.074011,NaN,1.182880,2.136169,1.041558

In [195]:
# Lendo os arquivos 10q
amzn_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

amzn_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

amzn_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

amzn_current_portion_lease_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10q.xlsx', 
    sheet_name='current_portion_lease', 
    index_col='Unnamed: 0'
)

amzn_current_portion_debt_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_10q.xlsx', 
    sheet_name='current_portion_debt', 
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
amzn_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amzn_bs_10q.columns]
amzn_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amzn_is_10q.columns]
amzn_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amzn_cf_10q.columns]
amzn_current_portion_lease_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amzn_current_portion_lease_10q.columns]
amzn_current_portion_debt_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in amzn_current_portion_debt_10q.columns]

In [196]:
# Preços da AMZN
amzn_close = yf.download('AMZN', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025',
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = amzn_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
amzn_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amzn_close_months = amzn_close_months.reindex(index=amzn_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = amzn_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
amzn_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
amzn_close_months_atual = amzn_close_months_atual.reindex(index=amzn_close_months_atual.index[::-1])

# Juntando as duas series pandas
amzn_close_months = pd.concat([amzn_close_months_atual, amzn_close_months])

# Arredondamento de duas casas decimais
amzn_close_months = round(amzn_close_months, 2)

# Teve um split de 20:1 em 06/06/2022 (https://br.investing.com/equities/amazon-com-inc-historical-data-splits)
amzn_close_months.loc['03-2022'] = amzn_close_months.loc['03-2022'] * 20
amzn_close_months.loc['09-2021'] = amzn_close_months.loc['09-2021'] * 20
amzn_close_months.loc['06-2021'] = amzn_close_months.loc['06-2021'] * 20
amzn_close_months.loc['03-2021'] = amzn_close_months.loc['03-2021'] * 20

# Substituindo o index para ficar igual ao dos dados fundamentalistas
amzn_close_months.index = amzn_bs_10q.columns[:-3]

amzn_close_months

[*********************100%***********************]  1 of 1 completed

2026-06-30     238.34
2026-03-31     208.27
2025-09-30     219.57
2025-06-30     219.39
2025-03-31     190.26
2024-09-30     186.33
2024-06-30     193.25
2024-03-31     180.38
2023-09-30     127.12
2023-06-30     130.36
2023-03-31     103.29
2022-09-30     113.00
2022-06-30     106.21
2022-03-31    3260.00
2021-09-30    3285.00
2021-06-30    3440.20
2021-03-31    3094.00
dtype: float64

* Os dados do fluxo de caixa são não acumulados:
    - Todas as funções que utilizam dados do fluxo de caixa utilizar com o parâmetro 'ten_k'=True;
    - Para fazer o cálculo da série acumulada utilizar a função 'indicador_acumular_series_trimestrais'.

In [197]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = amzn_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=amzn_close_months, df_is=amzn_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=amzn_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=amzn_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=amzn_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=amzn_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=amzn_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
depreciacao_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=depreciacao_10q, idx=idx_10q)

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=amzn_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=amzn_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=amzn_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=amzn_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=amzn_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=amzn_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=amzn_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=amzn_bs_10q, df_is=amzn_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=amzn_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents', 
    'Marketable Securities'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=amzn_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Long-term Lease Liabilities', 
    'Long-term Debt'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=amzn_bs_10q, lst_itens_divida=lst_divida)
div_bruta_total_10q = div_bruta_10q.values + amzn_current_portion_lease_10q.iloc[:, 0:-3].values + amzn_current_portion_debt_10q.iloc[:, 0:-3].values
div_bruta_total_10q = pd.Series(div_bruta_total_10q[0], index=idx_10q[0:-3])

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_total_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=amzn_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=amzn_is_10q, df_bs=amzn_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=amzn_is_10q, df_bs=amzn_bs_10q, div_bruta=div_bruta_total_10q, idx=idx_10q)

# FCO - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fco_10q = f_eua.indicador_fco(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None) 
fco_10q_sliced = f_eua.indicador_fco(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None)[:-3]
fco_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fco_10q, idx=idx_10q)

# FCI - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fci_10q = f_eua.indicador_fci(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None) 
fci_10q_sliced = f_eua.indicador_fci(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None)[:-3]
fci_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fci_10q, idx=idx_10q)

# FCF - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fcf_10q = f_eua.indicador_fcf(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None) 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None)[:-3]
fcf_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fcf_10q, idx=idx_10q)

# CAPEX - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, lst_itens=lst_capex_10q, idx=idx_10q)
capex_10q_sliced = f_eua.indicador_capex(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, lst_itens=lst_capex_10q, idx=idx_10q)[:-3]
capex_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=capex_10q, idx=idx_10q)

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
sbc_10q = f_eua.indicador_sbc(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
sbc_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=sbc_10q, idx=idx_10q)

# Outros custos fluxo de caixa - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_custos_cf = ['Finance Lease, Principal Payments']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, lst_itens=lst_custos_cf, idx=idx_10q)
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=amzn_cf_10q, first_quarter=None, lst_itens=lst_custos_cf, idx=idx_10q)[:-3]
outros_custos_cf_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=outros_custos_cf_10q, idx=idx_10q)

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=amzn_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=amzn_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=amzn_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=amzn_bs_10q)

# Change in non cash working capital - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Accounts Receivable and Other Operating Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities and Other Operating Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=amzn_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=amzn_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)[:-3]
change_non_cash_wc_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=change_non_cash_wc_10q, idx=idx_10q)

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=amzn_is_10q, idx=idx_10q)

# New borrowing - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_new_borrowing = [
    'Proceeds from Short-term Debt', 
    'Proceeds from Issuance of Long-term Debt'
]

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
new_borrowing_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=new_borrowing_10q, idx=idx_10q)

# Debt paid - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_debt_paid = [
    'Repayments of Short-term Debt', 
    'Repayments of Long-term Debt', 
    'Finance Lease, Principal Payments', 
    'Repayments Of Long Term Financing Obligations'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=amzn_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
debt_paid_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=debt_paid_10q, idx=idx_10q)

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=amzn_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=amzn_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=amzn_is_10q,
        idx=idx_10q
)

# DPA e Payout - Amazon não paga dividendo

# Buyback - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
buyback_10q = f_eua.indicador_buyback(ten_k=True, df_cf=amzn_cf_10q,  first_quarter=None)[:-3]

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=amzn_bs_10q, df_is=amzn_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=amzn_bs_10q, df_is=amzn_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=amzn_bs_10q, df_is=amzn_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=amzn_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=amzn_bs_10q, df_is=amzn_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=amzn_is_10q, df_bs=amzn_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=amzn_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_total_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_acum,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
amzn_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    # DPA - não paga dividendo
    # Payout - não paga dividendo
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
amzn_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
amzn_indicadores_10q = amzn_indicadores_10q.fillna(0)

amzn_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,40.97,19.33,5.17,47449.0,158862.0,31.23,52.26,13.69,23.65,4.65,...,0,160.282245,145.515254,561.878511,0.724488,0.439129,0.019417,0.956543,-0.418695,2.712027
2026-03-31,73.95,25.62,3.90,42797.0,144080.0,16.67,51.82,13.14,23.58,5.06,...,0,151.880409,152.463442,520.601683,0.860420,0.416111,0.005414,0.608267,-0.839960,2.333228
2025-09-30,110.62,32.43,3.08,34218.0,132136.0,11.76,50.79,9.67,18.99,6.34,...,0,123.932946,170.805346,436.468704,1.676736,0.339542,-0.021848,1.038196,-0.183650,2.089486
2025-06-30,128.48,36.08,2.77,34398.0,124628.0,10.83,51.81,11.43,20.51,6.99,...,0,124.962582,184.399324,443.936010,1.790079,0.342363,-0.023203,0.945258,0.183880,2.113548
2025-03-31,117.79,35.43,2.82,32667.0,117221.0,11.00,50.55,11.82,20.99,6.59,...,0,127.122897,170.057680,423.157413,0.993461,0.348282,0.000191,0.520862,0.412915,1.754242
2024-09-30,127.65,39.56,2.53,30853.0,107873.0,9.65,49.03,10.96,19.42,7.55,...,0,118.631835,162.732566,381.195278,1.694350,0.325019,-0.019865,0.841766,1.553627,1.682785
2024-06-30,149.71,49.42,2.02,26710.0,96290.0,9.11,50.14,9.92,18.05,8.54,...,0,123.591437,168.730569,404.732737,1.874750,0.338607,-0.022851,0.946499,1.889803,1.463698
2024-03-31,179.72,61.56,1.62,26991.0,85477.0,7.28,49.32,10.68,18.83,8.65,...,0,121.659026,156.521898,367.185990,1.820439,0.333312,-0.017196,0.703531,0.805675,1.277388
2023-09-30,132.82,57.52,1.74,23319.0,71215.0,6.90,47.57,7.82,16.30,7.17,...,0,110.762984,172.258671,350.316707,2.147687,0.303460,-0.024776,0.909859,-0.064177,1.028687
2023-06-30,198.63,124.15,0.81,19270.0,60807.0,5.02,48.38,5.72,14.34,7.95,...,0,108.440986,192.499315,365.568233,2.440889,0.297099,-0.021678,0.855008,-2.389778,0.988437
2023-03-31,333.77,0.00,-6.93,15897.0,54184.0,2.49,46.77,3.75,12.48,6.85,...,0,107.891063,183.977962,360.240371,1.509458,0.295592,-0.003693,0.301189,-12.261349,1.277263
2022-09-30,400.97,0.00,-1.11,12729.0,52087.0,2.26,44.71,1.99,10.01,8.38,...,0,103.824596,190.359125,351.972448,3.970752,0.284451,-0.021047,0.895907,-13.199513,1.605057
2022-06-30,-532.88,7.66,13.06,12911.0,55098.0,-1.67,45.21,2.74,10.65,8.23,...,3334,104.784631,209.650804,391.348534,-4.420611,0.287081,-0.028185,0.694369,17.015779,1.638941
2022-03-31,-431.67,108.09,0.93,12647.0,58560.0,-3.30,42.89,3.15,10.86,12.38,...,2666,101.885542,192.036798,376.241071,0.725806,0.279138,-0.002873,-0.220606,9.265869,1.665293
2021-09-30,527.72,65.24,1.53,13800.0,58630.0,2.85,43.21,4.38,12.45,13.81,...,0,94.237537,179.414349,414.556015,2.317174,0.258185,-0.012510,0.529928,-5.378961,1.759946
2021-06-30,223.36,62.98,1.59,15740.0,56421.0,6.88,43.25,6.81,13.92,15.13,...,0,86.618102,137.176437,375.885845,1.634739,0.237310,-0.015961,0.807814,0.592183,1.777557
2021-03-31,192.35,69.83,1.43,16373.0,50032.0,7.47,42.50,8.17,15.09,15.09,...,0,81.695986,139.494656,373.908145,0.519674,0.223825,0.014308,0.257314,0.301961,1.609217

In [200]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//amazon//amzn_indicators.xlsx') as writer:
    amzn_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    amzn_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Apple

* 1Q -> Lançamento em Dezembro (12);
* 2Q -> Lançamento em Março (03);
* 3Q -> Lançamento em Junho (06);
* 10K -> Lançamento em Setembro (09).

In [ ]:
ticker = 'aapl'
f_sec.cik_matching_ticker(ticker)

### Scraping Apple 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_aapl = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_aapl.index = pd.to_datetime(df_lst_acc_num_aapl.index, format='%Y-%m-%d')

# Selecionando os 'acc_num' dos 10-k a partir de 2017 p/ iteração
df_lst_acc_num_aapl = df_lst_acc_num_aapl.loc['2017-09-30':]

df_lst_acc_num_aapl

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_aapl['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Marketable Securities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Available-for-sale Securities, Current'
df_balance_sheet_10k.loc['Marketable Securities, Current', '2018-09-29'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2018-09-29'] 
df_balance_sheet_10k.loc['Marketable Securities, Current', '2017-09-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2017-09-30'] 

# A linha 'Marketable Securities, Noncurrent' nas colunas abaixo estão zeradas
# As informações estão na linha 'Available-for-sale Securities, Noncurrent'
df_balance_sheet_10k.loc['Marketable Securities, Noncurrent', '2018-09-29'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Noncurrent', '2018-09-29'] 
df_balance_sheet_10k.loc['Marketable Securities, Noncurrent', '2017-09-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Noncurrent', '2017-09-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Available-for-sale Securities, Current',
    'Available-for-sale Securities, Noncurrent'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop('us-gaap_AssetsCurrentAbstract')

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_aapl['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Revenues' e 'Revenue, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2018-09-29'] = df_income_statement_10k.loc['Revenues', '2018-09-29'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-09-30'] = df_income_statement_10k.loc['Revenue, Net (Deprecated 2018-01-31)', '2017-09-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Revenues',
    'Revenue, Net (Deprecated 2018-01-31)'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_OperatingExpensesAbstract',
    'us-gaap_IncomeStatementAbstract',
    'Common Stock, Dividends, Per Share, Declared'
])

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_aapl['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-09-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-09-29'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-09-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-09-30'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Available-for-sale Securities'
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2018-09-29'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2018-09-29'] 
df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2017-09-30'] = df_cash_flow_10k.loc['Payments to Acquire Available-for-sale Securities', '2017-09-30'] 

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities	'
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2018-09-29'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2018-09-29'] 
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-09-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-09-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-09-29'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-09-29'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-09-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-09-30'] 

# A linha 'Depreciation, Depletion and Amortization' na coluna abaixo está zerada
# As informações estão na linha 'Depreciation, Amortization and Accretion, Net'
df_cash_flow_10k.loc['Depreciation, Depletion and Amortization', '2017-09-30'] = df_cash_flow_10k.loc['Depreciation, Amortization and Accretion, Net', '2017-09-30'] 

# A linha 'Interest Paid, Excluding Capitalized Interest, Operating Activities' na coluna abaixo está zerada
# As informações estão na linha 'Interest Paid, Including Capitalized Interest, Operating and Investing Activities'
df_cash_flow_10k.loc['Interest Paid, Excluding Capitalized Interest, Operating Activities', '2017-09-30'] = df_cash_flow_10k.loc['Interest Paid, Including Capitalized Interest, Operating and Investing Activities', '2017-09-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Cash and Cash Equivalents, at Carrying Value',
    'Payments to Acquire Available-for-sale Securities',
    'Proceeds from Sale of Available-for-sale Securities',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Depreciation, Amortization and Accretion, Net',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop('us-gaap_StatementOfCashFlowsAbstract')

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2018-09-29'] = -3000
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-09-30'] = -593000
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Other Investments', '2017-09-30'] = 126000

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Long-term Debt, Current Maturities': 'Long-term Debt, Current',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt, Noncurrent',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted',
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Selecionando o 'acc_num' do ano de 2023 - Apple tem o custo 'interest expense' em 2023. Em 2024 e 2025, ela não possui esse custo 
acc_num_2023 = '000032019323000106'

# Fazendo o scraping do financial statement details (10-K) -> 'Note 6 – Consolidated Financial Statement Details' -> 'Other Income/(Expense), Net' -> 'Interest expense''
interest_expense_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2023, statement_name='interest_expense')
interest_expense_10k = f_sec.rename_statement(interest_expense_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
interest_expense_10k = interest_expense_10k.drop('us-gaap_OrganizationConsolidationAndPresentationOfFinancialStatementsAbstract')

# Formatando o número para ficar positivo
interest_expense_10k.loc['Interest Expense'] = interest_expense_10k.loc['Interest Expense'] * -1

# Selecionando a linha desejada
interest_expense_10k = interest_expense_10k.loc[['Interest Expense']]

interest_expense_10k

In [ ]:
# 'acc_num' entre 2020 e 2025
df_lst_acc_num_aapl_sorted = df_lst_acc_num_aapl.sort_index()
acc_num_list_aapl_sliced = df_lst_acc_num_aapl_sorted.loc['2020':'2025', 'acc_num']

# Fazendo o scraping do leases (10-K)
lease_lst = []

for acc_num in acc_num_list_aapl_sliced:

# Fazendo o scraping do leases (10-K) -> 'Note 8 – Leases' -> 'Total lease liabilities'
    leases_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10k = f_sec.rename_statement(leases_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10k = leases_10k.iloc[:, 0]
    lease_lst.append(leases_10k)

# Removendo duplicatas de índice em cada série
lease_lst_clean = [df[~df.index.duplicated(keep='first')] for df in lease_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10k = pd.concat(lease_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_leases_10k = df_leases_10k.drop('us-gaap_AssetsAndLiabilitiesLesseeAbstract')

# Renomeando a linha do índice
df_leases_10k = df_leases_10k.rename(index={
    'aapl_OperatingandFinanceLeaseLiability': 'Total Lease Liabilities',
})

# Selecionando a linha desejada
df_leases_10k = df_leases_10k.loc[['Total Lease Liabilities']]

####################################################################################################################

# 'acc_num' entre 2017 e 2019
acc_num_list_aapl_sliced_2 = df_lst_acc_num_aapl_sorted.loc['2017':'2019', 'acc_num']

# Fazendo o scraping do leases (10-K)
lease_lst_17_18_19 = []

for acc_num in acc_num_list_aapl_sliced_2:

# Fazendo o scraping do leases (10-K) -> 'Note 8 – Leases' -> 'Total lease liabilities'
    leases_10k_17_18_19 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10k_17_18_19 = f_sec.rename_statement(leases_10k_17_18_19, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10k_17_18_19 = leases_10k_17_18_19.iloc[:, 0]
    lease_lst_17_18_19.append(leases_10k_17_18_19)

# Removendo duplicatas de índice em cada série
lease_lst_clean_17_18_19 = [df[~df.index.duplicated(keep='first')] for df in lease_lst_17_18_19]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10k_17_18_19 = pd.concat(lease_lst_clean_17_18_19, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_leases_10k_17_18_19 = df_leases_10k_17_18_19.drop('us-gaap_OperatingLeasesFutureMinimumPaymentsDueAbstract')

# Renomeando a linha do índice
df_leases_10k_17_18_19 = df_leases_10k_17_18_19.rename(index={
    'Operating Leases, Future Minimum Payments Due': 'Total Lease Liabilities',
})

# Selecionando a linha desejada
df_leases_10k_17_18_19 = df_leases_10k_17_18_19.loc[['Total Lease Liabilities']]

####################################################################################################################

# Contatenando os dfs
df_leases_10k = pd.concat([df_leases_10k, df_leases_10k_17_18_19], axis=1)

# Ordenando o df
df_leases_10k = df_leases_10k[sorted(df_leases_10k.columns, reverse=True)]

df_leases_10k

In [ ]:
# Selecionando o 'acc_num' do ano mais recente
last_acc_num = df_lst_acc_num_aapl.iloc[0][0]

# Fazendo o scraping do financial statement details (10-K) -> 'Note 6 – Consolidated Financial Statement Details' -> 'Other non-current assets'
cross_holding_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='cross_holding')
cross_holding_10k = f_sec.rename_statement(cross_holding_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
cross_holding_10k = cross_holding_10k.drop('us-gaap_OrganizationConsolidationAndPresentationOfFinancialStatementsAbstract')

# Renomeando a linha do índice
cross_holding_10k = cross_holding_10k.rename(index={
    'Other Assets, Miscellaneous, Noncurrent': 'Other Noncurrent Assets',

})

# Selecionando a linha desejada
cross_holding_10k = cross_holding_10k.loc[['Other Noncurrent Assets']]

cross_holding_10k

In [ ]:
# Fazendo o scraping do restricted stock units (10-K) -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
rsu_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='rsu')
rsu_10k = f_sec.rename_statement(rsu_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
rsu_10k = rsu_10k.drop('us-gaap_ShareBasedCompensationArrangementByShareBasedPaymentAwardEquityInstrumentsOtherThanOptionsNonvestedRollForward')

# Resetando o index do df, porque ele possui vários index igauis
rsu_10k = rsu_10k.reset_index(drop=True)

# Renomeando a linha do índice
rsu_10k = rsu_10k.rename(index={
    4: 'RSUs',
})

# Selecionando a linha desejada
rsu_10k = rsu_10k.loc[['RSUs']]

rsu_10k

In [ ]:
# Fazendo o scraping das receitas por segmento geográfico
geographic_revenue_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='geographic_revenue')
geographic_revenue_10k = f_sec.rename_statement(geographic_revenue_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
geographic_revenue_10k = geographic_revenue_10k.drop('us-gaap_SegmentReportingInformationLineItems')

# Resetando o index do df, porque ele possui vários index igauis
geographic_revenue_10k = geographic_revenue_10k.reset_index(drop=True)

# Renomeado o index do df
geographic_revenue_10k = geographic_revenue_10k.rename(index={
    0: 'Net Sales - Total',
    5: 'Operating Income - Total',
    7: 'Net Sales - America',
    10: 'Operating Income - America',
    11: 'Net Sales - Europe',
    14: 'Operating Income - Europe',
    15: 'Net Sales - Greater China',
    18: 'Operating Income - Greater China',
    19: 'Net Sales - Japan',
    22: 'Operating Income - Japan',
    23: 'Net Sales - Rest of Asia Pacific',
    26: 'Operating Income - Rest of Asia Pacific',
})

geographic_revenue_10k

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')
    interest_expense_10k.to_excel(writer, sheet_name='interest_expense')
    df_leases_10k.to_excel(writer, sheet_name='leases')
    cross_holding_10k.to_excel(writer, sheet_name='cross_holding')
    rsu_10k.to_excel(writer, sheet_name='num_shares')
    geographic_revenue_10k.to_excel(writer, sheet_name='geographic_revenue')

### Scraping Apple 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_aapl = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Transformando em datetime o index
df_lst_acc_num_10q_aapl.index = pd.to_datetime(df_lst_acc_num_10q_aapl.index, format='%Y-%m-%d')

df_lst_acc_num_10q_aapl

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de '2019-12-28' p/ iteração
df_lst_acc_num_10q_aapl_sliced = df_lst_acc_num_10q_aapl.loc['2019-12-28':]
df_lst_acc_num_10q_aapl_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_aapl_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Commercial Paper' nas colunas '2020-06-27' e '2020-03-28' estão zeradas
# As informações estão na linha 'Other Short-term Borrowings'
df_balance_sheet_10q.loc['Commercial Paper', '2020-03-28'] = df_balance_sheet_10q.loc['Other Short-term Borrowings', '2020-03-28'] 
df_balance_sheet_10q.loc['Commercial Paper', '2020-06-27'] = df_balance_sheet_10q.loc['Other Short-term Borrowings', '2020-06-27'] 

# # Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop('Other Short-term Borrowings')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Common Stock, Shares, Outstanding'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'aapl_IntangibleAssetsNetExcludingGoodwillNoncurrent': 'Intangible Assets Net Excluding Goodwill, Noncurrent'
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_aapl_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop('us-gaap_OperatingExpensesAbstract')

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_aapl_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# # Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop('us-gaap_StatementOfCashFlowsAbstract')

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Long-term Debt, Current Maturities': 'Long-term Debt, Current',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt, Noncurrent',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted',
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

* Não preciso fazer o scraping do financial statement details (10-Q) -> 'Note 6 – Consolidated Financial Statement Details' -> 'Other Income/(Expense), Net' -> 'Interest expense', porque essa info não é publicada;
* Não preciso fazer o scraping do leases (10-Q) -> 'Note 8 – Leases' -> 'Total lease liabilities', porque essa info não é publicada;
* Não preciso fazer o scraping do financial statement details (10-Q) -> 'Note 6 – Consolidated Financial Statement Details' -> 'Other non-current assets', porque essa info não é publicada;
* Não preciso fazer o scraping das geographic revenues (10-Q) -> 'Segment Operating Performance', porque uso a informação do 10-K;

In [ ]:
# Selecionando o 'acc_num' do trimestre mais recente
last_acc_num_10q = df_lst_acc_num_10q_aapl_sliced['acc_num'].iloc[0]

# Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
rsu_10q = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num_10q, statement_name='rsu')
rsu_10q = f_sec.rename_statement(rsu_10q, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
rsu_10q = rsu_10q.drop('us-gaap_ShareBasedCompensationArrangementByShareBasedPaymentAwardEquityInstrumentsOtherThanOptionsNonvestedRollForward')

# Resetando o index do df, porque ele possui vários index igauis
rsu_10q = rsu_10q.reset_index(drop=True)

# Renomeando a linha do índice
rsu_10q = rsu_10q.rename(index={
    4: 'RSUs',
})

# Selecionando a linha desejada
rsu_10q = rsu_10q.loc[['RSUs']]

rsu_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')
    rsu_10q.to_excel(writer, sheet_name='num_shares')

### Indicadores Fundamentalistas

In [201]:
# Lendo os arquivos 10k
aapl_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

aapl_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

aapl_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

aapl_leases = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10k.xlsx', 
    sheet_name='leases', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
aapl_bs.columns = pd.to_datetime(aapl_bs.columns)
aapl_is.columns = pd.to_datetime(aapl_is.columns)
aapl_cf.columns = pd.to_datetime(aapl_cf.columns)
aapl_leases.columns = pd.to_datetime(aapl_leases.columns)

# Transformando as colunas em apenas o ano
aapl_bs.columns = aapl_bs.columns.year
aapl_is.columns = aapl_is.columns.year
aapl_cf.columns = aapl_cf.columns.year
aapl_leases.columns = aapl_leases.columns.year

In [202]:
# Preços da AAPL
aapl_close = yf.download('AAPL', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024', 
    '2025',
]

last_sep_close = []

for year in lst_years:
    last_close = aapl_close[f'{year}-09'].iloc[-1]
    last_sep_close.append(last_close)

# Transformando em uma série pandas
aapl_close_sep = pd.Series(last_sep_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
aapl_close_sep = aapl_close_sep.reindex(index=aapl_close_sep.index[::-1])

# Arredondamento de duas casas decimais
aapl_close_sep = round(aapl_close_sep, 2)

# Teve um split de 4:1 em 31/08/2020 (https://br.investing.com/equities/apple-computer-inc-historical-data-splits)
aapl_close_sep.loc['2019'] = aapl_close_sep.loc['2019'] * 4
aapl_close_sep.loc['2018'] = aapl_close_sep.loc['2018'] * 4
aapl_close_sep.loc['2017'] = aapl_close_sep.loc['2017'] * 4

# Transformando o index em int
aapl_close_sep .index = aapl_close_sep .index.astype(int)

aapl_close_sep

[*********************100%***********************]  1 of 1 completed

2025    253.69
2024    231.07
2023    168.93
2022    135.55
2021    138.02
2020    112.24
2019    214.92
2018    213.32
2017    143.48
dtype: float64

In [203]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = aapl_bs.columns

# Valor de Mercado - utilizando a função 'indicador_vm_2', porque o nº de ações está em escala diferente
vm = f_eua.indicador_vm_2(ten_k=True, price=aapl_close_sep, df_is=aapl_is) 

# LPA - utilizando a função 'indicador_lpa_2', porque o nº de ações está em escala diferente
lpa = f_eua.indicador_lpa_2(ten_k=True, df_is=aapl_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=aapl_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=aapl_close_sep, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=aapl_close_sep, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=aapl_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=aapl_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=aapl_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=aapl_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=aapl_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=aapl_is)

# VPA - utilizando a função 'indicador_vpa_2', porque o nº de ações está em escala diferente
vpa = f_eua.indicador_vpa_2(ten_k=True, df_bs=aapl_bs, df_is=aapl_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=aapl_close_sep, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents', 
    'Marketable Securities, Current', 
    'Marketable Securities, Noncurrent'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=aapl_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Commercial Paper', 
    'Long-term Debt, Current', 
    'Long-term Debt, Noncurrent'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=aapl_bs, lst_itens_divida=lst_divida)
div_bruta_total = div_bruta.values + aapl_leases.values
div_bruta_total = pd.Series(div_bruta_total[0], index=idx)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta_total, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=aapl_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=aapl_is, df_bs=aapl_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=aapl_is, df_bs=aapl_bs, div_bruta=div_bruta_total, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=aapl_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=aapl_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=aapl_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=aapl_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=aapl_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa 
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=aapl_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=aapl_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=aapl_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Accounts Receivable', 
    'Increase (Decrease) in Other Receivables', 
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Other Operating Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=aapl_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=aapl_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=aapl_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayments of Long-term Debt', 'Proceeds from (Repayments of) Commercial Paper']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=aapl_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=aapl_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=aapl_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=aapl_is,
        idx=idx
)

# Dividendo por Ação - utilizando a função 'indicador_dpa_2', porque o nº de ações está em escala diferente
dpa = f_eua.indicador_dpa_2(ten_k=True, df_cf=aapl_cf, df_is=aapl_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=aapl_cf, df_is=aapl_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=aapl_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=aapl_bs, df_is=aapl_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=aapl_bs, df_is=aapl_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=aapl_bs, df_is=aapl_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=aapl_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=aapl_bs, df_is=aapl_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=aapl_is, df_bs=aapl_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=aapl_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda, 
    p_vpa,
    vm,
    div_bruta_total,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
aapl_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
aapl_indicadores_10k.columns = nomes_col
aapl_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,33.86,33.87,2.95,144748.0,26.92,46.91,31.97,34.78,51.46,3.792285e+09,...,90711,34.886991,9.445465,115.400525,0.995286,0.095581,0.001458,0.770180,0.881769,1.086938
2024,37.82,37.82,2.64,134661.0,23.97,46.21,31.51,34.44,62.28,3.545488e+09,...,94949,31.185572,12.642571,119.658477,1.261564,0.085440,-0.068337,0.878161,1.160781,0.825426
2023,27.42,27.42,3.65,125820.0,25.31,44.13,29.82,32.83,42.77,2.659673e+09,...,77550,28.100291,10.791292,106.721468,1.139677,0.076987,-0.038416,0.878581,1.026692,0.951385
2022,22.02,22.04,4.54,130541.0,25.31,43.31,30.29,33.10,43.45,2.198074e+09,...,89402,26.087825,8.075698,104.685277,1.223921,0.071473,-0.063511,0.935729,1.116630,0.964337
2021,24.35,24.34,4.11,120233.0,25.88,41.78,29.78,32.87,36.51,2.305110e+09,...,85971,26.219312,11.276593,93.851071,1.098838,0.071834,-0.027732,0.865303,0.981760,0.982364
2020,33.92,33.91,2.95,77344.0,20.91,38.23,24.15,28.17,29.77,1.947602e+09,...,72358,21.433437,8.741883,91.048190,1.405201,0.058722,-0.070238,1.043054,1.277891,0.661089
2019,17.96,17.95,5.57,76477.0,21.24,37.82,24.57,29.39,10.97,9.924649e+08,...,66897,32.163052,9.263639,104.314077,1.255809,0.088118,-0.040143,0.907345,1.065875,0.836455
2018,17.76,17.76,5.63,81801.0,22.41,38.34,26.69,30.80,9.87,1.057081e+09,...,72738,31.863891,8.817631,124.570214,1.300734,0.087298,-0.048318,0.946614,1.077103,1.221040
2017,15.48,15.48,6.46,71501.0,21.09,38.47,26.76,31.19,5.59,7.485699e+08,...,32900,28.460045,12.563631,126.927606,1.315340,0.077973,NaN,0.889470,1.057827,1.225854

In [204]:
# Lendo os arquivos 10q
aapl_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

aapl_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

aapl_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
aapl_bs_10q.columns = [f_sec.ajustar_mes_12_03_06_aapl(col) for col in aapl_bs_10q.columns]
aapl_is_10q.columns = [f_sec.ajustar_mes_12_03_06_aapl(col) for col in aapl_is_10q.columns]
aapl_cf_10q.columns = [f_sec.ajustar_mes_12_03_06_aapl(col) for col in aapl_cf_10q.columns]

In [205]:
# Preços da AAPL
aapl_close = yf.download('AAPL', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025',
]

lst_months = ['12', '03', '06']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = aapl_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
aapl_close_months = pd.Series(last_close_months, index=lst_idx)

# Retirando as datas ('03-2020' e '06-2020')
aapl_close_months = aapl_close_months.drop(index=['03-2020', '06-2020'])

# Revertendo o index da série p/ ficar igual com os dos indicadores
aapl_close_months = aapl_close_months.reindex(index=aapl_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    #'12',
    '03',
    '06', 
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = aapl_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
aapl_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
aapl_close_months_atual = aapl_close_months_atual.reindex(index=aapl_close_months_atual.index[::-1])

# Juntando as duas series pandas
aapl_close_months = pd.concat([aapl_close_months_atual, aapl_close_months])

# Arredondamento de duas casas decimais
aapl_close_months = round(aapl_close_months, 2)

# Teve um split de 4:1 em 30/08/2020 (https://br.investing.com/equities/apple-computer-inc-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
aapl_close_months.index = aapl_bs_10q.columns[:-3]

aapl_close_months

[*********************100%***********************]  1 of 1 completed

2026-06-27    289.11
2026-03-28    253.34
2025-12-27    204.18
2025-06-28    220.77
2025-03-29    271.12
2024-12-28    208.63
2024-06-29    169.63
2024-03-30    248.62
2023-12-30    191.12
2023-06-01    162.26
2023-03-01    190.21
2022-12-31    133.91
2022-06-25    170.78
2022-03-26    127.65
2021-12-25    133.39
2021-06-26    118.76
2021-03-27    173.45
2020-12-26    128.82
dtype: float64

In [206]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = aapl_bs_10q.columns

# Valor de Mercado - utilizando a função 'indicador_vm_2', porque o nº de ações está em escala diferente
vm_10q = f_eua.indicador_vm_2(ten_k=False, price=aapl_close_months, df_is=aapl_is_10q)

# LPA - utilizando a função 'indicador_lpa_2', porque o nº de ações está em escala diferente
lpa_acum = f_eua.indicador_lpa_2(ten_k=False, df_is=aapl_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa_2(ten_k=False, df_is=aapl_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=aapl_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=aapl_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=aapl_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=aapl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=aapl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=aapl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=aapl_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=aapl_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=aapl_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=aapl_is_10q)

# VPA - utilizando a função 'indicador_vpa_2', porque o nº de ações está em escala diferente
vpa_10q = f_eua.indicador_vpa_2(ten_k=False, df_bs=aapl_bs_10q, df_is=aapl_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=aapl_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents', 
    'Marketable Securities, Current', 
    'Marketable Securities, Noncurrent'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=aapl_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta - não somei o custo dos 'leases', porque ele não é divulgado no 10q
lst_divida = [
    'Commercial Paper', 
    'Long-term Debt, Current', 
    'Long-term Debt, Noncurrent'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=aapl_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=aapl_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=aapl_is_10q, df_bs=aapl_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=aapl_is_10q, df_bs=aapl_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=aapl_cf_10q, first_quarter='12', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=aapl_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=aapl_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=aapl_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=aapl_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Other Receivables',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Other Operating Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=aapl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=aapl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=aapl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='12')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=aapl_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayments of Long-term Debt', 'Proceeds from (Repayments of) Commercial Paper']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=aapl_cf_10q, first_quarter='12', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=aapl_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=aapl_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=aapl_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=aapl_cf_10q, first_quarter='12')

# Dividendo por Ação - utilizando a função 'indicador_dpa_2', porque o nº de ações está em escala diferente
dpa_10q = f_eua.indicador_dpa_2(ten_k=False, df_cf=aapl_cf_10q, df_is=aapl_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=aapl_cf_10q, df_is=aapl_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=aapl_cf_10q,  first_quarter='12')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=aapl_bs_10q, df_is=aapl_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=aapl_bs_10q, df_is=aapl_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=aapl_bs_10q, df_is=aapl_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=aapl_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=aapl_bs_10q, df_is=aapl_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=aapl_is_10q, df_bs=aapl_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=aapl_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q   
]

# Juntando todos os indicadores em um df
aapl_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
aapl_indicadores_10q.columns = nomes_col
aapl_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-27,142.24,34.13,2.93,39015.0,163437.0,27.23,50.06,32.62,35.66,39.39,...,25105.0,104.739392,74.086043,430.977455,1.153748,0.286957,-0.012815,0.880918,4.518514,0.739458
2026-03-28,125.68,31.32,3.19,39324.0,156672.0,26.60,49.27,32.28,35.37,34.90,...,12288.0,99.598279,43.661773,371.121837,0.970383,0.272872,0.002495,0.729885,4.177733,0.573132
2025-12-27,71.53,24.08,4.15,54066.0,163260.0,29.28,48.16,35.37,37.61,34.14,...,24701.0,101.360395,28.773901,345.712915,1.280970,0.277700,-0.032702,0.997392,2.941611,0.738332
2025-06-28,140.40,31.40,3.18,31032.0,137396.0,24.92,46.49,29.99,33.00,49.95,...,21075.0,106.962280,42.979153,365.406216,1.189170,0.293047,-0.013370,0.898009,4.224119,1.223322
2025-03-29,164.05,38.79,2.58,32250.0,137100.0,25.99,47.05,31.03,33.82,60.93,...,25898.0,100.039220,45.317773,391.269706,0.966586,0.274080,0.002477,0.742698,3.844915,1.154077
2024-12-28,86.61,27.71,3.61,45912.0,148071.0,29.23,46.88,34.46,36.94,47.09,...,23606.0,87.033266,38.205452,342.251420,0.823975,0.238447,0.018334,0.652008,3.080072,0.954545
2024-06-29,120.91,26.55,3.77,28202.0,128209.0,25.00,46.26,29.56,32.88,38.91,...,26522.0,96.997738,48.812881,376.678670,1.345487,0.265747,-0.022231,1.023261,5.090964,0.754737
2024-03-30,162.05,38.13,2.62,30736.0,131223.0,26.04,46.58,30.74,33.87,51.58,...,23205.0,87.826353,46.918031,344.454540,0.959976,0.240620,0.002826,0.738222,4.574717,0.703808
2023-12-30,87.40,27.78,3.60,43221.0,139419.0,28.36,45.87,33.76,36.15,39.98,...,20139.0,70.799164,36.719947,327.924753,1.176288,0.193970,-0.017076,0.923047,3.468923,0.839888
2023-06-01,128.12,27.55,3.63,26050.0,122079.0,24.31,44.52,28.12,31.85,42.26,...,17478.0,87.232845,59.120285,375.575864,1.326895,0.238994,-0.019361,1.012668,5.077159,0.685780
2023-03-01,124.29,30.88,3.24,31216.0,128745.0,25.48,44.26,29.86,32.92,48.28,...,19594.0,69.031170,51.663451,296.536606,1.182119,0.189126,-0.012888,0.914915,4.234437,1.006211
2022-12-31,70.94,19.87,5.03,38932.0,141714.0,25.61,42.96,30.74,33.23,37.51,...,19475.0,74.000717,37.252701,316.363922,1.133576,0.202742,-0.011009,0.873446,4.027702,1.298697
2022-06-25,141.98,27.72,3.61,25881.0,129740.0,23.44,43.26,27.82,31.20,47.44,...,21865.0,95.928049,42.126121,374.839508,1.177451,0.262817,-0.010358,0.884510,5.637589,0.749376
2022-03-26,83.09,20.04,4.99,32716.0,134159.0,25.71,43.75,30.82,33.63,30.83,...,22631.0,78.100650,36.420622,351.412307,1.126190,0.213974,-0.009177,0.860924,4.419352,0.918524
2021-12-25,63.14,20.43,4.90,44185.0,137643.0,27.94,43.76,33.47,35.65,30.38,...,20478.0,88.972891,30.770136,389.402456,1.356223,0.243761,-0.033556,1.062940,3.469217,1.039303
2021-06-26,90.83,16.89,5.92,26958.0,109301.0,26.70,43.29,29.63,33.10,30.69,...,22900.0,78.325699,40.927045,319.393772,0.970107,0.214591,0.002009,0.782476,4.170438,0.739054
2021-03-27,122.97,20.90,4.79,30300.0,97982.0,26.38,42.51,30.70,33.82,42.00,...,18548.0,75.388406,36.985438,284.367634,1.014854,0.206544,-0.001068,0.791452,3.518366,0.811226
2020-12-26,75.87,10.80,9.26,36200.0,96067.0,25.80,39.78,30.09,32.48,32.95,...,24775.0,88.764840,27.046907,347.242479,1.348044,0.243191,-0.028814,1.070801,3.124187,1.312828

In [209]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//apple//aapl_indicators.xlsx') as writer:
    aapl_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    aapl_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Google

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'googl'
f_sec.cik_matching_ticker(ticker)

### Scraping Google 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_googl = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017, 2018, 2019, 2020 e 2021
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000165204423000016', # 2022
            '000165204422000019', # 2021
            '000165204421000010', # 2020
            '000165204420000008', # 2019
            '000165204419000004', # 2018
            '000165204418000007', # 2017
        ]
    },
    index=pd.to_datetime([
        '2022-12-31', 
        '2021-12-31', 
        '2020-12-31',
        '2019-12-31',
        '2018-12-31',
        '2017-12-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_googl = pd.concat([df_lst_acc_num_googl, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_googl.index = pd.to_datetime(df_lst_acc_num_googl.index, format='%Y-%m-%d')

df_lst_acc_num_googl

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_googl['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Property, Plant and Equipment, Net' nas colunas abaixo estão zeradas
# As informações estão na linha 'goog_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization' e 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization'
df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2019-12-31'] = df_balance_sheet_10k.loc['goog_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization', '2019-12-31'] 
df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2025-12-31'] = df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2025-12-31'] 

# A linha 'Marketable Securities, Current' na coluna abaixo está zerada
# As informações estão na linha 'Available-for-sale Securities, Current'
df_balance_sheet_10k.loc['Marketable Securities, Current', '2017-12-31'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2017-12-31'] 

# A linha 'Contract with Customer, Liability, Noncurrent' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Revenue, Noncurrent'
df_balance_sheet_10k.loc['Contract with Customer, Liability, Noncurrent', '2017-12-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Noncurrent', '2017-12-31'] 

# A linha 'Accrued Income Taxes, Noncurrent' na coluna abaixo está zerada
# As informações estão na linha 'Liability for Uncertainty in Income Taxes, Noncurrent'
df_balance_sheet_10k.loc['Accrued Income Taxes, Noncurrent', '2017-12-31'] = df_balance_sheet_10k.loc['Liability for Uncertainty in Income Taxes, Noncurrent', '2017-12-31'] 

# A linha 'Contract with Customer, Liability, Current' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Revenue, Current'
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2017-12-31'] = df_balance_sheet_10k.loc['Deferred Revenue, Current', '2017-12-31'] 

# A linha 'Long-term Debt and Lease Obligation' na coluna abaixo está zerada
# As informações estão na linha 'Long-term Debt, Excluding Current Maturities'
df_balance_sheet_10k.loc['Long-term Debt and Lease Obligation', '2025-12-31'] = df_balance_sheet_10k.loc['Long-term Debt, Excluding Current Maturities', '2025-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Available-for-sale Securities, Current',
    'Deferred Revenue, Noncurrent',
    'Liability for Uncertainty in Income Taxes, Noncurrent',
    'Deferred Revenue, Current',
    'goog_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization',
    'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization',
    'Long-term Debt, Excluding Current Maturities',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Convertible Preferred Stock, Nonredeemable or Redeemable, Issuer Option, Value',
    'Common Stock, Shares Authorized',
    'Preferred Stock, Shares Authorized',
    'Preferred Stock, Par or Stated Value Per Share'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'goog_AccruedRevenueShare': 'Accrued Revenue Share'
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_googl['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-12-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-12-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-12-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-12-31'] 

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' nas colunas abaixo estão zeradas
# As informações estão na linha 'Revenues'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2025-12-31'] = df_income_statement_10k.loc['Revenues', '2025-12-31'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2021-12-31'] = df_income_statement_10k.loc['Revenues', '2021-12-31'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-12-31'] = df_income_statement_10k.loc['Revenues', '2020-12-31'] 
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-31'] = df_income_statement_10k.loc['Revenues', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Revenues'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'us-gaap_CostsAndExpensesAbstract',
    'Preferred Stock Dividends and Other Adjustments',
    'Loss Contingency, Loss in Period',
    'Net Income (Loss) Available to Common Stockholders, Basic'
])

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10k.loc['Cost of Revenue']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_googl['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# # A linha 'Depreciation' nas colunas abaixo estão zeradas
# # As informações estão na linha 'goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment'
df_cash_flow_10k.loc['Depreciation', '2022-12-31'] = df_cash_flow_10k.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2022-12-31'] 
df_cash_flow_10k.loc['Depreciation', '2021-12-31'] = df_cash_flow_10k.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2021-12-31'] 
df_cash_flow_10k.loc['Depreciation', '2020-12-31'] = df_cash_flow_10k.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2020-12-31'] 
df_cash_flow_10k.loc['Depreciation', '2019-12-31'] = df_cash_flow_10k.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2019-12-31'] 
df_cash_flow_10k.loc['Depreciation', '2018-12-31'] = df_cash_flow_10k.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2018-12-31'] 
df_cash_flow_10k.loc['Depreciation', '2017-12-31'] = df_cash_flow_10k.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2017-12-31'] 

# # A linha 'Payments for (Proceeds from) Other Investing Activities' nas colunas abaixo estão zeradas
# # As informações estão na linha 'Proceeds from Sale of Property, Plant, and Equipment'
df_cash_flow_10k.loc['Payments for (Proceeds from) Other Investing Activities', '2018-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale of Property, Plant, and Equipment', '2018-12-31'] 
df_cash_flow_10k.loc['Payments for (Proceeds from) Other Investing Activities', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale of Property, Plant, and Equipment', '2017-12-31'] 

# # A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# # As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2018-12-31'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2017-12-31'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-12-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-12-31'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-12-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-12-31'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-12-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-12-31'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-31'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-12-31'] 

# # A linha 'Increase (Decrease) in Contract with Customer, Liability' na coluna abaixo está zeradas
# # As informações estão na linha 'Increase (Decrease) in Deferred Revenue'
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue', '2017-12-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment',
    'Proceeds from Sale of Property, Plant, and Equipment',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash and Cash Equivalents, at Carrying Value',
    'Increase (Decrease) in Deferred Revenue'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Increase (Decrease) in Collateral Held under Securities Lending',
    'Proceeds from (Payments for) Securities Purchased under Agreements to Resell'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Debt and Equity Securities, Gain (Loss)', '2017-12-31'] = 37

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'goog_IncreaseDecreaseInAccruedRevenueShare': 'Increase (Decrease) in Accrued Revenue Share',
    'goog_AcquisitionsNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets': 'Acquisitions Net Of Cash Acquired And Purchases Of Intangible And Other Assets',
    'goog_NetProceedsPaymentsRelatedToStockBasedAwardActivities': 'Net Proceeds Payments Related To Stock Based Award Activities',
    'goog_AmortizationAndImpairmentOfIntangibleAssets': 'Amortization And Impairment Of Intangible Assets',
    'goog_GainLossOnMarketableAndNonMarketableInvestmentsNet': 'Gain Loss On Marketable And Non Marketable Investments, Net',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Accounts Payable, Current': 'Accounts Payable',
    'Other Long-term Investments': 'Non-marketable Securities',
    'Long-term Debt and Lease Obligation': 'Long-term Debt',
    'Operating Lease, Liability, Noncurrent': 'Operating Lease Liabilities',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'

})

In [ ]:
# Selecionando o 'acc_num' do ano mais recente
last_acc_num = df_lst_acc_num_googl.iloc[0].item()

# Fazendo o scraping do interest expense (10-K) -> 'Other Income (Expense), Net' 
interest_expense_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='interest_expense')
interest_expense_10k = f_sec.rename_statement(interest_expense_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
interest_expense_10k = interest_expense_10k.drop('goog_BalanceSheetComponentsDisclosureAbstract')

# Renomeando a linha do índice que está sem formato 
interest_expense_10k = interest_expense_10k.rename(index={
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
interest_expense_10k.loc['Interest Expense'] = interest_expense_10k.loc['Interest Expense'] * -1

# Selecionando a linha desejada
interest_expense_10k = interest_expense_10k.loc[['Interest Expense']]

interest_expense_10k

In [ ]:
# 'acc_num' de 2024 - eu não coloquei no loop for abaixo, porque ele tem um df com três colunas ('2024-09-30', '2024-12-31' e '2023-12-31')
acc_num_2024 = '000165204425000014'

# Fazendo o scraping do leases (10-K) -> 'Note 8 – Leases' -> 'Total lease liabilities'
leases_10k_2024 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2024, statement_name='leases')
leases_10k_2024 = f_sec.rename_statement(leases_10k_2024, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
leases_10k_2024 = leases_10k_2024.drop('goog_BalanceSheetComponentsDisclosureAbstract')
leases_10k_2024 = leases_10k_2024.drop('Loss Contingency Accrual, Payments')

# Renomeando a linha do índice
leases_10k_2024 = leases_10k_2024.rename(index={
    'Operating Lease, Liability, Current': 'Current Operating Lease Liabilities',
})

# Selecionando a linha e a coluna desejada
leases_10k_2024 = leases_10k_2024.loc[['Current Operating Lease Liabilities']]
leases_10k_2024 = leases_10k_2024.loc[:, '2024-12-31']

##############################################################################################

# 'acc_num' entre 2023 e 2019
df_lst_acc_num_googl_sorted = df_lst_acc_num_googl.sort_index()
acc_num_list_googl_sliced = df_lst_acc_num_googl_sorted.loc['2019':'2023', 'acc_num']

# Fazendo o scraping do leases (10-K)
leases_lst = []

for acc_num in acc_num_list_googl_sliced:

    # Fazendo o scraping do leases (10-K) -> 'Note 8 – Leases' -> 'Total lease liabilities'
    leases_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10k = f_sec.rename_statement(leases_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10k = leases_10k.iloc[:, 0]
    leases_lst.append(leases_10k)

# Removendo duplicatas de índice em cada série
lease_lst_clean = [df[~df.index.duplicated(keep='first')] for df in leases_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10k = pd.concat(lease_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_leases_10k = df_leases_10k.drop('goog_BalanceSheetComponentsDisclosureAbstract')

# Renomeando a linha do índice
df_leases_10k = df_leases_10k.rename(index={
    'Operating Lease, Liability, Current': 'Current Operating Lease Liabilities',
})

# Selecionando a linha desejada
df_leases_10k = df_leases_10k.loc[['Current Operating Lease Liabilities']]

# Criando as colunas dos anos de 2017, 2018, 2024 e 2025
df_leases_10k['2017-12-31'] = 0
df_leases_10k['2018-12-31'] = 0	
df_leases_10k['2024-12-31'] = leases_10k_2024
df_leases_10k['2025-12-31'] = 0

# Ordenando o df
df_leases_10k = df_leases_10k[sorted(df_leases_10k.columns, reverse=True)]

df_leases_10k

In [ ]:
# 'acc_num' entre 2023 e 2019
df_lst_acc_num_googl_sorted = df_lst_acc_num_googl.sort_index()
acc_num_list_googl_sliced = df_lst_acc_num_googl_sorted.loc['2020':'2023', 'acc_num']

# Fazendo o scraping do leases (10-K)
current_portion_lease_lst = []

for acc_num in acc_num_list_googl_sliced:

    # Fazendo o scraping do long-term debt (10-K) -> # 'Note 6. Debt' -> 'Long-Term Debt' -> 'Current portion of future finance lease payments'
    current_portion_lease_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='current_portion_lease')
    current_portion_lease_10k = f_sec.rename_statement(current_portion_lease_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    current_portion_lease_10k = current_portion_lease_10k.iloc[:, 0]
    current_portion_lease_lst.append(current_portion_lease_10k)

# Removendo duplicatas de índice em cada série
current_portion_lease_lst_clean = [df[~df.index.duplicated(keep='first')] for df in current_portion_lease_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_current_portion_lease_10k = pd.concat(current_portion_lease_lst_clean, axis=1)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_current_portion_lease_10k = df_current_portion_lease_10k.drop('us-gaap_LongTermDebtNoncurrentAbstract')

# Renomeando a linha do índice
df_current_portion_lease_10k = df_current_portion_lease_10k.rename(index={
    'Finance Lease, Liability, Current': 'Current Portion of Future Finance Lease Payments',
})

# Formatando o número para ficar positivo
df_current_portion_lease_10k.loc['Current Portion of Future Finance Lease Payments'] = df_current_portion_lease_10k.loc['Current Portion of Future Finance Lease Payments'] * -1

# Selecionando a linha desejada
df_current_portion_lease_10k = df_current_portion_lease_10k.loc[['Current Portion of Future Finance Lease Payments']]

# Criando as colunas dos anos de 2017, 2018, 2019, 2024 e 2025
df_current_portion_lease_10k['2017-12-31'] = 0
df_current_portion_lease_10k['2018-12-31'] = 0	
df_current_portion_lease_10k['2019-12-31'] = 115
df_current_portion_lease_10k['2024-12-31'] = 0
df_current_portion_lease_10k['2025-12-31'] = 0

# Ordenando o df
df_current_portion_lease_10k = df_current_portion_lease_10k[sorted(df_current_portion_lease_10k.columns, reverse=True)]

df_current_portion_lease_10k

In [ ]:
# Pegando os dados dos nº de ações de todo o período para usar esses dados na parte dos indicadores fundamentalistas

# 'acc_num' de 2025
acc_num_2025 = '000165204426000018'

# Fazendo o scraping do restricted stock units (10-K) -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10k_25 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2025, statement_name='rsu')
shares_10k_25 = f_sec.rename_statement(shares_10k_25, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10k_25 = shares_10k_25.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10k_25 = shares_10k_25.reset_index(drop=True)

# Selecionando as linhas desejadas e a coluna '2025-12-31'
shares_10k_25 = shares_10k_25.iloc[[5, 11, 15, 27], [0]]

# Renomeando a linha do índice
shares_10k_25 = shares_10k_25.rename(index={
    5: 'RSUs',
    11: 'Class A',
    15: 'Class B',
    27: 'Class C',
})

##################################################

# 'acc_num' de 2024
acc_num_2024 = '000165204425000014'

# Fazendo o scraping do restricted stock units (10-K) -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10k_24_23_22 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2024, statement_name='rsu')
shares_10k_24_23_22 = f_sec.rename_statement(shares_10k_24_23_22, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10k_24_23_22 = shares_10k_24_23_22.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10k_24_23_22 = shares_10k_24_23_22.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10k_24_23_22 = shares_10k_24_23_22.iloc[[5, 11, 15, 26]]

# Renomeando a linha do índice
shares_10k_24_23_22 = shares_10k_24_23_22.rename(index={
    5: 'RSUs',
    11: 'Class A',
    15: 'Class B',
    26: 'Class C',
})

##################################################

# 'acc_num' de 2021
acc_num_2021 = '000165204422000019'

# Fazendo o scraping do restricted stock units (10-K) -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10k_21_20_19 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2021, statement_name='rsu')
shares_10k_21_20_19 = f_sec.rename_statement(shares_10k_21_20_19, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10k_21_20_19 = shares_10k_21_20_19.drop('us-gaap_WeightedAverageNumberOfSharesOutstandingBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10k_21_20_19 = shares_10k_21_20_19.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10k_21_20_19 = shares_10k_21_20_19.iloc[[3, 7, 8, 14]]

# Renomeando a linha do índice
shares_10k_21_20_19 = shares_10k_21_20_19.rename(index={
    8: 'RSUs',
    3: 'Class A',
    7: 'Class B',
    14: 'Class C',
})

##################################################

# 'acc_num' de 2018
acc_num_2018 = '000165204419000004'

# Fazendo o scraping do restricted stock units (10-K) -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10k_18_17 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2018, statement_name='rsu')
shares_10k_18_17 = f_sec.rename_statement(shares_10k_18_17, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10k_18_17 = shares_10k_18_17.drop('us-gaap_WeightedAverageNumberOfSharesOutstandingBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10k_18_17 = shares_10k_18_17.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10k_18_17 = shares_10k_18_17.iloc[[3, 9, 10, 19]]

# Renomeando a linha do índice
shares_10k_18_17 = shares_10k_18_17.rename(index={
    10: 'RSUs',
    3: 'Class A',
    9: 'Class B',
    19: 'Class C',
})

# Removendo a coluna de 2016
shares_10k_18_17 = shares_10k_18_17.drop(columns='2016-12-31')

##################################################

# Concatenando os dfs
shares_10k = pd.concat([
    shares_10k_25,
    shares_10k_24_23_22, 
    shares_10k_21_20_19,
    shares_10k_18_17
], axis=1)

shares_10k

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')
    interest_expense_10k.to_excel(writer, sheet_name='interest_expense')
    df_leases_10k.to_excel(writer, sheet_name='leases')
    df_current_portion_lease_10k.to_excel(writer, sheet_name='current_portion_lease')
    shares_10k.to_excel(writer, sheet_name='num_shares')

### Scraping Google 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_googl = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 1Q, 2Q e 3Q dos anos de 2020 e 2021
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000165204423000045', # 1Q 2023
            '000165204422000090', # 3Q 2022
            '000165204422000071', # 2Q 2022
            '000165204422000029', # 1Q 2022
            '000165204421000057', # 3Q 2021
            '000165204421000047', # 2Q 2021
            '000165204421000020', # 1Q 2021
            '000165204420000050', # 3Q 2020
            '000165204420000032', # 2Q 2020
            '000165204420000021', # 1Q 2020
        ]
    },
    index=pd.to_datetime([
        '2023-03-31', 
        '2022-09-30', 
        '2022-06-30',
        '2022-03-31',
        '2021-09-30', 
        '2021-06-30',
        '2021-03-31',
        '2020-09-30', 
        '2020-06-30',
        '2020-03-31',

    ])
)

# Concatenando os dfs
df_lst_acc_num_10q_googl = pd.concat([df_lst_acc_num_10q_googl, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_10q_googl.index = pd.to_datetime(df_lst_acc_num_10q_googl.index, format='%Y-%m-%d')

df_lst_acc_num_10q_googl

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_googl['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Property, Plant and Equipment, Net' e 'goog_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization'
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2025-03-31'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2025-03-31'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2024-09-30'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2024-09-30'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2024-06-30'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2024-06-30'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2024-03-31'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2024-03-31'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-03-31'] = df_balance_sheet_10q.loc['goog_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization', '2020-03-31'] 

# A linha 'Long-term Debt and Lease Obligation' nas colunas abaixo estão zeradas
# As informações estão na linha 'Long-term Debt, Excluding Current Maturities' 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2026-06-30'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2026-06-30'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2026-03-31'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2026-03-31'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2025-09-30'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2025-09-30'] 
df_balance_sheet_10q.loc['Long-term Debt and Lease Obligation', '2025-06-30'] = df_balance_sheet_10q.loc['Long-term Debt, Excluding Current Maturities', '2025-06-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Property, Plant and Equipment, Net',
    'goog_PropertyPlantandEquipmentandFinanceLeaseRightofUseAssetafterAccumulatedDepreciationandAmortization',
    'Long-term Debt, Excluding Current Maturities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Convertible Preferred Stock, Nonredeemable or Redeemable, Issuer Option, Value',
    'Preferred Stock, Par or Stated Value Per Share',
    'Preferred Stock, Shares Authorized',
    'Common Stock, Shares Authorized',
    'Common Stock, Shares, Issued'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'goog_AccruedRevenueShare': 'Accrued Revenue Share'
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_googl['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Revenues' nas colunas abaixo estao zeradas
# As informações estão na linha 'Revenue from Contract with Customer, Excluding Assessed Tax'
df_income_statement_10q.loc['Revenues', '2025-03-31'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2025-03-31'] 
df_income_statement_10q.loc['Revenues', '2024-09-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2024-09-30'] 
df_income_statement_10q.loc['Revenues', '2024-06-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2024-06-30'] 
df_income_statement_10q.loc['Revenues', '2024-03-31'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2024-03-31'] 
df_income_statement_10q.loc['Revenues', '2023-09-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2023-09-30'] 
df_income_statement_10q.loc['Revenues', '2023-06-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2023-06-30'] 
df_income_statement_10q.loc['Revenues', '2023-03-31'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2023-03-31'] 
df_income_statement_10q.loc['Revenues', '2022-09-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2022-09-30'] 
df_income_statement_10q.loc['Revenues', '2022-06-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2022-06-30'] 
df_income_statement_10q.loc['Revenues', '2022-03-31'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2022-03-31'] 
df_income_statement_10q.loc['Revenues', '2021-09-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2021-09-30'] 
df_income_statement_10q.loc['Revenues', '2021-06-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2021-06-30'] 
df_income_statement_10q.loc['Revenues', '2021-03-31'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2021-03-31'] 
df_income_statement_10q.loc['Revenues', '2020-09-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-09-30'] 
df_income_statement_10q.loc['Revenues', '2020-06-30'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-06-30'] 
df_income_statement_10q.loc['Revenues', '2020-03-31'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2020-03-31'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-06-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-06-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-03-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-09-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-06-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-06-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Revenue from Contract with Customer, Excluding Assessed Tax',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'Loss Contingency, Loss in Period'
])

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Cost of Revenue']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_googl['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Depreciation' nas colunas abaixo estão zeradas
# As informações estão na linha 'goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment'
df_cash_flow_10q.loc['Depreciation', '2023-09-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2023-09-30'] 
df_cash_flow_10q.loc['Depreciation', '2023-06-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2023-06-30'] 
df_cash_flow_10q.loc['Depreciation', '2023-03-31'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2023-03-31'] 
df_cash_flow_10q.loc['Depreciation', '2022-09-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2022-09-30'] 
df_cash_flow_10q.loc['Depreciation', '2022-06-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2022-06-30'] 
df_cash_flow_10q.loc['Depreciation', '2022-03-31'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2022-03-31'] 
df_cash_flow_10q.loc['Depreciation', '2021-09-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2021-09-30'] 
df_cash_flow_10q.loc['Depreciation', '2021-06-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2021-06-30'] 
df_cash_flow_10q.loc['Depreciation', '2021-03-31'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2021-03-31'] 
df_cash_flow_10q.loc['Depreciation', '2020-09-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2020-09-30'] 
df_cash_flow_10q.loc['Depreciation', '2020-06-30'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2020-06-30'] 
df_cash_flow_10q.loc['Depreciation', '2020-03-31'] = df_cash_flow_10q.loc['goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment', '2020-03-31'] 

# A linha 'Depreciation' na coluna abaixo está zerada
# As informações estão na linha 'Payments of Ordinary Dividends'
df_cash_flow_10q.loc['Payments of Dividends', '2026-06-30'] = df_cash_flow_10q.loc['Payments of Ordinary Dividends', '2026-06-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop('goog_DepreciationAndImpairmentOnDispositionOfPropertyAndEquipment')
df_cash_flow_10q = df_cash_flow_10q.drop('Payments of Ordinary Dividends')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop('us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract')

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'goog_IncreaseDecreaseInAccruedRevenueShare': 'Increase (Decrease) in Accrued Revenue Share',
    'goog_AcquisitionsNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets': 'Acquisitions Net Of Cash Acquired And Purchases Of Intangible And Other Assets',
    'goog_NetProceedsPaymentsRelatedToStockBasedAwardActivities': 'Net Proceeds Payments Related To Stock Based Award Activities',
    'goog_AmortizationAndImpairmentOfIntangibleAssets': 'Amortization And Impairment Of Intangible Assets',
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Other Long-term Investments': 'Non-marketable Securities',
    'Long-term Debt and Lease Obligation': 'Long-term Debt',
    'Operating Lease, Liability, Noncurrent': 'Operating Lease Liabilities',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Depreciation': 'Depreciation, Depletion and Amortization',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Selecionando o 'acc_num' do trimestre mais recente
last_acc_num_10q = df_lst_acc_num_10q_googl.iloc[0].item()

# Fazendo o scraping do interest expense -> 'Other Income (Expense), Net'
interest_expense_10q = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num_10q, statement_name='interest_expense')
interest_expense_10q = f_sec.rename_statement(interest_expense_10q, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
interest_expense_10q = interest_expense_10q.drop('goog_BalanceSheetComponentsDisclosureAbstract')

# Renomeando a linha do índice que está sem formato 
interest_expense_10q = interest_expense_10q.rename(index={
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
interest_expense_10q.loc['Interest Expense'] = interest_expense_10q.loc['Interest Expense'] * -1

# Selecionando a linha desejada
interest_expense_10q = interest_expense_10q.loc[['Interest Expense']]

# Selecionando a 1º e 2º coluna do df que são os nº não acumulados
interest_expense_10q = interest_expense_10q.iloc[:, [0,1]]

interest_expense_10q

In [ ]:
# Dados dos nº de ações (Class A, B, C e RSUs) de 2020 e 2021 
# 'acc_num' de 1Q2021
acc_num_1Q2021 = '000165204421000020'

# Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10q_1Q2021 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_1Q2021, statement_name='rsu')
shares_10q_1Q2021 = f_sec.rename_statement(shares_10q_1Q2021, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10q_1Q2021 = shares_10q_1Q2021.drop('us-gaap_WeightedAverageNumberOfSharesOutstandingBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10q_1Q2021 = shares_10q_1Q2021.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10q_1Q2021 = shares_10q_1Q2021.iloc[[3, 7, 9, 14]]

# Renomeando a linha do índice
shares_10q_1Q2021 = shares_10q_1Q2021.rename(index={
    9: 'RSUs',
    3: 'Class A',
    7: 'Class B',
    14: 'Class C',
})


# Os dfs dos 'acc_num' de 2Q2021 e 3Q2021 tinham tamanhos iguais
lst_acc_2021 = [
    '000165204421000047',  # 2Q2021
    '000165204421000057',  # 3Q2021
]

shares_lst_2021 = []

for acc_num in lst_acc_2021:
    # Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
    shares_10q_2021 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='rsu')
    shares_10q_2021 = f_sec.rename_statement(shares_10q_2021, label_dictionary=labels_dict)
    # Selecionando a 1º e 2º coluna do df que são os nº não acumulados
    shares_10q_2021 = shares_10q_2021.iloc[:, [0,1]]
    # Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
    shares_10q_2021 = shares_10q_2021.drop('us-gaap_WeightedAverageNumberOfSharesOutstandingBasicAbstract')
    # Resetando o index do df, porque ele possui vários index iguais
    shares_10q_2021 = shares_10q_2021.reset_index(drop=True)
    shares_lst_2021.append(shares_10q_2021)

# Concatenando os dfs
df_shares_10q_2020_2021 = pd.concat(shares_lst_2021, ignore_index=True, axis=1)

# Selecionando as linhas desejadas
df_shares_10q_2020_2021 = df_shares_10q_2020_2021.iloc[[3, 7, 10, 17]]

# Renomeando a linha do índice e as colunas
df_shares_10q_2020_2021 = df_shares_10q_2020_2021.rename(index={
    10: 'RSUs',
    3: 'Class A',
    7: 'Class B',
    17: 'Class C',
})

df_shares_10q_2020_2021 = df_shares_10q_2020_2021.rename(columns={
    0: '2021-06-30',
    1: '2020-06-30',
    2: '2021-09-30',
    3: '2020-09-30',
})

# Concatenando os dfs de 1Q2021
df_shares_10q_2020_2021 = pd.concat([df_shares_10q_2020_2021, shares_10q_1Q2021], axis=1)

# Transformando as colunas em datetime
df_shares_10q_2020_2021.columns = pd.to_datetime(df_shares_10q_2020_2021.columns, format='%Y-%m-%d')

# Ordenando as colunas
df_shares_10q_2020_2021 = df_shares_10q_2020_2021[sorted(df_shares_10q_2020_2021.columns, reverse=True)]

###################################################################################################################
# Dados dos nº de ações (Class A, B, C e RSUs) de 2022 e 2023 
# 'acc_num' de 1Q2023
acc_num_1Q2023 = '000165204423000045'

# Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10q_1Q2023 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_1Q2023, statement_name='rsu')
shares_10q_1Q2023 = f_sec.rename_statement(shares_10q_1Q2023, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10q_1Q2023 = shares_10q_1Q2023.drop('us-gaap_WeightedAverageNumberOfSharesOutstandingBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10q_1Q2023 = shares_10q_1Q2023.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10q_1Q2023 = shares_10q_1Q2023.iloc[[3, 7, 13, 17]]

# Renomeando a linha do índice
shares_10q_1Q2023 = shares_10q_1Q2023.rename(index={
    17: 'RSUs',
    3: 'Class A',
    7: 'Class B',
    13: 'Class C',
})

# Os dfs dos 'acc_num' de 2Q2023 e 3Q2023 tinham tamanhos iguais
lst_acc_2023 = [
    '000165204423000070',  # 2Q2023
    '000165204423000094',  # 3Q2023
]

shares_lst_2023 = []

for acc_num in lst_acc_2023:
    # Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
    shares_10q_2023 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='rsu')
    shares_10q_2023 = f_sec.rename_statement(shares_10q_2023, label_dictionary=labels_dict)
    # Selecionando a 1º e 2º coluna do df que são os nº não acumulados
    shares_10q_2023 = shares_10q_2023.iloc[:, [0,1]]
    # Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
    shares_10q_2023 = shares_10q_2023.drop('us-gaap_WeightedAverageNumberOfSharesOutstandingBasicAbstract')
    # Resetando o index do df, porque ele possui vários index iguais
    shares_10q_2023 = shares_10q_2023.reset_index(drop=True)
    shares_lst_2023.append(shares_10q_2023)

# Concatenando os dfs
df_shares_10q_2022_2023 = pd.concat(shares_lst_2023, ignore_index=True, axis=1)

# Selecionando as linhas desejadas
df_shares_10q_2022_2023 = df_shares_10q_2022_2023.iloc[[3, 7, 15, 20]]

# Renomeando a linha do índice e as colunas
df_shares_10q_2022_2023 = df_shares_10q_2022_2023.rename(index={
    20: 'RSUs',
    3: 'Class A',
    7: 'Class B',
    15: 'Class C',
})

df_shares_10q_2022_2023 = df_shares_10q_2022_2023.rename(columns={
    0: '2023-06-30',
    1: '2022-06-30',
    2: '2023-09-30',
    3: '2022-09-30',
})

# Concatenando os dfs de 1Q2023
df_shares_10q_2022_2023 = pd.concat([df_shares_10q_2022_2023, shares_10q_1Q2023], axis=1)

# Transformando as colunas em datetime
df_shares_10q_2022_2023.columns = pd.to_datetime(df_shares_10q_2022_2023.columns, format='%Y-%m-%d')

# Ordenando as colunas
df_shares_10q_2022_2023 = df_shares_10q_2022_2023[sorted(df_shares_10q_2022_2023.columns, reverse=True)]

###################################################################################################################
# Dados dos nº de ações (Class A, B, C e RSUs) de 2024 e 2025
# 'acc_num' de 1Q2025
acc_num_1Q2025 = '000165204425000043'

# Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10q_1Q2025 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_1Q2025, statement_name='rsu')
shares_10q_1Q2025 = f_sec.rename_statement(shares_10q_1Q2025, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10q_1Q2025 = shares_10q_1Q2025.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10q_1Q2025 = shares_10q_1Q2025.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10q_1Q2025 = shares_10q_1Q2025.iloc[[5, 11, 15, 26]]

# Renomeando a linha do índice
shares_10q_1Q2025 = shares_10q_1Q2025.rename(index={
    5: 'RSUs',
    11: 'Class A',
    15: 'Class B',
    26: 'Class C',
})

# Os dfs dos 'acc_num' de 2Q2025 e 3Q2025 tinham tamanhos iguais
lst_acc_2025 = [
    '000165204425000062',  # 2Q2025
    '000165204425000091',  # 3Q2025
]

shares_lst_2025 = []

for acc_num in lst_acc_2025:
    # Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
    shares_10q_2025 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='rsu')
    shares_10q_2025 = f_sec.rename_statement(shares_10q_2025, label_dictionary=labels_dict)
    # Selecionando a 1º e 2º coluna do df que são os nº não acumulados
    shares_10q_2025 = shares_10q_2025.iloc[:, [0,1]]
    # Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
    shares_10q_2025 = shares_10q_2025.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')
    # Resetando o index do df, porque ele possui vários index iguais
    shares_10q_2025 = shares_10q_2025.reset_index(drop=True)
    shares_lst_2025.append(shares_10q_2025)

# Concatenando os dfs
df_shares_10q_2024_2025 = pd.concat(shares_lst_2025, ignore_index=True, axis=1)

# Selecionando as linhas desejadas
df_shares_10q_2024_2025 = df_shares_10q_2024_2025.iloc[[5, 11, 15, 26]]

# Renomeando a linha do índice
df_shares_10q_2024_2025 = df_shares_10q_2024_2025.rename(index={
    5: 'RSUs',
    11: 'Class A',
    15: 'Class B',
    26: 'Class C',
})

df_shares_10q_2024_2025 = df_shares_10q_2024_2025.rename(columns={
    0: '2025-06-30',
    1: '2024-06-30',
    2: '2025-09-30',
    3: '2024-09-30',
})

# Concatenando os dfs de 1Q2023
df_shares_10q_2024_2025 = pd.concat([df_shares_10q_2024_2025, shares_10q_1Q2025], axis=1)

# Transformando as colunas em datetime
df_shares_10q_2024_2025.columns = pd.to_datetime(df_shares_10q_2024_2025.columns, format='%Y-%m-%d')

# Ordenando as colunas
df_shares_10q_2024_2025 = df_shares_10q_2024_2025[sorted(df_shares_10q_2024_2025.columns, reverse=True)]

###################################################################################################################
# 'acc_num' de 1Q2026
acc_num_1Q2026 = '000165204426000048'

# Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10q_1Q2026 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_1Q2026, statement_name='rsu')
shares_10q_1Q2026 = f_sec.rename_statement(shares_10q_1Q2026, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10q_1Q2026 = shares_10q_1Q2026.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10q_1Q2026 = shares_10q_1Q2026.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10q_1Q2026 = shares_10q_1Q2026.iloc[[5, 11, 15, 27]]

# Renomeando a linha do índice
shares_10q_1Q2026 = shares_10q_1Q2026.rename(index={
    5: 'RSUs',
    11: 'Class A',
    15: 'Class B',
    27: 'Class C',
})

# Selecionando a 1º coluna do df que são os nº não acumulados
shares_10q_1Q2026 = shares_10q_1Q2026.iloc[:, [0]]

###################################################################################################################
# 'acc_num' de 2Q2026
acc_num_2Q2026 = '000165204426000071'

# Fazendo o scraping do restricted stock units -> 'Note 11 – Share-Based Compensation' -> 'Number of RSUs'
shares_10q_2Q2026 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2Q2026, statement_name='rsu')
shares_10q_2Q2026 = f_sec.rename_statement(shares_10q_2Q2026, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
shares_10q_2Q2026 = shares_10q_2Q2026.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')

# Resetando o index do df, porque ele possui vários index iguais
shares_10q_2Q2026 = shares_10q_2Q2026.reset_index(drop=True)

# Selecionando as linhas desejadas
shares_10q_2Q2026 = shares_10q_2Q2026.iloc[[7, 14, 19, 31]]

# Renomeando a linha do índice
shares_10q_2Q2026 = shares_10q_2Q2026.rename(index={
    7: 'RSUs',
    14: 'Class A',
    19: 'Class B',
    31: 'Class C',
})

# Selecionando a 1º coluna do df que são os nº não acumulados
shares_10q_2Q2026 = shares_10q_2Q2026.iloc[:, [0]]

###################################################################################################################
# Concatenando todos os dfs
df_shares_10q = pd.concat([
    df_shares_10q_2020_2021,
    df_shares_10q_2022_2023,
    df_shares_10q_2024_2025,
    shares_10q_1Q2026,
    shares_10q_2Q2026
], axis=1)

# Ordenando as colunas
df_shares_10q = df_shares_10q[sorted(df_shares_10q.columns, reverse=True)]

# Arrumando e adicionando alguns números no df
df_shares_10q.loc['Class A', '2022-03-31'] = 300478 		
df_shares_10q.loc['Class B', '2022-03-31'] = 44535 
df_shares_10q.loc['Class C', '2022-03-31'] = 315158 
df_shares_10q.loc['RSUs', '2022-03-31'] = 5

df_shares_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')
    interest_expense_10q.to_excel(writer, sheet_name='interest_expense')
    df_shares_10q.to_excel(writer, sheet_name='num_shares')

### Indicadores Fundamentalistas

In [210]:
# Lendo os arquivos 10k
googl_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

googl_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

googl_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

googl_leases = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx', 
    sheet_name='leases', 
    index_col='Unnamed: 0'
)

googl_current_portion_lease = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx', 
    sheet_name='current_portion_lease', 
    index_col='Unnamed: 0'
)

googl_shares = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10k.xlsx', 
    sheet_name='num_shares',
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
googl_bs.columns = pd.to_datetime(googl_bs.columns)
googl_is.columns = pd.to_datetime(googl_is.columns)
googl_cf.columns = pd.to_datetime(googl_cf.columns)
googl_leases.columns = pd.to_datetime(googl_leases.columns)
googl_current_portion_lease.columns = pd.to_datetime(googl_current_portion_lease.columns)
googl_shares.columns = pd.to_datetime(googl_shares.columns)

# Transformando as colunas em apenas o ano
googl_bs.columns = googl_bs.columns.year
googl_is.columns = googl_is.columns.year
googl_cf.columns = googl_cf.columns.year
googl_leases.columns = googl_leases.columns.year
googl_current_portion_lease.columns = googl_current_portion_lease.columns.year
googl_shares.columns = googl_shares.columns.year

# Removendo a linha 'RSUs'
googl_shares = googl_shares.drop(index='RSUs')
# Fazendo a soma entre o nº de ações das classes A, B e C
googl_shares_total = googl_shares.sum()
# Transformando em um df
df_googl_shares_total = pd.DataFrame(googl_shares_total).T
# Transformando em float
df_googl_shares_total = df_googl_shares_total.astype(float)
# Arrumando a escala das colunas
df_googl_shares_total.loc[:, 2021] = df_googl_shares_total.loc[:, 2021].values[0] / 1000
df_googl_shares_total.loc[:, 2020] = df_googl_shares_total.loc[:, 2020].values[0] / 1000
df_googl_shares_total.loc[:, 2019] = df_googl_shares_total.loc[:, 2019].values[0] / 1000
df_googl_shares_total.loc[:, 2018] = df_googl_shares_total.loc[:, 2018].values[0] / 1000
df_googl_shares_total.loc[:, 2017] = df_googl_shares_total.loc[:, 2017].values[0] / 1000
# Renomeando o index
df_googl_shares_total = df_googl_shares_total.rename({0: 'Number of Shares - Basic'})
# Arrendondamento das casas decimais
df_googl_shares_total = df_googl_shares_total.round(2)
# Concatenando os dados de nº de ações no income statement
googl_is = pd.concat([googl_is, df_googl_shares_total])

In [211]:
# Preços da GOOGL
googl_close = yf.download('GOOGL', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025'
]

last_dec_close = []

for year in lst_years:
    last_close = googl_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
googl_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
googl_close_dec = googl_close_dec.reindex(index=googl_close_dec.index[::-1])

# Arredondamento de duas casas decimais
googl_close_dec = round(googl_close_dec, 2)

# Teve um split de 20:1 em 18/07/2022 (https://br.investing.com/equities/google-inc-historical-data-splits)
googl_close_dec.loc['2021'] = googl_close_dec.loc['2021'] * 20
googl_close_dec.loc['2020'] = googl_close_dec.loc['2020'] * 20
googl_close_dec.loc['2019'] = googl_close_dec.loc['2019'] * 20
googl_close_dec.loc['2018'] = googl_close_dec.loc['2018'] * 20
googl_close_dec.loc['2017'] = googl_close_dec.loc['2017'] * 20

# Transformando o index em int
googl_close_dec .index = googl_close_dec .index.astype(int)

googl_close_dec

[*********************100%***********************]  1 of 1 completed

2025     312.39
2024     188.20
2023     138.37
2022      87.40
2021    2869.80
2020    1736.20
2019    1326.80
2018    1035.20
2017    1043.40
dtype: float64

In [212]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = googl_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=googl_close_dec, df_is=googl_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=googl_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=googl_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=googl_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=googl_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=googl_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=googl_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=googl_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=googl_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=googl_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=googl_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=googl_bs, df_is=googl_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=googl_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=googl_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Long-term Debt', 'Operating Lease Liabilities']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=googl_bs, lst_itens_divida=lst_divida)
div_bruta_total = div_bruta.values + googl_leases.values + googl_current_portion_lease.values
div_bruta_total = pd.Series(div_bruta_total[0], index=idx)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta_total, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=googl_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=googl_is, df_bs=googl_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=googl_is, df_bs=googl_bs, div_bruta=div_bruta_total, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=googl_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=googl_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=googl_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=googl_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=googl_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Net Proceeds Payments Related To Stock Based Award Activities']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=googl_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=googl_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=googl_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Income Taxes',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Accrued Revenue Share',
    'Increase (Decrease) in Contract with Customer, Liability'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=googl_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=googl_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Debt, Net of Issuance Costs']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=googl_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt and Lease Obligation']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=googl_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=googl_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=googl_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=googl_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=googl_cf, df_is=googl_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=googl_cf, df_is=googl_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=googl_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=googl_bs, df_is=googl_is)

# DIO - não divulga o invetário no 10-k

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=googl_bs, df_is=googl_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=googl_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=googl_bs, df_is=googl_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=googl_is, df_bs=googl_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=googl_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta_total,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    # dio - não divulga o invetário no 10-k
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
googl_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    # 'DIO' - não divulga o invetário no 10-k
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
googl_indicadores_10k.columns = nomes_col
googl_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Payout,Buyback,DSO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,28.64,28.63,3.49,150175.0,32.81,59.65,32.03,37.28,9.12,3.784917e+09,...,7.60,45709,56.979490,27.397176,1.246221,0.156108,-0.062251,1.096807,0.554332,4.326599
2024,23.16,23.15,4.32,127701.0,28.60,58.20,32.11,36.48,7.13,2.318436e+09,...,7.35,62222,54.580336,19.925738,1.251513,0.149535,-0.059065,0.981190,0.726782,3.431193
2023,23.68,23.69,4.22,96239.0,24.01,56.63,27.42,31.31,6.17,1.747613e+09,...,0.00,61504,56.952510,20.512293,1.378765,0.156034,-0.072822,1.057222,0.941730,2.699732
2022,19.04,19.04,5.25,90129.0,21.20,55.38,26.46,31.87,4.46,1.141706e+09,...,0.00,59296,51.952969,14.831026,1.525629,0.142337,-0.087016,1.015156,1.000634,2.059593
2021,25.20,25.20,3.97,90269.0,29.51,56.94,30.55,35.04,7.61,1.916022e+09,...,0.00,50274,55.682841,19.862312,1.205424,0.152556,-0.046014,1.015321,0.881354,2.132410
2020,29.35,29.35,3.41,54129.0,22.06,53.58,22.59,29.66,5.31,1.182040e+09,...,0.00,31149,61.850849,24.075733,1.617224,0.169454,-0.083473,1.203126,1.063920,1.726540
2019,26.76,26.76,3.74,45087.0,21.22,55.58,21.15,27.86,4.56,9.189417e+08,...,0.00,18396,57.112080,28.231960,1.587514,0.156471,-0.079328,1.209218,0.901843,2.169123
2018,23.41,23.41,4.27,34485.0,22.46,56.48,19.24,25.20,4.05,7.196089e+08,...,0.00,9075,55.590744,26.834540,1.560743,0.152303,-0.080147,1.391069,0.742842,3.079250
2017,57.10,57.11,1.75,32249.0,11.42,58.88,23.59,29.09,4.74,7.229719e+08,...,0.00,4846,60.372920,25.119123,2.929316,0.165405,NaN,1.150144,1.888090,2.160249

In [213]:
# Lendo os arquivos 10q
googl_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

googl_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

googl_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

googl_shares_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_10q.xlsx',
    sheet_name='num_shares',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
googl_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in googl_bs_10q.columns]
googl_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in googl_is_10q.columns]
googl_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in googl_cf_10q.columns]
googl_shares_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in googl_shares_10q.columns]

# Removendo a linha 'RSUs'
googl_shares_10q = googl_shares_10q.drop(index='RSUs')
# Fazendo a soma entre o nº de ações das classes A, B e C
googl_shares_total_10q = googl_shares_10q.sum()
# Transformando em um df
df_googl_shares_total_10q = pd.DataFrame(googl_shares_total_10q).T
# Transformando em float
df_googl_shares_total_10q = df_googl_shares_total_10q.astype(float)
# Arrumando a escala das colunas
df_googl_shares_total_10q.loc[:, '2022-06-30'] = df_googl_shares_total_10q.loc[:, '2022-06-30'].values[0] / 10    # Eu dividi por 10 para ficar na mesma escala que os outros trimestres
df_googl_shares_total_10q.loc[:, '2022-03-31'] = df_googl_shares_total_10q.loc[:, '2022-03-31'].values[0] / 1000
df_googl_shares_total_10q.loc[:, '2021-09-30'] = df_googl_shares_total_10q.loc[:, '2021-09-30'].values[0] / 1000
df_googl_shares_total_10q.loc[:, '2021-06-30'] = df_googl_shares_total_10q.loc[:, '2021-06-30'].values[0] / 1000
df_googl_shares_total_10q.loc[:, '2021-03-31'] = df_googl_shares_total_10q.loc[:, '2021-03-31'].values[0] / 1000
df_googl_shares_total_10q.loc[:, '2020-09-30'] = df_googl_shares_total_10q.loc[:, '2020-09-30'].values[0] / 1000
df_googl_shares_total_10q.loc[:, '2020-06-30'] = df_googl_shares_total_10q.loc[:, '2020-06-30'].values[0] / 1000
df_googl_shares_total_10q.loc[:, '2020-03-31'] = df_googl_shares_total_10q.loc[:, '2020-03-31'].values[0] / 1000
# Renomeando o index
df_googl_shares_total_10q = df_googl_shares_total_10q.rename({0: 'Number of Shares - Basic'})
# Arrendondamento das casas decimais
df_googl_shares_total_10q = df_googl_shares_total_10q.round(2)
# Concatenando os dados de nº de ações no income statement
googl_is_10q = pd.concat([googl_is_10q, df_googl_shares_total_10q])

In [214]:
# Preços da GOOGL
googl_close = yf.download('GOOGL', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025',
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = googl_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
googl_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
googl_close_months = googl_close_months.reindex(index=googl_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = googl_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
googl_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
googl_close_months_atual = googl_close_months_atual.reindex(index=googl_close_months_atual.index[::-1])

# Juntando as duas series pandas
googl_close_months = pd.concat([googl_close_months_atual, googl_close_months])

# Arredondamento de duas casas decimais
googl_close_months = round(googl_close_months, 2)

# Teve um split de 20:1 em 18/07/2022 (https://br.investing.com/equities/google-inc-historical-data-splits)
googl_close_months.loc['06-2022'] = googl_close_months.loc['06-2022'] * 20
googl_close_months.loc['03-2022'] = googl_close_months.loc['03-2022'] * 20
googl_close_months.loc['09-2021'] = googl_close_months.loc['09-2021'] * 20
googl_close_months.loc['06-2021'] = googl_close_months.loc['06-2021'] * 20
googl_close_months.loc['03-2021'] = googl_close_months.loc['03-2021'] * 20

# Substituindo o index para ficar igual ao dos dados fundamentalistas
googl_close_months.index = googl_bs_10q.columns[:-3]

googl_close_months

[*********************100%***********************]  1 of 1 completed

2026-06-30     357.14
2026-03-31     287.20
2025-09-30     242.47
2025-06-30     175.62
2025-03-31     153.91
2024-09-30     164.69
2024-06-30     180.64
2024-03-31     149.51
2023-09-30     129.63
2023-06-30     118.57
2023-03-31     102.75
2022-09-30      94.75
2022-06-30    2158.80
2022-03-31    2755.20
2021-09-30    2648.40
2021-06-30    2418.80
2021-03-31    2043.00
dtype: float64

In [215]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = googl_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=googl_close_months, df_is=googl_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=googl_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=googl_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=googl_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=googl_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=googl_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=googl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=googl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=googl_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=googl_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=googl_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=googl_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=googl_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=googl_bs_10q, df_is=googl_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=googl_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=googl_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta - não somei o custo dos 'leases' e 'current portion lease', porque eles não são divulgados no 10q
lst_divida = ['Long-term Debt', 'Operating Lease Liabilities']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=googl_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q =  f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=googl_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=googl_is_10q, df_bs=googl_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=googl_is_10q, df_bs=googl_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa
lst_custos_cf = ['Net Proceeds Payments Related To Stock Based Award Activities']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=googl_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=googl_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=googl_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=googl_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=googl_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Income Taxes',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Accrued Revenue Share',
    'Increase (Decrease) in Contract with Customer, Liability'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=googl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=googl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=googl_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=googl_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Debt, Net of Issuance Costs']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Repayments of Debt and Lease Obligation']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=googl_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=googl_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=googl_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=googl_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=googl_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=googl_cf_10q, df_is=googl_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=googl_cf_10q, df_is=googl_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=googl_cf_10q, first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=googl_bs_10q, df_is=googl_is_10q)

# DIO - divulga o invetário no 10-q
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=googl_bs_10q, df_is=googl_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=googl_bs_10q, df_is=googl_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=googl_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=googl_bs_10q, df_is=googl_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=googl_is_10q, df_bs=googl_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=googl_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
googl_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
googl_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
googl_indicadores_10q = googl_indicadores_10q.fillna(0)

googl_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,38.68,18.20,5.49,47874.0,167160.0,93.65,61.65,34.03,39.96,6.78,...,0.0,210.765593,79.374769,160.942255,0.348230,0.577440,0.102700,0.816080,0.303254,6.323761
2026-03-31,55.53,21.71,4.61,46178.0,154379.0,56.94,62.45,36.12,42.02,7.26,...,0.0,209.239963,0.000000,149.038792,0.731727,0.573260,0.028471,0.991598,0.940123,5.503548
2025-09-30,83.78,23.77,4.21,36839.0,140707.0,34.18,59.58,30.51,35.99,7.57,...,11504.0,203.808845,0.000000,93.047693,1.384088,0.558380,-0.027795,1.314205,1.896910,4.268936
2025-06-30,75.50,19.05,5.25,36269.0,135001.0,29.24,59.51,32.43,37.61,5.87,...,13638.0,208.368109,0.000000,78.041318,0.984076,0.570872,0.000979,0.765033,1.962867,4.490996
2025-03-31,54.29,17.49,5.72,35093.0,127617.0,38.28,59.70,33.92,38.89,5.43,...,15068.0,206.296961,0.000000,85.294821,1.046613,0.565197,-0.003648,1.030120,1.936306,3.832628
2024-09-30,76.96,21.90,4.57,32506.0,117538.0,29.80,58.68,32.31,36.83,6.44,...,15291.0,203.051616,0.000000,70.540248,1.167180,0.556306,-0.010634,0.944379,2.681571,3.277541
2024-06-30,94.40,26.45,3.78,31133.0,110149.0,27.87,58.10,32.36,36.74,7.41,...,15684.0,202.812714,0.000000,62.623708,1.127905,0.555651,-0.007573,0.855684,3.161395,3.556095
2024-03-31,78.45,24.51,4.08,28885.0,99491.0,29.38,58.14,31.63,35.86,6.34,...,15696.0,201.908144,0.000000,67.105778,1.219170,0.553173,-0.013352,0.998719,3.314809,3.519484
2023-09-30,82.83,24.64,4.06,25014.0,91674.0,25.67,56.67,27.83,32.62,5.97,...,15787.0,195.223814,32.480815,63.742364,1.557012,0.534860,-0.029053,1.225554,3.945147,2.194225
2023-06-30,81.78,7.47,13.39,25117.0,89811.0,24.62,57.22,29.27,33.67,5.62,...,14969.0,189.848534,25.514319,60.760904,1.560649,0.520133,-0.027899,1.141299,3.684070,2.100640
2023-03-31,87.25,2.61,38.28,20475.0,88379.0,21.57,56.14,24.95,29.34,5.03,...,14557.0,188.475504,27.602737,49.887626,1.561956,0.516371,-0.023281,1.148181,4.066906,2.055229
2022-09-30,88.67,1.42,70.28,21068.0,92020.0,20.13,54.90,24.80,30.49,4.86,...,15392.0,183.297705,36.970922,73.836414,1.678864,0.502185,-0.026764,1.108458,4.508339,1.849987
2022-06-30,177.17,23.16,4.32,23151.0,93043.0,22.96,56.80,27.92,33.22,11.10,...,15197.0,187.028127,24.006777,53.457514,1.213723,0.512406,-0.009905,0.838927,3.938758,1.846403
2022-03-31,110.67,25.59,3.91,23685.0,88854.0,24.17,56.48,29.55,34.83,7.16,...,13300.0,186.243328,16.881820,42.371026,1.527501,0.510256,-0.025344,1.059996,3.880567,2.725146
2021-09-30,93.11,26.67,3.75,24116.0,79671.0,29.08,57.58,32.30,37.03,7.21,...,12610.0,190.840551,16.888237,60.998516,1.348701,0.522851,-0.020422,1.059006,3.171631,2.210373
2021-06-30,87.35,29.83,3.35,22091.0,65116.0,29.94,57.62,31.29,35.70,6.81,...,12796.0,188.557773,12.622679,65.521028,1.181646,0.516597,-0.010963,0.990901,2.695816,2.013187
2021-03-31,76.71,32.25,3.10,18962.0,53901.0,32.41,56.43,29.72,34.28,5.98,...,11395.0,184.802943,13.447289,72.703190,1.075795,0.506309,-0.004526,1.017245,2.174679,2.353267

In [218]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//google//googl_indicators.xlsx') as writer:
    googl_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    googl_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Meta

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'meta'
f_sec.cik_matching_ticker(ticker)

### Scraping Meta 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_meta = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017, 2018, 2019, 2020, 2021, 2022 e 2023
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000132680124000012', # 2023
            '000132680123000013', # 2022
            '000132680122000018', # 2021
            '000132680121000014', # 2020
            '000132680120000013', # 2019
            '000132680119000009', # 2018
            '000132680118000009', # 2017
        ]
    },
    index=pd.to_datetime([
        '2023-12-31', 
        '2022-12-31', 
        '2021-12-31', 
        '2020-12-31',
        '2019-12-31',
        '2018-12-31',
        '2017-12-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_meta = pd.concat([df_lst_acc_num_meta, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_meta.index = pd.to_datetime(df_lst_acc_num_meta.index, format='%Y-%m-%d')

df_lst_acc_num_meta

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_meta['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Marketable Securities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Debt Securities, Available-for-sale, Current'
df_balance_sheet_10k.loc['Marketable Securities, Current', '2021-12-31'] = df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2021-12-31'] 
df_balance_sheet_10k.loc['Marketable Securities, Current', '2020-12-31'] = df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2020-12-31'] 
df_balance_sheet_10k.loc['Marketable Securities, Current', '2019-12-31'] = df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2019-12-31'] 
df_balance_sheet_10k.loc['Marketable Securities, Current', '2018-12-31'] = df_balance_sheet_10k.loc['Debt Securities, Available-for-sale, Current', '2018-12-31'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'fb_PropertyPlantAndEquipmentAndFinanceLeaseRightofUseAssetAfterAccumulatedDepreciationAndAmortization' e 'Property, Plant and Equipment, Net'
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2019-12-31'] = df_balance_sheet_10k.loc['fb_PropertyPlantAndEquipmentAndFinanceLeaseRightofUseAssetAfterAccumulatedDepreciationAndAmortization', '2019-12-31'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2018-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2018-12-31'] 
df_balance_sheet_10k.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2017-12-31'] = df_balance_sheet_10k.loc['Property, Plant and Equipment, Net', '2017-12-31'] 


# A linha 'meta_NonmarketableEquitySecuritiesCarryingValue' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'fb_NonmarketableEquitySecuritiesCarryingValue' e 'Equity Securities without Readily Determinable Fair Value, Amount'
df_balance_sheet_10k.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2021-12-31'] = df_balance_sheet_10k.loc['fb_NonmarketableEquitySecuritiesCarryingValue', '2021-12-31'] 
df_balance_sheet_10k.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2020-12-31'] = df_balance_sheet_10k.loc['Equity Securities without Readily Determinable Fair Value, Amount', '2020-12-31'] 

# A linha 'Accounts Payable, Trade, Current' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'Accounts Payable, Other, Current'
df_balance_sheet_10k.loc['Accounts Payable, Trade, Current', '2018-12-31'] = df_balance_sheet_10k.loc['Accounts Payable, Other, Current', '2018-12-31'] 
df_balance_sheet_10k.loc['Accounts Payable, Trade, Current', '2017-12-31'] = df_balance_sheet_10k.loc['Accounts Payable, Other, Current', '2017-12-31'] 

# A linha 'Contract with Customer, Liability, Current' na coluna abaixo estão zeradas
# As informações estão nas linhas 'fb_ContractWithCustomerLiabilityAndUnusedDeposits'
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2021-12-31'] = df_balance_sheet_10k.loc['fb_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-12-31'] 
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2017-12-31'] = df_balance_sheet_10k.loc['Deferred Revenue and Credits, Current', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Debt Securities, Available-for-sale, Current',
    'fb_PropertyPlantAndEquipmentAndFinanceLeaseRightofUseAssetAfterAccumulatedDepreciationAndAmortization',
    'Property, Plant and Equipment, Net',
    'fb_NonmarketableEquitySecuritiesCarryingValue',
    'Equity Securities without Readily Determinable Fair Value, Amount',
    'Accounts Payable, Other, Current',
    'fb_ContractWithCustomerLiabilityAndUnusedDeposits',
    'Deferred Revenue and Credits, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Common Stock, Value, Issued'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc['Accrued Income Taxes, Noncurrent', '2023-12-31'] = 7514
df_balance_sheet_10k.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2019-12-31'] = 86

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'meta_NonmarketableEquitySecuritiesCarryingValue': 'Non-marketable Equity Securities Carrying Value',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_meta['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' na coluna abaixo está zerada
# As informações estão na linha 'Revenues'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-12-31'] = df_income_statement_10k.loc['Revenues', '2017-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop('Revenues')

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
    'us-gaap_CostsAndExpensesAbstract',
    'Undistributed Earnings (Loss) Allocated to Participating Securities, Basic',
    'Net Income (Loss) Available to Common Stockholders, Basic'
])

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10k.loc['Cost of Revenue']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_meta['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Deferred Income Taxes and Tax Credits' nas colunas abaixo estão zeradas
# As informações estão na linha 'Deferred Income Tax Expense (Benefit)'
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2023-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2023-12-31'] 
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2022-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2022-12-31'] 
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2021-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2021-12-31'] 
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2020-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2020-12-31'] 
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2019-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2019-12-31'] 
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2018-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2018-12-31'] 
df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2017-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2017-12-31'] 

# A linha 'meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets' nas colunas abaixo estão zeradas
# As informações estão na linha 'fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets'
df_cash_flow_10k.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2021-12-31'] = df_cash_flow_10k.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2021-12-31'] 
df_cash_flow_10k.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-12-31'] = df_cash_flow_10k.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-12-31'] 
df_cash_flow_10k.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2019-12-31'] = df_cash_flow_10k.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2019-12-31'] 
df_cash_flow_10k.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2018-12-31'] = df_cash_flow_10k.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2018-12-31'] 
df_cash_flow_10k.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2017-12-31'] = df_cash_flow_10k.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2017-12-31'] 

# A linha 'Payments to Acquire Marketable Securities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Debt Securities, Available-for-sale'
df_cash_flow_10k.loc['Payments to Acquire Marketable Securities', '2023-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2023-12-31'] 
df_cash_flow_10k.loc['Payments to Acquire Marketable Securities', '2022-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2022-12-31'] 
df_cash_flow_10k.loc['Payments to Acquire Marketable Securities', '2021-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Debt Securities, Available-for-sale', '2021-12-31'] 

# A linha 'Increase (Decrease) in Accounts Payable, Trade' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accounts Payable'
df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable, Trade', '2018-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable', '2018-12-31'] 
df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable, Trade', '2017-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Accounts Payable', '2017-12-31'] 

# A linha 'meta_AcquisitionOfBusinessAndIntangibleAssets' nas colunas abaixo estão zeradas
# As informações estão na linha 'meta_AcquisitionIncurredButNotYetPaid'
df_cash_flow_10k.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2023-12-31'] = df_cash_flow_10k.loc['meta_AcquisitionIncurredButNotYetPaid', '2023-12-31'] 
df_cash_flow_10k.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2022-12-31'] = df_cash_flow_10k.loc['meta_AcquisitionIncurredButNotYetPaid', '2022-12-31'] 

# A linha 'Impairment of Long-Lived Assets Held-for-use' na coluna abaixo está zerada
# As informações estão na linha 'us-gaap_RestructuringCharges'
df_cash_flow_10k.loc['Impairment of Long-Lived Assets Held-for-use', '2022-12-31'] = df_cash_flow_10k.loc['us-gaap_RestructuringCharges', '2022-12-31'] 

# A linha 'Increase (Decrease) in Other Noncurrent Liabilities' na coluna abaixo está zerada
# As informações estão na linha 'Increase (Decrease) in Other Operating Liabilities'
df_cash_flow_10k.loc['Increase (Decrease) in Other Noncurrent Liabilities', '2017-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Other Operating Liabilities', '2017-12-31'] 

# A linha 'Proceeds from Sale and Maturity of Marketable Securities' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale'
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2023-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2023-12-31'] 

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' na coluna abaixo está zerada
# As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-12-31'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2017-12-31'] 

# A linha 'meta_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities' na coluna abaixo está zerada
# As informações estão na linha 'fb_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities'
df_cash_flow_10k.loc['meta_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities', '2021-12-31'] = df_cash_flow_10k.loc['fb_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities', '2021-12-31'] 

# A linha 'meta_OtherSignificantNoncashTransaction' na coluna abaixo está zerada
# As informações estão na linha 'fb_OtherSignificantNoncashTransaction'
df_cash_flow_10k.loc['meta_OtherSignificantNoncashTransaction', '2021-12-31'] = df_cash_flow_10k.loc['fb_OtherSignificantNoncashTransaction', '2021-12-31'] 

# A linha 'Proceeds from Sale of Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities'
df_cash_flow_10k.loc['Proceeds from Sale of Debt Securities, Available-for-sale', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-12-31'] 

# A linha 'Increase (Decrease) in Contract with Customer, Liability' na coluna abaixo está zerada
# As informações estão na linha 'Increase (Decrease) in Deferred Revenue and Customer Advances and Deposits'
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue and Customer Advances and Deposits', '2017-12-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Deferred Income Tax Expense (Benefit)',
    'fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets',
    'Payments to Acquire Debt Securities, Available-for-sale',
    'Increase (Decrease) in Accounts Payable',
    'meta_AcquisitionIncurredButNotYetPaid',
    'us-gaap_RestructuringCharges',
    'Increase (Decrease) in Other Operating Liabilities',
    'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'fb_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities',
    'fb_OtherSignificantNoncashTransaction',
    'Proceeds from Sale of Available-for-sale Securities',
    'Increase (Decrease) in Deferred Revenue and Customer Advances and Deposits'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'fb_RepaymentsOfCapitalLeaseAndOtherFinancingObligations',
    'Restricted Cash and Cash Equivalents, Current',
    'Restricted Cash and Cash Equivalents, Noncurrent',
    'Notes Issued',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities',
    'fb_TaxBenefitfromSharebasedCompensationOperatingActivities',
    'meta_PaymentsForEquitySecuritiesWithoutReadilyDeterminableFairValue',
    'fb_IncreaseDecreaseInPrepaidsAndLiabilitiesRelatedToPropertyAndEquipmentAdditions',
    'fb_IncreaseDecreaseinPrepaidsandLiabilitiesRelatedtoPropertyandEquipmentAdditions',
    'fb_SettlementOfContingentConsiderationLiability',
    'fb_IncreaseDecreaseInRestrictedCashAndDeposits',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Equity Securities, FV-NI, Gain (Loss)',
    'fb_ChangeinUnsettledRepurchasesofCommonStock',
    'fb_AcquisitionIncurredButNotYetPaid',
    'fb_PaymentsForEquitySecuritiesWithoutReadilyDeterminableFairValue',
    'Restricted Cash and Cash Equivalents',
    'meta_OtherSignificantNoncashTransaction',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash and Cash Equivalents, at Carrying Value'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Proceeds from Sale and Maturity of Marketable Securities', '2022-12-31'] = 13158
df_cash_flow_10k.loc['Payments for (Proceeds from) Other Investing Activities', '2017-12-31'] = -13
df_cash_flow_10k.loc['Capital Expenditures Incurred but Not yet Paid', '2018-12-31'] = 1955

df_cash_flow_10k.loc['Finance Lease, Principal Payments', '2018-12-31'] = -3208
df_cash_flow_10k.loc['Finance Lease, Principal Payments', '2017-12-31'] = -3246

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets': 'Payments To Acquire Businesses Net Of Cash Acquired And Purchases Of Intangible And Other Assets',
    'meta_AcquisitionOfBusinessAndIntangibleAssets': 'Acquisition Of Business And Intangible Assets',
    'meta_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities': 'Repurchase Of Common Stock In Accrued Expenses And Other Current Liabilities',
    'meta_UnrealizedGainLossOnMarketableAndNonmarketableEquityInvestments': 'Unrealized Gain Loss On Marketable And Nonmarketable Equity Investments',
    'meta_PaymentsForHeldForSaleAssets': 'Payments For Held For Sale Assets',
    'meta_ProceedsFromOneTimeVentureDistribution': 'Proceeds From One Time Venture Distribution'
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Accounts Payable, Current': 'Accounts Payable',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'

})

In [ ]:
# Selecionando o 'acc_num' do ano mais recente
last_acc_num = df_lst_acc_num_meta.iloc[0].item()

# Fazendo o scraping do interent expense (10-K) -> 'Note 14. Interest and Other Income (Expense), Net'
interest_expense_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='interest_expense')
interest_expense_10k = f_sec.rename_statement(interest_expense_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
interest_expense_10k = interest_expense_10k.drop('us-gaap_OtherIncomeAndExpensesAbstract')

# Renomeando a linha do índice que está sem formato 
interest_expense_10k = interest_expense_10k.rename(index={
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
interest_expense_10k.loc['Interest Expense'] = interest_expense_10k.loc['Interest Expense'] * -1

# Selecionando a linha desejada
interest_expense_10k = interest_expense_10k.loc[['Interest Expense']]

interest_expense_10k

In [ ]:
# 'acc_num' de 2024
acc_num_2024 = '000132680125000017'

# Fazendo o scraping do restructuring (10-K) -> 'Note 3. Restructuring'
restructuring_pretax_charges_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2024, statement_name='restructuring_pretax_charges')
restructuring_pretax_charges_10k = f_sec.rename_statement(restructuring_pretax_charges_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
restructuring_pretax_charges_10k = restructuring_pretax_charges_10k.drop('us-gaap_RestructuringPlanAxis=meta_A2022RestructuringMember')

# Resetando o index do df, porque ele possui vários index iguais
restructuring_pretax_charges_10k = restructuring_pretax_charges_10k.reset_index(drop=True)

# Selecionando as linhas desejadas
restructuring_pretax_charges_10k = restructuring_pretax_charges_10k.iloc[[2]]

# Renomeando a linha do índice
restructuring_pretax_charges_10k = restructuring_pretax_charges_10k.rename(index={
    2: 'Restructuring Pre-tax Charges',
})

# Criando a coluna do ano de 2025
restructuring_pretax_charges_10k['2025-12-31'] = 0

# Ordenando o df
restructuring_pretax_charges_10k = restructuring_pretax_charges_10k[sorted(restructuring_pretax_charges_10k.columns, reverse=True)]

restructuring_pretax_charges_10k

In [ ]:
# 'acc_num' entre 2019 e 2025
df_lst_acc_num_meta_sorted = df_lst_acc_num_meta.sort_index()
acc_num_list_meta_sliced = df_lst_acc_num_meta_sorted.loc['2019':'2025', 'acc_num']

# Fazendo o scraping do leases (10-K)
leases_lst = []

for acc_num in acc_num_list_meta_sliced:

    # Fazendo o scraping do leases (10-K) -> 'Note 8. Leases'
    leases_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10k = f_sec.rename_statement(leases_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10k = leases_10k.iloc[:, 0]
    leases_lst.append(leases_10k)

# Removendo duplicatas de índice em cada série
lease_lst_clean = [df[~df.index.duplicated(keep='first')] for df in leases_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10k = pd.concat(lease_lst_clean, axis=1)

# Renomeando a linha do índice
df_leases_10k = df_leases_10k.rename(index={
    'Operating Lease, Liability': 'Present Value of Lease Liabilities - Operating Leases',
    'Finance Lease, Liability': 'Present Value of Lease Liabilities - Finance Leases',
})

# Selecionando as linhas desejadas
df_leases_10k = df_leases_10k.loc[[
    'Present Value of Lease Liabilities - Operating Leases',
    'Present Value of Lease Liabilities - Finance Leases'
]]

#####################################################################################

# 'acc_num' de 2018
acc_num_2018 = '000132680119000009'

# Fazendo o scraping do leases (10-K) -> 'Note 8. Leases'
leases_10k_2018 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2018, statement_name='leases')
leases_10k_2018 = f_sec.rename_statement(leases_10k_2018, label_dictionary=labels_dict)

# Selecionando a coluna desejada 
leases_10k_2018 = leases_10k_2018.iloc[:, [1]]

# Renomeando a linha do índice
leases_10k_2018 = leases_10k_2018.rename(index={
    'Operating Leases, Future Minimum Payments Due': 'Present Value of Lease Liabilities - Operating Leases'
})

# Criando uma linha nova
leases_10k_2018.loc['Present Value of Lease Liabilities - Finance Leases'] = 0

# Selecionando as linhas desejadas
leases_10k_2018 = leases_10k_2018.loc[[
    'Present Value of Lease Liabilities - Operating Leases', 
    'Present Value of Lease Liabilities - Finance Leases'
]]

#####################################################################################

# 'acc_num' de 2017
acc_num_2017 = '000132680118000009'

# Fazendo o scraping do leases (10-K) -> 'Note 8. Leases'
leases_10k_2017 = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num_2017, statement_name='leases')
leases_10k_2017 = f_sec.rename_statement(leases_10k_2017, label_dictionary=labels_dict)

# Selecionando a coluna desejada 
leases_10k_2017 = leases_10k_2017.iloc[:, [0]]

# Renomeando a linha do índice
leases_10k_2017 = leases_10k_2017.rename(index={
    'Operating Leases, Future Minimum Payments Due': 'Present Value of Lease Liabilities - Operating Leases'
})

# Criando uma linha nova
leases_10k_2017.loc['Present Value of Lease Liabilities - Finance Leases'] = 0

# Selecionando as linhas desejadas
leases_10k_2017 = leases_10k_2017.loc[[
    'Present Value of Lease Liabilities - Operating Leases', 
    'Present Value of Lease Liabilities - Finance Leases'
]]

#####################################################################################

# Concatenando os dfs
df_leases_10k = pd.concat([df_leases_10k, leases_10k_2018, leases_10k_2017], axis=1)

# Ordenando o df
df_leases_10k = df_leases_10k[sorted(df_leases_10k.columns, reverse=True)]

df_leases_10k

In [ ]:
# Fazendo o scraping do restricted stock units (10-K) -> 'Note 4. Earnings per Share'
rsu_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='rsu')
rsu_10k = f_sec.rename_statement(rsu_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
rsu_10k = rsu_10k.drop('us-gaap_NetIncomeLossAvailableToCommonStockholdersBasicAbstract')

# Renomeando a linha do índice
rsu_10k = rsu_10k.rename(index={
    'Incremental Common Shares Attributable to Dilutive Effect of Share-based Payment Arrangements': 'RSUs',
})

# Selecionando a linha desejada
rsu_10k = rsu_10k.loc[['RSUs']]

rsu_10k

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')
    interest_expense_10k.to_excel(writer, sheet_name='interest_expense')
    restructuring_pretax_charges_10k.to_excel(writer, sheet_name='restructuring_pretax_charges')
    df_leases_10k.to_excel(writer, sheet_name='leases')
    rsu_10k.to_excel(writer, sheet_name='num_shares')

### Scraping Meta 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_meta = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 1Q, 2Q e 3Q dos anos de 2020, 2021, 2022 e 2023
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000132680124000049', # 1Q 2024
            '000132680123000103', # 3Q 2023
            '000132680123000093', # 2Q 2023
            '000132680123000067', # 1Q 2023
            '000132680122000108', # 3Q 2022
            '000132680122000082', # 2Q 2022
            '000132680122000057', # 1Q 2022
            '000132680121000065', # 3Q 2021
            '000132680121000049', # 2Q 2021
            '000132680121000033', # 1Q 2021
            '000132680120000084', # 3Q 2020
            '000132680120000076', # 2Q 2020
            '000132680120000048', # 1Q 2020
        ]
    },
    index=pd.to_datetime([
        '2024-03-31',
        '2023-09-30', 
        '2023-06-30',
        '2023-03-31',
        '2022-09-30', 
        '2022-06-30',
        '2022-03-31',
        '2021-09-30', 
        '2021-06-30',
        '2021-03-31',
        '2020-09-30', 
        '2020-06-30',
        '2020-03-31',

    ])
)

# Concatenando os dfs
df_lst_acc_num_10q_meta = pd.concat([df_lst_acc_num_10q_meta, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_10q_meta.index = pd.to_datetime(df_lst_acc_num_10q_meta.index, format='%Y-%m-%d')

df_lst_acc_num_10q_meta

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_meta['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Marketable Securities, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Debt Securities, Available-for-sale, Current' 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2022-03-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2022-03-31'] 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2021-09-30'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2021-09-30'] 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2021-06-30'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2021-06-30'] 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2021-03-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2021-03-31'] 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2020-09-30'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2020-09-30'] 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2020-06-30'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2020-06-30'] 
df_balance_sheet_10q.loc['Marketable Securities, Current', '2020-03-31'] = df_balance_sheet_10q.loc['Debt Securities, Available-for-sale, Current', '2020-03-31'] 

# A linha 'meta_ContractWithCustomerLiabilityAndUnusedDeposits' nas colunas abaixo estão zeradas
# As informações estão na linha 'fb_ContractWithCustomerLiabilityAndUnusedDeposits' 
df_balance_sheet_10q.loc['meta_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-09-30'] = df_balance_sheet_10q.loc['fb_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-09-30'] 
df_balance_sheet_10q.loc['meta_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-06-30'] = df_balance_sheet_10q.loc['fb_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-06-30'] 
df_balance_sheet_10q.loc['meta_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-03-31'] = df_balance_sheet_10q.loc['fb_ContractWithCustomerLiabilityAndUnusedDeposits', '2021-03-31'] 
df_balance_sheet_10q.loc['meta_ContractWithCustomerLiabilityAndUnusedDeposits', '2020-09-30'] = df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2020-09-30'] 
df_balance_sheet_10q.loc['meta_ContractWithCustomerLiabilityAndUnusedDeposits', '2020-06-30'] = df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2020-06-30'] 
df_balance_sheet_10q.loc['meta_ContractWithCustomerLiabilityAndUnusedDeposits', '2020-03-31'] = df_balance_sheet_10q.loc['Contract with Customer, Liability, Current', '2020-03-31'] 

# A linha 'meta_NonmarketableEquitySecuritiesCarryingValue' nas colunas abaixo estão zeradas
# As informações estão na linha 'Equity Securities without Readily Determinable Fair Value, Amount' 
df_balance_sheet_10q.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2021-09-30'] = df_balance_sheet_10q.loc['Equity Securities without Readily Determinable Fair Value, Amount', '2021-09-30'] 
df_balance_sheet_10q.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2021-06-30'] = df_balance_sheet_10q.loc['Equity Securities without Readily Determinable Fair Value, Amount', '2021-06-30'] 
df_balance_sheet_10q.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2021-03-31'] = df_balance_sheet_10q.loc['Equity Securities without Readily Determinable Fair Value, Amount', '2021-03-31'] 
df_balance_sheet_10q.loc['meta_NonmarketableEquitySecuritiesCarryingValue', '2020-09-30'] = df_balance_sheet_10q.loc['Equity Securities without Readily Determinable Fair Value, Amount', '2020-09-30'] 

# A linha 'Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization' nas colunas abaixo estão zeradas
# As informações estão na linha 'Property, Plant and Equipment, Net' 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-09-30'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-09-30'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-06-30'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-06-30'] 
df_balance_sheet_10q.loc['Property, Plant, and Equipment and Finance Lease Right-of-Use Asset, after Accumulated Depreciation and Amortization', '2020-03-31'] = df_balance_sheet_10q.loc['Property, Plant and Equipment, Net', '2020-03-31'] 

# A linha 'Accounts Payable, Other, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Accounts Payable and Other Accrued Liabilities, Current' 
df_balance_sheet_10q.loc['Accounts Payable, Other, Current', '2020-09-30'] = df_balance_sheet_10q.loc['Accounts Payable and Other Accrued Liabilities, Current', '2020-09-30'] 
df_balance_sheet_10q.loc['Accounts Payable, Other, Current', '2020-06-30'] = df_balance_sheet_10q.loc['Accounts Payable and Other Accrued Liabilities, Current', '2020-06-30'] 
df_balance_sheet_10q.loc['Accounts Payable, Other, Current', '2020-03-31'] = df_balance_sheet_10q.loc['Accounts Payable and Other Accrued Liabilities, Current', '2020-03-31'] 

# A linha 'Accounts Payable, Trade, Current' nas colunas abaixo estão zeradas
# As informações estão na linha 'Accounts Payable, Current' 
df_balance_sheet_10q.loc['Accounts Payable, Trade, Current', '2020-09-30'] = df_balance_sheet_10q.loc['Accounts Payable, Current', '2020-09-30'] 
df_balance_sheet_10q.loc['Accounts Payable, Trade, Current', '2020-06-30'] = df_balance_sheet_10q.loc['Accounts Payable, Current', '2020-06-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Debt Securities, Available-for-sale, Current',
    'fb_ContractWithCustomerLiabilityAndUnusedDeposits',
    'Contract with Customer, Liability, Current',
    'Equity Securities without Readily Determinable Fair Value, Amount',
    'Property, Plant and Equipment, Net',
    'Accounts Payable and Other Accrued Liabilities, Current',
    'Accounts Payable, Current'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Common Stock, Value, Issued'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'meta_NonmarketableEquitySecuritiesCarryingValue': 'Nonmarketable Equity Securities Carrying Value',
    'meta_ContractWithCustomerLiabilityAndUnusedDeposits': 'Contract With Customer Liability And Unused Deposits',
})

# Arrumando e adicionando alguns números no df
df_balance_sheet_10q.loc['Accounts Payable, Trade, Current', '2026-06-30'] = 15889

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_meta['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
    'us-gaap_CostsAndExpensesAbstract'
])

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenue from Contract with Customer, Excluding Assessed Tax'] - df_income_statement_10q.loc['Cost of Revenue']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_meta['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Proceeds from Sale and Maturity of Debt Securities, Available-for-sale' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale'
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2022-09-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2022-09-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2022-06-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2022-06-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2022-03-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2022-03-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2021-09-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-09-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2021-06-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-06-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2021-03-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2021-03-31'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-09-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-09-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-06-30'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-06-30'] 
df_cash_flow_10q.loc['Proceeds from Sale and Maturity of Debt Securities, Available-for-sale', '2020-03-31'] = df_cash_flow_10q.loc['Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale', '2020-03-31'] 

# A linha 'meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets' nas colunas abaixo estão zeradas
# As informações estão na linha 'fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets' 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2021-09-30'] = df_cash_flow_10q.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2021-09-30'] 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2021-06-30'] = df_cash_flow_10q.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2021-06-30'] 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-09-30'] = df_cash_flow_10q.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-09-30'] 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-06-30'] = df_cash_flow_10q.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-06-30'] 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-03-31'] = df_cash_flow_10q.loc['fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2020-03-31'] 

# A linha 'meta_AcquisitionOfBusinessAndIntangibleAssets' nas colunas abaixo estão zeradas
# As informações estão nas linhas 'meta_PaymentsToAcquireBusinessesAndIntangibleAssets' e 'meta_AcquisitionOfBusinessesInAccruedExpensesAndOtherCurrentLiabilitiesAndOtherLiabilities'
df_cash_flow_10q.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2024-03-31'] = df_cash_flow_10q.loc['meta_AcquisitionIncurredButNotYetPaid', '2024-03-31'] 
df_cash_flow_10q.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2023-09-30'] = df_cash_flow_10q.loc['meta_AcquisitionIncurredButNotYetPaid', '2023-09-30'] 
df_cash_flow_10q.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2023-06-30'] = df_cash_flow_10q.loc['meta_AcquisitionIncurredButNotYetPaid', '2023-06-30'] 
df_cash_flow_10q.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2023-03-31'] = df_cash_flow_10q.loc['meta_AcquisitionIncurredButNotYetPaid', '2023-03-31'] 
df_cash_flow_10q.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2022-03-31'] = df_cash_flow_10q.loc['meta_AcquisitionIncurredButNotYetPaid', '2022-03-31'] 
df_cash_flow_10q.loc['meta_AcquisitionOfBusinessAndIntangibleAssets', '2022-09-30'] = df_cash_flow_10q.loc['meta_AcquisitionOfBusinessesInAccruedExpensesAndOtherCurrentLiabilitiesAndOtherLiabilities', '2022-09-30'] 

# A linha 'meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets' nas colunas abaixo estão zeradas
# As informações estão na linha 'meta_PaymentsToAcquireBusinessesAndIntangibleAssets'
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2022-09-30'] = df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesAndIntangibleAssets', '2022-09-30'] 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2022-06-30'] = df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesAndIntangibleAssets', '2022-06-30'] 
df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets', '2022-03-31'] = df_cash_flow_10q.loc['meta_PaymentsToAcquireBusinessesAndIntangibleAssets', '2022-03-31'] 

# A linha 'Increase (Decrease) in Contract with Customer, Liability' nas colunas abaixo estão zeradas
# As informações estão na linha 'meta_IncreaseDecreaseInContractWithCustomerLiabilityAndUnusedDeposits'
df_cash_flow_10q.loc['Increase (Decrease) in Contract with Customer, Liability', '2022-09-30'] = df_cash_flow_10q.loc['meta_IncreaseDecreaseInContractWithCustomerLiabilityAndUnusedDeposits', '2022-09-30'] 
df_cash_flow_10q.loc['Increase (Decrease) in Contract with Customer, Liability', '2022-06-30'] = df_cash_flow_10q.loc['meta_IncreaseDecreaseInContractWithCustomerLiabilityAndUnusedDeposits', '2022-06-30'] 
df_cash_flow_10q.loc['Increase (Decrease) in Contract with Customer, Liability', '2022-03-31'] = df_cash_flow_10q.loc['meta_IncreaseDecreaseInContractWithCustomerLiabilityAndUnusedDeposits', '2022-03-31'] 

# A linha 'Increase (Decrease) in Other Accounts Payable' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Accounts Payable and Other Operating Liabilities'
df_cash_flow_10q.loc['Increase (Decrease) in Other Accounts Payable', '2020-09-30'] = df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable and Other Operating Liabilities', '2020-09-30'] 
df_cash_flow_10q.loc['Increase (Decrease) in Other Accounts Payable', '2020-06-30'] = df_cash_flow_10q.loc['Increase (Decrease) in Accounts Payable and Other Operating Liabilities', '2020-06-30'] 

# A linha 'Income Taxes Paid, Net' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income Taxes Paid'
df_cash_flow_10q.loc['Income Taxes Paid, Net', '2021-09-30'] = df_cash_flow_10q.loc['Income Taxes Paid', '2021-09-30'] 
df_cash_flow_10q.loc['Income Taxes Paid, Net', '2021-06-30'] = df_cash_flow_10q.loc['Income Taxes Paid', '2021-06-30'] 

# A linha 'Payments to Acquire Debt Securities, Available-for-sale' na coluna abaixo está zerada
# As informações estão na linha 'Payments to Acquire Marketable Securities'
df_cash_flow_10q.loc['Payments to Acquire Debt Securities, Available-for-sale', '2020-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Marketable Securities', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale',
    'fb_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets',
    'meta_AcquisitionIncurredButNotYetPaid',
    'meta_AcquisitionOfBusinessesInAccruedExpensesAndOtherCurrentLiabilitiesAndOtherLiabilities',
    'meta_PaymentsToAcquireBusinessesAndIntangibleAssets',
    'meta_IncreaseDecreaseInContractWithCustomerLiabilityAndUnusedDeposits',
    'Increase (Decrease) in Accounts Payable and Other Operating Liabilities',
    'Income Taxes Paid',
    'Payments to Acquire Marketable Securities'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Restricted Cash and Cash Equivalents, Current',
    'Restricted Cash and Cash Equivalents, Noncurrent',
    'meta_SettlementOfConversionNotesWithMarketableEquitySecurities',
    'meta_SettlementOfConvertibleNotesInExchangeOfEquitySecuritiesInOtherCurrentAssets',
    'fb_NoncashOrPartNoncashAcquisitionAndOtherInvestmentsOtherLiabilitiesAssumed',
    'Noncash or Part Noncash Acquisition, Other Liabilities Assumed',
    'meta_NonMarketableEquityInvestmentsInAccruedExpensesAndOtherCurrentLiabilities',
    'fb_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities',
    'fb_OtherSignificantNoncashTransaction',
    'meta_OtherSignificantNoncashTransaction',
    'fb_AcquisitionIncurredButNotYetPaid',
    'fb_PaymentsForEquitySecuritiesWithoutReadilyDeterminableFairValue'
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'meta_PaymentsForHeldForSaleAssets': 'Payments For Held For Sale Assets',
    'meta_PaymentsToAcquireBusinessesNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets': 'Payments To Acquire Businesses Net Of Cash Acquired And Purchases Of Intangible And Other Assets',
    'meta_AcquisitionOfBusinessAndIntangibleAssets': 'Acquisition Of Business And Intangible Assets',
    'meta_RepurchaseOfCommonStockInAccruedExpensesAndOtherCurrentLiabilities': 'Repurchase Of Common Stock In Accrued Expenses And Other Current Liabilities',
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Marketable Securities, Current': 'Marketable Securities',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Accounts Payable, Trade, Current': 'Accounts Payable',
    'Long-term Debt, Excluding Current Maturities': 'Long-term Debt',
    'Operating Lease, Liability, Current': 'Operating Lease, Current',
    'Operating Lease, Liability, Noncurrent': 'Operating Lease, Noncurrent',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'

})

Os dados abaixo não aparecem no 10-Q pela função 'get_statement_file_names_in_filing_summary' - eu vou ter quer ADICIONAR NA MÃO:
* 'Interest expense';
* 'RSUs'.

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [219]:
# Lendo os arquivos 10k
meta_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

meta_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

meta_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

meta_leases = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10k.xlsx', 
    sheet_name='leases', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
meta_bs.columns = pd.to_datetime(meta_bs.columns)
meta_is.columns = pd.to_datetime(meta_is.columns)
meta_cf.columns = pd.to_datetime(meta_cf.columns)
meta_leases.columns = pd.to_datetime(meta_leases.columns)

# Transformando as colunas em apenas o ano
meta_bs.columns = meta_bs.columns.year
meta_is.columns = meta_is.columns.year
meta_cf.columns = meta_cf.columns.year
meta_leases.columns = meta_leases.columns.year

In [220]:
# Preços da META
meta_close = yf.download('META', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_dec_close = []

for year in lst_years:
    last_close = meta_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
meta_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
meta_close_dec = meta_close_dec.reindex(index=meta_close_dec.index[::-1])

# Arredondamento de duas casas decimais
meta_close_dec = round(meta_close_dec, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Transformando o index em int
meta_close_dec .index = meta_close_dec .index.astype(int)

meta_close_dec

[*********************100%***********************]  1 of 1 completed

2025    658.40
2024    582.17
2023    350.60
2022    119.20
2021    333.16
2020    270.57
2019    203.30
2018    129.85
2017    174.79
dtype: float64

In [221]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = meta_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=meta_close_dec, df_is=meta_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=meta_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=meta_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=meta_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=meta_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=meta_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=meta_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=meta_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=meta_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=meta_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=meta_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=meta_bs, df_is=meta_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=meta_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=meta_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Long-term Debt']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=meta_bs, lst_itens_divida=lst_divida)
div_bruta_total = div_bruta.values + meta_leases.sum().values
div_bruta_total = pd.Series(div_bruta_total, index=idx)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta_total, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=meta_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=meta_is, df_bs=meta_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=meta_is, df_bs=meta_bs, div_bruta=div_bruta_total, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=meta_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=meta_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=meta_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Purchases Of Property And Equipment And Intangible Assets']

capex= f_eua.indicador_capex(ten_k=True, df_cf=meta_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=meta_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = [
    'Payment, Tax Withholding, Share-based Payment Arrangement',
    'Finance Lease, Principal Payments'
]

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=meta_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=meta_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=meta_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Taxes and Tax Credits',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable, Trade',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=meta_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=meta_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=meta_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Finance Lease, Principal Payments']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=meta_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=meta_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=meta_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=meta_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=meta_cf, df_is=meta_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=meta_cf, df_is=meta_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=meta_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=meta_bs, df_is=meta_is)

# DIO - não divulga o invetário no 10-k

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=meta_bs, df_is=meta_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=meta_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=meta_bs, df_is=meta_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=meta_is, df_bs=meta_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=meta_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta_total,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    # dio - não divulga o invetário no 10-k
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
meta_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    # 'DIO' - não divulga o invetário no 10-k
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'

]

# Atribuindo os novos nomes das colunas do df
meta_indicadores_10k.columns = nomes_col
meta_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Payout,Buyback,DSO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,27.45,27.46,3.64,101892.0,30.08,82.00,41.44,50.70,7.64,1.659826e+09,...,8.81,26248,35.905004,0.000000,1.915379,0.098370,-0.172385,1.136497,0.762662,3.743608
2024,23.66,23.66,4.23,84878.0,37.91,81.67,42.18,51.60,8.08,1.475219e+09,...,8.13,30125,37.706822,0.000000,1.464529,0.103306,-0.114571,1.075991,0.867094,2.403923
2023,23.08,23.08,4.33,57929.0,28.98,80.76,34.66,42.94,5.89,9.024444e+08,...,0.00,19774,43.747943,0.000000,1.818840,0.119857,-0.154159,1.227589,1.121464,2.439256
2022,13.81,13.81,7.24,37630.0,19.90,78.35,24.82,32.27,2.55,3.202904e+08,...,0.00,27956,42.150177,0.000000,2.175647,0.115480,-0.155098,1.341350,0.820862,3.618582
2021,23.82,23.81,4.20,54720.0,33.38,80.79,39.65,46.40,7.51,9.378454e+08,...,0.00,44537,43.451865,0.000000,1.465151,0.119046,-0.112590,1.054148,0.993548,2.330488
2020,26.47,26.47,3.78,39533.0,33.90,80.58,38.01,45.99,6.01,7.713951e+08,...,0.00,6272,48.127436,29.104661,1.329411,0.131856,-0.065605,0.980118,0.810815,2.202711
2019,31.39,31.37,3.19,29727.0,26.15,81.94,33.93,42.05,5.74,5.802182e+08,...,0.00,4202,49.140275,38.958105,1.964512,0.134631,-0.154558,1.221583,1.147525,2.630552
2018,16.97,16.97,5.89,29228.0,39.60,83.25,44.62,52.34,4.46,3.752665e+08,...,0.00,12879,49.594452,31.993586,1.323897,0.135875,-0.078765,1.001574,0.694600,3.224797
2017,31.82,31.84,3.14,23228.0,39.20,86.58,49.70,57.14,6.82,5.070658e+08,...,0.00,1976,52.362187,25.430876,1.519769,0.143458,NaN,1.042535,1.097214,2.225785

In [222]:
# Lendo os arquivos 10q
meta_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

meta_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

meta_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
meta_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in meta_bs_10q.columns]
meta_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in meta_is_10q.columns]
meta_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in meta_cf_10q.columns]

In [223]:
# Preços da META
meta_close = yf.download('META', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025'
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = meta_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
meta_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
meta_close_months = meta_close_months.reindex(index=meta_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = meta_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
meta_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
meta_close_months_atual = meta_close_months_atual.reindex(index=meta_close_months_atual.index[::-1])

# Juntando as duas series pandas
meta_close_months = pd.concat([meta_close_months_atual, meta_close_months])

# Arredondamento de duas casas decimais
meta_close_months = round(meta_close_months, 2)

# Não realizou split recentemente (não possui dados de split no site da Investing)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
meta_close_months.index = meta_bs_10q.columns[:-3]

meta_close_months

[*********************100%***********************]  1 of 1 completed

2026-06-30    562.85
2026-03-31    571.15
2025-09-30    731.90
2025-06-30    735.10
2025-03-31    573.58
2024-09-30    568.72
2024-06-30    500.46
2024-03-31    481.48
2023-09-30    297.36
2023-06-30    284.26
2023-03-31    209.93
2022-09-30    134.39
2022-06-30    159.72
2022-03-31    220.25
2021-09-30    336.17
2021-06-30    344.41
2021-03-31    291.74
dtype: float64

In [224]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = meta_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=meta_close_months, df_is=meta_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=meta_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=meta_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=meta_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=meta_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=meta_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[0]
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[1]
depreciacao_10q_acum = f_eua.indicador_depreciacao(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[2]

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=meta_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=meta_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=meta_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=meta_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=meta_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=meta_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=meta_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=meta_bs_10q, df_is=meta_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=meta_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Marketable Securities']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=meta_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta - não somei o custo dos 'leases', porque eles não são divulgados no 10q
lst_divida = ['Long-term Debt', 'Operating Lease, Current', 'Operating Lease, Noncurrent']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=meta_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=meta_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=meta_is_10q, df_bs=meta_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=meta_is_10q, df_bs=meta_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO
fco_10q = f_eua.indicador_fco(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[0] 
fco_10q_sliced = f_eua.indicador_fco(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[1] 
fco_10q_acum = f_eua.indicador_fco(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[2] 

# FCI
fci_10q = f_eua.indicador_fci(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[0] 
fci_10q_sliced = f_eua.indicador_fci(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[1] 
fci_10q_acum = f_eua.indicador_fci(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[2] 

# FCF
fcf_10q = f_eua.indicador_fcf(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[0] 
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[1] 
fcf_10q_acum = f_eua.indicador_fcf(ten_k=False, df_cf=meta_cf_10q, first_quarter='03')[2] 

# CAPEX
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[0]
capex_10q_sliced = f_eua.indicador_capex(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[1]
capex_10q_acum = f_eua.indicador_capex(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', lst_itens=lst_capex_10q, idx=idx_10q)[2]

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC 
sbc_10q = f_eua.indicador_sbc(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[0]
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[1]
sbc_10q_acum = f_eua.indicador_sbc(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Outros custos fluxo de caixa
lst_custos_cf = [
    'Payment, Tax Withholding, Share-based Payment Arrangement',
    'Finance Lease, Principal Payments'
]

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[0]
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[1]
outros_custos_cf_10q_acum = f_eua.indicador_outros_custos_cf(ten_k=False, df_cf=meta_cf_10q, first_quarter='03', lst_itens=lst_custos_cf, idx=idx_10q)[2]

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=meta_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=meta_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=meta_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=meta_bs_10q)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Prepaid Expense and Other Assets',
    'Increase (Decrease) in Other Operating Assets',
    'Increase (Decrease) in Accounts Payable, Trade',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=meta_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[0]
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=meta_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[1]
change_non_cash_wc_10q_acum = f_eua.indicador_change_non_cash_wc(ten_k=False, df_cf=meta_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter='03')[2]

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=meta_is_10q, idx=idx_10q)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Long-term Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[0]
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[1]
new_borrowing_10q_acum = f_eua.indicador_new_borrowing(ten_k=False, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Debt paid
lst_itens_debt_paid = ['Finance Lease, Principal Payments']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[0]
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[1]
debt_paid_10q_acum = f_eua.indicador_debt_paid(ten_k=False, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=meta_cf_10q, first_quarter='03', idx=idx_10q)[2]

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=meta_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=meta_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=meta_is_10q,
        idx=idx_10q
)

# Dividendo não acumulado
div_nao_acum = f_eua.indicador_div_nao_acum(df_cf=meta_cf_10q, first_quarter='03')

# Dividendo por Ação
dpa_10q = f_eua.indicador_dpa(ten_k=False, df_cf=meta_cf_10q, df_is=meta_is_10q, div_nao_acum=div_nao_acum)

# Payout
payout_10q = f_eua.indicador_payout(ten_k=False, df_cf=meta_cf_10q, df_is=meta_is_10q, div_nao_acum=div_nao_acum)

# Buyback
buyback_10q = f_eua.indicador_buyback(ten_k=False, df_cf=meta_cf_10q,  first_quarter='03')

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=meta_bs_10q, df_is=meta_is_10q)

# DIO - não divulga o invetário no 10-q

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=meta_bs_10q, df_is=meta_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=meta_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=meta_bs_10q, df_is=meta_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=meta_is_10q, df_bs=meta_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=meta_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    # dio_10q - não divulga o invetário no 10-q
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
meta_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado',
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    # 'DIO' - não divulga o invetário no 10-q
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
meta_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
meta_indicadores_10q = meta_indicadores_10q.fillna(0)

meta_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Payout,Buyback,DSO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,90.32,22.37,4.47,25131.0,104283.0,26.07,81.37,30.88,41.33,5.48,...,8.54,0.0,130.581405,511.869815,2.010475,0.357757,-0.043008,1.267837,2.219081,4.738200
2026-03-31,54.06,22.38,4.47,28871.0,100607.0,47.54,81.85,40.62,51.27,5.94,...,5.03,0.0,113.238088,476.021726,1.203675,0.310241,-0.016146,1.116207,1.662384,3.166694
2025-09-30,680.03,34.61,2.89,25498.0,93113.0,5.29,82.03,40.07,49.76,9.49,...,49.10,3327.0,123.207623,309.175538,11.073828,0.337555,-0.097420,1.176524,17.624216,3.793875
2025-06-30,100.94,28.96,3.45,24783.0,86099.0,38.59,82.13,43.02,52.16,9.49,...,7.24,10167.0,127.215359,441.516311,1.393958,0.348535,-0.027521,1.031392,2.605170,3.808844
2025-03-31,87.08,24.98,4.00,21455.0,78508.0,39.33,82.11,41.49,50.70,7.83,...,7.98,12754.0,125.197571,410.311675,1.443523,0.343007,-0.029349,1.119832,3.099856,3.318205
2024-09-30,91.68,27.25,3.67,21377.0,73660.0,38.65,81.83,42.75,52.67,8.74,...,8.05,8818.0,132.190988,378.907119,1.575982,0.362167,-0.038233,1.156570,3.465579,2.050658
2024-06-30,94.18,28.27,3.54,18484.0,64298.0,34.46,81.30,38.00,47.31,8.09,...,9.40,6299.0,135.505234,158.476327,1.438544,0.371247,-0.027030,1.047933,3.638693,2.247182
2024-03-31,99.07,32.98,3.03,17192.0,55565.0,33.93,81.79,37.90,47.16,8.20,...,10.29,15008.0,134.465780,208.060994,1.555987,0.368399,-0.033766,1.119474,3.634409,1.896858
2023-09-30,66.13,26.13,3.83,16607.0,46212.0,33.92,81.81,40.26,48.64,5.36,...,0.00,3569.0,138.363498,256.969404,1.761374,0.379078,-0.044634,1.228518,2.799361,2.288562
2023-06-30,93.73,30.40,3.29,12015.0,39942.0,24.34,81.42,29.35,37.55,5.45,...,0.00,898.0,142.708053,189.898234,2.222522,0.390981,-0.050581,1.440616,2.977658,2.369806
2023-03-31,95.13,23.17,4.32,9751.0,38607.0,19.93,78.68,25.23,34.04,4.35,...,0.00,9365.0,140.724734,219.430255,2.451918,0.385547,-0.047541,1.435545,3.631459,2.710777
2022-09-30,82.01,13.28,7.53,7839.0,41274.0,15.86,79.38,20.44,28.29,2.90,...,0.00,6354.0,147.862272,247.185969,2.205233,0.405102,-0.030401,1.236382,5.313311,4.310345
2022-06-30,64.59,13.15,7.61,10337.0,47788.0,23.20,81.99,29.00,35.86,3.43,...,0.00,5233.0,145.951877,281.764253,1.823837,0.399868,-0.032369,1.179839,4.736055,3.826175
2022-03-31,80.40,16.92,5.91,10680.0,50801.0,26.75,78.48,30.54,38.27,4.87,...,0.00,9506.0,148.966246,197.300583,1.885599,0.408127,-0.040343,1.317978,4.690690,2.523655
2021-09-30,102.89,25.80,3.88,12418.0,49859.0,31.69,80.11,35.93,42.81,7.09,...,0.00,13458.0,152.089624,138.827759,1.532521,0.416684,-0.030985,1.134643,3.537198,2.162406
2021-06-30,93.91,29.74,3.36,14353.0,45108.0,35.75,81.43,42.53,49.36,7.06,...,0.00,7079.0,146.843553,65.779774,1.274485,0.402311,-0.018389,0.922943,2.248124,2.322256
2021-03-31,87.46,30.29,3.30,13350.0,38245.0,36.29,80.39,43.48,51.01,6.21,...,0.00,3939.0,143.316648,62.457611,1.289039,0.392648,-0.018185,0.917004,2.334948,2.166329

In [227]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//meta//meta_indicators.xlsx') as writer:
    meta_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    meta_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Microsoft

* 1Q -> Lançamento em Setembro (09);
* 2Q -> Lançamento em Dezembro (12);
* 3Q -> Lançamento em Março (03);
* 10K -> Lançamento em Junho (06).

In [ ]:
ticker = 'msft'
f_sec.cik_matching_ticker(ticker)

### Scraping Microsoft 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_msft = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017 e 2018
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000156459020034944', # 2020
            '000156459019027952', # 2019
            '000156459018019062', # 2018
            '000156459017014900', # 2017
        ]
    },
    index=pd.to_datetime([
        '2020-06-30',
        '2019-06-30',
        '2018-06-30',
        '2017-06-30',
    ])
)

# Concatenando os dfs
df_lst_acc_num_msft = pd.concat([df_lst_acc_num_msft, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_msft.index = pd.to_datetime(df_lst_acc_num_msft.index, format='%Y-%m-%d')

df_lst_acc_num_msft

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_msft['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Deferred Income Tax Liabilities, Net' nas colunas abaixo estão zeradas
# As informações estão na linha 'Deferred Tax Liabilities, Net, Noncurrent'
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2019-06-30'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2019-06-30'] 
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2018-06-30'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2018-06-30'] 
df_balance_sheet_10k.loc['Deferred Income Tax Liabilities, Net', '2017-06-30'] = df_balance_sheet_10k.loc['Deferred Tax Liabilities, Net, Noncurrent', '2017-06-30'] 

# A linha 'Short-term Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Available-for-sale Securities, Current'
df_balance_sheet_10k.loc['Short-term Investments', '2018-06-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2018-06-30'] 
df_balance_sheet_10k.loc['Short-term Investments', '2017-06-30'] = df_balance_sheet_10k.loc['Available-for-sale Securities, Current', '2017-06-30'] 

# A linha 'Commercial Paper' na coluna abaixo está zerada
# As informações estão na linha 'Short-term Debt'
df_balance_sheet_10k.loc['Commercial Paper', '2017-06-30'] = df_balance_sheet_10k.loc['Short-term Debt', '2017-06-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Deferred Tax Liabilities, Net, Noncurrent',
    'Available-for-sale Securities, Current',
    'Short-term Debt'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Deferred Revenue, Current',
    'Deferred Revenue, Noncurrent',
    'Deposits Received for Securities Loaned, at Carrying Value'
])

# Arrumando e adicionando alguns números no df
df_balance_sheet_10k.loc['Operating Lease, Right-of-Use Asset', '2017-06-30'] = 6555
df_balance_sheet_10k.loc['Contract with Customer, Liability, Current', '2017-06-30'] = 24013
df_balance_sheet_10k.loc['Accrued Income Taxes, Noncurrent', '2017-06-30'] = 13485
df_balance_sheet_10k.loc['Contract with Customer, Liability, Noncurrent', '2017-06-30'] = 2643
df_balance_sheet_10k.loc['Operating Lease, Liability, Noncurrent', '2017-06-30'] = 5372

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_msft['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-06-30'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-06-30'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-06-30'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-06-30'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-06-30'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-06-30'] 

# A linha 'Revenue from Contract with Customer, Excluding Assessed Tax' na coluna abaixo está zerada
# As informações estão na linha 'Sales Revenue, Goods, Net (Deprecated 2018-01-31)'
df_income_statement_10k.loc['Revenue from Contract with Customer, Excluding Assessed Tax', '2017-06-30'] = df_income_statement_10k.loc['Sales Revenue, Goods, Net (Deprecated 2018-01-31)', '2017-06-30'] 

# A linha 'Cost of Goods and Services Sold' na coluna abaixo está zerada
# As informações estão na linha 'msft_SalesRevenueServicesAndOtherNet'
df_income_statement_10k.loc['Cost of Goods and Services Sold', '2017-06-30'] = df_income_statement_10k.loc['msft_SalesRevenueServicesAndOtherNet', '2017-06-30'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'Sales Revenue, Goods, Net (Deprecated 2018-01-31)',
    'msft_SalesRevenueServicesAndOtherNet'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_EarningsPerShareAbstract',
    'Restructuring Charges',
    'msft_ImpairmentAndRestructuringExpenses',
    'Common Stock, Dividends, Per Share, Declared',
    'us-gaap_SalesRevenueNetAbstract',
    'Revenue, Net (Deprecated 2018-01-31)',
    'Cost of Goods Sold (Deprecated 2018-01-31)',
    'Cost of Revenue',
    'msft_ImpairmentIntegrationAndRestructuringExpenses',
    'msft_CostOfServicesAndOther'
])

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_msft['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations' nas colunas abaixo estão zeradas
# As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-06-30'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-06-30'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-06-30'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-06-30'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2019-06-30'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2019-06-30'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2018-06-30'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2018-06-30'] 
df_cash_flow_10k.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2017-06-30'] = df_cash_flow_10k.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2017-06-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, Period Increase (Decrease)'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2019-06-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2019-06-30'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2018-06-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2018-06-30'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect', '2017-06-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, Period Increase (Decrease)', '2017-06-30'] 

# A linha 'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents' nas colunas abaixo estão zeradas
# As informações estão na linha 'Cash and Cash Equivalents, at Carrying Value'
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2019-06-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2019-06-30'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2018-06-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2018-06-30'] 
df_cash_flow_10k.loc['Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents', '2017-06-30'] = df_cash_flow_10k.loc['Cash and Cash Equivalents, at Carrying Value', '2017-06-30'] 

# A linha 'msft_ProceedsFromInvestments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Proceeds from Sale of Available-for-sale Securities'
df_cash_flow_10k.loc['msft_ProceedsFromInvestments', '2018-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2018-06-30'] 
df_cash_flow_10k.loc['msft_ProceedsFromInvestments', '2017-06-30'] = df_cash_flow_10k.loc['Proceeds from Sale of Available-for-sale Securities', '2017-06-30'] 

# A linha 'Payments for (Proceeds from) Other Investing Activities' nas colunas abaixo estão zeradas
# As informações estão na linha 'Increase (Decrease) in Collateral Held under Securities Lending'
df_cash_flow_10k.loc['Payments for (Proceeds from) Other Investing Activities', '2018-06-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Collateral Held under Securities Lending', '2018-06-30'] 
df_cash_flow_10k.loc['Payments for (Proceeds from) Other Investing Activities', '2017-06-30'] = df_cash_flow_10k.loc['Increase (Decrease) in Collateral Held under Securities Lending', '2017-06-30'] 

# A linha 'Payments of Debt Restructuring Costs' na coluna abaixo está zerada
# As informações estão na linha 'Payment for Debt Extinguishment or Debt Prepayment Cost'
df_cash_flow_10k.loc['Payments of Debt Restructuring Costs', '2020-06-30'] = df_cash_flow_10k.loc['Payment for Debt Extinguishment or Debt Prepayment Cost', '2020-06-30'] 

# A linha 'Deferred Income Tax Expense (Benefit)' na coluna abaixo está zerada
# As informações estão na linha 'Deferred Income Taxes and Tax Credits'
df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2026-06-30'] = df_cash_flow_10k.loc['Deferred Income Taxes and Tax Credits', '2026-06-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash and Cash Equivalents, at Carrying Value',
    'Proceeds from Sale of Available-for-sale Securities',
    'Increase (Decrease) in Collateral Held under Securities Lending',
    'Payment for Debt Extinguishment or Debt Prepayment Cost',
    'Deferred Income Taxes and Tax Credits'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Asset Impairment Charges',
    'Net Cash Provided by (Used in) Operating Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Financing Activities, Continuing Operations',
    'Net Cash Provided by (Used in) Investing Activities, Continuing Operations',
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesContinuingOperationsAbstract'
])

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-06-30'] = 3820
df_cash_flow_10k.loc['Increase (Decrease) in Income Taxes Payable', '2017-06-30'] = 1792
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Operating Activities', '2017-06-30'] = 39507
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Financing Activities', '2017-06-30'] = 8408
df_cash_flow_10k.loc['Net Cash Provided by (Used in) Investing Activities', '2017-06-30'] = -46781


# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'msft_DepreciationAmortizationAndOther': 'Depreciation Amortization And Other',
    'msft_GainLossOnInvestmentsAndDerivativeInstruments': 'Gain Loss On Investments And Derivative Instruments',
    'msft_AcquisitionsNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets': 'Acquisitions Net Of Cash Acquired And Purchases Of Intangible And Other Assets',
    'msft_ProceedsFromInvestments': 'Proceeds From Investments',
})

df_cash_flow_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Long-term Investments': 'Equity and Other Investments',
    'Long-term Debt, Current Maturities': 'Current Portion of Long-term Debt',
    'Long-term Debt, Excluding Current Maturities': 'Long-term debt',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Depreciation Amortization And Other': 'Depreciation, Depletion and Amortization',
    'Property, Plant and Equipment, Net': 'Purchases Of Property And Equipment And Intangible Assets',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'

})

In [ ]:
# Selecionando o 'acc_num' do ano mais recente
last_acc_num = df_lst_acc_num_msft['acc_num'].iloc[0]

# Fazendo o scraping do interest expense (10-K) -> 'Other Income (Expense), Net' -> 'Interest expense'
interest_expense_10k = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num, statement_name='interest_expense')
interest_expense_10k = f_sec.rename_statement(interest_expense_10k, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
interest_expense_10k = interest_expense_10k.drop('us-gaap_OtherIncomeAndExpensesAbstract')

# Renomeando a linha do índice que está sem formato 
interest_expense_10k = interest_expense_10k.rename(index={
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
interest_expense_10k.loc['Interest Expense'] = interest_expense_10k.loc['Interest Expense'] * -1

# Selecionando a linha desejada
interest_expense_10k = interest_expense_10k.loc[['Interest Expense']]

interest_expense_10k

In [ ]:
# 'acc_num' entre 2018 e 2026
df_lst_acc_num_msft_sorted = df_lst_acc_num_msft.sort_index()
acc_num_list_msft_sliced = df_lst_acc_num_msft_sorted.loc['2018':'2026', 'acc_num']

# Fazendo o scraping do leases (10-K)
leases_lst = []

for acc_num in acc_num_list_msft_sliced:

    # Fazendo o scraping do leases (10-K) -> 'Note 8 – Leases' -> 'Total lease liabilities'
    leases_10k = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10k = f_sec.rename_statement(leases_10k, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10k = leases_10k.iloc[:, 0]
    leases_lst.append(leases_10k)

# Removendo duplicatas de índice em cada série
leases_lst_clean = [df[~df.index.duplicated(keep='first')] for df in leases_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10k = pd.concat(leases_lst_clean, axis=1)

# Renomeando as linhas do índice
df_leases_10k = df_leases_10k.rename(index={
    'Operating Lease, Liability': 'Total Operating Lease Liabilities',
    'Finance Lease, Liability': 'Total Finance Lease Liabilities',

})

# Selecionando as linhas desejadas
df_leases_10k = df_leases_10k.loc[['Total Operating Lease Liabilities', 'Total Finance Lease Liabilities']]

# Criando a coluna do ano de 2017 
df_leases_10k.loc['Total Operating Lease Liabilities', '2017-06-30'] = 6795
df_leases_10k.loc['Total Finance Lease Liabilities', '2017-06-30'] = 2538

# Ordenando o df
df_leases_10k = df_leases_10k[sorted(df_leases_10k.columns, reverse=True)]

df_leases_10k

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')
    interest_expense_10k.to_excel(writer, sheet_name='interest_expense')
    df_leases_10k.to_excel(writer, sheet_name='leases')

### Scraping Microsoft 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_msft = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])


# Adicionando os 'acc_num' de 1Q, 2Q e 3Q dos anos de 2020, 2021, 2022 e 2023
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000156459020019706', # 3Q 2020
            '000156459020002450', # 2Q 2020
            '000156459019037549', # 1Q 2020
        ]
    },
    index=pd.to_datetime([
        '2020-03-31',
        '2019-12-31',
        '2019-09-30',
    ])
)

# Concatenando os dfs
df_lst_acc_num_10q_msft = pd.concat([df_lst_acc_num_10q_msft, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_10q_msft.index = pd.to_datetime(df_lst_acc_num_10q_msft.index, format='%Y-%m-%d')


df_lst_acc_num_10q_msft

In [ ]:
# Selecionando os 'acc_num' dos 10-q a partir de '2019-09-30' p/ iteração
df_lst_acc_num_10q_msft_sliced = df_lst_acc_num_10q_msft.loc['2019-09-30':]
df_lst_acc_num_10q_msft_sliced

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_msft_sliced['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop('us-gaap_AssetsCurrentAbstract')

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_msft_sliced['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estao zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-09-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-03-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-12-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-12-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-09-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-03-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-12-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-12-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-09-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'us-gaap_EarningsPerShareAbstract'
])

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_msft_sliced['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations' nas colunas abaixo estão zeradas
# As informações estão na linha 'Effect of Exchange Rate on Cash and Cash Equivalents'
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2022-03-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2022-03-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-12-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-12-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-09-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-09-30'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2021-03-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2021-03-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-12-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-12-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-09-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-09-30'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2020-03-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2020-03-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2019-12-31'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2019-12-31'] 
df_cash_flow_10q.loc['Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Including Disposal Group and Discontinued Operations', '2019-09-30'] = df_cash_flow_10q.loc['Effect of Exchange Rate on Cash and Cash Equivalents', '2019-09-30'] 

# A linha 'Proceeds from (Repayments of) Short-term Debt, Maturing in Three Months or Less' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Short-term Debt, Maturing in Three Months or Less'
df_cash_flow_10q.loc['Proceeds from (Repayments of) Short-term Debt, Maturing in Three Months or Less', '2023-09-30'] = df_cash_flow_10q.loc['Proceeds from Short-term Debt, Maturing in Three Months or Less', '2023-09-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Proceeds from Short-term Debt, Maturing in Three Months or Less',
    'Effect of Exchange Rate on Cash and Cash Equivalents'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop('us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract')

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'msft_DepreciationAmortizationAndOther': 'Depreciation Amortization And Other',
    'msft_GainLossOnInvestmentsAndDerivativeInstruments': 'Gain Loss On Investments And Derivative Instruments',
    'msft_AcquisitionsNetOfCashAcquiredAndPurchasesOfIntangibleAndOtherAssets': 'Acquisitions Net Of Cash Acquired And Purchases Of Intangible And Other Assets',
    'msft_ProceedsFromInvestments': 'Proceeds From Investments',
})

df_cash_flow_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Cash and Cash Equivalents, at Carrying Value': 'Cash and Cash Equivalents',
    'Accounts Receivable, after Allowance for Credit Loss, Current': 'Accounts Receivable',
    'Inventory, Net': 'Inventories',
    'Accounts Payable, Current': 'Accounts Payable',
    'Long-term Investments': 'Equity and Other Investments',
    'Long-term Debt, Current Maturities': 'Current Portion of Long-term Debt',
    'Long-term Debt, Excluding Current Maturities': 'Long-term debt',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Goods and Services Sold': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Depreciation Amortization And Other': 'Depreciation, Depletion and Amortization',
    'Payments to Acquire Property, Plant, and Equipment': 'Purchases Of Property And Equipment And Intangible Assets',
    'Payments of Ordinary Dividends, Common Stock': 'Payments of Dividends',
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Selecionando o 'acc_num' do trimestre mais recente
last_acc_num_10q = df_lst_acc_num_10q_msft_sliced.iloc[0].item()

# Fazendo o scraping do interest expense -> 'Other Income (Expense), Net' -> 'Interest expense'
interest_expense_10q = f_sec.process_one_statement(ticker=ticker, accession_number=last_acc_num_10q, statement_name='interest_expense')
interest_expense_10q = f_sec.rename_statement(interest_expense_10q, label_dictionary=labels_dict)

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
interest_expense_10q = interest_expense_10q.drop('us-gaap_OtherIncomeAndExpensesAbstract')

# Renomeando a linha do índice que está sem formato 
interest_expense_10q = interest_expense_10q.rename(index={
    'InterestExpenseNonoperating': 'Interest Expense',
})

# Formatando o número para ficar positivo
interest_expense_10q.loc['Interest Expense'] = interest_expense_10q.loc['Interest Expense'] * -1

# Selecionando a linha desejada
interest_expense_10q = interest_expense_10q.loc[['Interest Expense']]

# Selecionando a 1º e 2º coluna do df que são os nº não acumulados
interest_expense_10q = interest_expense_10q.iloc[:, [0,1]]

interest_expense_10q

In [ ]:
# Fazendo o scraping do leases (10-K)
leases_lst = []

for acc_num in  df_lst_acc_num_10q_msft_sliced['acc_num']:

    # Fazendo o scraping do leases (10-K) -> 'Note 8 – Leases' -> 'Total lease liabilities'
    leases_10q = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='leases')
    leases_10q = f_sec.rename_statement(leases_10q, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    leases_10q = leases_10q.iloc[:, 0]
    leases_lst.append(leases_10q)

# Removendo duplicatas de índice em cada série
leases_lst_clean = [df[~df.index.duplicated(keep='first')] for df in leases_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_leases_10q = pd.concat(leases_lst_clean, axis=1)

# Renomeando as linhas do índice
df_leases_10q = df_leases_10q.rename(index={
    'Operating Lease, Liability': 'Total Operating Lease Liabilities',
    'Finance Lease, Liability': 'Total Finance Lease Liabilities',

})

# Selecionando as linhas desejadas
df_leases_10q = df_leases_10q.loc[['Total Operating Lease Liabilities', 'Total Finance Lease Liabilities']]

# Ordenando o df
df_leases_10q = df_leases_10q[sorted(df_leases_10q.columns, reverse=True)]

df_leases_10q

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')
    interest_expense_10q.to_excel(writer, sheet_name='interest_expense')
    df_leases_10q.to_excel(writer, sheet_name='leases')

### Indicadores Fundamentalistas

In [228]:
# Lendo os arquivos 10k
msft_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

msft_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

msft_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

msft_leases = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10k.xlsx', 
    sheet_name='leases', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
msft_bs.columns = pd.to_datetime(msft_bs.columns)
msft_is.columns = pd.to_datetime(msft_is.columns)
msft_cf.columns = pd.to_datetime(msft_cf.columns)
msft_leases.columns = pd.to_datetime(msft_leases.columns)

# Transformando as colunas em apenas o ano
msft_bs.columns = msft_bs.columns.year
msft_is.columns = msft_is.columns.year
msft_cf.columns = msft_cf.columns.year
msft_leases.columns = msft_leases.columns.year

In [229]:
# Preços da MSFT
msft_close = yf.download('MSFT', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024', 
    '2025', '2026'
]

last_dec_close = []

for year in lst_years:
    last_close = msft_close[f'{year}-06'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
msft_close_jun = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
msft_close_jun = msft_close_jun.reindex(index=msft_close_jun.index[::-1])

# Arredondamento de duas casas decimais
msft_close_jun = round(msft_close_jun, 2)

# Não realizou split recentemente (https://br.investing.com/equities/microsoft-corp-historical-data-splits)

# Transformando o index em int
msft_close_jun .index = msft_close_jun .index.astype(int)

msft_close_jun

[*********************100%***********************]  1 of 1 completed

2026    372.32
2025    492.54
2024    439.21
2023    332.04
2022    248.02
2021    259.49
2020    193.07
2019    125.54
2018     90.94
2017     62.35
dtype: float64

In [230]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = msft_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=msft_close_jun, df_is=msft_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=msft_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=msft_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=msft_close_jun, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=msft_close_jun, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=msft_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=msft_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=msft_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=msft_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=msft_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=msft_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=msft_bs, df_is=msft_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=msft_close_jun, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Short-term Investments']
caixa = f_eua.indicador_caixa(ten_k=True, df_bs=msft_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Current Portion of Long-term Debt', 'Long-term debt']
div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=msft_bs, lst_itens_divida=lst_divida)
div_bruta_total = div_bruta.values + msft_leases.sum().values
div_bruta_total = pd.Series(div_bruta_total, index=idx)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta_total, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=msft_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=msft_is, df_bs=msft_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=msft_is, df_bs=msft_bs, div_bruta=div_bruta_total, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=msft_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=msft_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=msft_cf, first_quarter=None) 

# CAPEX
lst_capex = ['Payments to Acquire Property, Plant, and Equipment']

capex= f_eua.indicador_capex(ten_k=True, df_cf=msft_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=msft_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=msft_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=msft_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Current Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Income Taxes Payable',
    'Increase (Decrease) in Other Current Liabilities',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=msft_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=msft_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Debt, Maturing in More than Three Months']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=msft_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = [
    'Repayments of Debt, Maturing in More than Three Months', 
    'Proceeds from (Repayments of) Short-term Debt, Maturing in Three Months or Less'
]

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=msft_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=msft_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=msft_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=msft_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=msft_cf, df_is=msft_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=msft_cf, df_is=msft_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=msft_cf, first_quarter=None)

# DSO
dso = f_eua.indicador_dso(ten_k=True, df_bs=msft_bs, df_is=msft_is)

# DIO
dio = f_eua.indicador_dio(ten_k=True, df_bs=msft_bs, df_is=msft_is)

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=msft_bs, df_is=msft_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=msft_is)

# Recebíveis/Receita
recebiveis_receita = f_eua.indicador_recebiveis_receita(ten_k=True, df_bs=msft_bs, df_is=msft_is)

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=msft_is, df_bs=msft_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=msft_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta_total,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    dso,
    dio,
    dpo,
    fco_ll,
    recebiveis_receita,
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
msft_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
msft_indicadores_10k.columns = nomes_col
msft_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026,20.68,20.68,4.83,193771.0,40.31,67.94,46.78,58.39,6.25,2.765965e+09,...,22271,88.958019,4.793512,145.541580,1.367749,0.243721,-0.071420,0.944078,0.500841,3.008979
2025,35.95,35.95,2.78,162681.0,36.15,68.82,45.62,57.74,10.66,3.661050e+09,...,18420,90.568517,3.898054,115.212852,1.337124,0.248133,-0.060698,0.836988,0.703227,1.890054
2024,37.03,37.03,2.70,131720.0,35.96,69.76,44.64,53.74,12.16,3.263770e+09,...,17254,84.762934,6.136358,108.326902,1.345058,0.232227,-0.065817,0.900000,0.840417,1.995648
2023,34.17,34.16,2.93,102384.0,34.15,68.92,41.77,48.31,11.99,2.472370e+09,...,22245,83.859661,13.854516,100.278988,1.210348,0.229752,-0.039188,0.855427,0.821921,2.027776
2022,25.56,25.57,3.91,97843.0,36.69,68.40,42.06,49.35,11.16,1.859158e+09,...,32696,81.481137,21.800958,110.694334,1.224051,0.223236,-0.046655,0.909978,0.895667,1.651867
2021,31.96,31.96,3.13,81602.0,36.45,68.93,41.59,48.55,13.80,1.958371e+09,...,27385,82.609675,18.420509,105.959852,1.252469,0.226328,-0.048714,0.940418,0.915898,1.764676
2020,33.18,33.17,3.01,65755.0,30.96,67.78,37.03,45.98,12.42,1.469263e+09,...,22968,81.697829,15.010960,99.254525,1.370227,0.223830,-0.055775,0.922744,1.021522,1.206705
2019,24.55,24.57,4.07,54641.0,31.18,65.90,34.14,43.42,9.41,9.632684e+08,...,19543,85.632574,17.548241,79.804941,1.329893,0.234610,-0.047469,0.955052,0.975025,1.192005
2018,42.26,42.30,2.36,45319.0,15.02,65.25,31.77,41.06,8.47,7.002380e+08,...,10721,87.582140,25.333872,82.006753,2.648241,0.239951,-0.109266,0.968336,1.946292,1.133613
2017,22.78,22.76,4.39,31104.0,37.08,97.38,39.04,54.39,6.67,4.829631e+08,...,11788,126.317188,24.299908,82.336691,1.863186,0.346074,NaN,1.270158,1.479815,0.926065

In [231]:
# Lendo os arquivos 10q
msft_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

msft_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

msft_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

msft_leases_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_10q.xlsx',
    sheet_name='leases',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
msft_bs_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in msft_bs_10q.columns]
msft_is_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in msft_is_10q.columns]
msft_cf_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in msft_cf_10q.columns]
msft_leases_10q.columns = [f_sec.ajustar_mes_12_03_06(col) for col in msft_leases_10q.columns]

In [232]:
# Preços da MSFT
msft_close = yf.download('MSFT', auto_adjust=True, multi_level_index=False, start='2020-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Dezembro
lst_years = [
    '2020', '2021', '2022', '2023', 
    '2024', '2025',
]
lst_months = ['03', '09', '12']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = msft_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
msft_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
msft_close_months = msft_close_months.reindex(index=msft_close_months.index[::-1])

# Retirando o preço de '03-2020' 
msft_close_months = msft_close_months.drop(index='03-2020')


# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Dezembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    # '09',
    # '12'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = msft_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
msft_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
msft_close_months_atual = msft_close_months_atual.reindex(index=msft_close_months_atual.index[::-1])

# Juntando as duas series pandas
msft_close_months = pd.concat([msft_close_months_atual, msft_close_months])

# Arredondamento de duas casas decimais
msft_close_months = round(msft_close_months, 2)

# Não realizou split recentemente (https://br.investing.com/equities/microsoft-corp-historical-data-splits)

# Substituindo o index para ficar igual ao dos dados fundamentalistas
msft_close_months.index = msft_bs_10q.columns[:-3]

msft_close_months

[*********************100%***********************]  1 of 1 completed

2026-03-31    368.68
2025-12-31    480.57
2025-09-30    513.72
2025-03-31    371.03
2024-12-31    415.78
2024-09-30    423.61
2024-03-31    412.69
2023-12-31    368.18
2023-09-30    308.52
2023-03-31    280.49
2022-12-31    232.74
2022-09-30    225.39
2022-03-31    297.05
2021-12-31    323.37
2021-09-30    270.57
2021-03-31    225.32
2020-12-31    212.08
2020-09-30    200.02
dtype: float64

* Os dados do fluxo de caixa são não acumulados:
    - Todas as funções que utilizam dados do fluxo de caixa utilizar com o parâmetro 'ten_k'=True;
    - Para fazer o cálculo da série acumulada utilizar a função 'indicador_acumular_series_trimestrais'.

In [233]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = msft_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=msft_close_months, df_is=msft_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=msft_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=msft_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=msft_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=msft_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=msft_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=True, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=True, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
depreciacao_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=depreciacao_10q, idx=idx_10q)

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=msft_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=msft_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=msft_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=msft_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=msft_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=msft_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=msft_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=msft_bs_10q, df_is=msft_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=msft_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = ['Cash and Cash Equivalents', 'Short-term Investments']
caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=msft_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = ['Current Portion of Long-term Debt', 'Long-term debt']
div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=msft_bs_10q, lst_itens_divida=lst_divida)
div_bruta_total_10q = div_bruta_10q.values + msft_leases_10q.sum().values[0:-3]
div_bruta_total_10q = pd.Series(div_bruta_total_10q, index=idx_10q[0:-3])

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_total_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=msft_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=msft_is_10q, df_bs=msft_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=msft_is_10q, df_bs=msft_bs_10q, div_bruta=div_bruta_total_10q, idx=idx_10q)

# FCO - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fco_10q = f_eua.indicador_fco(ten_k=True, df_cf=msft_cf_10q, first_quarter=None)
fco_10q_sliced = f_eua.indicador_fco(ten_k=True, df_cf=msft_cf_10q, first_quarter=None)[:-3]
fco_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fco_10q, idx=idx_10q)

# FCI - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fci_10q = f_eua.indicador_fci(ten_k=True, df_cf=msft_cf_10q, first_quarter=None)
fci_10q_sliced = f_eua.indicador_fci(ten_k=True, df_cf=msft_cf_10q, first_quarter=None)[:-3]
fci_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fci_10q, idx=idx_10q)

# FCF - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fcf_10q = f_eua.indicador_fcf(ten_k=True, df_cf=msft_cf_10q, first_quarter=None)
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=True, df_cf=msft_cf_10q, first_quarter=None)[:-3]
fcf_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fcf_10q, idx=idx_10q)

# CAPEX - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_capex_10q = ['Purchases Of Property And Equipment And Intangible Assets']

capex_10q = f_eua.indicador_capex(ten_k=True, df_cf=msft_cf_10q, first_quarter=None, lst_itens=lst_capex_10q, idx=idx_10q)
capex_10q_sliced = f_eua.indicador_capex(ten_k=True, df_cf=msft_cf_10q, first_quarter=None, lst_itens=lst_capex_10q, idx=idx_10q)[:-3]
capex_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=capex_10q, idx=idx_10q)

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
sbc_10q = f_eua.indicador_sbc(ten_k=True, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=True, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
sbc_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=sbc_10q, idx=idx_10q)

# Outros custos fluxo de caixa - não possui 'tax paid rsu' ou 'leasing' no fluxo de caixa

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=None)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=msft_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=msft_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=msft_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=msft_bs_10q)

# Change in non cash working capital - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense (Benefit)',
    'Increase (Decrease) in Accounts Receivable',
    'Increase (Decrease) in Inventories',
    'Increase (Decrease) in Other Current Assets',
    'Increase (Decrease) in Other Noncurrent Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Income Taxes Payable',
    'Increase (Decrease) in Other Current Liabilities',
    'Increase (Decrease) in Other Noncurrent Liabilities'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=msft_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=msft_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)[:-3]
change_non_cash_wc_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=change_non_cash_wc_10q, idx=idx_10q)

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=msft_is_10q, idx=idx_10q)

# New borrowing - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_new_borrowing = ['Proceeds from Debt, Maturing in More than Three Months']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
new_borrowing_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=new_borrowing_10q, idx=idx_10q)

# Debt paid - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_debt_paid = [
    'Proceeds from (Repayments of) Short-term Debt, Maturing in Three Months or Less', 
    'Repayments of Debt, Maturing in More than Three Months'
]

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=msft_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
debt_paid_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=debt_paid_10q, idx=idx_10q)

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=msft_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=msft_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=msft_is_10q,
        idx=idx_10q
)

# Dividendo por Ação - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
dpa_10q = f_eua.indicador_dpa(ten_k=True, df_cf=msft_cf_10q, df_is=msft_is_10q, div_nao_acum=None)[:-3]

# Payout - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
payout_10q = f_eua.indicador_payout(ten_k=True, df_cf=msft_cf_10q, df_is=msft_is_10q, div_nao_acum=None)[:-3]

# Buyback - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
buyback_10q = f_eua.indicador_buyback(ten_k=True, df_cf=msft_cf_10q,  first_quarter=None)[:-3]

# DSO
dso_10q = f_eua.indicador_dso(ten_k=False, df_bs=msft_bs_10q, df_is=msft_is_10q)

# DIO
dio_10q = f_eua.indicador_dio(ten_k=False, df_bs=msft_bs_10q, df_is=msft_is_10q)

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=msft_bs_10q, df_is=msft_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=msft_is_10q)

# Recebíveis/Receita
recebiveis_receita_10q = f_eua.indicador_recebiveis_receita(ten_k=False, df_bs=msft_bs_10q, df_is=msft_is_10q)

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=msft_is_10q, df_bs=msft_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=msft_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_total_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    dso_10q,
    dio_10q,
    dpo_10q,
    fco_ll_10q,
    recebiveis_receita_10q,
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
msft_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado',
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    'DSO',
    'DIO',
    'DPO',
    'FCO/LL',
    'Recebíveis/Receita',
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
msft_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
msft_indicadores_10q = msft_indicadores_10q.fillna(0)

msft_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,Buyback,DSO,DIO,DPO,FCO/LL,Recebíveis/Receita,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-03-31,86.15,22.13,4.52,48565.0,187800.0,38.34,67.63,46.33,58.59,6.61,...,4627,264.398873,16.584725,510.371440,1.468909,0.724380,-0.023712,0.961165,2.128737,3.036884
2025-12-31,92.86,30.77,3.25,47473.0,177715.0,47.32,68.04,47.09,58.41,9.14,...,7415,253.900742,14.879321,524.471476,0.929794,0.695618,0.004503,0.753228,1.516746,3.248097
2025-09-30,137.62,37.33,2.68,51022.0,168177.0,35.72,69.05,48.87,65.69,10.52,...,5650,248.558830,17.154681,494.601339,1.623851,0.680983,-0.029861,0.883090,2.584279,1.484879
2025-03-31,106.81,28.58,3.50,40740.0,150763.0,36.86,68.72,45.67,58.15,8.57,...,4781,269.324637,14.121082,437.120763,1.434480,0.737876,-0.021435,0.909278,2.594796,1.915904
2024-12-31,128.23,33.40,2.99,38480.0,143014.0,34.62,68.69,45.46,55.26,10.21,...,4986,252.593922,15.220194,378.545805,0.924631,0.692038,0.003618,0.579288,2.315704,2.314926
2024-09-30,127.65,34.69,2.88,37935.0,135350.0,37.61,69.35,46.58,57.84,10.94,...,4107,245.696729,29.528335,413.469327,1.385657,0.673142,-0.019639,0.901015,2.838043,2.021265
2024-03-31,139.78,36.36,2.75,33608.0,123316.0,35.47,70.08,44.59,54.33,12.11,...,4213,259.798005,25.720616,356.755201,1.454807,0.711775,-0.023088,0.949685,3.126077,1.817156
2023-12-31,125.12,34.73,2.88,32991.0,113755.0,35.26,68.36,43.59,53.19,11.48,...,4000,252.068929,30.040004,329.138001,0.862048,0.690600,0.007225,0.571459,2.401326,1.633663
2023-09-30,102.82,30.82,3.24,30816.0,105072.0,39.44,71.16,47.59,54.53,10.38,...,4831,238.651114,67.169672,432.281622,1.371989,0.653839,-0.020587,0.992439,2.705756,2.529202
2023-03-31,114.06,30.36,3.29,25901.0,98393.0,34.62,69.49,42.29,49.00,10.72,...,5509,258.400969,65.110677,346.374318,1.335647,0.707948,-0.016951,0.943632,3.262145,1.861651
2022-12-31,105.58,25.08,3.99,24047.0,98235.0,31.14,66.85,38.67,45.59,9.47,...,5459,247.958083,62.196935,320.460316,0.680244,0.679337,0.014901,0.464632,3.073059,1.719846
2022-09-30,95.74,22.98,4.35,24308.0,97638.0,35.03,69.17,42.93,48.50,9.68,...,5573,227.780915,100.816723,392.330119,1.321372,0.624057,-0.016231,0.954336,3.662907,2.251971
2022-03-31,133.06,31.24,3.20,24137.0,93314.0,33.89,68.37,41.26,48.90,13.66,...,8822,241.161771,77.043868,375.986231,1.517575,0.660717,-0.026498,1.051746,3.854675,1.415319
2021-12-31,129.33,34.66,2.89,25743.0,89835.0,36.28,67.21,43.01,49.77,15.17,...,7433,236.521806,64.972583,329.576061,0.771649,0.648005,0.013297,0.562483,2.812523,1.677632
2021-09-30,99.14,31.21,3.20,23450.0,82613.0,45.25,69.89,44.66,51.75,13.37,...,7684,220.279034,91.236626,396.722849,1.196781,0.603504,-0.012680,1.046482,2.857352,1.808842
2021-03-31,109.90,30.66,3.26,19984.0,75256.0,37.06,68.72,40.88,47.92,12.63,...,6930,230.363257,62.815255,375.268685,1.434884,0.631132,-0.022621,1.109838,3.467490,1.733311
2020-12-31,103.62,31.05,3.22,20658.0,72366.0,35.90,67.05,41.55,47.96,12.30,...,6535,231.425388,49.475835,328.381711,0.809416,0.634042,0.010042,0.605867,2.822350,1.511771
2020-09-30,108.93,32.37,3.09,18521.0,67365.0,37.39,70.39,42.73,49.85,12.26,...,6743,224.487673,89.740502,414.995910,1.391708,0.615035,-0.018767,1.043950,3.291802,1.855198

In [236]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//microsoft//msft_indicators.xlsx') as writer:
    msft_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    msft_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')

## Netflix

* 1Q -> Lançamento em Março (03);
* 2Q -> Lançamento em Junho (06);
* 3Q -> Lançamento em Setembro (09);
* 10K -> Lançamento em Dezembro (12).

In [ ]:
ticker = 'nflx'
f_sec.cik_matching_ticker(ticker)

### Scraping Netflix 10-K

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents = f_sec.get_filtered_filings(ticker=ticker, ten_k=True, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num = {k: v.replace('-', '') for k, v in acc_documents.items()}

# Transformando o dicionário em um df
df_lst_acc_num_nflx = pd.DataFrame.from_dict(dict_acc_num, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 2017, 2018, 2019, 2020, 2021 e 2022
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000106528023000035', # 2022
            '000106528022000036', # 2021
            '000106528021000040', # 2020
            '000106528020000040', # 2019
            '000106528019000043', # 2018
            '000106528018000069', # 2017
        ]
    },
    index=pd.to_datetime([
        '2022-12-31', 
        '2021-12-31', 
        '2020-12-31',
        '2019-12-31',
        '2018-12-31',
        '2017-12-31',
    ])
)

# Concatenando os dfs
df_lst_acc_num_nflx = pd.concat([df_lst_acc_num_nflx, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_nflx.index = pd.to_datetime(df_lst_acc_num_nflx.index, format='%Y-%m-%d')

df_lst_acc_num_nflx

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-K)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_nflx['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10k = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10k = df_balance_sheet_10k.fillna(0)

# A linha 'Treasury Stock, Common, Value' na coluna abaixo está zerada
# As informações estão nas linhas 'Treasury Stock, Value'
df_balance_sheet_10k.loc['Treasury Stock, Common, Value', '2021-12-31'] = df_balance_sheet_10k.loc['Treasury Stock, Value', '2021-12-31'] 

# Removendo as linhas que movemos os seus itens para as linhas corretas
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'Treasury Stock, Value',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10k = df_balance_sheet_10k.drop([
    'us-gaap_AssetsCurrentAbstract',
    'Preferred Stock, Value, Issued',
    'Available-for-sale Securities, Current'
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'nflx_ContentAssetsNetNoncurrent': 'Content Assets Net Noncurrent',
    'nflx_ContentLiabilitiesCurrent': 'Content Liabilities Current',
    'nflx_ContentLiabilitiesNoncurrent': 'Content Liabilities Noncurrent',
    'nflx_ContentAssetsNetCurrent': 'Content Assets Net Current',
})

df_balance_sheet_10k

In [ ]:
# Fazendo o scraping do income statement (10-K)
income_statement_lst = []

for acc_num in df_lst_acc_num_nflx['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10k = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10k = df_income_statement_10k.fillna(0)

# A linha 'Selling and Marketing Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'Marketing Expense'
df_income_statement_10k.loc['Selling and Marketing Expense', '2023-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2023-12-31'] 
df_income_statement_10k.loc['Selling and Marketing Expense', '2022-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2022-12-31'] 
df_income_statement_10k.loc['Selling and Marketing Expense', '2021-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2021-12-31'] 
df_income_statement_10k.loc['Selling and Marketing Expense', '2020-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2020-12-31'] 
df_income_statement_10k.loc['Selling and Marketing Expense', '2019-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2019-12-31'] 
df_income_statement_10k.loc['Selling and Marketing Expense', '2018-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2018-12-31'] 
df_income_statement_10k.loc['Selling and Marketing Expense', '2017-12-31'] = df_income_statement_10k.loc['Marketing Expense', '2017-12-31'] 

# A linha 'Research and Development Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'nflx_TechnologyandDevelopmentExpense'
df_income_statement_10k.loc['Research and Development Expense', '2021-12-31'] = df_income_statement_10k.loc['nflx_TechnologyandDevelopmentExpense', '2021-12-31'] 
df_income_statement_10k.loc['Research and Development Expense', '2020-12-31'] = df_income_statement_10k.loc['nflx_TechnologyandDevelopmentExpense', '2020-12-31'] 
df_income_statement_10k.loc['Research and Development Expense', '2019-12-31'] = df_income_statement_10k.loc['nflx_TechnologyandDevelopmentExpense', '2019-12-31'] 
df_income_statement_10k.loc['Research and Development Expense', '2018-12-31'] = df_income_statement_10k.loc['nflx_TechnologyandDevelopmentExpense', '2018-12-31'] 
df_income_statement_10k.loc['Research and Development Expense', '2017-12-31'] = df_income_statement_10k.loc['nflx_TechnologyandDevelopmentExpense', '2017-12-31'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-12-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2019-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2019-12-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2018-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2018-12-31'] 
df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2017-12-31'] = df_income_statement_10k.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2017-12-31'] 

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'
df_income_statement_10k.loc['Interest Expense', '2025-12-31'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2025-12-31'] 
df_income_statement_10k.loc['Interest Expense', '2024-12-31'] = df_income_statement_10k.loc['InterestExpenseNonoperating', '2024-12-31'] 

# # Removendo as linhas que movemos os seus itens para as linhas corretas
df_income_statement_10k = df_income_statement_10k.drop([
    'Marketing Expense',
    'nflx_TechnologyandDevelopmentExpense',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
    'InterestExpenseNonoperating'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10k = df_income_statement_10k.drop([
    'us-gaap_IncomeStatementAbstract',
])

# Calculando o 'Gross Profit'
df_income_statement_10k.loc['Gross Profit'] = df_income_statement_10k.loc['Revenues'] - df_income_statement_10k.loc['Cost of Revenue']

df_income_statement_10k

In [ ]:
# Fazendo o scraping do cash flow statement (10-K)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_nflx['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10k = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10k = df_cash_flow_10k.fillna(0)

# A linha 'Payments to Acquire Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Short-term Investments'
df_cash_flow_10k.loc['Payments to Acquire Investments', '2023-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Short-term Investments', '2023-12-31'] 
df_cash_flow_10k.loc['Payments to Acquire Investments', '2022-12-31'] = df_cash_flow_10k.loc['Payments to Acquire Short-term Investments', '2022-12-31'] 

# A linha 'nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications' nas colunas abaixo estão zeradas
# As informações estão na linha 'Deferred Income Tax Expense (Benefit)'
df_cash_flow_10k.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2018-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2018-12-31'] 
df_cash_flow_10k.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2017-12-31'] = df_cash_flow_10k.loc['Deferred Income Tax Expense (Benefit)', '2017-12-31'] 

# A linha 'Foreign Currency Transaction Gain (Loss), before Tax' na coluna abaixo está zerada
# As informações estão na linha 'Foreign Currency Transaction Loss, before Tax'
df_cash_flow_10k.loc['Foreign Currency Transaction Gain (Loss), before Tax', '2017-12-31'] = df_cash_flow_10k.loc['Foreign Currency Transaction Loss, before Tax', '2017-12-31'] 

# A linha 'Increase (Decrease) in Contract with Customer, Liability' na coluna abaixo está zerada
# As informações estão na linha 'Increase (Decrease) in Deferred Revenue'
df_cash_flow_10k.loc['Increase (Decrease) in Contract with Customer, Liability', '2017-12-31'] = df_cash_flow_10k.loc['Increase (Decrease) in Deferred Revenue', '2017-12-31'] 

# A linha 'Proceeds from Issuance of Debt' na coluna abaixo está zerada
# As informações estão na linha 'Proceeds from Issuance of Long-term Debt'
df_cash_flow_10k.loc['Proceeds from Issuance of Debt', '2017-12-31'] = df_cash_flow_10k.loc['Proceeds from Issuance of Long-term Debt', '2017-12-31'] 

# A linha 'Interest Paid, Excluding Capitalized Interest, Operating Activities' na coluna abaixo está zerada
# As informações estão na linha 'Interest Paid, Including Capitalized Interest, Operating and Investing Activities'
df_cash_flow_10k.loc['Interest Paid, Excluding Capitalized Interest, Operating Activities', '2017-12-31'] = df_cash_flow_10k.loc['Interest Paid, Including Capitalized Interest, Operating and Investing Activities', '2017-12-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10k = df_cash_flow_10k.drop([
    'Payments to Acquire Short-term Investments',
    'Deferred Income Tax Expense (Benefit)',
    'Foreign Currency Transaction Loss, before Tax',
    'Increase (Decrease) in Deferred Revenue',
    'Proceeds from Issuance of Long-term Debt',
    'Interest Paid, Including Capitalized Interest, Operating and Investing Activities',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10k = df_cash_flow_10k.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
    'Payments to Acquire Debt Securities, Available-for-sale',
    'Proceeds from Sale of Debt Securities, Available-for-sale',
    'Excess Tax Benefit from Share-based Compensation, Operating Activities',
    'Excess Tax Benefit from Share-based Compensation, Financing Activities',
    'Proceeds from Maturities, Prepayments and Calls of Debt Securities, Available-for-sale',
    'Payments for (Proceeds from) Available-for-sale Securities, Short-term',
    'Proceeds from Sale of Available-for-sale Securities',
    'Proceeds from Sale, Maturity and Collection of Short-term Investments',
    'nflx_CostofServicesAmortizationofDVDContentAssets',
    'nflx_PaymentsForAcquisitionsOfDVDContentAssets',
    'nflx_ChangeinInvestingActivitiesIncludedInLiabilities',
    'Effect of Exchange Rate on Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Effect of Exchange Rate on Cash and Cash Equivalents',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents, Period Increase (Decrease), Including Exchange Rate Effect',
    'Cash and Cash Equivalents, Period Increase (Decrease)',
    'Cash, Cash Equivalents, Restricted Cash and Restricted Cash Equivalents',
    'Cash and Cash Equivalents, at Carrying Value',
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'nflx_AdditionstoStreamingContentAssets': 'Additions to Streaming Content Assets',
    'nflx_ChangeInStreamingContentLiabilities': 'Change In Streaming Content Liabilities',
    'nflx_CostofServicesAmortizationofStreamingContentAssets': 'Cost of Services Amortization of Streaming Content Assets',
    'nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications': 'Deferred Income Tax Expense Benefit Including Reclassifications',
})

# Arrumando e adicionando alguns números no df
df_cash_flow_10k.loc['Payment, Tax Withholding, Share-based Payment Arrangement', '2021-12-31'] = -224168

df_cash_flow_10k

In [ ]:
# O 'df_cash_flow_10k' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10k = [
    # 2025-12-31
    0,
    # 2024-12-31
    0,
    # 2023-12-31
    0,
    # 2022-12-31
    0,
    # 2021-12-31
    0,	
    # 2020-12-31	
    0,	
    # 2019-12-31	
    0,	
    # 2018-12-31	
    0,	
    # 2017-12-31	
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10k.loc['Payments of Dividends'] = new_row_div_cf_10k

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10k = df_balance_sheet_10k.rename(index={
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10k = df_income_statement_10k.rename(index={
    'Research and Development Expense': 'Research and Development',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10k = df_cash_flow_10k.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10k.xlsx') as writer:
    df_balance_sheet_10k.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10k.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10k.to_excel(writer, sheet_name='cash_flow')

### Scraping Netflix 10-Q

In [ ]:
# Número dos documentos que contém a DRE, BP e FC 
acc_documents_10q = f_sec.get_filtered_filings(ticker=ticker, ten_k=False, just_accession_numbers=True)

# Trocando os '-' para '' das strings ('0001045810-24-000264' -> '000104581024000264')
dict_acc_num_10q = {k: v.replace('-', '') for k, v in acc_documents_10q.items()}

# Transformando o dicionário em um df
df_lst_acc_num_10q_nflx = pd.DataFrame.from_dict(dict_acc_num_10q, orient='index', columns=['acc_num'])

# Adicionando os 'acc_num' de 1Q, 2Q e 3Q dos anos de 2020, 2021, 2022 e 2023
df_acc_num = pd.DataFrame(
    {
        'acc_num': [
            '000106528023000120', # 1Q 2023
            '000106528022000368', # 3Q 2022
            '000106528022000257', # 2Q 2022
            '000106528022000145', # 1Q 2022
            '000106528021000363', # 3Q 2021
            '000106528021000250', # 2Q 2021
            '000106528021000144', # 1Q 2021
            '000106528020000451', # 3Q 2020
            '000106528020000309', # 2Q 2020
            '000106528020000155', # 1Q 2020
        ]
    },
    index=pd.to_datetime([
        '2023-03-31',
        '2022-09-30', 
        '2022-06-30',
        '2022-03-31',
        '2021-09-30', 
        '2021-06-30',
        '2021-03-31',
        '2020-09-30', 
        '2020-06-30',
        '2020-03-31',

    ])
)

# Concatenando os dfs
df_lst_acc_num_10q_nflx = pd.concat([df_lst_acc_num_10q_nflx, df_acc_num])

# Transformando em datetime o index
df_lst_acc_num_10q_nflx.index = pd.to_datetime(df_lst_acc_num_10q_nflx.index, format='%Y-%m-%d')

df_lst_acc_num_10q_nflx

In [ ]:
# Rótulos
labels_dict = f_sec.get_label_dictionary(ticker, headers=f_sec.header)

In [ ]:
# Fazendo o scraping do balance sheet (10-Q)
balance_sheet_lst = []

for acc_num in df_lst_acc_num_10q_nflx['acc_num']:

    # Balance sheet
    balance_sheet = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='balance_sheet')
    balance_sheet = f_sec.rename_statement(balance_sheet, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    balance_sheet = balance_sheet.iloc[:, 0]
    balance_sheet_lst.append(balance_sheet)

# Removendo duplicatas de índice em cada série
balance_sheet_lst_clean = [df[~df.index.duplicated(keep='first')] for df in balance_sheet_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_balance_sheet_10q = pd.concat(balance_sheet_lst_clean, axis=1)

# Substituindo os NaN por 0
df_balance_sheet_10q = df_balance_sheet_10q.fillna(0)

# A linha 'Treasury Stock, Common, Value' nas colunas abaixo estão zeradas
# As informações estão na linha 'Treasury Stock, Value' 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2022-03-31'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2022-03-31'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-09-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-09-30'] 
df_balance_sheet_10q.loc['Treasury Stock, Common, Value', '2021-06-30'] = df_balance_sheet_10q.loc['Treasury Stock, Value', '2021-06-30'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'Treasury Stock, Value',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_balance_sheet_10q = df_balance_sheet_10q.drop([
    'us-gaap_AssetsCurrentAbstract',
])

# Renomeando a linha do índice que está sem formato 
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'nflx_ContentAssetsNetNoncurrent': 'Content Assets Net Noncurrent',
    'nflx_ContentLiabilitiesCurrent': 'Content Liabilities Current',
    'nflx_ContentLiabilitiesNoncurrent': 'Content Liabilities Noncurrent',
})

df_balance_sheet_10q

In [ ]:
# Fazendo o scraping do income statement (10-Q)
income_statement_lst = []

for acc_num in df_lst_acc_num_10q_nflx['acc_num']:

    # Income statement
    income_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='income_statement')
    income_statement = f_sec.rename_statement(income_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    income_statement = income_statement.iloc[:, 0]
    income_statement_lst.append(income_statement)

# Removendo duplicatas de índice em cada série
income_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in income_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_income_statement_10q = pd.concat(income_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_income_statement_10q = df_income_statement_10q.fillna(0)

# A linha 'Selling and Marketing Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'Marketing Expense'  
df_income_statement_10q.loc['Selling and Marketing Expense', '2024-09-30'] = df_income_statement_10q.loc['Marketing Expense', '2024-09-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2024-06-30'] = df_income_statement_10q.loc['Marketing Expense', '2024-06-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2024-03-31'] = df_income_statement_10q.loc['Marketing Expense', '2024-03-31'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2023-09-30'] = df_income_statement_10q.loc['Marketing Expense', '2023-09-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2023-06-30'] = df_income_statement_10q.loc['Marketing Expense', '2023-06-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2023-03-31'] = df_income_statement_10q.loc['Marketing Expense', '2023-03-31'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2022-09-30'] = df_income_statement_10q.loc['Marketing Expense', '2022-09-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2022-06-30'] = df_income_statement_10q.loc['Marketing Expense', '2022-06-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2022-03-31'] = df_income_statement_10q.loc['Marketing Expense', '2022-03-31'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2021-09-30'] = df_income_statement_10q.loc['Marketing Expense', '2021-09-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2021-06-30'] = df_income_statement_10q.loc['Marketing Expense', '2021-06-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2021-03-31'] = df_income_statement_10q.loc['Marketing Expense', '2021-03-31'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2020-09-30'] = df_income_statement_10q.loc['Marketing Expense', '2020-09-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2020-06-30'] = df_income_statement_10q.loc['Marketing Expense', '2020-06-30'] 
df_income_statement_10q.loc['Selling and Marketing Expense', '2020-03-31'] = df_income_statement_10q.loc['Marketing Expense', '2020-03-31'] 

# A linha 'Interest Expense' nas colunas abaixo estão zeradas
# As informações estão na linha 'InterestExpenseNonoperating'  
df_income_statement_10q.loc['Interest Expense', '2026-06-30'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-06-30'] 
df_income_statement_10q.loc['Interest Expense', '2026-03-31'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2026-03-31'] 
df_income_statement_10q.loc['Interest Expense', '2025-09-30'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-09-30'] 
df_income_statement_10q.loc['Interest Expense', '2025-06-30'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-06-30'] 
df_income_statement_10q.loc['Interest Expense', '2025-03-31'] = df_income_statement_10q.loc['InterestExpenseNonoperating', '2025-03-31'] 

# A linha 'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest' nas colunas abaixo estão zeradas
# As informações estão na linha 'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest'  
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-06-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-06-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2021-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2021-03-31'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-09-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-09-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-06-30'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-06-30'] 
df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest', '2020-03-31'] = df_income_statement_10q.loc['Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest', '2020-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_income_statement_10q = df_income_statement_10q.drop([
    'Marketing Expense',
    'InterestExpenseNonoperating',
    'Income (Loss) from Continuing Operations before Equity Method Investments, Income Taxes, Noncontrolling Interest',
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_income_statement_10q = df_income_statement_10q.drop([
    'us-gaap_IncomeStatementAbstract',
])

# Calculando o 'Gross Profit'
df_income_statement_10q.loc['Gross Profit'] = df_income_statement_10q.loc['Revenues'] - df_income_statement_10q.loc['Cost of Revenue']

df_income_statement_10q

In [ ]:
# Fazendo o scraping do cash flow statement (10-Q)
cash_flow_statement_lst = []

for acc_num in df_lst_acc_num_10q_nflx['acc_num']:

    # Cash flow statement
    cash_flow_statement = f_sec.process_one_statement(ticker=ticker, accession_number=acc_num, statement_name='cash_flow_statement')
    cash_flow_statement = f_sec.rename_statement(cash_flow_statement, label_dictionary=labels_dict)
    # Selecionando apenas a primeira coluna do df
    cash_flow_statement = cash_flow_statement.iloc[:, 0]
    cash_flow_statement_lst.append(cash_flow_statement)

# Removendo duplicatas de índice em cada série
cash_flow_statement_lst_clean = [df[~df.index.duplicated(keep='first')] for df in cash_flow_statement_lst]

# Concatenando tudo de uma vez, sem iniciar com DataFrame vazio
df_cash_flow_10q = pd.concat(cash_flow_statement_lst_clean, axis=1)

# Substituindo os NaN por 0
df_cash_flow_10q = df_cash_flow_10q.fillna(0)

# A linha 'nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications' nas colunas abaixo estão zeradas
# As informações estão na linha 'Deferred Income Tax Expense (Benefit)'
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2022-09-30'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2022-09-30'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2022-06-30'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2022-06-30'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2022-03-31'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2022-03-31'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2021-09-30'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2021-09-30'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2021-06-30'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2021-06-30'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2021-03-31'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2021-03-31'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2020-09-30'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2020-09-30'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2020-06-30'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2020-06-30'] 
df_cash_flow_10q.loc['nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications', '2020-03-31'] = df_cash_flow_10q.loc['Deferred Income Tax Expense (Benefit)', '2020-03-31'] 

# A linha 'Payments to Acquire Investments' nas colunas abaixo estão zeradas
# As informações estão na linha 'Payments to Acquire Short-term Investments'
df_cash_flow_10q.loc['Payments to Acquire Investments', '2023-06-30'] = df_cash_flow_10q.loc['Payments to Acquire Short-term Investments', '2023-06-30'] 
df_cash_flow_10q.loc['Payments to Acquire Investments', '2023-03-31'] = df_cash_flow_10q.loc['Payments to Acquire Short-term Investments', '2023-03-31'] 

# Removendo as linhas que já que movemos os seus itens para as linhas corretas
df_cash_flow_10q = df_cash_flow_10q.drop([
    'Deferred Income Tax Expense (Benefit)',
    'Payments to Acquire Short-term Investments'
])

# Removendo as linhas que não possuem nenhuma informação (NaN ou zeros)
df_cash_flow_10q = df_cash_flow_10q.drop([
    'us-gaap_NetCashProvidedByUsedInOperatingActivitiesAbstract',
])

# Renomeando a linha do índice que está sem formato 
df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'nflx_AdditionstoStreamingContentAssets': 'Additionsto Streaming Content Assets',
    'nflx_ChangeInStreamingContentLiabilities': 'Change In Streaming Content Liabilities',
    'nflx_CostofServicesAmortizationofStreamingContentAssets': 'Cost of Services Amortization of Streaming Content Assets',
    'nflx_DeferredIncomeTaxExpenseBenefitIncludingReclassifications': 'Deferred Income Tax Expense Benefit Including Reclassifications',
})

df_cash_flow_10q

In [ ]:
# O 'df_cash_flow_10q' não conseguiu puxar o dado da linha 'Payments of Dividends' 

# Linhas 'Payments of Dividends' a ser adicionada 
new_row_div_cf_10q = [
    # 2026-06-30	
    0,	
    # 2026-03-31
    0,	
    # 2025-09-30	
    0,	
    # 2025-06-30	
    0,	
    # 2025-03-31
    0,	
    # 2024-09-30	
    0,	
    # 2024-06-30	
    0,	
    # 2024-03-31
    0,	
    # 2023-09-30	
    0,	
    # 2023-06-30	
    0,	
    # 2023-03-31
    0,	
    # 2022-09-30	
    0,	
    # 2022-06-30	
    0,	
    # 2022-03-31
    0,	
    # 2021-09-30	
    0,	
    # 2021-06-30	
    0,	
    # 2021-03-31
    0,	
    # 2020-09-30	
    0,	
    # 2020-06-30	
    0,	
    # 2020-03-31
    0,	
]

# Adicionando as novas linhas
df_cash_flow_10q.loc['Payments of Dividends'] = new_row_div_cf_10q

In [ ]:
# Arrumando alguns index dos dfs para ficar padronizado com os index utilizados nas funções p/ calcular os indicadores fundamentalistas
df_balance_sheet_10q = df_balance_sheet_10q.rename(index={
    'Accounts Payable, Current': 'Accounts Payable',
    "Stockholders' Equity Attributable to Parent": 'Total Shareholders Equity'
})

df_income_statement_10q = df_income_statement_10q.rename(index={
    'Revenue from Contract with Customer, Excluding Assessed Tax': 'Revenues',
    'Cost of Revenue': 'Cost of Goods Sold',
    'Research and Development Expense': 'Research and Development',
    'Operating Income (Loss)': 'Operating Income',
    'Income (Loss) from Continuing Operations before Income Taxes, Noncontrolling Interest': 'Income Before Provision for Income Taxes',
    'Income Tax Expense (Benefit)': 'Provision for Income Taxes',
    'Net Income (Loss) Attributable to Parent': 'Net Income',
    'Weighted Average Number of Shares Outstanding, Basic': 'Number of Shares - Basic',
    'Weighted Average Number of Shares Outstanding, Diluted': 'Number of Shares - Diluted'
})

df_cash_flow_10q = df_cash_flow_10q.rename(index={
    'Share-based Payment Arrangement, Noncash Expense': 'Stock-based Compensation'
})

In [ ]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10q.xlsx') as writer:
    df_balance_sheet_10q.to_excel(writer, sheet_name='balance_sheet')
    df_income_statement_10q.to_excel(writer, sheet_name='income_statement')
    df_cash_flow_10q.to_excel(writer, sheet_name='cash_flow')

### Indicadores Fundamentalistas

In [237]:
# Lendo os arquivos 10k
nflx_bs = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10k.xlsx', 
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

nflx_is = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10k.xlsx', 
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

nflx_cf = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10k.xlsx', 
    sheet_name='cash_flow', 
    index_col='Unnamed: 0'
)

# Transformando as colunas em datetime
nflx_bs.columns = pd.to_datetime(nflx_bs.columns)
nflx_is.columns = pd.to_datetime(nflx_is.columns)
nflx_cf.columns = pd.to_datetime(nflx_cf.columns)

# Transformando as colunas em apenas o ano
nflx_bs.columns = nflx_bs.columns.year
nflx_is.columns = nflx_is.columns.year
nflx_cf.columns = nflx_cf.columns.year

In [238]:
# Preços da NFLX
nflx_close = yf.download('NFLX', auto_adjust=True, multi_level_index=False, start='2017-01-01')['Close']

# Selecionando o último preço do mês de Dezembro de cada ano 
lst_years = [
    '2017', '2018', '2019', '2020', 
    '2021', '2022', '2023', '2024',
    '2025',
]

last_dec_close = []

for year in lst_years:
    last_close = nflx_close[f'{year}-12'].iloc[-1]
    last_dec_close.append(last_close)

# Transformando em uma série pandas
nflx_close_dec = pd.Series(last_dec_close, index=lst_years)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nflx_close_dec = nflx_close_dec.reindex(index=nflx_close_dec.index[::-1])

# Arredondamento de duas casas decimais
nflx_close_dec = round(nflx_close_dec, 2)

# Teve um split de 10:1 em 16/11/2025 (https://br.investing.com/equities/netflix,-inc.-historical-data-splits)
nflx_close_dec.loc['2024'] = nflx_close_dec.loc['2024'] * 10
nflx_close_dec.loc['2023'] = nflx_close_dec.loc['2023'] * 10
nflx_close_dec.loc['2022'] = nflx_close_dec.loc['2022'] * 10
nflx_close_dec.loc['2021'] = nflx_close_dec.loc['2021'] * 10
nflx_close_dec.loc['2020'] = nflx_close_dec.loc['2020'] * 10
nflx_close_dec.loc['2019'] = nflx_close_dec.loc['2019'] * 10
nflx_close_dec.loc['2018'] = nflx_close_dec.loc['2018'] * 10
nflx_close_dec.loc['2017'] = nflx_close_dec.loc['2017'] * 10

# Transformando o index em int
nflx_close_dec .index = nflx_close_dec .index.astype(int)

nflx_close_dec

[*********************100%***********************]  1 of 1 completed

2025     93.76
2024    891.30
2023    486.90
2022    294.90
2021    602.40
2020    540.70
2019    323.60
2018    267.70
2017    192.00
dtype: float64

In [239]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx = nflx_bs.columns

# Valor de Mercado
vm = f_eua.indicador_vm(ten_k=True, price=nflx_close_dec, df_is=nflx_is) 

# LPA
lpa = f_eua.indicador_lpa(ten_k=True, df_is=nflx_is, idx=None)

# P/L Damodaran
p_lpa_damodaran = f_eua.indicador_p_lpa_2(ten_k=True, vm=vm, df_is=nflx_is)

# P/L
p_lpa = f_eua.indicador_p_lpa(ten_k=True, price=nflx_close_dec, lpa=lpa, idx=idx)

# L/P
lpa_p = f_eua.indicador_lpa_p(ten_k=True, price=nflx_close_dec, lpa=lpa, idx=idx) 

# Depreciação
depreciacao = f_eua.indicador_depreciacao(ten_k=True, df_cf=nflx_cf, first_quarter=None, idx=idx)

# EBITDA
ebitda = f_eua.indicador_ebitda(ten_k=True, df_is=nflx_is, idx=None, depreciacao=depreciacao)

# Margem Líquida
m_liq = f_eua.indicador_ml(ten_k=True, df_is=nflx_is)

# Margem bruta
m_bruta = f_eua.indicador_mb(ten_k=True, df_is=nflx_is)

# Margem operacional
m_operacional = f_eua.indicador_mo(ten_k=True, df_is=nflx_is)

# Margem ebitda
m_ebitda = f_eua.indicador_me(ten_k=True, ebitda=ebitda, df_is=nflx_is)

# VPA
vpa = f_eua.indicador_vpa(ten_k=True, df_bs=nflx_bs, df_is=nflx_is)

# P/VPA
p_vpa = f_eua.indicador_p_vpa(ten_k=True, price=nflx_close_dec, vpa=vpa, idx=idx)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value', 
    'Short-term Investments'
]

caixa = f_eua.indicador_caixa(ten_k=True, df_bs=nflx_bs, lst_itens_caixa=lst_caixa)

# Dívida Bruta
lst_divida = [
    'Short-term Debt', 
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta = f_eua.indicador_divida_bruta(ten_k=True, df_bs=nflx_bs, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq = f_eua.indicador_divida_liquida(ten_k=True, caixa=caixa, div_bruta=div_bruta, idx=idx)

# Dívida Líquida / EBITDA
dl_ebitda = f_eua.indicador_dl_ebitda(ten_k=True, ebitda=ebitda, div_liq=div_liq, idx=None)

# Dívida Líquida / PL
dl_pl = f_eua.indicador_dl_pl(ten_k=True, div_liq=div_liq, df_bs=nflx_bs) 

# EV/EBITDA
ev_ebitda = f_eua.indicador_ev_ebitda(vm=vm, div_liq=div_liq, ebitda=ebitda)

# ROE
roe = f_eua.indicador_roe(ten_k=True, df_is=nflx_is, df_bs=nflx_bs, idx=None)

# ROIC
roic = f_eua.indicador_roic(ten_k=True, df_is=nflx_is, df_bs=nflx_bs, div_bruta=div_bruta, idx=idx)

# FCO
fco = f_eua.indicador_fco(ten_k=True, df_cf=nflx_cf, first_quarter=None) 

# FCI
fci = f_eua.indicador_fci(ten_k=True, df_cf=nflx_cf, first_quarter=None) 

# FCF
fcf = f_eua.indicador_fcf(ten_k=True, df_cf=nflx_cf, first_quarter=None) 

# CAPEX
lst_capex = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'Payments to Acquire Investments'
]

capex= f_eua.indicador_capex(ten_k=True, df_cf=nflx_cf, first_quarter=None, lst_itens=lst_capex, idx=idx)

# Free Cash Flow
free_cash_flow = f_eua.indicador_free_cash_flow(fco=fco, capex=capex)

# SBC
sbc = f_eua.indicador_sbc(ten_k=True, df_cf=nflx_cf, first_quarter=None, idx=idx)

# Outros custos fluxo de caixa
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=nflx_cf, first_quarter=None, lst_itens=lst_custos_cf, idx=idx)

# Adjusted Free Cash Flow
adjusted_free_cash_flow = f_eua.indicador_adjusted_free_cash_flow(fco=fco, capex=capex, sbc=sbc, outros_custos_cf=outros_custos_cf)

# Free Cash Flow Yield
free_cash_flow_yield = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow, vm=vm)

# Net CAPEX
net_capex = f_eua.indicador_net_capex(capex=capex, depreciation=depreciacao)

# R&D
rd_expense = f_eua.indicador_rd(ten_k=True, df_is=nflx_is, idx=idx)

# Net CAPEX ajustado
adj_net_capex = f_eua.indicador_adj_net_capex(net_capex=net_capex, rd_expense=rd_expense)

# Working capital
working_capital = f_eua.indicador_working_capital(ten_k=True, df_bs=nflx_bs)

# Change in non cash working capital
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense Benefit Including Reclassifications',
    'Increase (Decrease) in Other Current Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Other Noncurrent Assets and Liabilities, Net'
]

change_non_cash_wc = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=nflx_cf, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)

# Reinvestment rate
reinvestment_rate = f_eua.indicador_reinvestment_rate(ten_k=True, net_capex=net_capex, change_non_cash_wc=change_non_cash_wc, df_is=nflx_is, idx=idx)

# New borrowing
lst_itens_new_borrowing = ['Proceeds from Issuance of Debt']

new_borrowing = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nflx_cf, first_quarter=None, idx=idx)

# Debt paid
lst_itens_debt_paid = ['Repayments of Long-term Debt']

debt_paid = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nflx_cf, first_quarter=None, idx=idx)

# Taxes on operating income
taxes_operating_income = f_eua.indicador_taxes_operating_income(ten_k=True, df_is=nflx_is, idx=idx)

# FCFE
fcfe_10k = f_eua.indicador_fcfe(
    ten_k=True, 
    depreciacao=depreciacao, 
    capex=capex, 
    change_non_cash_wc=change_non_cash_wc, 
    new_borrowing=new_borrowing,
    debt_paid=debt_paid,
    df_is=nflx_is,
    idx=idx
)

# FCFF
fcff_10k = f_eua.indicador_fcff(
        ten_k=True, 
        taxes_operating_income=taxes_operating_income,
        depreciacao=depreciacao, 
        capex=capex, 
        change_non_cash_wc=change_non_cash_wc, 
        df_is=nflx_is,
        idx=idx
)

# Dividendo por Ação
dpa = f_eua.indicador_dpa(ten_k=True, df_cf=nflx_cf, df_is=nflx_is, div_nao_acum=None)

# Payout
payout = f_eua.indicador_payout(ten_k=True, df_cf=nflx_cf, df_is=nflx_is, div_nao_acum=None)

# Buyback
buyback = f_eua.indicador_buyback(ten_k=True, df_cf=nflx_cf, first_quarter=None)

# DSO - não divulga o contas a receber no 10-k

# DIO - não divulga o invetário no 10-k

# DPO
dpo = f_eua.indicador_dpo(ten_k=True, df_bs=nflx_bs, df_is=nflx_is)

# FCO/LL
fco_ll = f_eua.indicador_fco_ll(ten_k=True, fco=fco, df_is=nflx_is)

# Recebíveis/Receita - não divulga o contas a receber no 10-k

# Accrual ratio
accrual_ratio = f_eua.indicador_accrual_ratio(ten_k=True, fco=fco, df_is=nflx_is, df_bs=nflx_bs)

# FCO/EBITDA
fco_ebitda = f_eua.indicador_fco_ebitda(ten_k=True, fco=fco, ebitda=ebitda)

# Free cash flow/LL
fcf_ll = f_eua.indicador_fcf_ll(ten_k=True, free_cash_flow=free_cash_flow, df_is=nflx_is)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# CAPEX/Depreciação
capex_depreciacao = f_eua.indicador_capex_depreciacao(capex=capex, depreciacao=depreciacao)

# Colocando todos os indicadores em uma lista
lst_indicadores = [
    p_lpa_damodaran,
    p_lpa,
    lpa_p,  
    ebitda, 
    m_liq,
    m_bruta,
    m_operacional,
    m_ebitda,
    p_vpa,
    vm,
    div_bruta,
    caixa,
    div_liq,
    dl_ebitda,
    dl_pl,
    ev_ebitda,
    roe,
    roic,
    fco,
    fci,
    fcf,
    free_cash_flow,
    sbc,
    adjusted_free_cash_flow,
    free_cash_flow_yield,
    capex,
    net_capex,
    rd_expense,
    adj_net_capex,
    working_capital,
    reinvestment_rate,
    fcfe_10k,
    fcff_10k,
    dpa,
    payout,
    buyback,
    # dso - não divulga o contas a receber no 10-k
    # dio - não divulga o invetário no 10-k
    dpo,
    fco_ll,
    # recebiveis_receita - não divulga o contas a receber no 10-k
    accrual_ratio,
    fco_ebitda,
    fcf_ll,
    capex_depreciacao
]

# Juntando todos os indicadores em um df
nflx_indicadores_10k = pd.concat(lst_indicadores, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    # 'DSO' - não divulga o contas a receber no 10-k
    # 'DIO' - não divulga o invetário no 10-k
    'DPO',
    'FCO/LL',
    # 'Recebíveis/Receita' - não divulga o contas a receber no 10-k
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
nflx_indicadores_10k.columns = nomes_col
nflx_indicadores_10k

,P/L Damodaran,P/L,L/P,EBITDA,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,Valor de Mercado,...,FCFF,DPA,Payout,Buyback,DPO,FCO/LL,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2025,36.28,36.34,2.75,13659992.0,24.30,48.49,29.49,30.23,14.98,3.984342e+11,...,11886337.0,0.0,0.0,9127167,14.123254,0.924241,0.015233,0.742993,0.844525,2.625699
2024,43.94,43.95,2.28,10746528.0,22.34,46.06,26.71,27.55,15.47,3.828303e+11,...,7940971.0,0.0,0.0,6263746,15.612679,0.845004,0.026382,0.684999,0.594559,6.633296
2023,39.76,39.75,2.52,7310950.0,16.04,41.54,20.62,21.68,10.44,2.150009e+11,...,5882029.0,0.0,0.0,6045347,13.837194,1.345103,-0.038351,0.994987,1.187296,2.390870
2022,29.19,29.20,3.42,5969513.0,14.21,39.37,17.82,18.88,6.31,1.311414e+11,...,2968484.0,0.0,0.0,0,12.786864,0.451089,0.052923,0.339434,-0.011161,6.167220
2021,52.18,52.16,1.92,6402921.0,17.23,41.64,20.86,21.56,16.85,2.669566e+11,...,5047558.0,0.0,0.0,600022,17.636121,0.076738,0.112648,0.061317,-0.179883,6.299704
2020,86.34,86.37,1.16,4700999.0,11.05,38.89,18.34,18.81,21.54,2.384065e+11,...,4241269.0,0.0,0.0,0,15.678305,0.878931,0.009127,0.516290,0.698616,4.303198
2019,75.89,75.96,1.32,2707833.0,9.26,38.28,12.92,13.43,18.68,1.416718e+11,...,2156748.0,0.0,0.0,0,19.785566,-1.546573,0.158606,-1.066285,-1.682109,2.442918
2018,96.22,96.29,1.04,1688383.0,7.67,36.89,10.16,10.69,22.25,1.165496e+11,...,1702769.0,0.0,0.0,0,20.615876,-2.213000,0.173015,-1.587601,-2.356610,2.091778
2017,148.36,148.84,0.67,910590.0,4.78,34.49,7.17,7.79,23.16,8.292192e+10,...,587577.0,0.0,0.0,0,17.133590,-3.195304,NaN,-1.961309,-3.505365,2.409951

In [240]:
# Lendo os arquivos 10q
nflx_bs_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10q.xlsx',
    sheet_name='balance_sheet', 
    index_col='Unnamed: 0'
)

nflx_is_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10q.xlsx',
    sheet_name='income_statement', 
    index_col='Unnamed: 0'
)

nflx_cf_10q = pd.read_excel(
    'C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_10q.xlsx',
    sheet_name='cash_flow',  
    index_col='Unnamed: 0'
)

# Aplicando o ajuste nas colunas
nflx_bs_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in nflx_bs_10q.columns]
nflx_is_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in nflx_is_10q.columns]
nflx_cf_10q.columns = [f_sec.ajustar_mes_03_06_09(col) for col in nflx_cf_10q.columns]

In [241]:
# Preços da NFLX
nflx_close = yf.download('NFLX', auto_adjust=True, multi_level_index=False, start='2021-01-01')['Close']

# Selecionando o último preço dos meses de Março, Junho e Setembro
lst_years = [
    '2021', '2022', '2023', '2024',
    '2025'
]
lst_months = ['03', '06', '09']
last_close_months = []

for year in lst_years:
    for month in lst_months:
        last_close = nflx_close[f'{year}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
        last_close_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx = []

for year in lst_years:
    for month in lst_months:
        lst_idx.append(f"{month}-{year}")

# Transformando em uma série pandas
nflx_close_months = pd.Series(last_close_months, index=lst_idx)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nflx_close_months = nflx_close_months.reindex(index=nflx_close_months.index[::-1])

# No ano mais atual, como ainda ele não acabou, não consigo fazer o loop com todos meses (Março, Junho e Setembro)
actual_year_int = datetime.now(timezone.utc).year  
actual_year_str = str(actual_year_int) 

lst_actual_months = [
    '03',
    '06', 
    # '09'
] 

last_close_actual_months = []

for month in lst_actual_months:
    last_close = nflx_close[f'{actual_year_str}-{month}'].dropna().iloc[-1]  # Dropna para lidar com meses sem dados
    last_close_actual_months.append(last_close)

# Criando uma lista em que junte os meses e os anos para que seja o index da serie pandas
lst_idx_actual = []

for month in lst_actual_months:
    lst_idx_actual.append(f"{month}-{actual_year_str}")

# Transformando em uma série pandas
nflx_close_months_atual = pd.Series(last_close_actual_months, index=lst_idx_actual)

# Revertendo o index da série p/ ficar igual com os dos indicadores
nflx_close_months_atual = nflx_close_months_atual.reindex(index=nflx_close_months_atual.index[::-1])

# Juntando as duas series pandas
nflx_close_months = pd.concat([nflx_close_months_atual, nflx_close_months])

# Arredondamento de duas casas decimais
nflx_close_months = round(nflx_close_months, 2)

# Teve um split de 10:1 em 16/11/2025 (https://br.investing.com/equities/netflix,-inc.-historical-data-splits)
nflx_close_months.loc['09-2025'] = nflx_close_months.loc['09-2025'] * 10
nflx_close_months.loc['06-2025'] = nflx_close_months.loc['06-2025'] * 10
nflx_close_months.loc['03-2025'] = nflx_close_months.loc['03-2025'] * 10
nflx_close_months.loc['09-2024'] = nflx_close_months.loc['09-2024'] * 10
nflx_close_months.loc['06-2024'] = nflx_close_months.loc['06-2024'] * 10
nflx_close_months.loc['03-2024'] = nflx_close_months.loc['03-2024'] * 10
nflx_close_months.loc['09-2023'] = nflx_close_months.loc['09-2023'] * 10
nflx_close_months.loc['06-2023'] = nflx_close_months.loc['06-2023'] * 10
nflx_close_months.loc['03-2023'] = nflx_close_months.loc['03-2023'] * 10
nflx_close_months.loc['09-2022'] = nflx_close_months.loc['09-2022'] * 10
nflx_close_months.loc['06-2022'] = nflx_close_months.loc['06-2022'] * 10
nflx_close_months.loc['03-2022'] = nflx_close_months.loc['03-2022'] * 10
nflx_close_months.loc['09-2021'] = nflx_close_months.loc['09-2021'] * 10
nflx_close_months.loc['06-2021'] = nflx_close_months.loc['06-2021'] * 10
nflx_close_months.loc['03-2021'] = nflx_close_months.loc['03-2021'] * 10

# Substituindo o index para ficar igual ao dos dados fundamentalistas
nflx_close_months.index = nflx_bs_10q.columns[:-3]

nflx_close_months

[*********************100%***********************]  1 of 1 completed

2026-06-30      71.40
2026-03-31      96.15
2025-09-30    1198.90
2025-06-30    1339.10
2025-03-31     932.50
2024-09-30     709.30
2024-06-30     674.90
2024-03-31     607.30
2023-09-30     377.60
2023-06-30     440.50
2023-03-31     345.50
2022-09-30     235.40
2022-06-30     174.90
2022-03-31     374.60
2021-09-30     610.30
2021-06-30     528.20
2021-03-31     521.70
dtype: float64

* Os dados do fluxo de caixa são não acumulados:
    - Todas as funções que utilizam dados do fluxo de caixa utilizar com o parâmetro 'ten_k'=True;
    - Para fazer o cálculo da série acumulada utilizar a função 'indicador_acumular_series_trimestrais'.

In [242]:
# Criando uma lista só para fazer a indexação em que o ano mais recente está no começo
idx_10q = nflx_bs_10q.columns

# Valor de Mercado
vm_10q = f_eua.indicador_vm(ten_k=False, price=nflx_close_months, df_is=nflx_is_10q)

# LPA
lpa_acum = f_eua.indicador_lpa(ten_k=False, df_is=nflx_is_10q, idx=idx_10q)[1]
lpa_10q = f_eua.indicador_lpa(ten_k=False, df_is=nflx_is_10q, idx=idx_10q)[0]

# P/L Damodaran
p_lpa_10q_damodaran = f_eua.indicador_p_lpa_2(ten_k=False, vm=vm_10q, df_is=nflx_is_10q)

# P/L
p_lpa_10q = f_eua.indicador_p_lpa(ten_k=False, price=nflx_close_months, lpa=lpa_acum, idx=idx_10q)

# L/P
lpa_p_10q = f_eua.indicador_lpa_p(ten_k=False, price=nflx_close_months, lpa=lpa_acum, idx=idx_10q) 

# Depreciação - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
depreciacao_10q = f_eua.indicador_depreciacao(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)
depreciacao_10q_sliced = f_eua.indicador_depreciacao(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
depreciacao_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=depreciacao_10q, idx=idx_10q)

# EBITDA
ebitda_10q = f_eua.indicador_ebitda(ten_k=False, df_is=nflx_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[0]
ebitda_10q_sliced = f_eua.indicador_ebitda(ten_k=False, df_is=nflx_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[1]
ebitda_10q_acum = f_eua.indicador_ebitda(ten_k=False, df_is=nflx_is_10q, idx=idx_10q, depreciacao=depreciacao_10q)[2]

# Margem Líquida
m_liq_10q = f_eua.indicador_ml(ten_k=False, df_is=nflx_is_10q)

# Margem bruta
m_bruta_10q = f_eua.indicador_mb(ten_k=False, df_is=nflx_is_10q)

# Margem operacional
m_operacional_10q = f_eua.indicador_mo(ten_k=False, df_is=nflx_is_10q)

# Margem ebitda
m_ebitda_10q = f_eua.indicador_me(ten_k=False, ebitda=ebitda_10q_sliced, df_is=nflx_is_10q)

# VPA
vpa_10q = f_eua.indicador_vpa(ten_k=False, df_bs=nflx_bs_10q, df_is=nflx_is_10q)

# P/VPA
p_vpa_10q = f_eua.indicador_p_vpa(ten_k=False, price=nflx_close_months, vpa=vpa_10q, idx=idx_10q)

# Caixa e Equivalentes
lst_caixa = [
    'Cash and Cash Equivalents, at Carrying Value',
    'Short-term Investments'
]

caixa_10q = f_eua.indicador_caixa(ten_k=False, df_bs=nflx_bs_10q, lst_itens_caixa=lst_caixa)

# Dívida Bruta 
lst_divida = [
    'Short-term Debt',
    'Long-term Debt, Excluding Current Maturities'
]

div_bruta_10q = f_eua.indicador_divida_bruta(ten_k=False, df_bs=nflx_bs_10q, lst_itens_divida=lst_divida)

# Dívida Líquida
div_liq_10q = f_eua.indicador_divida_liquida(ten_k=False, caixa=caixa_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# Dívida Líquida / EBITDA
dl_ebitda_10q = f_eua.indicador_dl_ebitda(ten_k=False, ebitda=ebitda_10q_acum, div_liq=div_liq_10q, idx=idx_10q)

# Dívida Líquida / PL
dl_pl_10q = f_eua.indicador_dl_pl(ten_k=False, div_liq=div_liq_10q, df_bs=nflx_bs_10q) 

# EV/EBITDA
ev_ebitda_10q = f_eua.indicador_ev_ebitda(vm=vm_10q, div_liq=div_liq_10q, ebitda=ebitda_10q_acum)

# ROE
roe_10q = f_eua.indicador_roe(ten_k=False, df_is=nflx_is_10q, df_bs=nflx_bs_10q, idx=idx_10q)

# ROIC 
roic_10q = f_eua.indicador_roic(ten_k=False, df_is=nflx_is_10q, df_bs=nflx_bs_10q, div_bruta=div_bruta_10q, idx=idx_10q)

# FCO - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fco_10q = f_eua.indicador_fco(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None) 
fco_10q_sliced = f_eua.indicador_fco(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None)[:-3]
fco_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fco_10q, idx=idx_10q)

# FCI - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fci_10q = f_eua.indicador_fci(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None)
fci_10q_sliced = f_eua.indicador_fci(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None)[:-3]
fci_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fci_10q, idx=idx_10q)

# FCF - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
fcf_10q = f_eua.indicador_fcf(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None)
fcf_10q_sliced = f_eua.indicador_fcf(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None)[:-3]
fcf_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=fcf_10q, idx=idx_10q)

# CAPEX - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_capex_10q = [
    'Payments to Acquire Property, Plant, and Equipment',
    'Payments to Acquire Businesses, Net of Cash Acquired',
    'Payments to Acquire Investments'
]

capex_10q = f_eua.indicador_capex(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, lst_itens=lst_capex_10q, idx=idx_10q)
capex_10q_sliced = f_eua.indicador_capex(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, lst_itens=lst_capex_10q, idx=idx_10q)[:-3]
capex_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=capex_10q, idx=idx_10q)

# Free Cash Flow
free_cash_flow_10q = f_eua.indicador_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum)

# SBC - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
sbc_10q = f_eua.indicador_sbc(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)
sbc_10q_sliced = f_eua.indicador_sbc(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
sbc_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=sbc_10q, idx=idx_10q)

# Outros custos fluxo de caixa - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_custos_cf = ['Payment, Tax Withholding, Share-based Payment Arrangement']

outros_custos_cf_10q = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, lst_itens=lst_custos_cf, idx=idx_10q)
outros_custos_cf_10q_sliced = f_eua.indicador_outros_custos_cf(ten_k=True, df_cf=nflx_cf_10q, first_quarter=None, lst_itens=lst_custos_cf, idx=idx_10q)[:-3]
outros_custos_cf_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=outros_custos_cf_10q, idx=idx_10q)

# Adjusted Free Cash Flow
adjusted_free_cash_flow_10q = f_eua.indicador_adjusted_free_cash_flow(fco=fco_10q_acum, capex=capex_10q_acum, sbc=sbc_10q_acum, outros_custos_cf=outros_custos_cf_10q_acum)

# Free Cash Flow Yield
free_cash_flow_yield_10q = f_eua.indicador_free_cash_flow_yield(free_cash_flow=adjusted_free_cash_flow_10q, vm=vm_10q)

# Net CAPEX
net_capex_10q = f_eua.indicador_net_capex(capex=capex_10q_acum, depreciation=depreciacao_10q_acum)

# R&D
rd_expense_10q = f_eua.indicador_rd(ten_k=False, df_is=nflx_is_10q, idx=idx_10q)[0]
rd_expense_10q_sliced = f_eua.indicador_rd(ten_k=False, df_is=nflx_is_10q, idx=idx_10q)[1]
rd_expense_10q_acum = f_eua.indicador_rd(ten_k=False, df_is=nflx_is_10q, idx=idx_10q)[2]

# Net CAPEX ajustado
adj_net_capex_10q = f_eua.indicador_adj_net_capex(net_capex=net_capex_10q, rd_expense=rd_expense_10q_acum)

# Working capital
working_capital_10q = f_eua.indicador_working_capital(ten_k=False, df_bs=nflx_bs_10q)

# Change in non cash working capital - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_change_non_cash_wc = [
    'Deferred Income Tax Expense Benefit Including Reclassifications',
    'Increase (Decrease) in Other Current Assets',
    'Increase (Decrease) in Accounts Payable',
    'Increase (Decrease) in Accrued Liabilities',
    'Increase (Decrease) in Contract with Customer, Liability',
    'Increase (Decrease) in Other Noncurrent Assets and Liabilities, Net'
]

change_non_cash_wc_10q = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=nflx_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)
change_non_cash_wc_10q_sliced = f_eua.indicador_change_non_cash_wc(ten_k=True, df_cf=nflx_cf_10q, lst_itens=lst_itens_change_non_cash_wc, first_quarter=None)[:-3]
change_non_cash_wc_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=change_non_cash_wc_10q, idx=idx_10q)

# Reinvestment rate
reinvestment_rate_10q = f_eua.indicador_reinvestment_rate(ten_k=False, net_capex=adj_net_capex_10q, change_non_cash_wc=change_non_cash_wc_10q, df_is=nflx_is_10q, idx=idx_10q)

# New borrowing - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_new_borrowing = ['Proceeds from Issuance of Debt']

new_borrowing_10q = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)
new_borrowing_10q_sliced = f_eua.indicador_new_borrowing(ten_k=True, lst_itens_new_borrowing=lst_itens_new_borrowing, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
new_borrowing_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=new_borrowing_10q, idx=idx_10q)

# Debt paid - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
lst_itens_debt_paid = ['Repayments of Long-term Debt']

debt_paid_10q = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)
debt_paid_10q_sliced = f_eua.indicador_debt_paid(ten_k=True, lst_itens_debt_paid=lst_itens_debt_paid, df_cf=nflx_cf_10q, first_quarter=None, idx=idx_10q)[:-3]
debt_paid_10q_acum = f_eua.indicador_acumular_series_trimestrais(serie_trimestral=debt_paid_10q, idx=idx_10q)

# Taxes on operating income
taxes_operating_income_10q = f_eua.indicador_taxes_operating_income(ten_k=False, df_is=nflx_is_10q, idx=idx_10q)

# FCFE
fcfe_10q = f_eua.indicador_fcfe(
    ten_k=False, 
    depreciacao=depreciacao_10q_acum, 
    capex=capex_10q_acum, 
    change_non_cash_wc=change_non_cash_wc_10q_acum, 
    new_borrowing=new_borrowing_10q_acum, 
    debt_paid=debt_paid_10q_acum, 
    df_is=nflx_is_10q,
    idx=idx_10q
)

# FCFF
fcff_10q = f_eua.indicador_fcff(
        ten_k=False, 
        taxes_operating_income=taxes_operating_income_10q,
        depreciacao=depreciacao_10q_acum, 
        capex=capex_10q_acum, 
        change_non_cash_wc=change_non_cash_wc_10q_acum, 
        df_is=nflx_is_10q,
        idx=idx_10q
)

# Dividendo por Ação - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
dpa_10q = f_eua.indicador_dpa(ten_k=True, df_cf=nflx_cf_10q, df_is=nflx_is_10q, div_nao_acum=None)[:-3]

# Payout - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
payout_10q = f_eua.indicador_payout(ten_k=True, df_cf=nflx_cf_10q, df_is=nflx_is_10q, div_nao_acum=None)[:-3]

# Buyback - os números do fluxo de caixa não são acumulados (utilizar o 'ten_k'=True)
buyback_10q = f_eua.indicador_buyback(ten_k=True, df_cf=nflx_cf_10q,  first_quarter=None)[:-3]

# DSO - não divulga o contas a receber no 10-q

# DIO - não divulga o invetário no 10-q

# DPO
dpo_10q = f_eua.indicador_dpo(ten_k=False, df_bs=nflx_bs_10q, df_is=nflx_is_10q)

# FCO/LL
fco_ll_10q = f_eua.indicador_fco_ll(ten_k=False, fco=fco_10q_sliced, df_is=nflx_is_10q)

# Recebíveis/Receita - não divulga o contas a receber no 10-q

# Accrual ratio
accrual_ratio_10q = f_eua.indicador_accrual_ratio(ten_k=False, fco=fco_10q_sliced, df_is=nflx_is_10q, df_bs=nflx_bs_10q)

# FCO/EBITDA
fco_ebitda_10q = f_eua.indicador_fco_ebitda(ten_k=False, fco=fco_10q_sliced, ebitda=ebitda_10q_sliced)

# Free cash flow/LL
fcf_ll_10q = f_eua.indicador_fcf_ll(ten_k=False, free_cash_flow=free_cash_flow_10q, df_is=nflx_is_10q)

# CAPEX/Depreciação
capex_depreciacao_10q = f_eua.indicador_capex_depreciacao(capex=capex_10q_sliced, depreciacao=depreciacao_10q_sliced)

# Lista com todos os indicadores
lst_indicadores_10q = [
    p_lpa_10q_damodaran,
    p_lpa_10q,
    lpa_p_10q,  
    ebitda_10q_sliced, 
    ebitda_10q_acum, 
    m_liq_10q,
    m_bruta_10q,
    m_operacional_10q,
    m_ebitda_10q,
    p_vpa_10q,
    vm_10q,
    div_bruta_10q,
    caixa_10q,
    div_liq_10q,
    dl_ebitda_10q,
    dl_pl_10q,
    ev_ebitda_10q,
    roe_10q,
    roic_10q,
    fco_10q_acum,
    fci_10q_acum,
    fcf_10q_acum,
    free_cash_flow_10q,
    sbc_10q_acum,
    adjusted_free_cash_flow_10q,
    free_cash_flow_yield_10q,
    capex_10q_acum,
    net_capex_10q,
    rd_expense_10q_sliced,
    adj_net_capex_10q,
    working_capital_10q,
    reinvestment_rate_10q,
    fcfe_10q,
    fcff_10q,
    dpa_10q,
    payout_10q,
    buyback_10q,
    # dso_10q - não divulga o contas a receber no 10-q
    # dio_10q - não divulga o invetário no 10-q
    dpo_10q,
    fco_ll_10q,
    # recebiveis_receita_10q - não divulga o contas a receber no 10-q
    accrual_ratio_10q,
    fco_ebitda_10q,
    fcf_ll_10q,
    capex_depreciacao_10q
]

# Juntando todos os indicadores em um df
nflx_indicadores_10q = pd.concat(lst_indicadores_10q, axis=1)

# Nomes das colunas
nomes_col = [
    'P/L Damodaran', 
    'P/L', 
    'L/P', 
    'EBITDA', 
    'EBITDA Acumulado', 
    'Margem Líquida',
    'Margem Bruta',
    'Margem Operacional',
    'Margem EBITDA',
    'P/VPA',
    'Valor de Mercado',
    'Dívida Bruta',
    'Caixa e Equivalentes',
    'Dívida Líquida',
    'Dívida Líquida/EBITDA',
    'Dívida Líquida/PL',
    'EV/EBITDA',
    'ROE',
    'ROIC',
    'FCO',
    'FCI',
    'FCF',
    'Free Cash Flow',
    'SBC',
    'Adjusted Free Cash Flow',
    'Free Cash Flow Yield',
    'Capex',
    'Net Capex',
    'R&D',
    'Adj Net Capex',
    'Working Capital',
    'Reinvestment Rate',
    'FCFE',
    'FCFF',
    'DPA',
    'Payout',
    'Buyback',
    # 'DSO' - não divulga o contas a receber no 10-q
    # 'DIO' - não divulga o invetário no 10-q
    'DPO',
    'FCO/LL',
    # 'Recebíveis/Receita' - não divulga o contas a receber no 10-q
    'Accrual Ratio',
    'FCO/EBITDA',
    'Free Cash Flow/LL',
    'Capex/Depreciação'
]

# Atribuindo os novos nomes das colunas do df
nflx_indicadores_10q.columns = nomes_col

# Preenchendo os NaN por zero
nflx_indicadores_10q = nflx_indicadores_10q.fillna(0)

nflx_indicadores_10q

,P/L Damodaran,P/L,L/P,EBITDA,EBITDA Acumulado,Margem Líquida,Margem Bruta,Margem Operacional,Margem EBITDA,P/VPA,...,FCFF,DPA,Payout,Buyback,DPO,FCO/LL,Accrual Ratio,FCO/EBITDA,Free Cash Flow/LL,Capex/Depreciação
2026-06-30,87.94,4.63,21.58,4293140.0,15538992.0,27.08,51.93,33.38,34.18,9.92,...,12928178.0,0.0,0.0,4714403,49.248441,0.512673,0.029719,0.406186,3.220961,2.174913
2026-03-31,76.86,4.50,22.22,4055572.0,14672918.0,43.13,51.93,32.30,33.11,13.05,...,12961760.0,0.0,0.0,1270588,55.459471,1.001403,-0.000131,1.304429,2.259329,7.931768
2025-09-30,199.80,46.78,2.14,3335573.0,13607737.0,22.13,46.45,28.22,28.98,19.61,...,10623823.0,0.0,0.0,1856885,46.969225,1.109253,-0.005191,0.846983,3.093633,1.930341
2025-06-30,182.18,54.39,1.84,3854707.0,12956228.0,28.21,51.93,34.07,34.79,22.82,...,9009693.0,0.0,0.0,1654327,43.366870,0.775340,0.013741,0.628649,2.058985,1.968918
2025-03-31,137.85,41.13,2.43,3427066.0,11821289.0,27.42,50.08,31.75,32.51,16.58,...,8775152.0,0.0,0.0,3536396,42.614900,0.965004,0.002005,0.813874,2.181834,3.550676
2024-09-30,128.52,35.99,2.78,2990391.0,10401277.0,24.06,47.89,29.61,30.44,13.37,...,7632156.0,0.0,0.0,1700000,45.765264,0.982057,0.000833,0.776186,2.407330,23.099946
2024-06-30,135.17,38.48,2.60,2684064.0,9327454.0,22.46,45.87,27.23,28.08,13.13,...,7906284.0,0.0,0.0,1599998,42.224056,0.601147,0.017144,0.480930,2.921701,0.963805
2024-03-31,112.51,39.23,2.55,2719768.0,8448042.0,24.89,46.89,28.09,29.02,12.28,...,7135120.0,0.0,0.0,2000000,44.540641,0.948681,0.002435,0.813497,2.991290,0.867941
2023-09-30,99.39,28.56,3.50,2007054.0,7346480.0,19.64,42.27,22.44,23.50,7.54,...,6061830.0,0.0,0.0,2500100,39.560935,1.187724,-0.006488,0.992656,3.166380,1.146360
2023-06-30,131.44,34.79,2.87,1916568.0,7001214.0,18.17,42.92,22.32,23.41,8.56,...,5585097.0,0.0,0.0,645146,48.060972,0.968152,0.000975,0.751464,2.263244,4.522012
2023-03-31,117.87,26.76,3.74,1804652.0,7130874.0,15.99,41.14,21.00,22.11,7.05,...,5968021.0,0.0,0.0,400101,44.981708,1.669379,-0.018427,1.207291,2.304733,2.918614
2022-09-30,74.90,17.77,5.63,1618206.0,7151728.0,17.64,39.58,19.34,20.42,5.10,...,6482887.0,0.0,0.0,0,42.696021,0.398221,0.018636,0.344091,0.720847,0.997324
2022-06-30,53.96,13.29,7.52,1661788.0,7419586.0,18.08,41.15,19.80,20.85,4.08,...,6564139.0,0.0,0.0,0,39.239199,0.071307,0.030650,0.061831,0.251243,1.902808
2022-03-31,104.15,27.20,3.68,2046228.0,7753395.0,20.30,45.54,25.06,26.01,9.48,...,7154038.0,0.0,0.0,0,52.577419,0.577696,0.015789,0.450995,0.697637,3.293196
2021-09-30,186.48,51.03,1.96,1825506.0,7050619.0,19.36,43.79,23.46,24.39,17.64,...,6936143.0,0.0,0.0,100000,55.797354,0.056850,0.033595,0.045127,1.098102,2.381777
2021-06-30,173.00,51.18,1.95,1886064.0,6609702.0,18.43,45.27,25.17,25.69,16.89,...,6298728.0,0.0,0.0,500022,56.587696,-0.047125,0.036260,-0.033806,1.903538,2.869282
2021-03-31,135.48,58.75,1.70,1995597.0,5710411.0,23.83,46.00,27.36,27.86,17.95,...,5542379.0,0.0,0.0,0,50.283903,0.455416,0.024725,0.389490,1.705878,2.266333

In [246]:
# Criando o arquivo excel em que cada informação está em uma aba diferente
with pd.ExcelWriter('C://B3//historico-arquivos//indicadores_fundamentalistas_eua//tecnologia//netflix//nflx_indicators.xlsx') as writer:
    nflx_indicadores_10k.to_excel(writer, sheet_name='indicators_10k')
    nflx_indicadores_10q.to_excel(writer, sheet_name='indicators_10q')